### ISSUE TITLE
LAMMPS+QUIP - GAP potential

### ISSUE THREAD

**Issue by alvarovm** [libAtoms/QUIP#101]
Hi,
We are trying to compile LAMMPS with QUIP to evaluate gap potentials.
We compiled both packages with gcc and gfortran with omp support.
We get this error (from the debugger) when we try to run the example provided by LAMMPS:

gdb ../../../src/lmp_serial < in.gap

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
LAMMPS (31 Mar 2017)
Reading data file ...
  orthogonal box = (0 0 0) to (10.9685 10.9685 10.9685)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  64 atoms
 WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
 WARNING: gpCoordinates_startElement_handler: covariance type is dot product, but no zeta attribute is present. This may mean an XML generated by an older version. If found, the single value from the theta element will be used, to ensure backwards compatibility
 WARNING: gpCoordinates_endElement_handler: dot product covariance is used, but found a theta element in the XML. This may be a sign of an XML generated by an older version. The first and only element of theta will be used as zeta.
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 4.3
  ghost atom cutoff = 4.3
  binsize = 2.15, bins = 6 6 6
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair quip, perpetual
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001

Program received signal SIGSEGV, Segmentation fault.
0x0000000000a3a6df in __potential_module_MOD_potential_cutoff ()

Any idea?
Thanks in advance
AVM

**Comment by gabor1** [comment]
try " ulimit -s unlimited"

-- Gábor

**Comment by alvarovm** [comment]
I get the same error message: Segmentation fault.
what should I be looking for?

I recompiled with DEBUG flags. 
This is where QUIP is complaining:
Program received signal SIGSEGV, Segmentation fault.
0x0000000000e338cf in potential_module::potential_cutoff (this=<error reading variable: Cannot access memory at address 0x2>, error=<error reading variable: Cannot access memory at address 0x0>)
    at /projects/CrystalsADSP/avazquez/QUIP/src/Potentials/Potential.f95:1046
1046	    if (this%is_simple) then

**Comment by noambernstein** [comment]
I would be very wary of OMP support in both pieces - I can easily believe
it'll conflict.  Can you try it with openmp enabled only in QUIP?

**Comment by alvarovm** [comment]
I tried without openmp in quip and lammps, both in serial with GNU compilers. no luck

**Comment by yghadar** [comment]
Hi, 
I have compiled lammps 16-Feb-16 with only molecule and user-quip. I have used QUIP_ARCH of linux_x86_64_gfortran. When I run the Lammps with examples I get segmentation fault. I would appreciate any help with this problem as well. I am using the current github version for QUIP and I just downloaded the GAP from the website. 
Thank you,

-Yasaman

**Comment by gabor1** [comment]
Can you try your input file in the precooked docker version of lammps+quip please. That's where I will go hunt for actual bugs

-- Gábor

**Comment by max-veit** [comment]
I believe the examples being referenced are the ones we supply along with QUIP for LAMMPS (in https://github.com/lammps/lammps/tree/master/examples/USER/quip). The one that should run with only molecule and user-quip packages installed is `in.molecular`. It would be well worth running these as part of our regression tests (if we don't already...).

**Comment by yghadar** [comment]
Hi, 
I compiled the LAMMPS from the GitHub and run in.molecular and it worked successfully. However, in.gap failed with seg fault. My question is what should I build LAMMPS with? beside molecule and user-quip to work with gap potential. QUIP by itself has been built with GAP. Thank you.

**Comment by alvarovm** [comment]
LAMMPS/QUIP/GAP works in Docker image. I think the source of the problem is my outdated the version of LAMMPS ( 31 Mar 2017), the version in Docker is 11 Aug 2017.

**Comment by yghadar** [comment]
Does that mean one needs to have LAMMPS 11Aug 2017, if he/she does not want the docker format?

**Comment by alvarovm** [comment]
Yes. With respect QUIP, so far in /opt/quip/GIT_VERSION:
https://github.com/libAtoms/QUIP.git,22731ad

**Comment by yghadar** [comment]
Hi,

As an update, the singularity package works. Also it turned out that **Lammps-11Aug17** with current version of QUIP and GAP works. I think this needs to be mentioned somewhere in documentation to avoid headache for other users. 
Best,
-Yasaman

**Comment by max-veit** [comment]
Oh right, that's when our lammps interface changed (see especially [this comment](https://github.com/lammps/lammps/pull/581#issuecomment-316346226), which indicates a segfault would be expected in this situation). This is indeed mentioned at the bottom of our README; however, I'll look into putting a note in the lammps documentation as well (which will only help those reading the latest online documentation, but I think that's almost everyone nowadays).

**Comment by gabor1** [comment]
Can I close this now?

**Comment by alvarovm** [comment]
Yes. thanks
