### ISSUE TITLE
GAP - 2 Body desciptor

### ISSUE THREAD

**Issue by g7dhaliwal** [libAtoms/QUIP#103]
Hi,

 I have a question about the output of 2 body descriptor. I used the following code on a 200 atom system (graphene data from data repository at LibAtoms website). I got output as a column vector with 3600 rows. Is there a way to get the atom index corresponding to each row of this column vector (d['descriptor'])? 

Thanks!

Code:
desc = descriptors.Descriptor('distance_2b Z1=6 Z2=6 cutoff=4.5 ')
at.set_cutoff(desc.cutoff()+0.5)
at.calc_connect()
d=desc.calc(at, grad = True)
print("shape of the descriptor ", d['descriptor'].shape)

**Comment by gabor1** [comment]
Unforunately this functionality is not yet propagated to python. But it’s a very good point, we’re thinking about how to propagate the indices. (the underlying fortran routine that calculates the descriptors returns an object which contains the indices as well as the descriptor values. )

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/

**Comment by albapa** [comment]
Hi, I have just added the indexing. The Docker is not complete yet but if you are using the github version you can try it now. Make sure you update your GAP as well.

To use, do the same as in your example code,  on return, `d` will have a `descriptor_index_0based` field. It has as many rows as descriptors, and each row should have the 0-based indices of the central atom(s) of the corresponding descriptor. For an atom-based descriptor such as SOAP, it will be a single number. For the dimer, it will be two numbers, and it can even be more for other descriptors.

Please report any problems.

**Comment by g7dhaliwal** [comment]
Thanks. For a 2Body descriptor, I am assuming descriptor_index_0based field returns the indices i and j denoting the distance between atom i and j. A quick check is giving different distances for atom i and j, than the corresponding descriptor values. I am appending the code below with the corresponding outputs. Maybe there is something that I am missing and will appreciate if you can help me with it.

Atomic configurations are from the Graphene dataset. Below I am using first configuration.

desc = descriptors.Descriptor('distance_2b Z1=6 Z2=6 cutoff=4.5 ')
a1 = quippy.AtomsList(dataFilePathA+trainFile)
at=a1[0]
at.set_cutoff(desc.cutoff()+0.5)
at.calc_connect()
d=desc.calc(at, grad = True)
print("shape of the descriptor ", d['descriptor'].shape)
print("shape ofthe gradient ", d['grad'].shape)

#getting the indices
index = d['descriptor_index_0based']

print(index[1,:])
Output>> array([  0, 180], dtype=int32)

print(d['descriptor'][1,:])
Output>>array([ 2.48196842])

print(d['cutoff'][1,:])
Output>>1

#computing the distances
print(np.sqrt(np.sum(np.power(at.positions[180]-at.positions[0],2))))
Output>>22.26576680021742

**Comment by gabor1** [comment]
perhaps the periodic unit cell is playing silly buggers with you? 

you can access the connectivity object through the standard ASE neighbourlist api. 

-- Gábor

**Comment by albapa** [comment]
I agree with Gabor, it must be periodic boundary conditions.

**Comment by gabor1** [comment]
Sorry I may not have been clear. I think the indices are correct, but you cannot measure the distance between two atoms by subtracting their positions when the unit cell is periodic. The distance between two atoms is defined as the shortest distance between all their possible periodic images, the descriptor is calculated in this way. ASE offers many tools to do this kind of distance computation, so does quippy. 

-- Gábor

**Comment by albapa** [comment]
In addition to that, when using small unit cells, you will find that the same pair of atom indices will correspond to multiple distances, or even the same index with itself - when the self image is in a different periodic replica.

**Comment by g7dhaliwal** [comment]
Thanks a lot. That explains the discrepancy. 

Another small comment is about 'angle_3b' descriptor. I was expecting index_0based field to return 3 indices for each row of the descriptor instead of the current output of a single number. If you can please look into it, that will be much appreciated.

**Comment by albapa** [comment]
That's a matter of definition. In the case of angle_3b, I found it natural to define a central atom, and that's what I did. I think distance_Nb with order=3 will do what you want, though.

**Comment by gabor1** [comment]
But shouldn't it also return the indices two neighbours of the central atom? 

-- Gábor

**Comment by albapa** [comment]
No, the point of that array is to distribute the local energies correctly. Allocating all the energy to the central atom is, I believe, correct.

**Comment by gabor1** [comment]
ah yes, of course. it's just not what he is looking for I guess. 

-- Gábor

**Comment by albapa** [comment]
I'm not against revising the definition, if others think there are more sensible ways. At the moment I can't make this a priority, though.

**Comment by gabor1** [comment]
No, I don't think it's necessary. 

-- Gábor

**Comment by g7dhaliwal** [comment]
Thanks.

Calling 'descriptor_Nb' is giving me the following error.
RuntimeError: Traceback (most recent call last)
  File "/home/MD/QUIP/src/GAP/descriptors.f95", line 659 kind unspecified
    descriptor_initialise found too few or too many IP Model types args_str='descriptor_Nb  order =3'

**Comment by gabor1** [comment]
it's called distance_Nb

-- Gábor

**Comment by albapa** [comment]
sorry, my fault!

**Comment by g7dhaliwal** [comment]
That worked. I am assuming 'distance_Nb' computes pair - distance between 3 atoms when order is set to 3 and is not same as 'angle_3b'. 

Thanks a ton for all the support provided.

**Comment by albapa** [comment]
correct. It is not a symmetrised descriptor (i.e. the elements permute depending the order of atoms), so when used in GAP, the kernel is symmetrised instead.

**Comment by gabor1** [comment]
It can compute distance between N atoms if you put order=N. useful Ns are 2,3,4, 5 gets quite expensive depending on the cutoff. 

-- Gábor
