### ISSUE TITLE
The spectrum starts to deviate after cutoff > 10.0 in set cutoff

### ISSUE THREAD

**Issue by Aki78** [libAtoms/QUIP#104]
The SOAP spectrum starts to deviate after the cutoff radius of 10.0. For example for a single hydrogen in vacuum with the following set up
```python
from quippy import *
import numpy as np

cutoff_radius = 10.10000000
soap = 'soap n_max=10 l_max=10 cutoff='+str(cutoff_radius)+' average=F atom_sigma=1.0'
d = Descriptor(soap)
a = Atoms("testSingle.xyz")
a.set_cutoff(cutoff_radius)
a.calc_connect()
q = d.calc_descriptor(a)
print("sum",    np.sum(np.abs(q)))
print("max",    np.max(q))
print("min",    np.min(q))
print("absmax", np.max(np.abs(q)))
```
with testSingle.xyz
```
1

H 0 0 0 
```
the sum of  np.abs(q) is 1.0 from  cutoff = 0.1 to cutoff = 10.0, but at cutoff = 10.1 the sum is 1.1523 and at cutoff = 11.0 the sum is 3.7526. Could this be a numerical issue?

**Comment by gabor1** [comment]
No, it's because we don't support nonprofit systems. You don't specify a periodic lattice, so the code makes one up, by adding a padding of 10 A to the extent of your system.

-- Gábor

**Comment by jameskermode** [comment]
(I'm guessing nonprofit is an autocorrection for non-periodic!)

**Comment by noambernstein** [comment]
Also, I’m not sure it’s true that we don’t support non periodic. At one point at least if you made a pbc vector 0 it would make that direction non periodic, at least the neighbor list routine would.

     Noam

**Comment by gabor1** [comment]
Yes of course.

-- Gábor
