### ISSUE TITLE
Gradients index for SOAP

### ISSUE THREAD

**Issue by g7dhaliwal** [libAtoms/QUIP#105]
Hi,

  I am using SOAP descriptor and has a question about the 'grad_index_0based' key. As per documentation, this key should return 2 values as 'descriptor index' and 'atom index'. I think this is not the case.

For the atomic configuration and certain parameter values, my descriptor array has dimension as 200 X 51, where 200 is the number of atoms and 51 is the number of columns of the descriptor. If I run the following code, I am expecting the result to be 50, 199. Instead, the output is 199, 199

d=desc.calc(at, grad = True)
descriptorArray = d['descriptor']
gradIndex = d['grad_index_0based']

print(descriptorArray.shape)
print(gradIndex.shape)
print(np.max(gradIndex, axis =0))   ## expected output (50,199)

Output 
>>(200, 51)
>> (3760, 2)
>> array([199, 199], dtype=int32)

**Comment by gabor1** [comment]
what is your descriptor? can you send me the complete test code (including structure to be read in, and the descriptor definition) ? 

-- Gábor

**Comment by g7dhaliwal** [comment]
Hi,

 I am using the 'Graphene_GAP_Training.xyz' file from data repository at libatoms
[Graphene_GAP_Training.xyz.tar.gz](https://github.com/libAtoms/QUIP/files/2069107/Graphene_GAP_Training.xyz.tar.gz). The code is the following

dataFilePathA = 'DataGraphene/'
trainFile = 'Graphene_GAP_Training.xyz'
a1 = quippy.AtomsList(dataFilePathA+trainFile)

at = a1[0]
desc = descriptors.Descriptor("soap cutoff=4 l_max=4 n_max=4 atom_sigma=0.5 n_Z=1 Z={6} ")
at.set_cutoff(desc.cutoff()+1.0)
at.calc_connect()

d=desc.calc(at, grad = True)
descriptorArray = d['descriptor']
gradIndex = d['grad_index_0based']

print(descriptorArray.shape) ## output (200,51)
print(gradIndex.shape)
print(np.max(gradIndex, axis =0)) ## expected output (50,199)

**Comment by gabor1** [comment]
Albert will correct me if I'm wrong, but the grad-index has two columns, and both are indexing into the atoms array. you have 200 atoms, each with 51 decriptor values. the gradient gives the derviative of each of these with respect to ANOTHER atom position. so for example, you have atom i and descriptor element n. then the gradient the derivative of this descriptor with respect to atom j. the grad_index gives you i and j. 

-- Gábor

**Comment by albapa** [comment]
Yes, @gabor1 is right.

Descriptor index means the index of the the descriptor. For an atom based descriptor with a single element, such as SOAP in this case, it maps directly to the atom number. In other cases it may be different. There is no need to separately index the elements of a particular descriptor.

The code below (added to yours) will confirm that you have 18 neighbours per atom (add one for the central to get 19), there are 200 atoms, meaning 200 descriptors, so you expect 19 x 200 descriptor gradients.

```print gradIndex.shape

print at.n

at.set_cutoff(desc.cutoff())
at.calc_connect()
for i in quippy.frange(at.n):
    print at.n_neighbours(i)
```
