### ISSUE TITLE
Can't add single atom to `quippy.atoms.Atoms`

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [libAtoms/QUIP#107]
I have an `Atoms` object (created, if it matters, from an ASE `Atoms` using `copy_from`.

I'm trying to add a single atom to it using the `add_atoms` method, like so:
```
lattice.add_atoms((0.0, 0.0, 0.0), 3)
```
which fails with this error:
```
File "/home/.../QUIP/src/libAtoms/Atoms.f95", line 1425 kind unspecified
    Atoms_Add: this atoms has no species property
```

According to [the docs](http://libatoms.github.io/QUIP/atoms.html#quippy.atoms.Atoms.add_atoms) this is the correct usage of `add_atoms`. I tried both lists and tuples for the position and got the same error.

I was able to work around this issue --
```
lattice.append(qpAtoms(positions=[(0.0, 0.0, 0.0)], numbers=[3]))
```
-- but I wanted to report and see if it's a bug.

**Comment by gabor1** [comment]
I can’t reproduce your error: 

In [13]: type(a)
Out[13]: quippy.atoms.Atoms
In [14]: a.add_atoms((0.0,0.0,0.0), 2)
In [15]: a.Z
Out[15]: FortranArray([1, 1, 2, 2], dtype=int32)
In [16]: 

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/

**Comment by noambernstein** [comment]
It’s fairly plausible that how the atoms object was created matters. Are you both doing it the same?

**Comment by Linux-cpp-lisp** [comment]
My `Atoms` was created from an `ase.Atoms` like so:
```
a = quippy.Atoms()
a.copy_from(some_ase_atoms_object)
```

(Might -- or might not -- be relevant that, before trying to add the atom and getting the error, I delete some other atoms from `a` using `del`: `del a[indexes]`)

**Comment by jameskermode** [comment]
Can you give full script that reproduces this error?

**Comment by gabor1** [comment]
I used a constructor directly from an ase atoms object

-- Gábor

**Comment by gabor1** [comment]
I can confirm that this works in the latest docker:

import ase
import quippy
a = ase.Atoms('H2')
b = quippy.Atoms(a)
b.add_atoms((0.0,0.0,0.0), 2)

**Comment by Linux-cpp-lisp** [comment]
If I do the copy the way gabor1 shows:
```
qp_atoms = quippy.Atoms(some_ase_atoms)
```
then `qp_atoms.add_atoms((0.0, 0.0, 0.0), 2)` works perfectly.

But using `copy_from`, I still get the error.

On my installation, this script
```
import ase, quippy
a = ase.Atoms("H2")
b = quippy.Atoms()
b.copy_from(a)
b.add_atoms((0.0, 0.0, 0.0), 2)
```
still produces
```
RuntimeError: Traceback (most recent call last)
  File "/home/.../QUIP/src/libAtoms/Atoms.f95", line 1425 kind unspecified
    Atoms_Add: this atoms has no species property
```

**Comment by jameskermode** [comment]
Sorry for slow response. `copy_from()` is a low-level routine, not designed to work with generic objects. If you convert `a` to a `quippy.Atoms` before calling `copy_from()` as in the following i works as expected:

```python
import ase, quippy
a = ase.Atoms("H2")
b = quippy.Atoms()
b.copy_from(quippy.Atoms(a))
b.add_atoms((0.0, 0.0, 0.0), 2)
```

**Comment by Linux-cpp-lisp** [comment]
@jameskermode OK, makes perfect sense -- I think that closes this issue. 

Maybe a note to that effect wouldn't be out of place in the documentation?
