### ISSUE TITLE
Totally amorphous structure in equilibration

### ISSUE THREAD

**Issue by ali-hmd** [libAtoms/QUIP#109]
Hi,
I am using silicon GAP_2017_6_17_60_4_3_56_165 (LAMMPS+QUIP). When I am trying to equilibrate the system (300K, 10ps, Langevin+NVE+NVT ) instead of getting a relaxed crystal, the primary crystalline structure turns into a totally amorphous system. 
isn’t it weird? I suppose it’s related to the reference ab initio data with which GAP was trained, but does it mean that producing a perfect, equilibrated crystalline structure with GAP isn’t possible?

Thanks.
Ali.

**Comment by gabor1** [comment]
Something is obviously wrong, let’s figure out what. We’ve done lots of MD with that potential all over the phase diagram, and it should be very stable for a wide range of temperatures and pressures. Can send us your LAMMPS input file and starting condifugration? Did you compile things yourself, or is this in our Docker ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ali-hmd** [comment]
> Something is obviously wrong, let’s figure out what. We’ve done lots of MD with that potential all over the phase diagram, and it should be very stable for a wide range of temperatures and pressures. Can send us your LAMMPS input file and starting condifugration? Did you compile things yourself, or is this in our Docker ?
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 21 Oct 2018, at 16:21, alihamedanifme ***@***.***> wrote: Hi, I am using silicon GAP_2017_6_17_60_4_3_56_165 (LAMMPS+QUIP). When I am trying to equilibrate the system (300K, 10ps, Langevin+NVE+NVT ) instead of getting a relaxed crystal, the primary crystalline structure turns into a totally amorphous system. isn’t it weird? I suppose it’s related to the reference ab initio data with which GAP was trained, but does it mean that producing a perfect, equilibrated crystalline structure with GAP isn’t possible? Thanks. Ali. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.



I compiled quip and LAMMPS myself. 
I've enclosed input, dump files, and geometry data.
[Run.zip](https://github.com/libAtoms/QUIP/files/2499506/Run.zip)

**Comment by gabor1** [comment]
Your "sparseX" file (the one with filename ending in 1) is not what it claims to be. Instead of the sparseX file it contains the original fitting database. Where did you get these files from? You must have renamed it by accident.

-- Gábor

**Comment by ali-hmd** [comment]
> Your "sparseX" file (the one with filename ending in 1) is not what it claims to be. Instead of the sparseX file it contains the original fitting database. Where did you get these files from? You must have renamed it by accident.


Thank you very much, you were right. Everything goes well now. I got all files from "Silicon-testing-framework" directory here:
https://github.com/libAtoms/silicon-testing-framework/tree/master/models/GAP
