### ISSUE TITLE
object full, no more descriptors can be added

### ISSUE THREAD

**Issue by Leeyenxie** [libAtoms/QUIP#111]
Hi,
I tried to train a diamond system with 947 configurations , every configuration contains 64 atoms.
When I trained the configurations, it aborted "gpFull_addCoordinateDerivatives : object full ,no more descriptors can be added".

The teach_sparse command I used which was trained for Graphene (just for test).When I use 2b descriptor only , it was OK. But when I added 3b or soap into command ,it aborted the error as above. I couldn't find any related options in command.

I compared my xyz file with graphene (which offered by libatoms) , I found both the number of configurations and atoms in every configuration were smaller than graphene file.

Maybe there was something I missed?
Any suggetions?

Thanks in advance,
Yen

[Training_diamond.xyz.txt](https://github.com/libAtoms/QUIP/files/2603212/Training_diamond.xyz.txt)

**Comment by gabor1** [comment]
Can you post the exact command line (E.g. with 3b) that fails?

At what number of configurations does it fail for you? Easy to check just cut the file in half etc.

I'm sure we can sort it out, we've trained bigger datasets than graphene.. 

How much memory does the machine have that you are using?

-- Gábor

**Comment by Leeyenxie** [comment]
Hi , gabor

The Machine memory available : 125GB

The command line:
distance_2b cutoff=4.2 n_sparse=50 covariance_type=ard_se delta=10.0 theta_uniform=1.0 sparse_method=uniform : angle_3b cutoff=4.2 n_sparse=200 covariance_type=ard_se delta=3.663 theta_uniform=1.0 : soap l_max=8 n_max=8 atom_sigma=0.4 zeta=2 cutoff=4.2 cutoff_transition_width=1.0 n_sparse=650 delta=0.1 covariance_type=dot_product sparse_method=cur_points add_species=F

The number of configurations for 700 was still OK. 

But I think it may not related to the memory, in my machine I can training the graphene, it was larger than my system.
And I find a wired thing,when there are a lot of repetition configurations (copy and paste),and the number of  configurations even over 1000,it would not abort the error yet.

I think it could't be the problem for file format, or it will abort other errors.

Yen,

**Comment by albapa** [comment]
This is the first time I see this. It's an integer overflow problem: the angle_3b cutoff is so large that it has incredibly many descriptors per config and even more derivatives. We count how many we have, and getting close to the end, the counter overflows and everything goes bad after that.

For the time being, I suggest using a smaller cutoff for angle_3b - I don't think GAP would be able to fit so many terms anyway.

@gabor1 , catching the negative number should be relatively easy, but should we do something more clever as well?

**Comment by gabor1** [comment]
It's true that a long 3b cutoff isn't very physical. 

Can you run it with just 2b and soap? That should be enough to give you a good potential

-- Gábor

**Comment by Leeyenxie** [comment]
Hi,
Yeah,I reduce the cutoff of 3b descriptor it worked !
But I still can not understand why the command above could work on graphene..Maybe it relates to the configuration itself?

Anyway, 
Thanks a lot for gabor,albapa

Yen,

**Comment by gabor1** [comment]
A lot fewer terms appear in graphene because it is 2D

> On 21 Nov 2018, at 11:53, Leeyenxie <notifications@github.com> wrote:
> 
> Hi,
> Yeah,I reduce the cutoff of 3b descriptor it worked !
> But I still can not understand why the command above could work on graphene..Maybe it relates to the configuration itself?
> 
> Anyway,
> Thanks a lot for gabor,albapa
> 
> Yen,
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by Leeyenxie** [comment]
Hi,gabor
Yeah,It seems reasonable

Yen,
