### ISSUE TITLE
traj file reads

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#113]
When reading an ASE *.traj file with Quippy, only the first image is read. This is the opposite behavior that ASE has, where ASE reads the last image of the trajectory. For instance, if one does a geometry optimization with ASE that takes 100 ionic steps and saves it in "opt.traj", the following will happen when opening this file: ase.Atoms("opt.traj") will contain the positions of the 100th snapshot (presumably the optimized structure) and quippy.Atoms("opt.traj") will contain the positions of the 1st snapshot (the initial configuration before optimization). For those users that expect the same kind of behavior as ASE this may lead to problems.

On the online documentation *.traj is not on the list of supported file formats (so this is not a bug), but Quippy actually reads this file format without raising any errors. Is this the intended behavior?

**Comment by jameskermode** [comment]
quippy invokes `ase.io.read()` for `.traj` files. As with ASE, I think you can do `read("filename@:")` to read all the frames. 

To prevent this kind of confusion, I/O support will be dropped from quippy in the near future, with users required to use the standard `ase.io` functions instead.

**Comment by mcaroba** [comment]
Hi James,
For me, ase.io.read("opt.traj") and quippy.Atoms("opt.traj") are different. The first one reads the last snapshot and the second one reads the first snapshot. Does Quippy come with its own ASE files (perhaps it's obsolete behavior)?

(And you're right about the way to read all frames, you can also do atoms=ase.io.Trajectory("opt.traj") and in both cases then use atoms[-1] for the last snapshot)

**Comment by jameskermode** [comment]
No duplicated sources, just different defaults passed along from quippy to ASE - `quippy.Atoms()` has a default of `index=0` (first frame) while `ase.io.read()` defaults to `index=-1` (last frame). You can overritde with the `"filename@index"` syntax above or by passing `index` explictly. Haven't checked code so some argument names may be wrong, but this is basic point.

**Comment by mcaroba** [comment]
Aha, yes, that's the one. Thanks.

**Comment by jameskermode** [comment]
This confusion is one of the motivations for removing the I/O from quippy...

**Comment by gabor1** [comment]
can I close this now?

**Comment by jameskermode** [comment]
ok with me
