### ISSUE TITLE
isinstance error 

### ISSUE THREAD

**Issue by lipai** [libAtoms/QUIP#114]
I recently read the article published in PRX about GAP, and downloaded the GAP potential file and installed quippy. When i run these tests, i encountered a problem as follows:

>   File "/public/home/zyli/lipai/anaconda2/lib/python2.7/site-packages/quippy/atoms.py", line 365, in __init__
>      if symbols is not None and isinstance(symbols, PhonopyAtoms):
>  TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

 	I modified the "PhonopyAtoms" of the pointed line 365 in atoms.py into "type(PhonopyAtoms)", and it ran successfully. I do not know why this error happens and if my modification is ok. anyone can give me some suggestions on this issue?

**Comment by gabor1** [comment]
This is about to change, we are reengineering the quippy Atoms module (move even more towards ASE atoms)
