### ISSUE TITLE
3 Body cutoff 

### ISSUE THREAD

**Issue by g7dhaliwal** [libAtoms/QUIP#115]
Hi,

   While using GAP, I noticed that cutoff value from 3body descriptor is not equal to product of the respective cutoffs from two body descriptor, for same value of cutoff radius and transition width.

i.e. Cutoff_3B(i,j,k) != Cutoff_2B(i,j) * Cutoff_2B(i,k)

eg. if r[0,1] = 1.43762868, r[0,3] = 3.7836012, r[1,3] = 2.45374383 , then Cutoff_3b(0,1,3) = 0.9325913171341882 but product of the respective cutoffs from 2B descriptor is 0.3701840891244345. The cutoff radius for both the cases is 4.2 angstroms and transition width is 1 angstroms.

My understanding from the paper (arXiv:1502.01366v1) and please correct me if I am wrong, is that Cutoff_3b(i,j,k) = cutoff(i,j) * cutoff(i,k). Is this cutoff(i,j) same as Cutoff_2B(i,j)? I will really appreciate of your help here.

**Comment by gabor1** [comment]
The 2b term has its own cutoff, and the 3b term has its own cutoff, which you need to set separately. Each descriptor has its own separate cutoff (e.g. you can have multiple 2b terms if you like, each with their own cutoff)

The 3b term includes two distances, and the cutoff (which you set specifically for the 3b term) is indeed multiplied for AB and AC distances for the three atoms ABC that correspond to a 3b term. 

Let me know if it’s still unclear. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by g7dhaliwal** [comment]
Hi Gabor,

   Thanks for your response. I understand that cutoff should be set seprately for 2B and 3B. What confuses me is that what should be the functional form of the cutoff function for 3 b terms? The cutoff function used in the paper is as shown in the screenshot below. As you mentioned in your comment, cutoff values for 3b terms are multiplied for AB and AC distances.

If so, the value of cutoff(A,B,C) from quippy is not coming equal to the product of cutoff(A,B) and cutoff(A,C), i.e. cutoff(A,B)*cutoff(A,C)? The code that I used to generate quippy descriptors is 

desc = descriptors.Descriptor('angle_3b cutoff=4.2 cutoff_transition_width=1.0')
at2.set_cutoff(desc.cutoff())
at2.calc_connect()
d=desc.calc(at2, grad = True)

cutoff(A,B,C) can be easily obtained using gradient indices.

Using the same functional form, seperate cutoff values can be obtained for AB and AC distances [ for same values of cutoff radius (4.2) and transition width(1.0) ]. The product of these cutoff values, i.e., cutoff(A,B) and cutoff(A,C) is not coming equal to cutoff(A,B,C).

**Comment by g7dhaliwal** [comment]
![screen shot 2019-01-01 at 4 52 06 pm](https://user-images.githubusercontent.com/5044382/50576841-b0206e80-0de8-11e9-80c2-7ec1bea56c3e.png)

**Comment by g7dhaliwal** [comment]
An example of this mismatch I presented in my first post, reproduced as below

AB = 1.43762868
AC = 3.7836012
BC = 2.45374383

cutoff(A,B,C) = 0.9325913171341882  (computed using quippy)

Using the above expression, the following cutoff values are computed 
cutoff(A,B) = 1.0
cutoff(A,C) = 0.3701840891244345

As you can see, cutoff(A,B,C) != cutoff(A,B) * cutoff(A,C). The cutoff radius (denoted as rCut in the screenshot) is 4.2 and transition width (denoted as d in the screenshot) = 1.0

**Comment by gabor1** [comment]
hm.. might be a bug. does it work correctly for a transition width of 0.5 (rather than 1.0) ? 

> On 1 Jan 2019, at 23:28, g7dhaliwal <notifications@github.com> wrote:
> 
> An example of this mismatch I presented in my first post, reproduced as below
> 
> AB = 1.43762868
> AC = 3.7836012
> BC = 2.45374383
> 
> cutoff(A,B,C) = 0.9325913171341882 (computed using quippy)
> 
> Using the above expression, the following cutoff values are computed
> cutoff(A,B) = 1.0
> cutoff(A,C) = 0.3701840891244345
> 
> As you can see, cutoff(A,B,C) != cutoff(A,B) * cutoff(A,C).
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by g7dhaliwal** [comment]
Hi Gabor,

  Transition width equal to 0.5 gave matching results i.e cutoff(A,B,C) = cutoff(A,B) * cutoff(A,C)

**Comment by gabor1** [comment]
OK, in this case I know what the bug is. instead of passing the correct transition width, the code uses 0.5 hardcoded. this only affects the angle_3b descriptor. Thanks for catching it!

> On 2 Jan 2019, at 18:37, g7dhaliwal <notifications@github.com> wrote:
> 
> Hi Gabor,
> 
> Transition width equal to 0.5 gave matching results i.e cutoff(A,B,C) = cutoff(A,B) * cutoff(A,C)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by g7dhaliwal** [comment]
Thanks for your help. 

Happy new year to you and your team!

**Comment by gabor1** [comment]
I submitted a fix, let me know if it works. (The fix will make it to the docker eventually, you might want to pull the GAP tarball as linked from libatoms.org website)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
did my fix work?

**Comment by g7dhaliwal** [comment]
Thanks. It works for different wCuts.

**Comment by g7dhaliwal** [comment]
Thanks. It works for different wCuts.
