### ISSUE TITLE
GAP training parameters

### ISSUE THREAD

**Issue by lipai** [libAtoms/QUIP#116]
hello!
I have a relative large training set. when i try to run teach_sparse, i encountered an error as follows:

gp_predict.f95", line 468 kind unspecified
gpCoordinates_setParameters: negative value of n_xPrime = -1298356960 

I noticed the cutoff value in GAP example is relatively smaller than that in ANN potential.
if i want to get a more accurate potential, what is the more important parameter i need to adjust, the cutoff or the n_sparse?

**Comment by gabor1** [comment]
Hi ! Can you post your entire training command line, and a small sample of your XYZ file ? 

Both cutoff and n_sparse are important. Cutoff is a physical parameter of your model, it set the radius of the environment that is taken into account when predicting the energy (and derivatives) of an atom. n_sparse is the size of the basis. Typically to get more accuracy, you need either a larger cutoff or a larger n_sparse or both. But first you must check that you have a reasonable potential in the first place, i.e. eliminate other more trivial sources of problems. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Also, how large is your training set, what is the total number of atoms in it? 
-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai** [comment]
Hi,
this is my setting:
```
gap = "distance_2b cutoff=5.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=200 : angle_3b cutoff=4.5 covariance_type=ard_se delta=0.5 theta_fac=0.5 add_species=T n_sparse=250 sparse_method=uniform"
```
my training set size is :
```
Number of target energies (property name: energy) found: 20933
Number of target forces (property name: forces) found: 4976535
```
I delete half of structures in training set, but it still fails.
Now i just maintain 1/3 structures, and it is runing without this error.

Besides, i have also encountered another error when I using the full training set:
```
SYSTEM ABORT: Traceback (most recent call last)
File "/home/lipai/bin/QUIP/src/GAP/gp_predict.f95", line 1194 kind unspecified
gpFull_addCoordinateDerivatives: object full, no more descriptors can be added 
```

**Comment by gabor1** [comment]
How many different atomic species do you have?

**Comment by gabor1** [comment]
I have some comments on your training line. You are using a 2-body (one dimensional) and a 3-body (3-dimensional) descriptor. For your 2-body descriptor, you are using 200 Gaussians (n_sparse). This is complete overkill, use just 20. For your 3-body, you are using 250 Gaussians, which may be needed, but still sounds like a lot, I'd try with 50 first, then maybe a 100.

**Comment by lipai** [comment]
Hi, gabor
thank you for your quick response. I will try reducing n_sparse. My training set structures are as follows:
```
59
Lattice="7.710900 0.000000 0.000000 0.000000 8.904000 0.000000 0.000000 0.000000 26.296000 " Properties=species:S:1:pos:R:3:forces:R:3 energy=-325.48179926 pbc="T T T"
Cu            5.07787      6.01351     26.18833         0.167274      0.001266      0.148235
Cu            1.14837      8.05678      0.81199         0.538564      1.421208      0.679445
Cu            3.39160      4.65712      3.93117         0.638171     -0.205534      0.103606
Cu            4.85243      2.46585      5.26414        -0.060261      0.268843      0.957807
Cu            0.10020      1.48993      1.26861         0.996868     -0.965811      1.289205
Cu            2.32993      6.24932      2.54773         0.054861      0.605603     -0.273560
Cu            1.54017      5.83010      5.45563         0.228580      0.240225     -0.225310
Cu            4.01153      7.77769      1.16552        -0.290858      0.494083      0.352430
Cu            6.07945      6.10298      4.60923        -0.122813      0.485508     -0.220197
Cu            6.88046      2.63037     25.99319        -0.368431      1.080807     -1.469504
Cu            4.87871      0.09862      3.43011        -1.588967     -0.740208     -1.203878
Cu            6.74095      3.75824      4.54424        -0.353278     -0.108980      0.694266
Cu            2.63810      1.36680      1.22162        -0.285213      0.488995     -0.951024
Cu            4.63600      3.69539     25.62752         0.061016     -0.242002      0.191155
Cu            3.80710      2.20359      3.22793        -0.395216      0.661049     -0.727314
Cu            2.33448      0.04319      3.01977        -0.556228     -0.607552     -0.097676
Cu            1.09155      2.36784      3.21568         0.508028      0.315873     -0.001463
Cu            1.65939      3.55475      5.21931         0.180207     -1.005180     -0.152449
Cu            2.63644      0.96684      5.18486         0.863595     -0.079573     -0.119575
Cu            3.28250      3.89981      1.25037         0.388030      0.268474      0.768646
Cu            0.85433      7.95005      4.73643        -0.467873      0.439650     -0.438119
Cu            0.37013      1.41916      5.36746        -1.148949      0.002731     -0.074178
Cu            1.98673      6.03471      0.19141         0.978736     -1.041444     -0.378486
Cu            5.01503      1.68046      0.88077        -0.388340     -1.020770      0.002173
Cu            7.55972      6.20876      1.37172        -1.047245     -0.253995     -0.361194
Cu            6.66605      8.72366      0.12723        -0.847766     -0.527206      0.252439
Cu            5.03455      5.78322      2.25043         0.042575      0.085754      0.746462
Cu            3.37083      7.39838      4.49460         0.110602     -0.857293      0.336845
Cu            6.82834      8.10937      2.74887         1.026014     -0.302919     -0.179324
Cu            4.56624      4.99753      6.55992         1.068341     -2.002460     -1.879657
Cu            6.42443      1.73056      3.38424         0.632817     -0.068288      0.112619
Cu            0.41938      4.94605      3.25888         0.573165      0.410771      0.345053
Cu            5.12747      8.72294      5.59597         0.316615      0.110581      1.219826
Cu            0.92658      3.96898      1.08719        -0.599083     -0.449431     -0.120340
Cu            6.00514      3.52310      1.80689         0.420899      1.259951      0.448685
Cu            2.23663      2.85828     25.54211        -0.081969      0.176415      0.636173
C             0.78657      5.69463      7.73515        -0.170085     -5.330510     -0.122342
C             3.18289      5.69535      7.46522         1.573680      1.681137      2.439033
C             7.20988      7.96481      8.17728         1.767014     -7.378925     -1.574275
C             0.86595      7.01837      7.93105        -1.337396      6.066930      0.574528
C             0.89914      1.16004      8.07364        -0.920976     -0.016588     -0.164657
C             2.16809      7.71238      7.95063        -1.048050      2.460340      2.787133
C             3.41707      7.06206      7.98365        -0.871117      0.419441     -2.498747
C             3.27104      0.99288      8.03785         9.119644      6.833127     -2.473272
C             7.31970      0.39523      8.24047        -0.792229      2.748160     -0.151951
C             7.34535      3.44634      7.82072        -3.425729     -1.739589     -1.834366
C             0.88548      2.65398      7.74674        -0.833932     -1.026458      2.602640
C             2.19843      0.35253      8.22083        -7.820032     -4.096117     -1.207341
C             2.17214      3.34519      7.79765        -2.783768      2.416838     -0.878868
C             3.28264      2.56032      7.71392         4.835837     -3.168815      0.016691
C             7.18818      4.91064      7.47517         1.834318      0.007065      2.840194
C             2.09366      4.89938      7.83035        -1.253063     -1.095372     -1.702538
C             6.02279      5.77086      7.45430         0.457462      0.011699      0.363138
C             4.73292      7.89322      7.91934        -2.886345     -3.775635     -0.453046
C             5.88307      7.10872      7.96067         5.190935      0.698578     -0.319515
C             5.96432      1.00987      8.22244         2.482826      5.153391     -2.105064
C             4.78851      0.36371      7.80687        -4.282662      0.117006      2.382757
C             4.68168      3.02058      7.21241        -0.199611     -0.261129      1.803247
C             5.95709      2.48854      7.84186         0.230327      0.973117     -0.732408
```

**Comment by gabor1** [comment]
If you only have 2 species then  these potentials just correspond to a few hundred free parameters. In order to set them, you are giving it nearly 5 million pieces of data. This is completely unnecessary. A few hundred parameters can be very well determined by a few thousand pieces of data. So I suggest that you very aggressively subsample your data. It's simply not necessary. Your potential will not become better by using 5M data points. 

In order to significantly improve the accuracy, you will likely need to go beyond 3-body terms. the SOAP descriptor will give you a full many-body description. I suggest starting it with n_sparse=500 (and then go up in factors of 2), and again much less data, maybe start with 50-100k force components. The training will take hours. The largest training we have ever done used 300k force components.

**Comment by gabor1** [comment]
WIth 2 species, make sure you include the isolated atom in your training configuration (one for each species) . it helps to partition the total energy into atomic energies.

**Comment by gabor1** [comment]
Do you still have a problem, or can I close this issue ?

**Comment by lipai** [comment]
sorry, i just get your message. please close this issue. thank you.

**Comment by ZengZezhu** [comment]
Dear gabor,

Sorry to bother you,  I also encountered this same problem when used the gaps to fit the potential. 

This is my input:  ! gap_fit energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=stress do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.001 0.01 0.01 0} gap={distance_2b cutoff=6 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=20 : angle_3b cutoff=6 covariance_type=ard_se delta=0.5 theta_fac=0.5 add_sparse=T n_sparse=50 sparse_method=uniform : soap l_max=8 n_max=8 cutoff=6 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 sparse_method=cur_points n_sparse=500  covariance_type=dot_product}

My supercell  has 320 atoms, and I used about 500 structures to generate the training data, so the total number of force components is about 480000. 

After encountering this problem(gpCoordinates_setParameters: negative value of n_xPrime = -182271104), I added the cutoff from 6 to 8 and found that larger cutoff can solve this problem. However, I am so confused about this problem, could you give me some suggestions if I encounter this problem again?

Best,
Zzz

**Comment by gabor1** [comment]
Which cutoff did you increase to 8 ?

I have other comments about your parameters. 

You probably have an _enourmous_ number of 3-body terms. I suggest you take the cutoff of the 2b down to 3 or 4 A. 

You are missing add_species for your SOAP term.

for soap, l_max=8 is overkill, probably ok to use 4 or 6. Are you sure you need all the 500 configurations? 

We have been fitting the entire phase space of Si or C with this amount of data. What is your system, and how wide a range of configurations you are trying to capture? 

Your default_sigma values are very small. We use these for crystalline configurations at low temperature when we want to nail phonons. For defects, liquid, high temperature etc, these settings will result in an overfit I think.

**Comment by ZengZezhu** [comment]
Thank you for you prompt reply.

1. I just added all cutoffs to 8, so I will test decrease the cutoff of 2b and 3b.

2. My system is low-symmetry crystal material with three different elements, and has no defects, liquids or other strange structures. and I fitted the temperature range from 200 to 700, so maybe 500 configurations are ok.

**Comment by ZengZezhu** [comment]
just a simple crystal with low-symmetry (small space group)

**Comment by ZengZezhu** [comment]
I just found that the l_max is 14 in the paper of PRB of GAPs group, so I thought l_max should be larger...

**Comment by gabor1** [comment]
That was before we realised that it was overkill!

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
There is no harm in keeping the 2b cutoff high, but I strongly suggest cutting back on the 3b

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
ok, now I decreased the cutoff of 2b and 3b to 5, and it works.
you mean 3b should use a smaller cutoff than 2b?

**Comment by gabor1** [comment]
yes. I would suggest 6A cutoff for 2b, 3 or 4 A for 3b and between 5 or 6 for SOAP. (hard to say without knowing which atoms you have!)

you also need add_species for the soap!!

**Comment by gabor1** [comment]
If you have just one kind of crystal structure, and low temperature MD, I think you need much less than 500 frames. have you plotted the accuracy as a function of training data size? I would try with just 50...

**Comment by ZengZezhu** [comment]
Thank you so much for your kind help.
My elements are Ba, Te and Ag.

**Comment by gabor1** [comment]
your delta-s are also quite messed up. remember that the delta is per-descriptor, so you are saying currently you expect there to be 1eV energy FOR EVERY ATOM-TRIPLET... I suggest taking down the 3b delta to 0.001. the way I usually set the soap delta is to measure the RMS energy/atom error of the 2b+3b model, and use a soap delta a bit larger than that

**Comment by ZengZezhu** [comment]
Actually the accuracy is high when I used 300 configurations, but I just thought the more configs, the more stable when running the MD.

**Comment by gabor1** [comment]
I would plot a "learning curve", i.e. force component and energy accuracy as a function of input data.

For example, it might turn out that it is the n_sparse=500 that is limiting your accuracy, not the input data amount. 

What sort of energy and force errors are you getting ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
yes, I also plotted the cross-validation of forces, it about 0.05meV/Ang for n_sparse=500.

I am confused about the isolated energy of different elements, and I dont know how to obtain the isolated energy of Ba, Te and Ag. So I just set up a random value to the isolated energy like below:

1
Lattice="20.0 0.0 0.0 0.0 20.0 0.0 0.0 0.0 20.0" Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy=3.21 free_energy=3.21 pbc="T T T"
Ba        0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       3.21000000
1
Lattice="20.0 0.0 0.0 0.0 20.0 0.0 0.0 0.0 20.0" Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy=3.21 free_energy=3.21 pbc="T T T"
Ag        0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       3.21000000
1
Lattice="20.0 0.0 0.0 0.0 20.0 0.0 0.0 0.0 20.0" Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy=3.21 free_energy=3.21 pbc="T T T"
Te        0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       3.21000000

actually 3.21 is the isolated energy of H, but I think it is ok because the gaps only need the relative energy?

**Comment by ZengZezhu** [comment]
0.05eV/ang... sorry

**Comment by gabor1** [comment]
That’s not good! just compute the isolated atom in a big unit cell (lots of vacuum) with the same QM method. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Your force error is quite good. But you should look at the error as a function of QM force for a test set to make sure there are no outliers. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Ok, Thank you for your suggestions. I will refit this potential.

gabor1 <notifications@github.com>于2020年6月29日 周一下午10:33写道：

> Your force error is quite good. But you should look at the error as a
> function of QM force for a test set to make sure there are no outliers.
>
> -- Gábor
>
> Gábor Csányi
> Professor of Molecular Modelling
> Engineering Laboratory, University of Cambridge
> Pembroke College Cambridge
>
> Pembroke College supports CARA. A Lifeline to Academics at Risk.
> http://www.cara.ngo/
>

**Comment by ZengZezhu** [comment]
Sorry, I dont know what is QM....

**Comment by gabor1** [comment]
quantum mechanics. whatever you are using to generate your training data

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
do you mean quantum mechanics?

**Comment by ZengZezhu** [comment]
I see, thanks a lot!

**Comment by ZengZezhu** [comment]
Hi gabor,

I revised the input like below:

! gap_fit energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=stress do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.002 0.03 0.03 0} gap={distance_2b cutoff=7.5 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=20 : angle_3b cutoff=4.5 covariance_type=ard_se delta=0.5 theta_fac=0.5 add_sparse=T add_species=T n_sparse=50 sparse_method=uniform : soap l_max=6 n_max=6 cutoff=6 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 sparse_method=cur_points  add_species=T n_sparse=500 covariance_type=dot_product}

I also calculated the free energy of three elements by VASP and as a input of isolated energy.

However, there is a warning:

WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (50), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor :  angle_3b cutoff=4.5 covariance_type=ard_se delta=0.5 theta_fac=0.5 add_sparse=T 

Could you give me some suggestions?

**Comment by ZengZezhu** [comment]
I solved this problem by adding the cutoff of 3b to 7, and the testing RMSE of forces is 0.04eV/Ang.

**Comment by gabor1** [comment]
I wouldn’t recommend that. the reason you had the error is because with the shorter cutoff, there were some element triplets that didn’t exist. 

I am worried that a 3-body at 7A cutoff will behave badly. two options: either drop the 3b completely, or to list them explicitly so that you are able to exclude the one that doesn’t exist. if you want to try the latter, look at the output of the fit, it lists the descriptors that the add_species converts to, with all elements explicitly specified. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Thanks a lot for the comments.

I think about dropping the 3b completely is more reasonable. I will try

**Comment by ZengZezhu** [comment]
Hi, I totally dropped the 3b model, now the testing RMSE is 0.05eV/Ang ( it is acceptable). Could I have the chance to decrease the RMSE by adjusting the parameters? like N-sparse or l_max? or adding the configurations ? (now I have 370 configurations, 142089 force components)

**Comment by gabor1** [comment]
That’s a pretty good force error, but we can try a few things. Please make plots of the force component error coloured by element, as a function of the magnitude of the quantum force. post the complete command line that you are using. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Also tell me how you generated the training set. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
![rmse](https://user-images.githubusercontent.com/46587891/86127111-fa83c800-bb11-11ea-99b1-7384438568a2.png)
This is my testing RMSE of force.

I generated the training set by running the VASP AIMD at different temperatures.

**Comment by ZengZezhu** [comment]
Yes, the Ba atoms seem have a larger rmse than others.

**Comment by ZengZezhu** [comment]
! gap_fit energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=stress do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.002 0.03 0.03 0} gap={distance_2b cutoff=7.5 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=20 : soap l_max=5 n_max=5 cutoff=6 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 sparse_method=cur_points  add_species=T n_sparse=300 covariance_type=dot_product}

**Comment by gabor1** [comment]
Please plot force ERROR vs vasp force.

why are your energies points on training so different? What are those values near 1 and 2? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
I just added three isolated energies to train, so I think this is the reason between training and testing.

**Comment by gabor1** [comment]
change n_max to 12, leave l_max=5. Lower your force sigma to 0.02, and your energy sigma to 0.001. With these new settings, try n_sparse = 300, 600, 900.  

do you have H atoms? if yes, lower the atom_sigma to 0.4

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Ok, I will try. Thanks a lot!

**Comment by ZengZezhu** [comment]
I still have a problem about the configurations.
If I used the orthorhombic cell to run the AIMD and obtain the configs, but want to run the MD for oblique cell by GAPs potential. Is there any problem for the accuracy of MD?

**Comment by gabor1** [comment]
Not really. What is the size of your supercell in VASP? If you want to change the cell, it is important that your largest supercell is larger in each direction than 12 A (twice your SOAP cutoff). If you have that, then there should be no issue. 

I don't know this system well, but something that we know helps with shear deformations is to include very small primitive cells (if your system allows) with different lattice deformations. But for this your k-point sampling has to be very very fine (0.1 in VASP units). So you should try it without. Easy to test, just make a few oblique cells and test the forces against VASP.

**Comment by ZengZezhu** [comment]
My size of supercell is [15A,15A,15A]

**Comment by ZengZezhu** [comment]
Yes, before running the MD, I will test a few oblique cells, thanks a lot.

**Comment by gabor1** [comment]
then you should not have any problem extrapolating to larger or different cells. 

Note that the SOAP descriptor is very sensitive to densities. So if all your input data is for a given density, the prediction for larger or smaller densities will be very bad. They way to help it is to include a small variation in the volume in the training data (e.g. running MD at slightly different volumes)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
I don't comprehend the density of GAPs very well. But in my opinion, if I
do not consider the thermal expansion and just run the MD to get the
thermal conductivity and phonon properties, then do I still add these new
configurations that have different lattice constants?

**Comment by gabor1** [comment]
well, if you never change the volumes when you predict, then of course you don’t need good predictions at other volumes. but I think your calculation may be physically "wrong", i.e. not what you really want: when you run at high temperature and don’t change the volume, you will get high pressure. so you will get phonons and thermal conductivity at high pressure, instead of ambient pressure.

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
yes, I totally agree with you. However, there are some claims from the
previous paper that the thermal expansion and change of lattice volume is
slight.

**Comment by ZengZezhu** [comment]
you mean If I want to include thermal expansion, so I need to add some
configurations from AIMD at a small positive pressure (like 5Gpa) and a
negative pressure ?

**Comment by gabor1** [comment]
yes. and although it might be slight, that’s why I’m warning you that SOAP is sensitive. +- 1% change in the volume can already show up as worse force and energy prediction. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Ok, thank you for your information. I will add some configurations of
different volumes. But how many configs do I add to refit the potential? I
think it is much smaller than the basic configurations at 0 pressure?

**Comment by gabor1** [comment]
If you were starting from scratch, I would just pick a random volume for each configuration within some range (or using a Gaussian distribution of the volume). If you don’t want to recompute your 300-500 configurations, then you can start with a smaller amount. These recipes are always a bit ad-hoc… if you are really just interested in thermal conductivity at high temperature and ambient pressure, you can ignore the lower volumes for a start, those correspond to high positive pressure.  

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Thank you so much for your kind help. I will try.
