### ISSUE TITLE
ImportError: No module named quippy

### ISSUE THREAD

**Issue by leilakhalili87** [libAtoms/QUIP#117]
Hi,
I am trying to install quippy Python wrappers with GAP. I got no errors by make install-quippy. However when I import quippy it gives the error:ImportError: No module named quippy.

I tired make clean and "'build/linux_x86_64_gfortran/bdist.linux-x86_64' does not exist -- can't clean it" was in the output.
I am running on Ubuntu 16.04 (x86_64) with a Python 2.7 virtual environment. QUIP_ARCH is linux_x86_64_gfortran and Makefile.inc is attached (I added .txt )

Thanks,
Leila
[Makefile.inc.txt](https://github.com/libAtoms/QUIP/files/2750852/Makefile.inc.txt)

**Comment by gabor1** [comment]
Can you please start with a fresh download? Try make clean as the first thing! Make a record of all the commands you use and the output of the compile, and post it.

Alternatively, we have a docker in which everything is already compiled and installed.



-- Gábor

**Comment by leilakhalili87** [comment]
Thanks for your response. I am already using docker, but for some reasons I need to install it on my computer.

I did everything all over again.
these are my commands:
virtualenv -p /usr/bin/python2.7 quippy_env
source quippy_env/bin/activate
git clone --recursive https://github.com/libAtoms/QUIP.git
make clean
export QUIP_ARCH=linux_x86_64_gfortran
make config 
make  #the output is make.txt
make install-quippy  #the output is make_install.txt

[make.txt](https://github.com/libAtoms/QUIP/files/2751128/make.txt)
[make_install.txt](https://github.com/libAtoms/QUIP/files/2751129/make_install.txt)

Thanks,
Leila

**Comment by gabor1** [comment]
Your compile seems fine (looking on my phone) . I don't use virtualenvs myself... So I'm not sure why it's not finding the python module. Maybe someone else could comment..

-- Gábor

**Comment by gabor1** [comment]
You are installing quippy into /home/leila/.local/lib/python2.7/site-packages/ . Are you sure this directory is in your PYTHONPATH ?

**Comment by leilakhalili87** [comment]
Thanks for your response. I couldn't figure it out why it doesn't work in virtual environment. 
However, I could successfully install it globally. 
Thanks, 
Leila
