### ISSUE TITLE
energy baseline e0

### ISSUE THREAD

**Issue by Leeyenxie** [libAtoms/QUIP#118]
Hi,
I try to fit GAP potential recently, but confused by the parameter of energy baseline e0.
For the present work offered by libatoms.org, I found they set e0 default (equals 0) in graphene, and set e0 = -9.19483512529700 in tungsten, I could not found out any law between them. Though, I use `isolated_C = Atoms('C',calculator=EMT())` to get the e0 of C is 3.5.
So, how does e0 influence the final fitting result?  And how could I to determine it?

Yen,

**Comment by gabor1** [comment]
Indeed e0 was confusing to a lot of people. The just changed the code (get the latest from www.libatoms.org), so if you include a configuration in your training set with the isolated atom and its energy, then you don’t need to do anything else, it will be picked up automatically and e0 set correctly (assuming you remove all e0 related keywords from the command line). This also works for multiple species. 

> On 25 Jan 2019, at 03:04, Leeyenxie <notifications@github.com> wrote:
> 
> Hi,
> I try to fit GAP potential recently, but confused by the parameter of energy baseline e0.
> For the present work offered by , I found they set e0 default (equals 0) in graphene, and set e0 = -9.19483512529700 in tungsten, I could not found out any law between them. Though, I use isolated_C = Atoms('C',calculator=EMT()) to get the e0 of C is 3.5.
> So, how does e0 influence the final fitting result? And how could I to determine it?
> 
> Yen,
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by Leeyenxie** [comment]
Hi,gabor
Thanks for your replying!
My understanding is ,e.g. if I train graphene system, and every configuration includes more than one atom, then I need to set the e0 equals 3.5. If I train metal system, e.g. Fe, some configurations include only one atom, in that case, I don't need to set e0 anymore. In other words, the isolated atom means one configuration only include one atom?
I'm not sure my understanding is right or not, if wrong, please give me some advices, thanks!

Yen,

**Comment by gabor1** [comment]
by “isolated atom” I mean a configuration with only one atom in it. 

If you are interested in only connected graphene, and you NEVER want to study defect migration, adding or removing an atoms form the sheet by breaking/forming new bonds, then you don’t need isolated atom. Otherwise you do, and let the e0 be set automatically. 

Even if you set the e0 by hand, but you don’t include the isolated atom configuration, then bond dissociations won’t be properly described. 

> On 25 Jan 2019, at 12:33, Leeyenxie <notifications@github.com> wrote:
> 
> Hi,gabor
> Thanks for you replying!
> My understanding is ,e.g. if I train graphene system, and every configuration includes more than one atom, then I need to set the e0 equals 3.5. If I train metal system, e.g. Fe, some configurations include only one atom, in that case, I don't need to set e0 anymore. In other words, the isolated atom means one configuration only include one atom?
> I'm not sure my understanding is right or not, if wrong, please give me some advices, thanks!
> 
> Yen,
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
can I close this now?
