### ISSUE TITLE
Beginner for installing QUIP + GAP in Ubuntu

### ISSUE THREAD

**Issue by Houcoeng** [libAtoms/QUIP#120]
Hi, dear all users in QUIP + GAP, I cannot install quippy successfully. At the beginning, I try to install in Ubuntu, but I found permission denied. Then I switch to root user using command sudo -s. I can compile it well following the instruction online. Before I start to compile quippy, I already put GAP + GAP-filler under src as routine: src/GAP and src/GAP-filler. But when I run the tutorial of quippy-descriptor-tutorial, they give me that No module named _descriptor. Shown below:

![virtualbox_haoxiang_26_01_2019_16_54_39](https://user-images.githubusercontent.com/27861803/51793726-22d7fc00-2193-11e9-8bc0-d0c81c856c84.png)

![virtualbox_haoxiang_26_01_2019_16_53_32](https://user-images.githubusercontent.com/27861803/51793579-a17f6a00-2190-11e9-9453-3ffc173100a4.png)

Also, I try to compile atomeye under QUIP. 
The procedure as followed: 
1. I set QUIP_ARCH as: export QUIP_ARCH=linux_x86_64_gfortran and set QUIP_ROOT based on routine ${QUIP_ROOT}/build/${QUIP_ARCH}.

2. Under atomeye/, directly using command make, it can compile binary version, but python library cannot. It cannot find libAtomEye.a.

![virtualbox_haoxiang_23_01_2019_11_58_17](https://user-images.githubusercontent.com/27861803/51793720-089e1e00-2193-11e9-8778-fb151ae4805d.png)

![virtualbox_haoxiang_23_01_2019_11_59_35](https://user-images.githubusercontent.com/27861803/51793723-13f14980-2193-11e9-8df1-8f77a88c71c5.png)
 
anyone can help me solve this problem? It hinders me for a while.

Thanks.

**Comment by gabor1** [comment]
Are you sure you have compiled GAP (by saying ‘y’ to the question when you ‘make config’) into the library ? Without that you don’t have descriptors. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Have you gotten this to work? I'm using atomeye on the mac, and dockers don't like X forwarding so there is no easy way for me to check this.

**Comment by gmonpara** [comment]
I am facing problems installing on Ubuntu. When running make install-quippy, I get the following:

![image](https://user-images.githubusercontent.com/9788657/55375081-f8bef500-54c7-11e9-9da8-35a69d6e0e47.png)

**Comment by gabor1** [comment]
Can you post the entire log please

> On 2 Apr 2019, at 04:49, gmonpara <notifications@github.com> wrote:
> 
> I am facing problems installing on Ubuntu. When running make install-quippy, I get the following:
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gmonpara** [comment]
Sure. Could you please tell me where the logfile is located?

Thanks,
Geeta

**Comment by gabor1** [comment]
on your screen???

> On 2 Apr 2019, at 13:32, gmonpara <notifications@github.com> wrote:
> 
> Sure. Could you please tell me where the logfile is located?
> 
> Thanks,
> Geeta
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
so when you type make, pipe the output to a file, and post that file. 

> On 2 Apr 2019, at 13:34, Gabor Csanyi <gc121@cam.ac.uk> wrote:
> 
> on your screen???
> 
>> On 2 Apr 2019, at 13:32, gmonpara <notifications@github.com> wrote:
>> 
>> Sure. Could you please tell me where the logfile is located?
>> 
>> Thanks,
>> Geeta
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> 
> -- Gábor
> 
> Gábor Csányi
> Professor of Molecular Modelling
> Engineering Laboratory
> Pembroke College
> University of Cambridge
> 
> Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gmonpara** [comment]
Here. 
[make.txt](https://github.com/libAtoms/QUIP/files/3033948/make.txt)
[make_install_quippy.txt](https://github.com/libAtoms/QUIP/files/3033949/make_install_quippy.txt)

**Comment by gabor1** [comment]
The fortran compiles fine, it’s only the python that fails - the log doesn’t tell me what kind of python environment you are using, and that’s difficult to debug remotely in any case. I suggest that you use QUIP from the command line, and then ase the ASE python package to manipulate XYZ files, and lammps to run the QUIP potentials that you want. 

Alternatively, you can use our docker, where everything is precompiled:

https://hub.docker.com/r/libatomsquip/quip/

Gabor

> On 2 Apr 2019, at 13:46, gmonpara <notifications@github.com> wrote:
> 
> Here.
> make.txt
> make_install_quippy.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
