### ISSUE TITLE
fatal error: sys/sysinfo.h: No such file or directory on Mac

### ISSUE THREAD

**Issue by ahzeeshan** [libAtoms/QUIP#122]
After running `make` on Mac OS Mojave, I get the following error:
`/Users/zeeshan/Downloads/software/QUIP/src/libAtoms/cutil.c:45:25: fatal error: sys/sysinfo.h: No such file or directory: No such file or directory`

I am using a python virtual environment with `conda`.
>python --version
 2.7.15 :: Anaconda, Inc.

>gcc --version
gcc (MacPorts gcc5 5.5.0_4) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>gfortran --version
GNU Fortran (MacPorts gcc5 5.5.0_4) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by gabor1** [comment]
on PCs I recommend that you use our docker (libatomsquip on dockerhub). that's what I use on my macs. everything is precompiled.

-- Gábor
