### ISSUE TITLE
IndexError in quippy/crack.py

### ISSUE THREAD

**Issue by cyoahs** [libAtoms/QUIP#123]
I am running the scripts for fracture in Silicon from online documentation, and I've found an bug in quippy/crack.py.

In QUIP/quippy/quippy/crack/py, line 1131
`sigma[:,2.1] = 0.0`
The second index is not an integer, which will raise IndexError for numpy.

According the lines before, this line may probably be 
`sigma[:,2.1] = 0.0`

logs:

> Traceback (most recent call last):
>   File "make_crack.py", line 219, in <module>
>     crack_pos = find_crack_tip_stress_field(crack_slab, calc=mm_pot)
>   File "/usr/local/lib/python2.7/site-packages/quippy/crack.py", line 1200, in find_crack_tip_stress_field
>     avg_sigma, avg_decay, calc)
>   File "/usr/local/lib/python2.7/site-packages/quippy/crack.py", line 1131, in fit_crack_stress_field
>     sigma[:,2.1] = 0.0
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by jameskermode** [comment]
Thanks for spotting this - it’s a typo, the dot should be an comma, `sigma[:,2,1]`. Pull request welcome, or else I’ll check in a fix when I’m back in the office next week.
