### ISSUE TITLE
Cant find fortran module during QUIPPY build

### ISSUE THREAD

**Issue by yangjackie** [libAtoms/QUIP#125]
Hi, 

I'm trying to compile the QUIP and QUIPPY code with GAP. the fortran build with intel fortran and icc was OK, as i can use the compiled quip binary to calculate descriptors for molecular structures (which is my primary goal).

However, i have problems to execute

make quippy

to build the Python wrapper. When it proceeds to build the libAtoms, it always gives the following error and crashed:

 File "setup.py", line 124, in func
    raise ValueError("Can't find Fortran module corresponding to file %s" % file)
ValueError: Can't find Fortran module corresponding to file /short/QUIP/src/libAtoms/error.f95
make[1]: *** [build] Error 1
make[1]: Leaving directory `/short/QUIP/quippy'
make: *** [quippy] Error 2

How should i go about fixing this?

Thanks a lot,
Jack

**Comment by gabor1** [comment]
can you post the full output? maybe there are problems earlier. 

I don't know if it's an option for you temporarily, but we have a docker on dockerhub (libatomsquip/quip) where everything is compiled already, including quippy.

**Comment by yangjackie** [comment]
Hi Garbor,

here's the full stacktrace. (p.s. i prefer to do an own compilation as it will be run on the supercomputer)

Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Potentials/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Potentials -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Utils/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Utils -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP-filler/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP-filler -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Programs/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Programs -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/FilePot_drivers/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/FilePot_drivers -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Structure_processors/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Structure_processors -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[1]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
LIBQUIP_OBJS="ts_params.o transition_state.o elasticity.o phonons.o restraints_constraints_xml.o crackparams.o cracktools.o force_machine_learning_module.o real_space_covariance.o structure_analysis_traj_routines.o ScaLAPACK.o Matrix.o RS_SparseMatrix.o QUIP_Common.o Functions.o Ewald.o Multipole_Interactions.o Partridge_Schwenke_Dipole.o IPEwald.o Yukawa.o Multipoles.o IPModel_GAP.o IPModel_LJ.o IPModel_Morse.o IPModel_FC.o IPModel_SW.o IPModel_Tersoff.o IPModel_EAM_Ercolessi_Adams.o IPModel_Brenner.o IPModel_FS.o IPModel_BOP.o IPModel_FB.o IPModel_Si_MEAM.o IPModel_Brenner_Screened.o IPModel_Brenner_2002.o IPModel_TS.o IPModel_Glue.o IPModel_PartridgeSchwenke.o IPModel_Einstein.o IPModel_Coulomb.o IPModel_Sutton_Chen.o IPModel_FX.o IPModel_HFdimer.o IPModel_BornMayer.o IPModel_Custom.o IPModel_ConfiningMonomer.o IPModel_Template.o IPModel_SW_VP.o IPModel_WaterDimer_Gillan.o IPModel_WaterTrimer_Gillan.o IPModel_Tether.o IPModel_LMTO_TBE.o IPModel_Multipoles.o IPModel_FC4.o IPModel_Spring.o IPModel_DispTS.o IPModel_SCME.o IPModel_MTP.o IPModel_MBD.o IPModel_ZBL.o IPModel_LinearSOAP.o IPModel_TTM_nF.o IPModel_CH4.o IP.o FilePot.o CallbackPot.o SocketPot.o Potential_simple.o AdjustablePotential.o Potential.o ElectrostaticEmbed.o quip_unified_wrapper.o quip_lammps_wrapper.o make_permutations_v2.o descriptors.o gp_predict.o descriptors_wrapper.o lbfgs.o error.o System.o LinkedList.o ExtendableStr.o MPI_context.o Units.o linearalgebra.o Quaternions.o statistics.o Dictionary.o Table.o ParamReader.o PeriodicTable.o minimization.o Atoms_types.o Connection.o DomainDecomposition.o Atoms.o RigidBody.o Group.o angular_functions.o steinhardt_nelson_qw.o gamma_functions.o Constraints.o Thermostat.o Barostat.o DynamicalSystem.o Spline.o Sparse.o CInOutput.o clusters.o Structures.o frametools.o nye_tensor.o Topology.o Atoms_ll.o ringstat.o histogram1d.o find_surface_atoms.o k_means_clustering.o SocketTools.o partition.o libAtoms.o libAtoms_misc_utils.o libAtoms_utils_no_module.o cutil.o netcdf.o xyz.o sockets.o m_sax_types.o m_sax_tokenizer.o m_sax_reader.o m_sax_parser.o m_sax_operate.o m_sax_xml_source.o FoX_sax.o m_wxml_escape.o m_wxml_core.o m_wxml_overloads.o FoX_wxml.o FoX_utils.o fox_m_utils_mtprng.o fox_m_utils_uuid.o fox_m_utils_uri.o m_common_attrs.o m_common_buffer.o m_common_charset.o m_common_namespaces.o m_common_error.o m_common_elstack.o m_common_io.o FoX_common.o m_common_namecheck.o m_common_entities.o m_common_notations.o m_common_element.o m_common_struct.o m_common_entity_expand.o m_common_content_model.o fox_m_fsys_abort_flush.o fox_m_fsys_array_str.o fox_m_fsys_format.o fox_m_fsys_parse_input.o fox_m_fsys_count_parse_input.o fox_m_fsys_string.o fox_m_fsys_string_list.o fox_m_fsys_realtypes.o fox_m_fsys_varstr.o" && \
		     cd /short/dy3/QUIP/build/linux_x86_64_ifort_icc && for i in /short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib/libFoX_sax.a /short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib/libFoX_wxml.a /short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib/libFoX_utils.a /short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib/libFoX_common.a /short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib/libFoX_fsys.a; do ar -x $i; done && ar -rcs libquip.a $LIBQUIP_OBJS
make -C quippy -I/short/dy3/QUIP -I/short/dy3/QUIP/arch build
make[1]: Entering directory `/short/dy3/QUIP/quippy'
LD=/apps/intel-ct/bin/ifort CC=/apps/intel-ct/bin/icc F90=/apps/intel-ct/bin/ifort F77=/apps/intel-ct/bin/ifort QUIP_ROOT=/short/dy3/QUIP python setup.py build
Reading .f2py_f2cmap ...
	Mapping "real(kind=dp)" to "double"
	Mapping "complex(kind=qp)" to "complex_long_double"
	Mapping "complex(kind=dp)" to "complex_double"
Successfully applied user defined changes from .f2py_f2cmap
QUIP_ROOT /short/dy3/QUIP
QUIP_ARCH linux_x86_64_ifort_icc
make[2]: *** No targets specified and no makefile found.  Stop.
include_dirs ['/short/dy3/QUIP/src/libAtoms', '/short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/finclude']
libraries ['FoX_sax', 'FoX_wxml', 'FoX_utils', 'FoX_common', 'FoX_fsys']
lib_dirs ['/short/dy3/QUIP/src/fox/objs.linux_x86_64_ifort_icc/lib']
macros [('GIT_VERSION', '\\"https://github.com/libAtoms/QUIP.git,ad62f72-dirty\\"'), ('GETARG_F2003', None), ('FORTRAN_UNDERSCORE', None), ('GIT_VERSION', 'https://github.com/libAtoms/QUIP.git,ad62f72-dirty'), ('QUIP_ARCH', 'linux_x86_64_ifort_icc'), ('SIZEOF_FORTRAN_T', '2'), ('HAVE_GAP_FILLER', None), ('HAVE_GAP', None), ('HAVE_QR', None)]
extra_link_args ['-mkl']
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "quippy.arraydata" sources
building extension "quippy._quippy" sources
Rebuilding target libAtoms with command "cd /short/dy3/QUIP && make libAtoms"
Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
make[2]: Entering directory `/short/dy3/QUIP'
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make[2]: Leaving directory `/short/dy3/QUIP'
Rebuilding target GAP with command "cd /short/dy3/QUIP && make GAP"
Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
make[2]: Entering directory `/short/dy3/QUIP'
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make[2]: Leaving directory `/short/dy3/QUIP'
Rebuilding target GAP-filler with command "cd /short/dy3/QUIP && make GAP-filler"
Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
make[2]: Entering directory `/short/dy3/QUIP'
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Potentials/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Potentials -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Utils/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Utils -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP-filler/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP-filler -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make[2]: Leaving directory `/short/dy3/QUIP'
Rebuilding target Potentials with command "cd /short/dy3/QUIP && make Potentials"
Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
make[2]: Entering directory `/short/dy3/QUIP'
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Potentials/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Potentials -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make[2]: Leaving directory `/short/dy3/QUIP'
Rebuilding target Utils with command "cd /short/dy3/QUIP && make Utils"
Using QUIP_ARCH=linux_x86_64_ifort_icc, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/short/dy3/QUIP
make[2]: Entering directory `/short/dy3/QUIP'
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/libAtoms/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/libAtoms -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/GAP/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/GAP -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Potentials/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Potentials -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
rm -f /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
cp /short/dy3/QUIP/src/Utils/Makefile /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make -C /short/dy3/QUIP/build/linux_x86_64_ifort_icc QUIP_ROOT=/short/dy3/QUIP VPATH=/short/dy3/QUIP/src/Utils -I/short/dy3/QUIP -I/short/dy3/QUIP/arch
make[3]: Entering directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/short/dy3/QUIP/build/linux_x86_64_ifort_icc'
rm /short/dy3/QUIP/build/linux_x86_64_ifort_icc/Makefile
make[2]: Leaving directory `/short/dy3/QUIP'
Traceback (most recent call last):
  File "setup.py", line 502, in <module>
    options=default_options)
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/apps/python/2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/apps/python/2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/apps/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/apps/python/2.7.13/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/apps/python/2.7.13/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/apps/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 322, in build_extension_sources
    sources = self.generate_sources(sources, ext)
  File "/home/561/jy8620/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 375, in generate_sources
    source = func(extension, build_dir)
  File "setup.py", line 124, in func
    raise ValueError("Can't find Fortran module corresponding to file %s" % file)
ValueError: Can't find Fortran module corresponding to file /short/dy3/QUIP/src/libAtoms/error.f95
make[1]: *** [build] Error 1
make[1]: Leaving directory `/short/dy3/QUIP/quippy'
make: *** [quippy] Error 2

**Comment by gabor1** [comment]
Is it possible that your python needs to have been compiled with the same compiler? Can you try to switch to gcc/gfortran and see if that works? You can still of course use the fort-compiled command line tools. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by yangjackie** [comment]
Hi Gabor,

managed to get it compiled on my ubuntu laptop with gfortran/gcc. so i'll stick with it for the moment. 

On the supercomputer my python seems to be a bit problematic particularly with numpy, that's a separate issue for the moment

thanks a lot for the helps!

Jack
