### ISSUE TITLE
LA_Matrix_Factorise error when training a GAP model

### ISSUE THREAD

**Issue by cyoahs** [libAtoms/QUIP#126]
I am trying to make a GAP on my own dataset with an EAM potential as the core_ip and RDF as the descriptor. I succeeded a few times with a similar dataset using EAM+SOAP or 2b+SOAP but failed when using RDF.

Here is the error message.

> SYSTEM ABORT: Traceback (most recent call last)
> File "/opt/quip/src/libAtoms/linearalgebra.f95", line 2309 kind unspecified
> LA_Matrix_Factorise: cannot factorise, error: 114

The error code turns to be different in several tests. It can be 82, 10, 62, 25 in different tests.

Here in my input script.

```
#!/bin/bash
teach_sparse at_file=Cu.bulk_all_surf_8000.xyz do_copy_at_file=F gap={rdf n_gauss=30 cutoff=6.5 Z=29 covariance_type=dot_product delta=0.5 zeta=4 sparse_method=cur_points n_sparse=9000} default_sigma={0.001 0.01 0.0 0.0} energy_parameter_name=energy force_parameter_name=forces core_param_file=Mendelev_Cu2_2012.eam.xml core_ip_args={IP EAM_ErcolAd} e0={Cu:0} gp_file=gap.xml
```

I have tested `n_gauss` with different values and got this LA_Matrix_Factorise error with different code.

Tests are run both in docker and in icc+mpi+mkl environment with the same error.

The full log is given in the following link.
https://gist.github.com/cyoahs/e43d18565768fc5bda46c485a52ac5ee

**Comment by gabor1** [comment]
The 9000 sparse points possibly. Reduce it to 100 I would say.
The rdf is not a unique descriptor, and you are choosing 30 gaussians to describe it. Also I would use a gaussian (ard_se) covariance function with it, not the dot product. 

-- Gábor

**Comment by cyoahs** [comment]
It works. Thanks a lot for your advice.
Is it caused by the memory?

**Comment by gabor1** [comment]
no, not at all. think about what I said again. you have a pretty redundant descriptor with just 30 components.

-- Gábor

**Comment by cyoahs** [comment]
Thanks for you reply. Does my descriptor make the covariance matrix itself unable to be factorised mathematically?

**Comment by gabor1** [comment]
No I just think it's extremely degenerate. 

-- Gábor

**Comment by cyoahs** [comment]
emmmm......
Perhaps that was actually what I was trying to express. Thank you very much.
