### ISSUE TITLE
Issues building QUIP with GAP

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [libAtoms/QUIP#129]
Hi,

I'm trying to build QUIP on a new system and am having some issues. I download the GAP source code, extracted the `GAP` and `GAP-filler` folders into `src`, and said `y` to the GAP question in `make config`, but I'm getting this error after a while when I run `make`:

```
make[1]: *** No rule to make target `libgap.a', needed by `quip'.  Stop.
```

Thanks,
A.M.

**Comment by gabor1** [comment]
you have an old version of GAP and/or QUIP. the new one doesn't have GAP-filler, only GAP. update your versions, and let me know if it still doesn't work.

**Comment by Linux-cpp-lisp** [comment]
Hi Gabor,

You must be right. I had cloned QUIP earlier today but somehow I must have confused my more recent GAP source with the one from my old installation. Re-downloading solved the problem

Thank you for your help!

Best,
A.
