### ISSUE TITLE
Method calc_connect_hysteretic() does not deal with removing atoms

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#13]
First, was this method (in Atoms_types.f95, or the Python-wrapped version in quippy.atoms.Atoms) ever designed to be called again on an Atoms object after atoms were removed from it (using remove_atoms())? If not, this would be useful for me to have; any idea of how difficult it would be to support this usage?

**Comment by jameskermode** [comment]
None of the neighbour code wa designed with changing numbers of atoms in mind. You would have to re-map the atom indices from the old to the new atoms. If you need this, I would do it from Python, operating on the two sets of connectivity information using the high-level API: http://libatoms.github.io/QUIP/connection.html#quippy.atoms.Connection

**Comment by max-veit** [comment]
OK, I'll think about how to do this, though I might not get to it for a while. Would it make sense to have an integer property (something like `old_id`) to keep track of the IDs of the atoms unaffected by the mutation?

**Comment by max-veit** [comment]
Again closing, as changing the number of atoms (either during or between dynamics runs) is considered nonstandard usage.
