### ISSUE TITLE
different results from old and recent GAP versions

### ISSUE THREAD

**Issue by AssilBouzid** [libAtoms/QUIP#130]
Dear GAP developers,

I am training GAP on a DB made out of some crystal phases of Te oxide (obtained via first principles molecular dynamics) as well as isolated O and Te atoms. When using an old GAP version I get accurate fitting up to few meV/atom energy difference with respect to the DFT energies. Here is the command line I am using:

mpirun -np 2  $bin/teach_sparse_mpi at_file=TRAJEC_step_train_alpha-beta-gamma-Te-O.xyz gap={soap l_max=12 n_max=12 cutoff=5.0 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 config_type_n_sparse={alpha_TeO2:500:beta__TeO2:500:gamma_TeO2:500:Tellure:10:Oxygen:10:default:500} sparse_method=cur_points covariance_type=dot_product} e0_method=isolated sparse_jitter=1e-12 default_sigma={0.0001 0.01 0.01 0.0} config_type_sigma={alpha_TeO2:0.0001:0.01:0.01:0.0:beta__TeO2:0.0001:0.01:0.01:0.0:gamma_TeO2:0.0001:0.01:0.01:0.0:Tellure:0.0001:0.01:0.01:0.0:Oxygen:0.0001:0.01:0.01:0.0} gp_file=gp33b.xml > outputt

Now, I switched to a recent version of GAP and get very different results (using the same input with gap_fit_mpi). Both versions were compiled with the same compilers/options (lapack/3.8.0 blas/3.8.0 gcc/7.3.0 mpi/openmpi/3.1.3). 

For example: old GAP gives me for a given training configuration an energy=-34998.032847130438 eV. 
With the new version of GAP I get an energy=-35047.933170113443 eV. These energies have to be compared with the DFT energy= -34998.28447679 eV. I tried to change e0_method and specify e0 in the input but still have quite different numbers.

Another weird thing is that I have gap_version="0" in my xml file. The old gap_version is 1558090777.

Any input in this issue will be highly appreciated. Thank you!

best regards,
Assil Bouzid

**Comment by gabor1** [comment]
This is potentially serious, thanks for contacting us. Can you please share perhaps as subset of your dataset with which your command line works so that we can study the difference. There was a recent merge of two directories of the source tree.

Can you please also confirm that you are using a fresh clean checkout of both quip and gap?

-- Gábor

**Comment by AssilBouzid** [comment]
I sent you the DB by email to gc121...

Yes I compiled fresh versions of both GAP and QUIP.

**Comment by gabor1** [comment]
I'm looking into this. Can you help by narrowing down which gap_version results in the change? Presumably you are compiling it yourself and not using the docker? Is there a small DB which also shows the change so that we can run the training more quickly to help debug?

**Comment by AssilBouzid** [comment]
Yes I am compiling myself the code. I will send you a tarball with two runs of an old and a recent gap versions. In each folder you will find the GAP input, output, database, Quip run with the generated potential, and an energy comparison file (DFT vs GAP). I will also put a copy of the Quip/Gap source codes.

**Comment by gabor1** [comment]
There was a week around the beginning of June when the GAP code was messed up due to a bad git merge. It would either fail or give silly results depending on which options you chose

> On 4 Jul 2019, at 15:14, AssilBouzid <notifications@github.com> wrote:
> 
> Yes I am compiling myself the code. I will send you a tarball with two runs of an old and a recent gap versions. In each folder you will find the GAP input, output, database, Quip run with the generated potential, and an energy comparison file (DFT vs GAP). I will also put a copy of the Quip/Gap source codes.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Has this been resolved? As far as we know the bad git merge has been fixed now for a while. 

> On 5 Jul 2019, at 18:30, Gabor Csanyi <gc121@cam.ac.uk> wrote:
> 
> There was a week around the beginning of June when the GAP code was messed up due to a bad git merge. It would either fail or give silly results depending on which options you chose
> 
>> On 4 Jul 2019, at 15:14, AssilBouzid <notifications@github.com> wrote:
>> 
>> Yes I am compiling myself the code. I will send you a tarball with two runs of an old and a recent gap versions. In each folder you will find the GAP input, output, database, Quip run with the generated potential, and an energy comparison file (DFT vs GAP). I will also put a copy of the Quip/Gap source codes.
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> 
> -- Gábor
> 
> Gábor Csányi
> Professor of Molecular Modelling
> Engineering Laboratory
> Pembroke College
> University of Cambridge
> 
> Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by AssilBouzid** [comment]
I just come back from vacations, I will check the new version asap.

**Comment by AssilBouzid** [comment]
problem solved, I close this issue. Many thanks!
