### ISSUE TITLE
 Warning: "_OPENMP" redefined

### ISSUE THREAD

**Issue by sujona** [libAtoms/QUIP#131]
There is a gazillion of `Warning: "_OPENMP" redefined` while building QUIP. This is the latest version form `Public` branch.

**Comment by gabor1** [comment]
And your point is?

-- Gábor

**Comment by sujona** [comment]
Well my point was that whatever causes the warning might be an issue. But I guess that's not the case then... At least it clutters the build output and drowns other info/warnings.

**Comment by jameskermode** [comment]
We could probably remove the `-D_OPENMP` from Makefiles where we know that a particular compiler sets it automatically when openmp is enabled, but apart from that it's not a big deal. Pull requests welcome...
