### ISSUE TITLE
energy prediction deviated with different structure

### ISSUE THREAD

**Issue by fkxie** [libAtoms/QUIP#134]
Hi,

Recently, I used GAP to fit a model with the same element but different structures(one model two structures), but the energy predicted by model deviated from its true position(seems to make an average), although the prediction to forces were pretty.

Here's the prediction figure.
![train](https://user-images.githubusercontent.com/43362155/61019769-f37a1c00-a3cd-11e9-857c-651e0cb83d75.png)

And the `teach_sparse` line is:
```
gap={soap l_max=12 n_max=12 atom_sigma=0.5 zeta=4 cutoff=4.5 cutoff_transition_width=1.0 delta=1.0 covariance_type=dot_product 
sparse_method=cur_points config_type_n_sparse={structure1:2500:structure2:2500}} default_sigma={0.005 0.0005 0.005 0} sparse_jitter=1.0e-12 hessian_parameter_name=dummy virial_parameter_name=virial energy_parameter_name=energy force_parameter_name=force gp_file=GAP.xml
```

When I train the model with the structure separately(one model one structure), the prediction results are precise. That makes sure there's no problem with the dataset. 

So, is there any ways to solve this problem?

Thanks for the suggestion.

F.K.Xie

**Comment by gabor1** [comment]
Interesting . What are these structures, how do they differ?

-- Gábor

**Comment by fkxie** [comment]
Hi, gabor
Thanks for your reply.
Our system is metal Cu, and the structures are bcc and fcc with different temperatures.

fkxie,

**Comment by gabor1** [comment]
Did you exactly the same DFT parameters for the bcc and fcc calculations ? Including using the same k point SPACING (not same grid), and the same electronic temperature? What was your k-point spacing? We find you need at least 0.03 A^-1, but 0.02 is even better for getting consistency between different structures. 

But apart from that, the thing I spot immediately in your training line is that the energy accuracy you ask for is 0.005 per atom, and the force error you specify is much smaller. So the least squares fitting inherent in GAP will put a huge weight on the force (and virial) AT THE EXPENSE of fitting energies. So please try default_sigma={0.001 0.05 0.05 0.0}

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by fkxie** [comment]
Hi, gabor
I'll try to test your new suggestions.

Thanks a lot.
fkxie

**Comment by fkxie** [comment]
I try to reset the default_sigma, and it works!
