### ISSUE TITLE
Using trained potential (GAP.xml) for MD simulations - generating new structures

### ISSUE THREAD

**Issue by vsumaria** [libAtoms/QUIP#135]
I am new at using QUIP and GAP. I was wondering how we can use the GAP.xml file to generate new structures. I recently used GAP to train some surface structures, which worked perfectly well. I want to now use this trained potential to carry out some MD simulations, is there a way to that.

Also, can the training be done using python script instead of command line?

**Comment by vsumaria** [comment]
Oh, I just found the "Potential Objects" documentation (https://libatoms.github.io/QUIP/potential.html), I think I understand how to use the .xml file to use the create a ASE calculator. Thanks.

**Comment by gabor1** [comment]
Or you can use the lammps plugin. Then it's parallel using lammps' parallelization.

-- Gábor

**Comment by vsumaria** [comment]
About the training - is there a way to use python to do it instead of command line? 

Also while submitting the command line code to a computer cluster, does the training happen on parallel cores automatically ?

**Comment by gabor1** [comment]
Not from python. But you can always use a shell command in your python script.. 

If you compiled gap_fit using parallel Makefile (either openmp or MPI) and correctly setting the number of omp threads or using mpirun then yes.

-- Gábor
