### ISSUE TITLE
Operating system error: Cannot allocate memory

### ISSUE THREAD

**Issue by xyk-62** [libAtoms/QUIP#137]
Hi!
when I try to run gap_fit, I encountered an error as follows:

Operating system error: Cannot allocate memory
Allocation would exceed memory limit

**Comment by gabor1** [comment]
Well yes, you need a lot of memory to solve large linear systems. 

-- Gábor

**Comment by xyk-62** [comment]
> Hi!
> when I try to run gap_fit, I encountered an error as follows:
> 
> Operating system error: Cannot allocate memory
> Allocation would exceed memory limit

Does it mean that I need to expand the memory for my computer, or run it on the server?

**Comment by gabor1** [comment]
FYI, when we train using 500,000 scalars as data (energies and forces), and use 10,000 sparse points, we use over 1 TB of memory. things roughly scale linearly with both data and sparse point number.
