### ISSUE TITLE
Specify  an  existing  QUIP  potential  as  a  base-line

### ISSUE THREAD

**Issue by vsumaria** [libAtoms/QUIP#139]
In the "Gaussian Approximation Potentials: A Brief Tutorial Introduction" paper, you mention this: 
"It  is  possible  to  specify  an  existing  QUIP  potential  as  a  base-line,  so energies/forces/virials  are  subtracted  from  the  target values   before   fitting.   These   are   added   back   automatically when   the   potential   is   called.   Naturally,   the   baseline   can   be another   GAP,   resulting   in   hierarchical   models   with   arbitrary level  of  recursion."

Can you please help me understanding this?

**Comment by gabor1** [comment]
can you help me by focussing on which part of the quote you don’t understand? 


> On 29 Jul 2019, at 19:07, vsumaria <notifications@github.com> wrote:
> 
> In the "Gaussian Approximation Potentials: A Brief Tutorial Introduction" paper, you mention this:
> "It is possible to specify an existing QUIP potential as a base-line, so energies/forces/virials are subtracted from the target values before fitting. These are added back automatically when the potential is called. Naturally, the baseline can be another GAP, resulting in hierarchical models with arbitrary level of recursion."
> 
> Can you please help me understanding this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by vsumaria** [comment]
The part- "specify an existing QUIP potential as a base-line"
Does that mean an a trained model can be used to start another training ?

Vaidish Sumaria

**Comment by gabor1** [comment]
We call a baseline a model that you add to to achieve a fit. So if you want to model the energy E, and instead of fitting a GAP to it directly, you define a model M, and write E=M+GAP. 

-- Gábor

**Comment by vsumaria** [comment]
Oh, ok. That makes sense. I was’t thinking of it in that way. 

Thanks. You can close this issue.
