### ISSUE TITLE
atoms from ASE passed into fortran has no species strings

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#141]
If I create an ase.Atoms object and invoke a quippy Potential that's a FilePot, the species strings are empty, so the FilePot creates a bad filepot.xyz file, with blanks for the species.  The attached bug.py script demonstrates the issue.
[bug.py.gz](https://github.com/libAtoms/QUIP/files/3468940/bug.py.gz)

**Comment by gabor1** [comment]
isn't this a problem with the xyz writer? it should be creating the strings from the Z property on the fly

-- Gábor

**Comment by bernstei** [comment]
> On Aug 5, 2019, at 3:02 PM, gabor1 <notifications@github.com> wrote:
> 
> isn't this a problem with the xyz writer? it should be creating the strings from the Z property on the fly

Does the Fortran xyz writer really do that?

							Noam

**Comment by jameskermode** [comment]
The Fortran reader does set both species and Z, but in ASE they’re equivalent so only Z is set. I’ll add species to the converter to QUIP Atoms

**Comment by jameskermode** [comment]
Should now be fixed - we now call `Atoms.set_atoms()` Fortran function which sets Z and species

**Comment by bernstei** [comment]
> On Aug 6, 2019, at 9:28 AM, James Kermode <notifications@github.com> wrote:
> 
> Should now be fixed - we now call Atoms.set_atoms() Fortran function which sets Z and species
> 
> 

Thanks.  I’ll either get back to you or close the issue.

				Noam

**Comment by jameskermode** [comment]
I just tried your filepot example and that still doesn't work, so I think it's not quite there yet...

**Comment by jameskermode** [comment]
(Closed in error by over-optimistic commit dca30c7, reopening)

**Comment by jameskermode** [comment]
I think it really is fixed now, but `make install-quippy` didn't copy over the updated source files for me for some reason.
