### ISSUE TITLE
quippy calculator randomly writes things to stdout

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#143]
Should line 222 of potential.py
```        print('Calling QUIP Potential.calc() with args_str "{}"'.format(args_str))```
be removed, or replaced with a print to stderr?

**Comment by jameskermode** [comment]
This debug print was removed in commit  d204dca (7 Aug)

**Comment by bernstei** [comment]
> On Aug 27, 2019, at 4:15 AM, James Kermode <notifications@github.com> wrote:
> 
> This debug print was removed in commit d204dca <https://github.com/libAtoms/QUIP/commit/d204dca4985d890cc63327d9bba245af378175e7> (7 Aug)
> 

Sorry - I have no idea how this slipped by me.  I actually had the latest github version and everything, but somehow I was still running with an older installation.  I'll close the issue.

							Noam
