### ISSUE TITLE
Dependence of SOAP on unit cell size

### ISSUE THREAD

**Issue by AndreasLeitherer** [libAtoms/QUIP#145]
Hi,

I want to calculate the SOAP descriptor of a structure which is isotropically scaled to reduce the dependency on lattice parameters. The example code below computes the SOAP descriptor for a diamond structure first without and then with scaling of atomic positions and unit cell. It would be desirable to get the same result for both cases, but  the calculated descriptors actually differ. I am aware that this may be a specialized use case  but wanted to ask if there is a way to get around the observed difference in SOAP descriptors? I assume that the calc_connect() function causes the difference.
![Figure_1](https://user-images.githubusercontent.com/34130704/64347318-fcfdba00-cff3-11e9-8a63-8d76c70bde7a.png)

`
import quippy
from quippy import descriptors
import matplotlib.pyplot as plt
import numpy as np

desc = descriptors.Descriptor("soap cutoff=3 l_max=4 n_max=4 atom_sigma=0.5 n_Z=1 Z={6} ")
at = quippy.diamond(3.5, 6)
at.set_pbc(True)
at.set_cutoff(desc.cutoff())
at.calc_connect()
SOAP_descriptor = np.mean(desc.calc(at)['descriptor'],axis=0)

## Scale structure isotropically
scale_factor = 0.9
at.positions *= scale_factor
at.cell *= scale_factor

## compute SOAP descriptor of scaled structure
at.set_cutoff(desc.cutoff())
at.calc_connect()
SOAP_descriptor_with_scaling = np.mean(desc.calc(at)['descriptor'],axis=0)

plt.plot(SOAP_descriptor,label='without scaling')
plt.plot(SOAP_descriptor_with_scaling, label = 'with scaling')
plt.legend()`

**Comment by gabor1** [comment]
Hi! 

You need to create a new scaled soap descriptor in which all the length scales are also scaled. For your case these are the cutoff and the atom_sigma. There is also another parameter for which you are using the default value, but now you should specify it (and scale it) explicitly, that is the cutoff_transition_width. 

-- Gábor

**Comment by AndreasLeitherer** [comment]
Thanks a lot, that soves it.

I would have a follow-up question:
The above example is for pbc=True; when I choose pbc=False, I also get some undesirable behavior in the following scenario (example code below): I define the diamond structure as before, and then scale the atomic positions  and finally calculate SOAP. I do this one time without scaling the cell and one time with scaling the cell - for pbc=False I would expect that the outcome is the same as the unit cell size shouldn't matter - but I suspect that something is happening in the function calc_connect? The difference of descriptors is reduced when simply setting the cell to zero, i.e., [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]].

![Figure_1-1](https://user-images.githubusercontent.com/34130704/64406400-fd449680-d081-11e9-8fc6-941efed01689.png)


`import quippy
from quippy import descriptors
import matplotlib.pyplot as plt
import numpy as np

cutoff = 3.0
atom_sigma = 0.5
cutoff_transition_width = 0.5


desc = descriptors.Descriptor("soap cutoff="+str(cutoff)+" l_max=4 n_max=4 atom_sigma="+str(atom_sigma)+" n_Z=1 Z={6} cutoff_transition_width="+str(cutoff_transition_width))
at = quippy.diamond(3.5, 6)
at.set_pbc(False)
# scale structure positions, but not cell
scale_factor = 0.9
at.positions *= scale_factor
at.set_cutoff(desc.cutoff())
at.calc_connect()
SOAP_descriptor = np.mean(desc.calc(at)['descriptor'],axis=0)

# Now scale also cell  
at.cell *= scale_factor

# compute SOAP descriptor of scaled structure
at.set_cutoff(desc.cutoff())
at.calc_connect()
SOAP_descriptor_with_scaling = np.mean(desc.calc(at)['descriptor'],axis=0)


plt.plot(SOAP_descriptor,label='without scaled cell')
plt.plot(SOAP_descriptor_with_scaling, label = 'with scaled cell')
plt.legend()`

**Comment by gabor1** [comment]
Hm. 

Pbc=false is not supported by quippy. 

-- Gábor

**Comment by noambernstein** [comment]
Sent from my iPhone

> On Sep 6, 2019, at 7:41 AM, gabor1 <notifications@github.com> wrote:
> 
> Hm. 
> 
> Pbc=false is not supported by quippy. 


Is that really true? FORTRAN Quip did used to support nonperiodic cells by setting the corresponding vector to 0 0 0.

     Noam

**Comment by gabor1** [comment]
Did that ever work? Not without special casing it, you could get weird results if you assume that you can enumerate things by adding integer times lattice vector to positions. I can see it could work but I wouldn't bet the code always does the right thing

-- Gábor

**Comment by jameskermode** [comment]
Yes, it did work - but I agree it's not widely supported

Can I just note that this code is using old-quippy with Python 2.7, which we are no longer supporting. Please move to the latest docker images and/or code in current public branch, which works with Python 3.x

**Comment by bernstei** [comment]
> On Sep 6, 2019, at 8:07 AM, gabor1 <notifications@github.com> wrote:
> 
> Did that ever work? Not without special casing it, you could get weird results if you assume that you can enumerate things by adding integer times lattice vector to positions. I can see it could work but I wouldn't bet the code always does the right thing

That's why you shouldn't do that, but instead use the nn list function. It at least used to handle it automatically.  

							Noam

**Comment by AndreasLeitherer** [comment]
So, the Python 2.7 version does support pbc=False? I have been using it quite a lot recently , and also setting the cell vectors to zero seems to work. Is this not supported in Python 3.x versions?

**Comment by jameskermode** [comment]
This was not what I meant to imply - setting pbc should also work in Python 3 - but your script as written will not work with the new quippy since the `Atoms` object, `calc_connect()` routine etc are no longer directly exposed. You should instead pass an ASE Atoms object directly to the `Descriptor` wrapper.

**Comment by AndreasLeitherer** [comment]
Ok, thank you very much - just to clarify and answer my intial question: When settting pbc=False, is setting the cell vectors to 0 the best way or is pbc=False not supported and should not be used?

**Comment by jameskermode** [comment]
From memory they should be equivalent but the only way to be sure is to read the source code :)

**Comment by gabor1** [comment]
If I was doing it, I wouldn't use pbc=false or zero lattice. If I don't want periodicity because I'm doing a molecule I give it a large cell that is beyond twice the cutoff.

This is not my generic view of life, just that I don't trust this particular code to do the right thing for this case.

-- Gábor

**Comment by gabor1** [comment]
can we close this now?
