### ISSUE TITLE
slice_sample command

### ISSUE THREAD

**Issue by fkxie** [libAtoms/QUIP#147]
Hi,
When I use `slice_sample` command to go about MC simulation to generate various deformed lattice, I was confused about some options given by `slice_sample`:

```
Usage: slice_sample lattice='{r r r r r r r r r}' [atom_1={0.0 0.0 0.0}] [atom_2='{r r r}']
                    Z_1='i' [Z_2='i'] [param_file='file'] [init_args='str']
                    [n_configs=60] e0='r' temp='r' lattice_delta='r' [atom_delta='r'] m_max=i
                    [rng_seed=i] [init_d=1]
```

I would like to know what `m_max` and `atom_delta` means and whether the `e0` represents the isolated energy of the atom?

Could any guys tell me something about these options?

Thanks in advance.

fkxie,

**Comment by gabor1** [comment]
This is very old code, and has not been used by any of us for many years. Please read the source code for documentation (..src/Programs/slice_sample.f95)

I have just looked at it, and atom_delta (and lattice_delta) correspond to small increments in the atom and lattice coordinates respectively, when searching for the appropriate range in the slice. E0 is indeed the isolated atom energy and that is used together with the energy returned by the model to compute the pressure and apply any external pressure. Type "slice_sample --help" to get a list of all options, and look at the top of the file for the same. "m_max" seems to me some maximum number of iterations for each sampling of the slice. 



-- Gábor

**Comment by fkxie** [comment]
Hi, gabor
Thanks for your suggestion, I'll look at the source code carefully.


fkxie,
