### ISSUE TITLE
python ImportError:  undefined symbol: dgemm_

### ISSUE THREAD

**Issue by JieLuo0810** [libAtoms/QUIP#148]
I have completed the compilation of quippy. But still have a problem when I import quippy.

[jluo@admin QUIP]$ python 
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quippy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scms/jluo/software/quippy/QUIP/build/linux_x86_64_gfortran/quippy/__init__.py", line 2, in <module>
    import _quippy
ImportError: /home/scms/jluo/software/quippy/QUIP/build/linux_x86_64_gfortran/_quippy.cpython-36m-x86_64-linux-gnu.so: undefined symbol: dgemm_

**Comment by gabor1** [comment]
dgemm is a LAPACK routine, part of the standard mathematics library on your system. Were you able to successfully make the main programs of QUIP ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by JieLuo0810** [comment]
I have successfully make the main programs and got  an executable program 'quip'.  
I can run the example with command:
 

> 'quip at_file=test.xyz init_args='IP LJ' \
 param_file=share/Parameters/ip.parms.LJ.xml E'

**Comment by gabor1** [comment]
OK, so somehow lapack is missing from your python environment. Maybe someone here with more python experience can help? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by jameskermode** [comment]
What is your `MATH_LINKOPTS` setting in Makefile.inc? Most likely it's missing the path to `liblapack.a`, which should be included as a `-L` option.

**Comment by jameskermode** [comment]
If you are using a dynamically (rather than statically) compiled version of lapack you might need to set `LD_LIBRARY_PATH`. You can check which library is being searched for with `ldd _quippy.so`.

**Comment by JieLuo0810** [comment]
I have already set the `MATH_LINKOPTS`  as `MATH_LINKOPTS=-L/home/scms/jluo/.local/lapack -llapack -L/home/scms/jluo/.local/lapack -lblas`, and set the  `LD_LIBRARY_PATH`  in `.bashrc`. The `ldd _quippy.so` results is:
`     linux-vdso.so.1 =>  (0x00007fff58bec000)
       libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f8eaa00e000)
       libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f8ea9ceb000)
       libm.so.6 => /lib64/libm.so.6 (0x00007f8ea99e9000)
       libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8ea97d3000)
       libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f8ea9596000)
       libc.so.6 => /lib64/libc.so.6 (0x00007f8ea91d3000)
       libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8ea8fb7000)
       /lib64/ld-linux-x86-64.so.2 (0x000055c38d6bf000)`
The program is still not working.

**Comment by jameskermode** [comment]
Looks to me like `-llapack` is missing from `MATH_LINKOPTS`

**Comment by gabor1** [comment]
can we close this now please?

**Comment by lvjian8596** [comment]
Using path-to-quip rather than path-to-quip/build/linux_x86_64_gfortran 


> I have completed the compilation of quippy. But still have a problem when I import quippy.
> 
> [jluo@admin QUIP]$ python
> Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import quippy
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/scms/jluo/software/quippy/QUIP/build/linux_x86_64_gfortran/quippy/**init**.py", line 2, in 
> > > > import _quippy
> > > > ImportError: /home/scms/jluo/software/quippy/QUIP/build/linux_x86_64_gfortran/_quippy.cpython-36m-x86_64-linux-gnu.so: undefined symbol: dgemm_

**Comment by gabor1** [comment]
your python doesn't find the linear algebra (lapack) routines

**Comment by lvjian8596** [comment]
I meet the same problem for quippy in Linux, while quippy works well in my MAC. 
quip works in both systems.

The MATH_LINKOPTS in Makefile.inc is set as /home/lvjian/Soft/BLAS-3.8.0/blas_LINUX.a /home/lvjian/Soft/lapack-3.8.0/liblapack.a /home/lvjian/Soft/lapack-3.8.0/librefblas.a  /home/lvjian/Soft/lapack-3.8.0/libtmglib.a

**Comment by gabor1** [comment]
and those have the dgemm function? (check with 'nm')

**Comment by gabor1** [comment]
I guess otherwise 'quip' wouldn't work

**Comment by jameskermode** [comment]
Problem could be that they are static libraries (`.a` files) not compiled with `-fPIC`, so they can't be included in a dynamically linked library. Try using the dynamic versions, named something like `libblas.so` and `liblapack.so` instead.

**Comment by lvjian8596** [comment]
Thanks very much! It works now for a dynamically linked library liblapack.so.
