### ISSUE TITLE
Cannot import objects

### ISSUE THREAD

**Issue by Tolga28A** [libAtoms/QUIP#149]
This looks very fundamental but I just got confused because I heard the same issue from a couple of other people (who ended up with using docker) and I've only seen one thread similar to this and that was not providing any solution.

I installed the package just as it is described and 'import quippy' works without any error. However, it gives 'cannot import name' error when I want to call objects such as 'from quippy import Atoms' where it can not find Atoms object. I'm using Linux Mint 18.3 , and have added the installation directory in PYTONPATH in bashrc (hoping that it is right though).

I'm assuming that there should be a solution without docker or any virtual platform.

**Comment by jameskermode** [comment]
The QUIP Atoms class is no longer exposed directly from quippy, you should use an ASE Atoms instance instead with quippy Potential and Descriptor classes. We appreciate that documentation updates are urgently needed, but for now I suggest looking in the tests/ directory for examples to work from.

**Comment by gabor1** [comment]
Is this python2.7 or python3 ? The latest repo is python3, but the quippy interface is much reduced (essentially the only objects available are Potential and Descriptor) because we want you to use ASE's infrastructure for everything else. You can access the last version which supports python 2.7 by using the python2 tag. 

-- Gábor

**Comment by joshgabriel** [comment]
we resolved the issue with calling Atoms by using ASE. However when trying to call the Descriptor class and instantiate it using `from quippy.descriptors import Descriptor` and then `desc = Descriptor(args_str='distance_2b cutoff=5')` we get the error
> 'quippy' has no attribute 'descriptors_module' 

Same error when running the unit test file QUIP/tests/test_descriptor.py. The traceback shows that the error is thrown in line 74 of quippy.descriptors module : 
`self._quip_descriptor = quippy.descriptors_module.descriptor(args_str)` 

Where is quippy.descriptors_module.descriptor located in the package?

**Comment by jameskermode** [comment]
Do you have the GAP source repository checked out out under `QUIP/src`?

**Comment by Tolga28A** [comment]
I have the same exact issue with joshgabriel and yes I have copied the GAP repository in QUIP/src, but having the same error AttributeError: module 'quippy' has no attribute 'descriptors_module'.

**Comment by gabor1** [comment]
When you made config, did you answer 'y' when asked about GAP support? Please post your Makefile.inc here

-- Gábor

**Comment by joshgabriel** [comment]
GAP was installed successfully. I am able to use the `gap_fit` command successfully from the command line (independent of quippy). Here is the Makefile.inc for reference:

(excluding the top header)

MATH_LINKOPTS=-llapack -lblas
EXTRA_LINKOPTS=
USE_MAKEDEP=1
MAKEDEP=makedep.py
HAVE_CP2K=0
HAVE_VASP=0
HAVE_TB=0
HAVE_PRECON=1
HAVE_LOTF=0
HAVE_ONIOM=0
HAVE_LOCAL_E_MIX=0
HAVE_QC=0
HAVE_GAP=1
HAVE_QR=1
HAVE_THIRDPARTY=0
HAVE_FX=0
HAVE_SCME=0
HAVE_MTP=0
HAVE_MBD=0
HAVE_TTM_NF=0
HAVE_CH4=0
HAVE_NETCDF4=0
HAVE_MDCORE=0
HAVE_ASAP=0
HAVE_CGAL=0
HAVE_METIS=0
HAVE_LMTO_TBE=0
SIZEOF_FORTRAN_T=2

**Comment by jameskermode** [comment]
That looks ok - if you look at `quippy/Makefile`, you will see that it builds the descriptors wrapper only when `HAVE_GAP = 1`, but you do have this set. Can you try rebuilding `quippy` and pasting your output?

**Comment by gabor1** [comment]
One common error is that you initially don't have HAVE_GAP set, (did not answer Y at make config), then when you realise it, you go back and set it, but without a proper make clean, so some parts of the code are not remade. Could this be the problem ?

-- Gábor

**Comment by joshgabriel** [comment]
We did answer 'y' for HAVE_GAP during the make config. The arch is linux_x86_64_gfortran . Just checking, by rebuilding quippy do you mean `make install-quippy` or some other command? We used the sequence `make config`, `make`, `make install` and finally `make install-quippy` after setting the required environment variables as per the installation docs. Note: We tried the `make install-quippy` both under system-wide python 2.7.16 and also an anaconda virtual environment supporting python 3.6.9. We get the same error in both

**Comment by jameskermode** [comment]
`make deepclean; make install-quippy` would be my suggestion - and look for any mention of `descriptors` in the output when it's generating the wrappers

This is new code so we appreciate your patience trying it out.

**Comment by joshgabriel** [comment]
Thanks for your patience in helping us with understanding the code changes. We are looking at how to generate the descriptor vectors as could be done in the previous version's examples.

In the process of building... here is some partial output.. does it look on the right track? 

`gfortran  -x f95-cpp-input -ffree-line-length-none -ffree-form -fno-second-underscore -fPIC -I/home/joshua/Software/NewQUIP/QUIP/src/libAtoms -I/home/joshua/Software/NewQUIP/QUIP/src/fox/objs.linux_x86_64_gfortran_custom_commit_gap/finclude -O3  -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,74a7d3a05-dirty"' -D'GAP_VERSION=1563528539' -D'QUIP_ARCH="linux_x86_64_gfortran_custom_commit_gap"' -D'SIZEOF_FORTRAN_T=2' -DHAVE_GAP -DHAVE_PRECON -DHAVE_QR  -c  /home/joshua/Software/NewQUIP/QUIP/src/GAP/descriptors_wrapper.f95 -o descriptors_wrapper.o
ar src libgap.a make_permutations_v2.o descriptors.o gp_predict.o descriptors_wrapper.o clustering.o`

Later on I get this output..
`In: :_quippy:f90wrap_descriptors.f90:f90wrap_descriptors_module__get__dt_soap_express
get_useparameters: no module descriptors_module info used by f90wrap_descriptors_module__get__dt_soap_express`

Perhaps not the best way to pick the above output up, but here is what I did `make deepclean; make install-quippy | grep descriptors`

Another note: I changed the name of the arch to "linux_x86_64_gfortran_custom_commit_gap" but this refers to the same "linux_x86_64_gfortran". The name change is just to identify the build with the GAP code installed.

**Comment by joshgabriel** [comment]
The build seems to have completed successfully. It ended with these lines, probably finalizing paths to the python modules:
`copying quippy/descriptors_module.py -> build/lib.linux-x86_64-3.6/quippy`

`copying quippy/descriptors.py -> build/lib.linux-x86_64-3.6/quippy`

`copying build/lib.linux-x86_64-3.6/quippy/descriptors_module.py -> build/bdist.linux-x86_64/egg/quippy`

`copying build/lib.linux-x86_64-3.6/quippy/descriptors.py -> build/bdist.linux-x86_64/egg/quippy`

`byte-compiling build/bdist.linux-x86_64/egg/quippy/descriptors_module.py to descriptors_module.cpython-36.pyc`
`byte-compiling build/bdist.linux-x86_64/egg/quippy/descriptors.py to descriptors.cpython-36.pyc`

`zip_safe flag not set; analyzing archive contents...`
`__pycache__._quippy.cpython-36: module references __file__`

Maybe some helpful info here?

**Comment by jameskermode** [comment]
Looks ok to me. Does it still fail to import `quippy.descriptor_module`? Now you can see where it is installed to you can check `import quippy; print(quippy.__file__)` matches the expected directory

**Comment by jameskermode** [comment]
You can also check `make test` from QUIP directory - there is a test of the descriptor interface which should work without installing as it imports from the `build.${QUIP_ARCH}` directory

**Comment by joshgabriel** [comment]
`make test` did not return any failed tests, running 18 tests in 0.282s. 

Unfortunately, `desc = Descriptor(args_str='distance_2b cutoff=5')` still fails with the quippy has no attribute descriptors_module error. Can you clarify what is the expected directory for `import quippy; print(quippy.__file__)`, Is it the site-packages location in the python virtual environment library? Is my usage of the Descriptor class correct as well?

**Comment by jameskermode** [comment]
> Can you clarify what is the expected directory for import quippy; print(quippy.__file__)

wherever you installed it :-) Look at the last output from `make install-quippy` to see where the Python package is being copied

Descriptor usage looks ok, but as I said above start by trying to run the test provided.

**Comment by jameskermode** [comment]
Sorry, just saw that 18 tests ran ok - this includes the descriptor test, so it's working from the local build directory and you are most likely just importing an old version of quippy when you try to use it yourself. Checking the install path as discussed above should help you resolve this; you can either clean up old installations or set `PYTHON_PATH` explicitly so the correct one is found first.

**Comment by joshgabriel** [comment]
Yes looks like I am having conflicting versions of quippy in my python virtual environment. Just some more clarification : what did `make deepclean` do as opposed to `make clean` , just for future reference?

**Comment by jameskermode** [comment]
`deepclean` also rebuilds `FoX` and other bundled libraries

**Comment by Tolga28A** [comment]
We fixed the problem by adding the following line in bashrc file;

export PYTHONPATH="address/:$PYTHONPATH"

where address is the directory of the quippy installation. I am not sure if this would create any problem about using other Python packages but I think this is gonna work for me. 

Thank you so much for your patience, quick replies and helpful manner, I'm closing the issues.
