### ISSUE TITLE
relaxation with finite difference virials not working if "force" property is present in input file

### ISSUE THREAD

**Issue by gabor1** [libAtoms/QUIP#15]
This is a really weird bug. Take the small xyz file below, and try to relax it including the lattice. it will fail. If you remove the "force" property from the input file, which should have absolutely nothing to do with the calculation, then it works. If the lattice is not relaxed, then it also works.  the command line below has the LJ potential, but the bug exists for all potentials. 

here is the command line: 

~/Code/QUIP/build/darwin_x86_64_gfortran/quip at_file=tmp.xyz param_file=~/Code/QUIP/share/Parameters/ip.parms.LJ.xml E F V init_args={IP LJ} calc_args={force_using_fd virial_using_fd} relax relax_tol=1e-14

and here is the input file structure : 

4
Lattice="3.01484186      -0.00000000       0.00000000      -0.00000107       4.40909241      -0.00000073       0.00000059      -0.00000000       4.02186270" Properties=species:S:1:pos:R:3:force:R:3
Ag              0.12280690      3.26263582      0.78350571        0 0 0 
Ag              2.88503883      1.05808959      2.79443636        0 0 0
Ag              1.33694608      1.05808980      0.78350545        0 0 0
Ag              1.67089963      3.26263560      2.79443662        0 0 0

**Comment by libAtoms** [comment]
Gabor, did you say his is now fixed by changing to the correct `remove_value(dict, key)` usage?

**Comment by gabor1** [comment]
Yes

  -- Gábor
