### ISSUE TITLE
quippy/convert.py

### ISSUE THREAD

**Issue by houzf** [libAtoms/QUIP#153]
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import quippy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "QUIP/build/linux_x86_64_gfortran/quippy/__init__.py", line 40, in <module>
    import quippy.convert
  File "QUIP/build/linux_x86_64_gfortran/quippy/convert.py", line 41
    def ase_to_quip(ase_atoms: ase.Atoms, quip_atoms=None):
                             ^
SyntaxError: invalid syntax

**Should I make a change for "ase_atoms: ase.Atoms"? e.g., "ase_atoms= ase.Atoms"**

Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import quippy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "QUIP/build/linux_x86_64_gfortran/quippy/__init__.py", line 41, in <module>
    import quippy.potential
  File "QUIP/build/linux_x86_64_gfortran/quippy/potential.py", line 43, in <module>
    class Potential(ase.calculators.calculator.Calculator):
  File "QUIP/build/linux_x86_64_gfortran/quippy/convert.py", line 170, in wrap
    method.__doc__ = update_doc_string(doc, extra)
AttributeError: attribute '__doc__' of 'type' objects is not writable

How could I fix this problem?  Thanks!

**Comment by jameskermode** [comment]
Use Python 3.6 or greater. Python 2.7 is no longer supported, as stated in README.

**Comment by gabor1** [comment]
Also, we recommend that you use "ase convert" now, not the quippy convert script. Functionality has been added to "ase convert" that duplicates almost everything that quippy convert did.

**Comment by jameskermode** [comment]
(This is actually a different `convert.py`, namely a module `quippy.convert` in the new Py3 quippy which does the ASE <--> QUIP Atoms conversion; the script you are referring to has been expunged so there's no choice but to use `ase convert` from now on)

**Comment by gabor1** [comment]
oops, my bad. so let's close this issue then.
