### ISSUE TITLE
The examples (from quippy import Atoms) of tutorial failed.

### ISSUE THREAD

**Issue by houzf** [libAtoms/QUIP#158]
I have successfully installed QUIP (lastest version downloaded from this github site) on my computer (Ubuntu 18, fortran95). The information of "make test" showed "Successfully imported quippy3".   However, the importing "Atoms" from quippy cannot work::
>>> import quippy
>>> from quippy import Atoms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Atoms' from 'quippy' (/home/zh/anaconda3/lib/python3.7/site-packages/quippy-https_github.com_libAtoms_QUIP.git_3ac45a155_dirty-py3.7-linux-x86_64.egg/quippy/__init__.py)
>>> 
I have checked the installed fold of quippy:
---------------------------------------------
zh@tiger:~/anaconda3/lib/python3.7/site-packages/quippy-https_github.com_libAtoms_QUIP.git_3ac45a155_dirty-py3.7-linux-x86_64.egg/quippy$ ls
atoms_module.py        convert.py             descriptors.py        dynamicalsystem_module.py  __init__.py          potential.py  system_module.py
atoms_types_module.py  descriptors_module.py  dictionary_module.py  dynamicalsystem.py         potential_module.py  __pycache__/
-----------------------------------------------
It shows that there is atoms_module.py instead of atoms.py.  How can I fix this problem? If you have any idea, please let me know. Thanks!

**Comment by jameskermode** [comment]
Atoms is no longer part of quippy - use the ASE Atoms class instead. The quippy documentation is in the process of being updated, for now there is an example notebook you can follow at https://github.com/libAtoms/GAP/blob/master/doc_src/quippy-descriptor-tutorial.ipynb

**Comment by houzf** [comment]
I see. Thank you very much for your reply!

**Comment by GideonChampion** [comment]
The ASE Atoms class is missing several of the methods that were available for the quippy atoms class that are used in the tutorials. I am trying to use the soap descriptor tutorial, and methods like set_cutoff and calc_connect aren't in ASE Atoms. When I follow the tutorial, skipping the methods that don't appear in ase, it doesn't give the same values, at times off by a factor of 10^10.

**Comment by gabor1** [comment]
We moved to python3 and much of the overlap with the ASE system was removed from quippy. We are building new documentation, there are tutorials already on libatoms.github.io/GAP

-- Gábor

**Comment by GideonChampion** [comment]
Ah, I see. Sorry, I was looking in https://github.com/libAtoms/GAP-doc/, which has outdated tutorials. I thought that's what was being referenced.

**Comment by ZengZezhu** [comment]
Dear Professor,

If I used the ASE atoms to read the initial structure and run the MD, then there is a error:

WARNING: Potential_initialise using default init_args "Potential xml_label=GAP_2020_7_1_480_14_25_49_518"
Traceback (most recent call last):
  File "run_md.py", line 35, in <module>
    atoms.set_cutoff(7.0)
AttributeError: 'Atoms' object has no attribute 'set_cutoff'

There is a slice of my simple script:

import os
import numpy as np
import matplotlib.pylab as plt
import quippy
from quippy.potential import Potential
from quippy.descriptors import Descriptor
from ase.io import write, read
from ase import Atoms, units
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution,Stationary,ZeroRotation
from ase.md.verlet import VelocityVerlet
from ase.md import MDLogger
from ase.md.langevin import Langevin
from ase.io.trajectory import Trajectory

gap_soap = Potential(param_filename='GAP.xml')

# parameters
number_of_equilibration_steps = 10000
number_of_MD_steps = 20000
time_step = 2  # in fs
dump_interval = 5
temperatures = [300]
log_file = 'md_runs_300K/logs_T{}'
traj_file = 'md_runs_300K/trajs_T{}.traj'
if not os.path.isdir(os.path.dirname(log_file)):
    os.mkdir(os.path.dirname(log_file))

# set up supercell
atoms = read('SPOSCAR')

#reference_positions = atoms.get_positions()

# get gap calculator
atoms.set_calculator(gap_soap)
atoms.set_cutoff(7.0)

What should I do?

**Comment by gabor1** [comment]
set_cutoff is not a method of an ASE atoms object. Why are you trying to call it? The potential will set its cutoff as it needs.

-- Gábor

**Comment by ZengZezhu** [comment]
I want to run the MD by ASE by using gaps potential.
But if I do not set the cutoff there is a warning:

WARNING: Potential_calc: cutoff of Atoms object (-1.0000000000000000) <
Potential cutoff (7.0000000000000000) - increasing it now

**Comment by gabor1** [comment]
so? it’s telling you that it’s setting the cutoff. no problem. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Thank you so much! Professor.
