### ISSUE TITLE
Python 2 in setup.py breaks Py3k-default systems

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#16]
Some operating systems (like Arch Linux) have Python 3 as their default, meaning `python` refers to the Python 3 executable. The file `quippy/setup.py` is written in Python 2 and contains things like unparenthesized print statements that cause Python 3 to fail.

I would like to change the change the rules in the makefiles `quippy/Makefile` and `tests/Makefile` to use the executable `python2` intstead of `python`, since (I think) even on Python-2-only systems, the executable `python2` is still present. Would this change cause problems for anyone?

**Comment by jameskermode** [comment]
I have no objection to changing executables to python2.

Python 3 compatibility for quippy is on my medium term TODO list. Volunteers welcome, the main job is to update this C extension module: https://github.com/jameskermode/f90wrap/blob/master/f90wrap/arraydatamodule.c

**Comment by max-veit** [comment]
OK, the change lets me compile with no SyntaxErrors on my Arch Linux system, but let me know if anyone encounters any problems with this.
