### ISSUE TITLE
/usr/bin/ld: cannot find -llapack /usr/bin/ld: cannot find -lblas

### ISSUE THREAD

**Issue by yufeib** [libAtoms/QUIP#160]
[
[makelog.txt](https://github.com/libAtoms/QUIP/files/3734169/makelog.txt)
](url)

**Comment by gabor1** [comment]
You need to find where the Lapack libraries are on your system...

> On 16 Oct 2019, at 13:08, yufeib <notifications@github.com> wrote:
> 
> [
> makelog.txt
> ](url)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by houzf** [comment]
If you install the anaconda package, you can use the MKL library provided by anaconda. For example:
MATH_LINKOPTS=-L${HOME}/anaconda3/lib  -Wl,--start-group -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -Wl,--end-group -lpthread
