### ISSUE TITLE
Use quip to compute phonons

### ISSUE THREAD

**Issue by fkxie** [libAtoms/QUIP#161]
Hi,
I use gap potential to calculate phonon dispertion of bcc structure of Fe.
The potential is offered by http://www.libatoms.org/Home/IronGAP.

Here is my calculation command:
```
quip phonons=T phonons_dx=0.01 phonon_supercell='8 8 8' phonon_supercell_fine='8 8 8' phonons_path_start='0 0 0' phonons_path_end='0.5 -0.5 0.5' phonons_path_steps=200 atoms_filename=bcc.xyz param_filename=gp33b.xml > g_h.xyz 
...(command with other path)
```
Then, I exact frequencies with label of `PHONONS_FILE` and plot them.
<img width="577" alt="图片" src="https://user-images.githubusercontent.com/43362155/67206539-6cb0f280-f444-11e9-94e9-86e801393959.png">
(Xlabel represents symmetry points, not labeled)

The results seems so wierd, not consistent with article https://journals.aps.org/prmaterials/abstract/10.1103/PhysRevMaterials.2.013808
So, is there any fault in my quip command?

BTW, the bcc.xyz including primitive cell of Iron.

fkxie,

**Comment by gabor1** [comment]
Until someone who feels ownership of the phonon module in quip comments, I recommend you use phonopy together with the quip force evaluator. 

-- Gábor

**Comment by 275689260** [comment]
Hi,
I recently wanted to use the gap potential to calculate the phonon dispersion. I also encountered the same problem with you. Can you provide the calculation command about using phonopy together with the quip force evaluator ?

**Comment by gabor1** [comment]
I recommend that you use ase to evaluate the forced needed by phonopy. An ase calculator can be initialised from a quippy.Potential object.

-- Gábor
