### ISSUE TITLE
QUIP GAP compile failed

### ISSUE THREAD

**Issue by 275689260** [libAtoms/QUIP#163]
Hi,
I am trying to install quippy Python wrappers with GAP. I was able to build the software using GAP (version: 1498734806) however, I get the following error:

QUIP/src/GAP/descriptors.f95:53.39:

   integer, parameter :: gap_version = 
                                       1
Error: Expected an initialization expression at (1)
make[1]: *** [descriptors.o] Error 1
make[1]: Leaving directory `/home/syj/tools/QUIP/build/linux_x86_64_gfortran'
make: *** [GAP] Error 2

I can not solve it

**Comment by gabor1** [comment]
for some reason your compilation is in a state where the variable GAP_VERSION is defined, but empty. Please paste the entire output of the compilation, so we can see that the GAP_VERSION variable is properly defined in the compile line, and we’ll go from there. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
also please execute the following command in the …src/GAP directory: `./gapversion` and paste the output

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by 275689260** [comment]
Thanks very much, I update the GAP_VERSION, and the compilation can be passed.
