### ISSUE TITLE
Strategies to solve memory errors when using gap_fit

### ISSUE THREAD

**Issue by joshgabriel** [libAtoms/QUIP#164]
This may be a simple silly question, but referring to the scaling in https://github.com/libAtoms/QUIP/issues/137, is there any way to make more efficient use of memory for gap_fit on a high-performance computing cluster? CPUs vs GPUs? Does gap_fit work on multi-threading? I could get a QUIP_ARCH "linux_x86_64_ifort_icc" build to work on a GPU with about 96 GB of memory for a training set containing 260 configurations (each with about 200 atoms)  and also with 8 cores of CPU working with 64 GB of memory, with the GPU being 10 minutes faster.  Those are the memory limits on one node in my high performance computing cluster that I can use at the moment. Would the ifort_icc_openmp or ifort_icc_mpi builds help with this? Or does 1 TB have to be on one node?

**Comment by gabor1** [comment]
multithreading yes, as you are using yourself, with openmp. mpi no, because gap_fit does not do data parallelism, so all the memory needs to be globally accessible. you can go a long way by reducing l_max and n_max (of course you sacrifice some accuracy too). empirical evidence for several systems is that l_max could  be lower than n_max by quite a bit without losing too much accuracy. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by joshgabriel** [comment]
Thanks. Just to clarify .. would using gap_fit/gap_fit_mpi on "ifort_icc", "ifort_icc_openmp", and "ifort_icc_mpi" with 8 cpu cores give no big difference in performance, with all other gap_fit parameters being the same?

**Comment by gabor1** [comment]
no. I’m saying that we have multithreading, so if you use openmp you get roughly xN performance boost if you have N cores. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Oct 24, 2019, at 11:20 AM, joshgabriel <notifications@github.com> wrote:
> 
> Thanks. Just to clarify .. would using gap_fit/gap_fit_mpi on "ifort_icc", "ifort_icc_openmp", and "ifort_icc_mpi" with 8 cpu cores give no big difference in performance, with all other gap_fit parameters being the same?
> 

Multi-threading (with OpenMP, requires an _openmp QUIP_ARCH), will help speed, but not memory usage. mpi will be worse than doing nothing.  Note that running with or without OpenMP will not change the memory usage, only the speed.  You do, however, need to get your HPC system to give you access to the entire node and all of its memory.

												Noam

____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by joshgabriel** [comment]
Thanks @bernstei and @gabor1. This was very helpful and I hope it will help others too. Closing the issue.
