### ISSUE TITLE
How do you run the published GaN potential with quip?

### ISSUE THREAD

**Issue by joshgabriel** [libAtoms/QUIP#165]
When running the published GaN potential I hit this error regarding a missing Coulomb potential. Is there some flag in the quip command that I am missing? 

`quip calc_args=local_gap_variance L=T E=T F=T atoms_filename=data_GaN.xyz param_filename=gp_bulk_GalliumNitride.xml`

This was run on a docker, maybe it is an old version of quip?

Error: 
libAtoms::Hello World: 24/10/2019   16:08:58
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,139023d-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran_openmp
libAtoms::Hello World: compiled on  Jun 14 2019 at 21:18:21
libAtoms::Hello World: OpenMP parallelisation with 36 threads
WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
libAtoms::Hello World: Random Seed = 58138806
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

Using calc args: local_gap_variance
Using pre-relax calc args:
Using param_filename: gp_bulk_GalliumNitride.xml
Using init args:
WARNING: Potential_initialise using default init_args "Potential xml_label=GAP_2015_6_1_60_16_13_34_864"
WARNING: gpCoordinates_startElement_handler: covariance type is dot product, but no zeta attribute is present. This may mean an XML generated by an older version. If found, the single value from the theta element will be used, to ensure backwards compatibility
WARNING: gpCoordinates_endElement_handler: dot product covariance is used, but found a theta element in the XML. This may be a sign of an XML generated by an older version. The first and only element of theta will be used as zeta.
WARNING: gpCoordinates_startElement_handler: covariance type is dot product, but no zeta attribute is present. This may mean an XML generated by an older version. If found, the single value from the theta element will be used, to ensure backwards compatibility
WARNING: gpCoordinates_endElement_handler: dot product covariance is used, but found a theta element in the XML. This may be a sign of an XML generated by an older version. The first and only element of theta will be used as zeta.
SYSTEM ABORT: Traceback (most recent call last - error kind unspecified):
File "/opt/quip/src/Programs/quip.f95", line 709 kind unspecified
File "/opt/quip/src/Potentials/Potential.f95", line 937 kind unspecified
File "/opt/quip/src/Potentials/Potential_Sum_routines.f95", line 95 kind unspecified
File "/opt/quip/src/Potentials/Potential.f95", line 934 kind unspecified
File "/opt/quip/src/Potentials/Potential_simple.f95", line 1277 kind unspecified
potential_calc after actual calc
File "/opt/quip/src/Potentials/IPModel_Coulomb.f95", line 315 kind unspecified
IPModel_Coulomb_Calc: unknown method

**Comment by gabor1** [comment]
I’ve confirmed that this is happenning. We will track down change in the last ~10 years has caused this to stop working! Thanks for report. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by joshgabriel** [comment]
Is there any way I can help with this? Here is something I did to get this to work, more like a patch fix though: I found that the Coulomb method was not being read in by the xml parser. So based on what was done for other tags (charge, smooth_coulomb_cutoff, etc.) at line 448 in /src/Potentials//IPModel_Coulomb.f95, I added:

      call QUIP_FoX_get_value(attributes, "method", value, status)
      if (status /= 0) call system_abort ("IPModel_Coulomb_read_params_xml cannot find method")
      read (value, *) parse_ip%method

I think this restricts "method" to be an integer. Referencing line 77 of the same IPModel_Coulomb.f95
      integer, parameter :: IPCoulomb_Method_Ewald = 3

I changed the method tag in the Coulomb potential definition in the published xml to "3" and it worked! 
My next question is how do you get this to work when you want to use "gap_fit' to perform a fit?

**Comment by joshgabriel** [comment]
For getting this to work with `gap_fit` here is where I came up to after figuring out some translations from the CDATA tag:

`gap_fit at_file=data_GaN.xyz gap={soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans add_species} default_sigma={0.001 0.1 0.05 0.05} energy_parameter_name=DFT_energy force_parameter_name=DFT_force virial_parameter_name=DFT_virial sparse_jitter=1.0e-8 e0_offset=2.0 core_param_file=ip.parms.Coulomb.xml core_ip_args={IP Coulomb} gp_file=trial.xml`

This command makes it to the Report on number of descriptors found and then crashes with a segmentation fault.

libAtoms::Hello World: 31/10/2019   21:11:46
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,139023d-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran_openmp
libAtoms::Hello World: compiled on  Jun 14 2019 at 21:18:21
libAtoms::Hello World: OpenMP parallelisation with 36 threads
WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
libAtoms::Hello World: Random Seed = 76306622
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default


================================ Input parameters ==============================

at_file = data_GaN.xyz
gap = "soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans add_species"
e0 = 0.0
local_property0 = 0.0
e0_offset = 2.0
e0_method = isolated
default_sigma = "0.001 0.1 0.05 0.05"
sparse_jitter = 1.0e-8
hessian_delta = 1.0e-2
core_param_file = ip.parms.Coulomb.xml
core_ip_args = "IP Coulomb"
energy_parameter_name = DFT_energy
local_property_parameter_name = local_property
force_parameter_name = DFT_force
virial_parameter_name = DFT_virial
hessian_parameter_name = hessian
config_type_parameter_name = config_type
sigma_parameter_name = sigma
config_type_sigma =
sigma_per_atom = T
do_copy_at_file = T
sparse_separate_file = T
sparse_use_actual_gpcov = F
gp_file = trial.xml
verbosity = NORMAL
rnd_seed = -1
do_ip_timing = F
template_file = template.xyz
sparsify_only_no_fit = F

========================================  ======================================


============== Gaussian Approximation Potentials - Database fitting ============


Initial parsing of command line arguments finished.
Found 1 GAPs.
Descriptors have been parsed
XYZ file read
Old GAP: {soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans add_species}
New GAP: {soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans             n_species=2 Z=31 species_Z={31 7 }}
New GAP: {soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans             n_species=2 Z=7 species_Z={31 7 }}
Multispecies support added where requested

===================== Report on number of descriptors found ====================


Descriptor: soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans             n_species=2 Z=31 species_Z={31 7 }
Number of descriptors:                        289
Number of partial derivatives of descriptors: 25038

Descriptor: soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans             n_species=2 Z=7 species_Z={31 7 }
Number of descriptors:                        289
Number of partial derivatives of descriptors: 25038

========================================  ======================================


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

**Comment by gabor1** [comment]
That command line looks fine. It must be something to do with the coulomb baseline. If you remove that does it work?

Note that it would be unscreened coulomb, so quite unsuitable for anything but low temperature md of the perfect crystal. If you want a screened coulomb, that’s best subtracted from your data before the fit and then added back for simulation (eg in lammps or ase)

-- Gábor

**Comment by joshgabriel** [comment]
So, it didn't work removing the coulomb baseline. I found that it was due to the e0_offset option, at least so it seems. This command worked with and without the Coulomb stuff added:

`gap_fit at_file=data_GaN.xyz gap={soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=4.0 cutoff_transition_width=0.5 central_weight=1.0 n_sparse=150 delta=1.0 f0=0.0 covariance_type=dot_product sparse_method=kmeans add_species} default_sigma={0.001 0.1 0.05 0.05} energy_parameter_name=DFT_energy force_parameter_name=DFT_force virial_parameter_name=DFT_virial sparse_jitter=1.0e-8 e0={Ga:-0.8,N:-0.3} core_param_file=ip.parms.Coulomb.xml core_ip_args={IP Coulomb} gp_file=trial.xml`

Also, I edited ip.parms.Coulomb.xml to only include the "default_ewald" label, otherwise it was getting confused with the other methods. 

I made a random substitution for e0, perhaps this is just something to do with the docker version I used. I could test this with the latest git pull, and compare if the results are the same, if that helps.

**Comment by gabor1** [comment]
So the way we handle all the e0 stuff has changed over the years quite a bit. For example, the old command line doesn’t specify an e0 at all, so the new code defaults to looking for an isolated atom in the dataset. there probably isn’t one. That should lead to a graceful error, but it might not - depending on other options like e0_offset. 

Can you verify this? i.e. if you remove all e0-related options, do you get a sensible error about not finding the isolated atom configurations? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by joshgabriel** [comment]
Yes I do get an error about not finding the isolated atom configuration when removing the e0 option.

**Comment by gabor1** [comment]
If you set the e0_method parameter to "average" (and omit the e0 setting itself) then that should recover the old behavior from 2010. I should hope then the e0_offset setting would work again.

-- Gábor

**Comment by joshgabriel** [comment]
No that doesn't work either unfortunately. I have a larger issue though. The potential generated by the fix I made in the previous comments, gives different forces and energies when run on the same system, between `quip` and `lammps`, with the `lammps` result being clearly wrong. This is what I did, maybe I did something wrong in re-compiling lammps with QUIP support?
1. In $QUIP_ROOT, 
  $ make libquip
2. In /path/to/lammps/src/
  $ make clean-mpi
  $ make no-USER-QUIP
  $ make mpi
  $ make yes-USER-QUIP
  $ make mpi

**Comment by gabor1** [comment]
why are you making lammps without QUIP first? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by joshgabriel** [comment]
Just to keep it simple. I did try compiling together with the `make yes-USER-QUIP` option before the `make mpi`. Maybe my addition of lines for the Coulomb potential broke something elsewhere? The Lammps evaluation works perfectly for QUIP potentials where I didn't use the Coulomb potential in my `gap_fit` potential. Any advise on which section of the code does the force and energy calculation when called through lammps?

**Comment by gabor1** [comment]
Sorry I'm confused now. I thought you determined that it was the e0 that was causing the problem not the coulomb...

-- Gábor

**Comment by joshgabriel** [comment]
Sorry about the confusion, I actually resolved the e0_method problem, specifying e0_method to "average" worked. 

The issue is the calculated energy and forces when using the potential, whether in LAMMPS or `quip`.

When running with `quip`, here are the RMSEs with original DFT data 

Energy: 6.18 eV/atom 
Forces: 2.21 eV/A
 
Running the potential with LAMMPS, something wrong is happening:

Energy: 0.7 eV/atom
Force: 16771 eV/A

Here are a few attachments. Maybe I did something wrong on either the Lammps input script side or the data file? I have also attached the modified potential (substituting "method" = "ewald" for "method" = "3") 

The Lammps input script:
[in.GAP.run.GaN.txt](https://github.com/libAtoms/QUIP/files/3825531/in.GAP.run.GaN.txt)

The Lammps data file for the first GaN configuration from the training set
[LammpsReady.GaN.0.data.txt](https://github.com/libAtoms/QUIP/files/3825533/LammpsReady.GaN.0.data.txt)

The GaN potential with the modified method tag:

[gp_bulk_GalliumNitride.xml.txt](https://github.com/libAtoms/QUIP/files/3825544/gp_bulk_GalliumNitride.xml.txt)

**Comment by gabor1** [comment]
Can you please confirm that for any other (and recent) potential the direct and lammps-driven code gives the same answer? 

-- Gábor

**Comment by joshgabriel** [comment]
Yes, I tested for the more recent Si potential (2017-2018) and the answer from both Lammps and `quip` is the same.

**Comment by joshgabriel** [comment]
I found an earlier [commit](https://github.com/libAtoms/QUIP/commit/395a5c6c16d7fbf4d1a38354026051a7d49a5fd8#diff-661552e4d604390590dd6118cca0abf1) which shows where the xml_read in of "method" may have been deleted by accident. I added back the lines 599 - 616 in IPModel_Coulomb.f95 and could recover running of the GaN potential with the "method"="ewald" in the xml tag. Nonetheless, I get the incorrect results for energy and force.  Did something else change at that commit that I am missing?

**Comment by jameskermode** [comment]
I agree that does look like the inability to run the old potential could be due to accidental removal of some of the XML reading code during a merge. I'm not aware of any changes to the units used in either QUIP or LAMMPS so I can't explain the numerical differences; LAMMPS `metal` units should be equivalent to QUIP's eV/A/fs system. 

Maybe @albapa will be willing to take a look at how you are running LAMMPS?

**Comment by albapa** [comment]
I don't think our Ewald will work with LAMMPS - perhaps we should abort the code if the user tries to do that. For this I think we planned to combine GAP with LAMMPS' own electrostatic treatment. I've never done this, but there should be examples available as this happens for other interatomic potentials in LAMMPS.

**Comment by bernstei** [comment]
> On Nov 19, 2019, at 8:45 AM, albapa <notifications@github.com> wrote:
> I don't think our Ewald will work with LAMMPS - perhaps we should abort the code if the user tries to do that. For this I think we planned to combine GAP with LAMMPS' own electrostatic treatment. I've never done this, but there should be examples available as this happens for other interatomic potentials in LAMMPS.
> 
Well, probably if you claimed the cutoff was larger than the system size (probably also have to run with a single MPI process), you'd end up passing the whole thing to QUIP, and then the QUIP Ewald would probably give correct values.  But the GAP part would be incredibly inefficient if the system wasn't very small. Really the whole QUIP interface implicitly presupposes that interactions are local, which Coulomb is not, and the LAMMPS equivalent of a Sum Potential, with LAMMPS doing the Coulomb, is the way to go.

									Noam

**Comment by albapa** [comment]
Exactly - the reciprocal part of our Ewald needs the entire system, so if it was domain-decomposed, it will fail instantly. Besides, our Ewald doesn't know about ghost and local atoms, although this could be fixed, but still remain a very very limited solution.

I think LAMMPS calls the Sum Potential "overlay" - but I have very little experience with those, but that could be a way to combine fixed-charge electrostatics with GAP in LAMMPS.

**Comment by joshgabriel** [comment]
Thanks for your comments on this! I am happy to do some testing in lammps on this. Perhaps this link is along the above lines of using a hybrid/overlay potential? https://lammps.sandia.gov/doc/pair_hybrid.html
