### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by 275689260** [libAtoms/QUIP#167]
Hi,
I recently started using QUIP with GAP for fitting interatomic potentials. I have already a simple input data, which include the energy and force. And the command is as follows:  gap_fit at_file=images.extxyz gap={soap atom_sigma=0.5 l_max=8 n_max=8 cutoff=6.0 cutoff_transition_width=1.0 delta=0.01 covariance_type=ard_se n_sparse=200 theta_fac=0.02 zeta=4 theta_uniform=1} d
efault_sigma={0.0001 0.002 0 0} e0=0.0 sparse_jitter=1e-10 gp_file=gp.xml

The log is "libAtoms::Hello World: 31/10/2019   14:46:17
libAtoms::Hello World: git version  NOT_A_GIT_REPOSITORY
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Oct 28 2019 at 10:19:11
libAtoms::Hello World: Random Seed = 53177049
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

================================ Input parameters ==============================

atoms_filename = //MANDATORY//
at_file = images.extxyz
gap = "soap atom_sigma=0.5 l_max=8 n_max=8 cutoff=6.0 cutoff_transition_width=1.0 delta=0.01 covariance_type=ard_se n_sparse=200 theta_fac=0.02 zeta=4 theta_uniform=1"
e0 = 0.0
local_property0 = 0.0
e0_offset = 0.0
e0_method = isolated
default_kernel_regularisation = //MANDATORY//
default_sigma = "0.0001 0.002 0 0"
sparse_jitter = 1e-10
hessian_displacement = 1.0e-2
hessian_delta = 1.0e-2
baseline_param_filename = quip_params.xml
core_param_file = quip_params.xml
baseline_ip_args =
core_ip_args =
energy_parameter_name = energy
local_property_parameter_name = local_property
force_parameter_name = force
virial_parameter_name = virial
hessian_parameter_name = hessian
config_type_parameter_name = config_type
kernel_regularisation_parameter_name = sigma
sigma_parameter_name = sigma
config_type_kernel_regularisation =
config_type_sigma =
kernel_regularisation_is_per_atom = T
sigma_per_atom = T
do_copy_atoms_file = T
do_copy_at_file = T
sparse_separate_file = T
sparse_use_actual_gpcov = F
gap_file = gap_new.xml
gp_file = gp.xml
verbosity = NORMAL
rnd_seed = -1
do_ip_timing = F
template_file = template.xyz
sparsify_only_no_fit = F

========================================  ======================================

============== Gaussian Approximation Potentials - Database fitting ============

Initial parsing of command line arguments finished.
Found 1 GAPs.
Descriptors have been parsed
XYZ file read
Unchanged GAP: {soap atom_sigma=0.5 l_max=8 n_max=8 cutoff=6.0 cutoff_transition_width=1.0 delta=0.01 covariance_type=ard_se n_sparse=200 theta_fac=0.02 zeta=4 theta_uniform=1}
Multispecies support added where requested

===================== Report on number of descriptors found ====================

---------------------------------------------------------------------
Descriptor: soap atom_sigma=0.5 l_max=8 n_max=8 cutoff=6.0 cutoff_transition_width=1.0 delta=0.01 covariance_type=ard_se n_sparse=200 theta_fac=0.02 zeta=4 theta_uniform=1
Number of descriptors:                        16016
Number of partial derivatives of descriptors: 3170832

========================================  ======================================

========== Report on number of target properties found in training XYZ: ========

Number of target energies (property name: energy) found: 1001
Number of target local_properties (property name: local_property) found: 0
Number of target forces (property name: force) found: 48048
Number of target virials (property name: virial) found: 0
Number of target Hessian eigenvalues (property name: hessian) found: 0

================================= End of report ================================

===== Report on per-configuration/per-atom sigma (error parameter) settings ====

Number of per-configuration setting of energy_sigma found:     0
Number of per-configuration setting of force_sigma found:      0
Number of per-configuration setting of virial_sigma found:     0
Number of per-configuration setting of hessian_sigma found:    0
Number of per-atom setting of force_atom_sigma found:          0

================================= End of report ================================

SYSTEM ABORT: fit_data_from_xyz: only one of theta_file, theta_uniform, theta_fac or zeta may be specified for
each GAP."
And the error has occured, "SYSTEM ABORT: fit_data_from_xyz: only one of theta_file, theta_uniform, theta_fac or zeta may be specified for
each GAP. "

The corresponding commands of theta_uniform, theta_fac and zeta have been gaven.

**Comment by gabor1** [comment]
The error message is correct. Your have used keywords that are exclusive of each other.  Here is my recommended command line (changes explained below)

> gap_fit at_file=images.extxyz gap={soap atom_sigma=0.5 l_max=8 n_max=8 cutoff=6.0 cutoff_transition_width=1.0 delta=1.0 covariance_type=dot_product n_sparse=200 zeta=4} default_sigma={0.001 0.02 0 0} e0=0.0 sparse_jitter=1e-10 gp_file=gp.xml
> 
delta:  you had 0.01, this is way too small if you are training DFT energies and forces directly. Delta needs to be on the order of the binding energy per atom

Covariance type: the one that most makes sense with the SOAP descriptor is the dot_product. The kernel is then raised to the power zeta, which is 4. No theta_uniform and theta_fac should be use, these are for the squared exponential kernel (ard_se)

e0 : this is OK, but make sure that the isolated atom has zero energy for your DFT (this depends on which code you use and which pseudopotential). We now recommend omitting the e0 from the command line and just putting the isolated atom configuration in the database. 

default_sigma : I increased them by a factor of 10, because you are very unlikely to have energies and forces with accuracies of 1e-4 and 2e-3. Energy cutoff and k-point error usually give higher errors (And you should check this by looking at the convergence!)

n_sparse: 200 is OK as a quick test but unlikely to be enough for a big database. We usually use thousands. 

-- Gábor

**Comment by 275689260** [comment]
Many thanks for your patient guidance. Can you give me the manual, tutorial, or examples about the training? Some parameters could not be found on the page http://libatoms.github.io/QUIP/gap_fit.html or gap_fit --help. Such as the descriptor of distance_2b could not be found.

**Comment by gabor1** [comment]
Lots of examples in published papers, including distance_2b. If you put in a valid training line and put --help inside the gap={}  string you get help on all the descriptor parameters
