### ISSUE TITLE
make install-quippy errors (and resolutions)

### ISSUE THREAD

**Issue by finnhambly** [libAtoms/QUIP#169]
During installation, the following errors come up.
When running `make install-quippy` for the first time, there is a `ln: failed to create symbolic link '_quippy.so': File exists` error. This disappears when running it again.

However, on the second run, I obtain the following error:
```
  File "../../quippy/setup.py", line 4, in <module>
    version = subprocess.getoutput(["../../bin/gitversion"]).strip()
AttributeError: 'module' object has no attribute 'getoutput'
```
I edited quippy/setup.py and replaced the offending line with `version = '2.17.1'` (after finding my version with `git --version`).

Then, running `sudo -E make install-quippy` (as I was getting permission errors), I get the following error which I think has been highlighted on a different issue:
```
byte-compiling build/bdist.linux-x86_64/egg/quippy/convert.py to convert.pyc
  File "build/bdist.linux-x86_64/egg/quippy/convert.py", line 41
    def ase_to_quip(ase_atoms: ase.Atoms, quip_atoms=None):
                             ^
SyntaxError: invalid syntax
```
Editing /quippy/quippy/convert.py and changing the : to = resolves that issue.

After that, the make command seems to run as expected, but I thought I would highlight them here so that these hacks aren't needed in the future.

**Comment by jameskermode** [comment]
Python 2.7 is no longer supported. You need to use Python 3.6 or later, and then you would not have to make these changes.

**Comment by finnhambly** [comment]
Thanks, I used `sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1` and `sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1` to get things working.

**Comment by ghost** [comment]
> Thanks, I used `sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1` and `sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1` to get things working.

hey man. I followed your steps and everything went well, but when I import quippy in python2, it raised "ImportError: dynamic module does not define init function (init_quippy)", and in python3, it raised "ModuleNotFoundError: No module named 'quippy'". How should I do now?

**Comment by ghost** [comment]
> Python 2.7 is no longer supported. You need to use Python 3.6 or later, and then you would not have to make these changes.

thanks, but how to change python2 to python3 when I install? I have both installed, and I don't want to uninstall python2. By the way, the install guide page said python3 support is in progress. Isn't that mean we should use python2?  Also, in this github-releases page, it's said the last version is using Python 2 (2.7)

**Comment by ghost** [comment]
I've figured this out finally! Here is for those guys like me:
Before make, edit /QUIP/quippy/makefile, add number 3 to the end of 'python', there should be two places. And if you encounter `/f90wrap not found` error when make & install, simply replace the / with a space in that makefile. It can be installed successfully overall, I've tried four times in two machines, but the tutorial is said to be out of date, so there will be some import errors, don't worry, that's not because you failed the installation.
