### ISSUE TITLE
error when run "make config" trying to install quip

### ISSUE THREAD

**Issue by wushanyun64** [libAtoms/QUIP#173]
Hi,

I ran into this error trying to install quip when I ran "make config":

```
Unable to determine SIZEOF_FORTRAN_T
Check that your compiler is working and try again!
Build error:
make[1]: Entering directory '/mnt/c/Users/wusha/QUIP/build/linux_x86_64_gfortran'
gfortran -x f95-cpp-input -ffree-line-length-none -ffree-form -fno-second-underscore -fPIC -I/mnt/c/Users/wusha/QUIP/src/libAtoms -I/mnt/c/Users/wusha/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude -O3  -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,a03cda334"'  -D'QUIP_ARCH="linux_x86_64_gfortran"' -D'SIZEOF_FORTRAN_T=' -DHAVE_PRECON -DHAVE_QR   sizeof_fortran_t.f90 -o sizeof_fortran_t
make[1]: gfortran: Command not found
Makefile:10: recipe for target 'sizeof_fortran_t' failed
make[1]: *** [sizeof_fortran_t] Error 127
make[1]: Leaving directory '/mnt/c/Users/wusha/QUIP/build/linux_x86_64_gfortran'
```

I already installed all the requested packages beforehand, can anyone help here?

**Comment by gabor1** [comment]
Well, you do need a Fortran compiler… have you got one? 

the clue is the line "make[1]: gfortran: Command not found"

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by wushanyun64** [comment]
> Well, you do need a Fortran compiler… have you got one? the clue is the line "make[1]: gfortran: Command not found"
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 2 Dec 2019, at 18:22, wushanyun64 ***@***.***> wrote: Hi, I ran into this error trying to install quip when I ran "make config": Unable to determine SIZEOF_FORTRAN_T Check that your compiler is working and try again! Build error: make[1]: Entering directory '/mnt/c/Users/wusha/QUIP/build/linux_x86_64_gfortran' gfortran -x f95-cpp-input -ffree-line-length-none -ffree-form -fno-second-underscore -fPIC -I/mnt/c/Users/wusha/QUIP/src/libAtoms -I/mnt/c/Users/wusha/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude -O3 -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,a03cda334"' -D'QUIP_ARCH="linux_x86_64_gfortran"' -D'SIZEOF_FORTRAN_T=' -DHAVE_PRECON -DHAVE_QR sizeof_fortran_t.f90 -o sizeof_fortran_t make[1]: gfortran: Command not found Makefile:10: recipe for target 'sizeof_fortran_t' failed make[1]: *** [sizeof_fortran_t] Error 127 make[1]: Leaving directory '/mnt/c/Users/wusha/QUIP/build/linux_x86_64_gfortran' I already installed all the requested packages beforehand, can anyone help here? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for the reply, yes I double-checked and found that gfortran was not installed correctly, so this part is fine now. However, when I'm trying to install quippy with "make install-quippy", it first shows that I don't have f90wrap, so I installed the f90wrap and rerun the command, this time it pops out an error message like the follow:

```
f90wrap: error: unrecognized arguments: --py-max-line-length 120 --f90-max-line-length 120
Makefile:85: recipe for target '_quippy.so' failed
make[1]: *** [_quippy.so] Error 2
make[1]: Leaving directory '/mnt/c/Users/wusha/QUIP/build/linux_x86_64_gfortran'
Makefile:218: recipe for target 'quippy' failed
make: *** [quippy] Error 2
```
How can I fix this part? Thank you again!

**Comment by jameskermode** [comment]
Please use the version of `f90wrap` distributed with QUIP - if you check out the repo with 
```
git clone --recursive https://github.com/libAtoms/QUIP.git
```
as directed in the README you should get this automatically.

**Comment by wushanyun64** [comment]
Thank you all for the help, now my problem is solved!

**Comment by Hamza1-coder** [comment]
> Please use the version of `f90wrap` distributed with QUIP - if you check out the repo with
> 
> ```
> git clone --recursive https://github.com/libAtoms/QUIP.git
> ```
> 
> as directed in the README you should get this automatically.

I do this,but problem is same?

**Comment by gabor1** [comment]
where is the "problem" reported? You are adding to an issue that was already closed. If you have a new problem to report, please open a new issue. If your problem is similar to another one, and the instructions there don't help, please post your output that shows the problem.
