### ISSUE TITLE
Error importing modules from quippy

### ISSUE THREAD

**Issue by wushanyun64** [libAtoms/QUIP#175]
Hi,
I install quippy with no problem and I can run `import quippy` successfully with jupyternotebook. However, when I run things such as  `from quippy import Atoms` or `quippy.diamond()` it raises an error like `ImportError: cannot import name 'Atoms' from 'quippy'`. What did I do wrong?

**Comment by stenczelt** [comment]
Functions and classes like `Atoms` and `dialond` have depricated with the update to python3. Please use the ASE equivalents, which are documented there and have a large user and developer base. If you find something that is not doable with them and have been here, please notify us.

Quippy is a high level interface to the potential and descriptors calculators, that are not available elsewhere, unlike the structure related part of the code.

**Comment by gabor1** [comment]
See also #158
