### ISSUE TITLE
The file "descriptors_module.py" is missing in quippy

### ISSUE THREAD

**Issue by YuanbinLiu** [libAtoms/QUIP#176]
I have successfully installed quippy without any problem. But I encountered the error: "AttributeError: module 'quippy' has no attribute 'descriptors_module'".
I checked the installed fold of quippy and found that only the file 'descriptors_module.py' was missing.
What is wrong? If you have any idea, please let me know. Thanks!

**Comment by gabor1** [comment]
You probably did not install GAP (undernead the src directory) before you compiled it as suggested in the instructions? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by YuanbinLiu** [comment]
> You probably did not install GAP (undernead the src directory) before you compiled it as suggested in the instructions?
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 12 Dec 2019, at 02:06, YuanbinLiu ***@***.***> wrote: I have successfully installed quippy without any problem. But I encountered the error: "AttributeError: module 'quippy' has no attribute 'descriptors_module'". I checked the installed fold of quippy and found that only the file 'descriptors_module.py' was missing. What is wrong? If you have any idea, please let me know. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Dear professor, 
Following your suggestions, I fix the problem successfully. Thanks a lot.
