### ISSUE TITLE
What does the error mean?

### ISSUE THREAD

**Issue by YuanbinLiu** [libAtoms/QUIP#177]
Hi,
When I run the gap_fit program, I got a message: "cur_decomposition: iteration: 1, error: .21401885747636334E-021". What does the error exactly mean?

**Comment by gabor1** [comment]
It’s not a program error, it’s just reporting the residual of some linear algebra operation. Did the run not continue? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by YuanbinLiu** [comment]
> It’s not a program error, it’s just reporting the residual of some linear algebra operation. Did the run not continue?
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 19 Dec 2019, at 10:30, YuanbinLiu ***@***.***> wrote: Hi, When I run the gap_fit program, I got a message: "cur_decomposition: iteration: 1, error: .21401885747636334E-021". What does the error exactly mean? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I see. Thanks, professor. The run can continue and I just did't understand what it did mean. Now I get it. Here, I have another question. I realize that running the gap_fit program requires large computer memory. So generally speaking, what computer configuration is competent to run the gap_fit program for a system consisting of more than 100 atoms?

**Comment by gabor1** [comment]
It’s not really the number of atoms (N) in your structure that determines the overall memory requirement. It’s the total number of atoms in the database (irrespective of how they are distributed in the different training structures) and the total number of SOAP sparse points (M). 

Different parts of the calculation have different memory requirement scales. One part is like N*M*M. Another scales with l_max and n_max, roughly as l_max*n_max*n_max. 

I can give you examples, e.g. for the PRX Si potential (N ~ 200k, M ~ 10k), with l_max=n_max=8 (I think), we need about ~1000GB of memory. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by YuanbinLiu** [comment]
> It’s not really the number of atoms (N) in your structure that determines the overall memory requirement. It’s the total number of atoms in the database (irrespective of how they are distributed in the different training structures) and the total number of SOAP sparse points (M). Different parts of the calculation have different memory requirement scales. One part is like N*M*M. Another scales with l_max and n_max, roughly as l_max*n_max*n_max. I can give you examples, e.g. for the PRX Si potential (N ~ 200k, M ~ 10k), with l_max=n_max=8 (I think), we need about ~1000GB of memory.
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 19 Dec 2019, at 11:56, YuanbinLiu ***@***.***> wrote: It’s not a program error, it’s just reporting the residual of some linear algebra operation. Did the run not continue? … -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory Pembroke College University of Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/ On 19 Dec 2019, at 10:30, YuanbinLiu @.***> wrote: Hi, When I run the gap_fit program, I got a message: "cur_decomposition: iteration: 1, error: .21401885747636334E-021". What does the error exactly mean? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. I see. Thanks, professor. The run can continue and I just did't understand what it did mean. Now I get it. Here, I have another question. I realize that running the gap_fit program requires large computer memory. So generally speaking, what computer configuration is competent to run the gap_fit program for a system consisting of more than 100 atoms? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank your very much for the detailed and clear explanation, professor. Now I see it.
