### ISSUE TITLE
How to optimize the parameters in the GAP potential fitting?

### ISSUE THREAD

**Issue by YuanbinLiu** [libAtoms/QUIP#179]
Hi,
There are several parameters to be determined before fitting, such as atom_sigma, cutoff, n_max, l_max, n_sparse and so on. So, are those parameters generally determined based on the experience or the algorithm? Is there any effective way to determine the optimal parameters at present?

**Comment by gabor1** [comment]
Cutoff : we determine it from locality tests (see 2017 amorphous carbon paper)
n_max, l_max: these are convergence parameters, the higher the better, but expensive. Increase n_max before you increase l_max. (12,4) and (12,6) is a good expensive setting, (14,14) is extreme), (6,3) is pretty cheapo and crude
atom_sigma: your idea of the smoothness of the landscape, so basically the “size” of the (smallest) atom (we don’t yet have the capability of making this different for every atom). 0.3 works well if you have H, 0.5 if you don’t, and 0.7 if you only have big atoms (La, Te etc)

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by YuanbinLiu** [comment]
> Cutoff : we determine it from locality tests (see 2017 amorphous carbon paper) n_max, l_max: these are convergence parameters, the higher the better, but expensive. Increase n_max before you increase l_max. (12,4) and (12,6) is a good expensive setting, (14,14) is extreme), (6,3) is pretty cheapo and crude atom_sigma: your idea of the smoothness of the landscape, so basically the “size” of the (smallest) atom (we don’t yet have the capability of making this different for every atom). 0.3 works well if you have H, 0.5 if you don’t, and 0.7 if you only have big atoms (La, Te etc)
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 29 Dec 2019, at 06:05, YuanbinLiu ***@***.***> wrote: Hi, There are several parameters to be determined before fitting, such as atom_sigma, cutoff, n_max, l_max, n_sparse and so on. So, are those parameters generally determined based on the experience or the algorithm? Is there any effective way to determine the optimal parameters at present? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks a lot, professor.
