### ISSUE TITLE
Can I set `GAP` as a calculator in ASE

### ISSUE THREAD

**Issue by ChangChunHe** [libAtoms/QUIP#180]
Hello, I want to set `GAP` as  ASE `calculator` to do some structures search or MD and so on, so I want to know how could I build this kind of API? Any suggestions will be appreciated.

**Comment by jameskermode** [comment]
This is already done, the `quippy.potential.Potential` class is an ASE calculator.

**Comment by ChangChunHe** [comment]
![DeepinScreenshot_select-area_20200201163818](https://user-images.githubusercontent.com/33366949/73589436-646f5580-4511-11ea-9974-c69962f555d8.png)

when I finished `pip install quippy` in my `vasp` virtualenv, this error occured

**Comment by ChangChunHe** [comment]
![DeepinScreenshot_select-area_20200201164703](https://user-images.githubusercontent.com/33366949/73589553-83bab280-4512-11ea-8c20-53a7cd83095c.png)
After make install-quippy with nothing error occurrence, but I still cannot import the `Potential` class, I want to know where I have missed?

**Comment by jameskermode** [comment]
Looks like a compilation problem. Did you get any errors?

**Comment by ChangChunHe** [comment]
> Looks like a compilation problem. Did you get any errors?

emmm, did not get any error during compilation, I guess maybe the `_quip*.so`  is not at the right place...
![DeepinScreenshot_select-area_20200201172952](https://user-images.githubusercontent.com/33366949/73590028-7bfe0c80-4518-11ea-8bb6-47cf4534af7f.png)

because in `__init__.py` file, is cannot import _quip

**Comment by jameskermode** [comment]
Try to run `make test`, this uses libraries from source directory so if that works ok it must be an installation problem.

**Comment by ChangChunHe** [comment]
![DeepinScreenshot_select-area_20200201173449](https://user-images.githubusercontent.com/33366949/73590083-2aa24d00-4519-11ea-8afa-6da23c5bfd15.png)
all tests passed...

In fact, I can mv `_quip*.so` to `quippy` dir, I can import Potential class from potential
![DeepinScreenshot_select-area_20200201173616](https://user-images.githubusercontent.com/33366949/73590112-8e2c7a80-4519-11ea-80e2-7d0d0202ae5d.png)

**Comment by ChangChunHe** [comment]
![DeepinScreenshot_select-area_20200201173924](https://user-images.githubusercontent.com/33366949/73590141-d055bc00-4519-11ea-91b8-ec7665c99169.png)
seems no problem...

**Comment by jameskermode** [comment]
Ok great. If you can figure out why the automatic install failed that would be useful
