### ISSUE TITLE
Some questions in your article (Data-Driven Learning of Total and Local Energies in Elemental Boron) 

### ISSUE THREAD

**Issue by ChangChunHe** [libAtoms/QUIP#182]
In your paper, Data-Driven Learning of Total and Local Energies in Elemental Boron, I found that you can calculate local energies

![DeepinScreenshot_select-area_20200226144620](https://user-images.githubusercontent.com/33366949/75319134-03843480-58a7-11ea-9491-368554771c42.png)

And you have mentioned that the local energies depend on the local region, I want to know the details that how to calculate local energies? May you simply explain that? Thanks for any reply...

**Comment by stenczelt** [comment]
In the case of a GAP model, the local energies are the function of the local environment of an atom, as the sum of contributions for all descriptors evaluated on it. eg. the prediction of energy of a SOAP vector. The total energy is then the sum of the local environments. 

To calculate it with `quippy`, use the `local_energy` argument in the potential calculator.
