### ISSUE TITLE
Missing quippy modules after installation

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [libAtoms/QUIP#183]
I have installed quippy on a Linux machine. Everything installed correctly and `make test` is all good. I can import `quippy` in Python, but many of the modules are not available. For instance, if I do `from quippy import Atoms` I get back `ImportError: cannot import name 'Atoms' from 'quippy' (/home/rosen/.local/lib/python3.7/site-packages/quippy-https_github.com_libAtoms_QUIP.git_2b9f46a_dirty-py3.7-linux-x86_64.egg/quippy/__init__.py)`. I also can't access things like `AtomsList`. Any ideas?

Using `dir(quippy)` in Python only shows the following:
```python
['QUIPPY_FALSE',
 'QUIPPY_TRUE',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_quippy',
 'absolute_import',
 'atexit',
 'atoms_module',
 'atoms_types_module',
 'convert',
 'descriptors',
 'descriptors_module',
 'dictionary_module',
 'division',
 'dynamicalsystem_module',
 'f90wrap',
 'logging',
 'potential',
 'potential_module',
 'print_function',
 'quippy',
 'quippy_cleanup',
 'system_module']
```

**Comment by gabor1** [comment]
See #158
