### ISSUE TITLE
How to calculate soap parallelly by using quippy

### ISSUE THREAD

**Issue by zhengcheng233** [libAtoms/QUIP#186]
In the tutorial, an example of using soap is given, but it is serial. I am not very clear about calculating the soap in parallel, may be use the functioin mpi_setup(), but i don't know how to set the parameter in mpi_setup.

**Comment by gabor1** [comment]
the quippy interface does not pass mpi communicators. quip itself (the fortran code) is mpi parallelised. You have two options for parallel evaluation of soap vectors: parallelise only within python, and in each mpi process, select a subset of structures and call the quippy soap evaluation only for those structures. alternatively, write out the structures you want into a file, and use the command line “quip” program to evaluate a soap vector (type “quip —help” to get command line options), that way you are making use of mpi parallelism. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by zhengcheng233** [comment]
Thank you for your nice and helpful answer. By the way, if i use same machine, which QUIP_ARCH may the fastest?

**Comment by gabor1** [comment]
I don’t think there will be a big speed difference. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by zhengcheng233** [comment]
Thank you, I get it.
