### ISSUE TITLE
f90wrap path parsing breaks in corner case

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#188]
This line:
https://github.com/libAtoms/QUIP/blob/b2781ac91f3b5b3a82570a95d11e2f9f2dec8033/quippy/Makefile#L62
breaks if you have a virtual environment with `lib` in the name because the substitution gets too greedy and clobbers the virtualenv as well. The obvious fix is two characters; just replace `lib.*` with `lib\/.*` in the second sed expression.

Not super urgent, but bewildering when I first encountered it.

**Comment by jameskermode** [comment]
Thanks for reporting, if you want to check in the fix (or make a PR) please go ahead.
