### ISSUE TITLE
Include GAP and Quip to lammps

### ISSUE THREAD

**Issue by rudi604** [libAtoms/QUIP#189]
Dear all,

I have installed QUIP and downloaded the GAP files and want to use them both with lammps.
Now I would just copy the GAP files into the src/Potentials folder of Quip and then build lammps. 
Is this procedure okay or do I miss something?

Best regards, Benedikt

**Comment by gabor1** [comment]
That’s not what the instructions say. You copy the GAP folder to under src, then compile quip, so that you get the library as well  then compile lammps with the quip option (and tell it where to find your quip library). 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by rudi604** [comment]
Ok thank you. Now as I do compiling quip I get the question about Turbo GAP. Do I have to mention the path to the GAP files in the src folder or just ignore it, because I do not know what Turbo means?

**Comment by gabor1** [comment]
Ignore that for the moment. It’s an alternative some parts of the current GAP that is not yet in production. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
And you don’t have to tell QUIP where GAP is, it is expecting to find it under “src"

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by rudi604** [comment]
Okay fine. Will lammps ask me where to find my QUIP library after I command 'make mpi' in my lammps/src folder or do I have to change a certain Makefile before?

**Comment by gabor1** [comment]
You need to enable the “quip pairstyle” 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by rudi604** [comment]
Okay. Thanks to the good documentation I used cmake in order to get all the makefiles where I included the Quip library and it all looked nice in principle, but cmake has got an error 

'CMake Error at Modules/StyleHeaderUtils.cmake:173 (message)'. Is this a known problem from lammps or from my cluster tools? 

Best regards, Benedikt

**Comment by rudi604** [comment]
Edit, I got the error, now cmake did everything I guess. The next issue comes from the following make command where I get the error that range based loops are not allowed in C++98 mode in Operation.h

I try to fix it but i do not know whether it will work.

**Comment by gabor1** [comment]
Aren’t these strictly lammps problems?

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by rudi604** [comment]
Yes for sure they are. Sorry for that, I was totally in the mood luckily you respond quickly. 
I will write to the lammps support. 
Thank you for your help, installing quip was an easy task.
