### ISSUE TITLE
can't initialize a QUIP Potential with a param_file or string

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#190]
Some QUIP Potentials don't need a param file at all, e.g. FilePot.  However, commit 5662832faedbcae45eaa53cfcda644bfa56e84a2 now causes `Potential.__init__()` to fail if no param filename or string is passed.  Are we happy with this new behavior, or should we go back to the previous behavior where this was possible?  It is still possible to work around the change by passing an empty param_str (but not an empty param_filename - it complains about that) if there's no param file.  If no one wants to go back, feel free to close this issue as wontfix.

**Comment by stenczelt** [comment]
I see, that was not the intention at all, I will fix it now.
