### ISSUE TITLE
problem with training with GAP

### ISSUE THREAD

**Issue by bpfrd** [libAtoms/QUIP#194]
Hello
I am trying to train some structure with GAP, but I think something goes wrong with the training. Please find in the attachments, the output and a sample of my structures. I was also wondering if I specified the descriptor correctly?

Best regards
[files.zip](https://github.com/libAtoms/QUIP/files/4464587/files.zip)

**Comment by gabor1** [comment]
so what exactly goes wrong? Your output file looks perfectly fine, except it hasn’t finished.  If your program stopped running, I am guessing that it has run out of memory - 18000 configurations is a huge amount.  GAP descriptors are very good, you don’t need this many training points for good accuracy. You should try it with much fewer, and then test your accuracy as a function of number of training samples. Start with just 100 configurations. 

You can also reduce the memory requirements by changing your descriptors, e.g. l_max down to 3 or 4 (but I’d keep n_max at near 8 for decent accuracy). Of course truncating the descriptors will also lower your accuracy, you need to explore a bit. 

the other parameter having a big effect on accuracy is the cutoff, that’s a very physical thing: it’s the range of your interactions. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Apr 11, 2020, at 9:00 AM, gabor1 <notifications@github.com> wrote:
> 
> 18000 configurations is a huge amount. GAP descriptors are very good, you don’t need this many training points for good accuracy. You should try it with much fewer, and then test your accuracy as a function of number of training samples. Start with just 100 configurations. 

Also, it's probably better to think about # of environments, i,e, $sum_{i_config} n_at(i_config)$.  18000 x 2 atom configs contain less information that 1000 x 128 atom configs.

						Noam

**Comment by bpfrd** [comment]
Thank you very much for your response. I reduced the number of structures
to 100 and did the training again. I attached the output. Then I used
GAP.xml file and ran the below command and got segmentation fault error:
$ /kernph/dedeb/bin/QUIP/build/linux_x86_64_ifort_gcc_openmp/quip E=T F=T
atoms_filename=train.xyz param_filename=GAP.xml
libAtoms::Hello World: 11/04/2020   18:11:04
libAtoms::Hello World: git version
https://github.com/libAtoms/QUIP.git,6c7bc64-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_ifort_gcc_openmp
libAtoms::Hello World: compiled on  Apr 09 2020 at 17:19:58
libAtoms::Hello World: OpenMP parallelisation with 16 threads
WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set
explicitly. The default value - system and compiler dependent - may be too
small for some applications.
libAtoms::Hello World: Random Seed = 65464912
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

Using calc args:
Using pre-relax calc args:
Using param_filename: GAP.xml
Using init args:
WARNING: Potential_initialise using default init_args "Potential
xml_label=GAP_2020_4_11_120_18_8_19_749"
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Segmentation fault

Best regards

**Comment by gabor1** [comment]
Try adding "ulimit -s unlimited" and setting a large OMP_STACKSIZE (Like 10000000)

-- Gábor

**Comment by bpfrd** [comment]
Thank you very much. It works now for 100 structures. The quality of
trained energies are bad but the quality of trained forces are amazingly
good (they are exactly on y=x line). Does it have something to do with may
parameters? (for example default_sigma={0.008 0.04 0 0} )
How can I improve the quality of both energies and forces? How many
structures would you recommend for training in order to get a good result?
(I have about 18000 structures)
Best regards

**Comment by gabor1** [comment]
yes. the "default_sigma" controls the relative weights of energies and forces (first two numbers respectively). Their absolute size also matters, it controls the tradeoff between regularity and goodness of fit (overfitting). Try to reduce the first number to 0.004 or 0.002 and see what happens. Be careful to test your potential not just on your training set but also on an independent test set. 

In your 18K configuarions you have about 900K atoms, that is an enormous amount of data (as Noam said above, that is the correct count of the training data). Our largest potentials, covering an extremely diverse range of configurations (many bulk phases, surfaces, defects etc) had <200k atoms. I would severely filter your dataset. Make sure you have a small as well as large configurations (small ones help with the energy because it is spread over fewer atoms, large ones help with the longer range interactions)

**Comment by bpfrd** [comment]
Thank you very much for your email. I trained them using GAP but I want to
test the result for some data set, I get the same energies and forces as
the energy and forces in my data set. but if my data set doesn't have
energy and forces, I get reasonable energies and forces. So, shouldn't quip
skip energies and forces in test.xyz?
quip E=T F=T atoms_filename=test.xyz param_filename=GAP.xml | grep AT | sed
's/AT//' >> quip_test.xyz
Best regards

**Comment by gabor1** [comment]
Sorry I have difficulty understanding your last message. Are you saying that if you have energies and forces in your test set, the quip command doesn't replace them with the predicted ones? (BTW I usually just pass "E F" rather than "E=T F=T")

**Comment by bpfrd** [comment]
exactly. energies and forces in quip_test.xyz are exactly the same as
test.xyz.

**Comment by gabor1** [comment]
Um… that’s strange. That’s not what quip does for me. Are you sure you didn’t by chance run the same program before, and have the same predicted energies in your test.xyz file? Try with just one configuration where you replace the energy in the test.xyz file with 0.0 and see what happens. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bpfrd** [comment]
Sorry, I understood why that happened. I specified the energy in my data
set by dft_energy but the output energy of quip is "energy". So, I was
grepping dft_energy not energy. Thanks

**Comment by gabor1** [comment]
I usually do that so that I have both the Target and predicted energy in the same file.

-- Gábor

**Comment by bpfrd** [comment]
I have a little question about the first two component of default_sigma={0.008 0.04 0 0}. are 0.008 and 0.04 the values in the diagonal of matrix \lambda in eq. 23 in the below paper?
https://arxiv.org/pdf/1901.10971.pdf

Best regards
Behnam

**Comment by bpfrd** [comment]
I have a little question about the first two component of default_sigma={0.008 0.04 0 0}. are 0.008 and 0.04 the values in the diagonal of matrix \Lambda (or \Lambda^-1) in eq. 23 in the below paper?
https://arxiv.org/pdf/1901.10971.pdf

Best regards
Behnam

**Comment by gabor1** [comment]
The units of sigma are units of energy/atom, force, virial/atom etc. In the notation of the paper you cite, the diagonal matrix we are talking about is Lambda. What goes on the diagonal Lambda are the Natoms*sigma_energy^2 for the total energy data points (for force data points, it is more complicated, and turns out to be sigma_energy*sigma_force). 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
