### ISSUE TITLE
One question about GAP

### ISSUE THREAD

**Issue by tiandijunhao** [libAtoms/QUIP#199]
Hello,

When I put several datasets into a XYZ file for training, the following error is always reported:
```txt
fields[0] = Nb, length 2
fields[1] = 0.00000000, length 10
fields[2] = 0.00000000, length 10
fields[3] = 0.00000000, length 10
fields[4] = 0.00000000, length 10
fields[5] = -0.00000000, length 11
fields[6] = -0.00000000, length 11
fields[7] = 
, length 1
SYSTEM ABORT: Traceback (most recent call last)
File "/BIGDATA1/caep_swcc_hygeng_1/software/QUIP-public/src/libAtoms/xyz.c", line 1047 kind IO
incomplete row, frame 0 atom 0 - got 8/7 entries line 0
            
libAtoms::Hello World: 19/04/2020   13:51:41
libAtoms::Hello World: git version  NOT_A_GIT_REPOSITORY
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Apr 13 2020 at 14:14:16
libAtoms::Hello World: Random Seed = 49901384
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default


================================ Input parameters ==============================

atoms_filename = //MANDATORY//
at_file = Nb_54.xyz
gap = "soap l_max=12 n_max=12 cutoff=5.0 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 config_type_n_sparse={elastics:100:md_300k:500:md_1200k:500:default:1000} sparse_method=cur_points covariance_type=dot_product"
e0 = Nb:-0.70796320
local_property0 = 0.0
e0_offset = 0.0
e0_method = isolated
default_kernel_regularisation = //MANDATORY//
default_sigma = "0.005 0.2 1.0 0.0"
sparse_jitter = 1e-12
hessian_displacement = 1.0e-2
hessian_delta = 1.0e-2
baseline_param_filename = quip_params.xml
core_param_file = quip_params.xml
baseline_ip_args =
core_ip_args =
energy_parameter_name = free_energy
local_property_parameter_name = local_property
force_parameter_name = forces
virial_parameter_name = stress
hessian_parameter_name = hessian
config_type_parameter_name = config_type
kernel_regularisation_parameter_name = sigma
sigma_parameter_name = sigma
config_type_kernel_regularisation =
config_type_sigma = elastics:0.0001:0.01:0.01:0.0:md_300k:0.001:0.05:1.0:0.0:md_1200k:0.001:0.05:1.0:0.0
kernel_regularisation_is_per_atom = T
sigma_per_atom = T
do_copy_atoms_file = T
do_copy_at_file = F
sparse_separate_file = T
sparse_use_actual_gpcov = F
gap_file = gap_new.xml
gp_file = GAP_Nb.xml
verbosity = NORMAL
rnd_seed = -1
do_ip_timing = F
template_file = template.xyz
sparsify_only_no_fit = F

========================================  ======================================


============== Gaussian Approximation Potentials - Database fitting ============


Initial parsing of command line arguments finished.
Found 1 GAPs.
Descriptors have been parsed
```

When I train different data sets separately, it can be carried out normally.

This is my command：
```bash
gap_fit energy_parameter_name=free_energy force_parameter_name=forces virial_parameter_name = stress do_copy_at_file=F sparse_separate_file=T gp_file=GAP_Nb.xml at_file=Nb_54.xyz \
gap={soap l_max=12 n_max=12 \
cutoff=5.0 cutoff_transition_width=1.0 delta=1.0 \
atom_sigma=0.5 zeta=4 config_type_n_sparse={elastics:100:md_300k:500:md_1200k:500:default:2000} \
sparse_method=cur_points \
covariance_type=dot_product} \
sparse_jitter=1e-12 \
default_sigma={0.005 0.2 1.0 0.0} \
config_type_sigma={elastics:0.0001:0.01:0.01:0.0:md_300k:0.001:0.05:1.0:0.0:md_1200k:0.001:0.05:1.0:0.0} \
e0={Nb:-0.70796320}
```

How can I solve it?

Best regards，
Wang

**Comment by gabor1** [comment]
Paste here the first few lines of your XYZ file.

-- Gábor

**Comment by gabor1** [comment]
BTW your l_max=12 is likely overkill and l_max=6 is just as good and faster

-- Gábor

**Comment by tiandijunhao** [comment]
> Paste here the first few lines of your XYZ file.

Thanks， I will try to set l_max.
This is my file.
[Nb_54.zip](https://github.com/libAtoms/QUIP/files/4498697/Nb_54.zip)

**Comment by gabor1** [comment]
your file has Windows style newlines. that usually screws things up. blame Bill Gates. remove the extra carriage return characters using “dos2unix” utility or something similar

the internet says this command should also do it : perl -pi -e 's/\r\n/\n/g' *

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
here is your example file converted. 
[Nb_54.xyz.zip](https://github.com/libAtoms/QUIP/files/4498903/Nb_54.xyz.zip)

**Comment by tiandijunhao** [comment]
> here is your example file converted.
> [Nb_54.xyz.zip](https://github.com/libAtoms/QUIP/files/4498903/Nb_54.xyz.zip)

Thank you very much for your help.

Best regards,
Wang

**Comment by gabor1** [comment]
did it work? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by tiandijunhao** [comment]
> did it work?
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 19 Apr 2020, at 13:10, tiandijunhao ***@***.***> wrote: here is your example file converted. Nb_54.xyz.zip Thank you very much for your help. Best regards, Wang — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, very thanks.
