### ISSUE TITLE
run_suffix labels

### ISSUE THREAD

**Issue by libAtoms** [libAtoms/QUIP#2]
Current issues with our run_suffix scheme:
1. Should we replace =mm= and =qm= with =fast= and =slow=?
2. What else (if anything) will have to be changed to be consistent?
    other `metapotentials' should also append stuff to =run_suffix=,
    e.g. castep_driver and vasp_driver
3. If an EVB Potential is used to make two separate =run_suffix=
    values, =cp2k_driver= will save two sets of wavefunctions
    (increasing disk usage, and slowing things down a bit if, for
    example, there's an EVB outside the QM region of a QM/MM). Do
    we care? Could be addressed similar to cp2k_state_change()

**Comment by jameskermode** [comment]
Closed as not under active development- high level job control like this should be implemented in Python
