### ISSUE TITLE
implementing new fingerprint in gap

### ISSUE THREAD

**Issue by bpfrd** [libAtoms/QUIP#200]
Hello
I was wondering if it is possible to implement a new fingerprint in gap in addition to soap. We have a fingerprint and we are curious to compare its performance with SOAP. If it is OK, how can we do that? where should we add it? what are the inputs and outputs? thanks
Best regards

**Comment by gabor1** [comment]
All the descriptors are in src/GAP/descriptors.f95 I suggest looking at one of the simpler ones first (e.g. "distance_2b")

**Comment by albapa** [comment]
There are a number of interfaces you need to create for a descriptor to work. Select a descriptor from rc/GAP/descriptors.f95 (e.g. `distance_2b` for a pair-type descriptor, or `coordination` for an atom-centred one) and search through the file to see what you need to implement.

**Comment by gabor1** [comment]
can I close this now?

**Comment by bpfrd** [comment]
Thanks for your response. I should still work on that. Sure you can close
but is it possible for me to ask questions after it is closed? I will
probably run into more questions.

**Comment by gabor1** [comment]
Sure. you can reopen the issue, or ask us in email.
