### ISSUE TITLE
Segmentation fault when trying to use GAP

### ISSUE THREAD

**Issue by DjordjeDangic** [libAtoms/QUIP#201]
Hello,

I have compiled QUIP with GAP version 1570970202. Compilation finished without any errors. However, when I try using the gap_fit or quip executables I get the segmentation faults. quip breaks at:
quip               000000000097E5D7  gp_predict_module        3971  gp_predict.f95
quip               00000000004E8AC3  ipmodel_gap_modul         186  IPModel_GAP.f95
quip               00000000004CB02D  ip_module_mp_ip_i         436  IP.f95
quip               00000000004AD4EC  potential_simple_         249  Potential_simple.f95
quip               00000000004895FA  potential_module_         636  Potential.f95
quip               000000000048A5CF  potential_module_         491  Potential.f95
quip               000000000048B10A  potential_module_         460  Potential.f95
quip               0000000000409818  MAIN__                    294  quip.f95
and gap_fit:
gap_fit            0000000000445A4C  gp_fit_module_mp_         328  gp_fit.f95
gap_fit            000000000043D1D9  gp_fit_module_mp_         422  gp_fit.f95
gap_fit            000000000041FC63  gap_fit_module_mp        1191  gap_fit_module.f95
gap_fit            00000000004075DA  MAIN__                     68  gap_fit.f95
I suspect that the program crashes when trying to call linearalgebra routines? I tried with linking with mkl -mkl or -llapack -lblas, with both compilations succesful and the same runtime errors. Could it be that I am missing some extra packages?

Weird thing is that I have compiled this same version on two other machines and it runs fine. 

I compiled it using architecture linux_x86_64_ifort_icc and my ifort version 19.0.5.281 . Do you have any suggestions on how to overcome this issue?

Thank you,

DJordje

**Comment by gabor1** [comment]
Have you set enough stack space? "ulimit -s unlimited" usually works

-- Gábor

**Comment by DjordjeDangic** [comment]
Hello,

This is set to unlimited by default on the machine I am using and I confirmed this by login to the node directly and checking it. 
limit
cputime      unlimited
filesize     unlimited
datasize     unlimited
stacksize    unlimited
coredumpsize 0 kbytes
memoryuse    unlimited
vmemoryuse   unlimited
descriptors  4096
memorylocked unlimited
maxproc      4096
maxlocks     unlimited
maxsignal    1804715
maxmessage   819200
maxnice      0
maxrtprio    0
maxrttime    unlimited
Could it be that this does not apply once I run the job?

**Comment by gabor1** [comment]
If you are submitting to a queue, maybe set it explicitly in the job script?

"quip" runs fine on your login node?

-- Gábor

**Comment by gabor1** [comment]
Can you paste the full output?

-- Gábor

**Comment by DjordjeDangic** [comment]
I do not have permission to change it. However, as I said the node I am running it on has the above limits. 

This is output for quip:
Started at Fri Apr 24 09:42:00 IST 2020
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
quip               0000000000E60993  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F4D005E05E0  Unknown               Unknown  Unknown
quip               000000000097E5D7  gp_predict_module        3971  gp_predict.f95
quip               00000000004E8AC3  ipmodel_gap_modul         186  IPModel_GAP.f95
quip               00000000004CB02D  ip_module_mp_ip_i         436  IP.f95
quip               00000000004AD4EC  potential_simple_         249  Potential_simple.f95
quip               00000000004895FA  potential_module_         636  Potential.f95
quip               000000000048A5CF  potential_module_         491  Potential.f95
quip               000000000048B10A  potential_module_         460  Potential.f95
quip               0000000000409818  MAIN__                    294  quip.f95
quip               0000000000EBE896  Unknown               Unknown  Unknown
libc-2.17.so       00007F4D0002BC05  __libc_start_main     Unknown  Unknown
quip               0000000000407369  Unknown               Unknown  Unknown
Completed at Fri Apr 24 09:42:16 IST 2020

And for gap_fit:
Started at Thu Apr 23 18:45:48 IST 2020
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
gap_fit            0000000000E95353  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F5B339925E0  Unknown               Unknown  Unknown
gap_fit            0000000000445A4C  gp_fit_module_mp_         328  gp_fit.f95
gap_fit            000000000043D1D9  gp_fit_module_mp_         422  gp_fit.f95
gap_fit            000000000041FC63  gap_fit_module_mp        1191  gap_fit_module.f95
gap_fit            00000000004075DA  MAIN__                     68  gap_fit.f95
gap_fit            0000000000EF3256  Unknown               Unknown  Unknown
libc-2.17.so       00007F5B333D4C05  __libc_start_main     Unknown  Unknown
gap_fit            0000000000407369  Unknown               Unknown  Unknown
Completed at Thu Apr 23 19:23:53 IST 2020

**Comment by gabor1** [comment]
So there is no output at all apart from the segfault ? That is unlikely to be a memory issue in the code. What happens when you use GCC?

-- Gábor

**Comment by DjordjeDangic** [comment]
You were right professor, quip runs fine on the login node. I will check with the IT service to give me permission to set stacksize limit to see if somehow this is causing trouble.

I have not tried compiling it with gcc. 

I will try these two suggestions. 

Thank you,

Djordje

**Comment by gabor1** [comment]
Sometimes "unlimited" is forbidden, but finite stack sizes are fine. experiment with what is the largest stack size you can set by hand. also set the OMP_STACK_SIZE variable if you are using multithreading with openmp

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by DjordjeDangic** [comment]
Hello again,

I have performed the above-mentioned checks. 

Firstly, although the limit command when called from the terminal says that the stack size is unlimited, if you call the same command in the PBS script where you run your job, it actually shows that there is a limit on the stack size. So the issue with this is most likely the stacksize limit, as you pointed out immediately. I think that as a non-root user you can only lower the limit, because I tried several larger limits and they all failed.

Second, the GCC compiled program runs fine. It does not have an issue with the stacksize. 

Thank you very much for your support. I will close the thread now.

Regards,

Djordje
