### ISSUE TITLE
quippy Descriptor class, error upon construction: module 'quippy' has no attribute 'descriptors_module'

### ISSUE THREAD

**Issue by chengeaa** [libAtoms/QUIP#202]
Basically, title says it all. The constructor for the Descriptor class has the line 
`
 self._quip_descriptor = quippy.descriptors_module.descriptor(args_str)
`
but I can't seem to find this module `descriptors_module` anywhere. 

I made sure to follow the build instructions and do see the other files in the resulting folder (`convert.py`, `atoms_types_module.py`, etc) but this `descriptors_module` doesn't seem to be anywhere. 

Any hints as to what might be going on? Thanks in advance.

**Comment by gabor1** [comment]
yeah, we upgraded to python3 and expose fewer classes. check through the closed issues here to see how to call the descriptors.

**Comment by gabor1** [comment]
upgraded tutorials that show usage are here: https://libatoms.github.io/GAP/

**Comment by chengeaa** [comment]
Sorry to be a bother, but- that is exactly the problem I am having. When following the upgraded tutorials (specifically, the ones found at https://libatoms.github.io/GAP/quippy-descriptor-tutorial.html and https://libatoms.github.io/GAP/gap_si_surface.html), I get the error I described above. And looking at issues such as  #152, #158, #175, and #183, they don't seem to help me either. Is there anything else that can perhaps point me in the right direction?

**Comment by gabor1** [comment]
Sorry. I was too hasty in reading your original issue. does the "quip" command line program work correctly, including calculating descriptors?

**Comment by jameskermode** [comment]
Most likely QUIP is compiled without GAP

**Comment by chengeaa** [comment]
@gabor1 : Since I am a new user of QUIP/QUIPPY, I am not 100% sure. However, I ran the following commands, from this tutorial https://libatoms.github.io/GAP/gap_fitting_tutorial.html, after generating the needed train.xyz set:

`
gap_fit energy_parameter_name=energy force_parameter_name=forces do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}
`

and 

`
quip E=T F=T atoms_filename=train.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_train.xyz
`
Both executed without error, so I believe this means that the `quip` command line program is working fine. 


@jameskermode : The `Makefile.inc` file in my build directory has `HAVE_GAP=1`, and I ran make test without issues (ran 35 tests in 1.202s, last line is OK), so I believe this should mean I have GAP compiled.

**Comment by jameskermode** [comment]
Ok, if the command line gap programs run correctly then I agree that’s not the problem. The `quippy.descriptors_module` is present only when `HAVE_GAP=1` is set so it’s worth double checking the quippy you are using is coming from the directory you have installed to (with `import quippy; print(quippy.__file__)`) in case you have multiple versions around on your Python path.

**Comment by chengeaa** [comment]
Looks like that was exactly the issue. Got messed up with the various places things had been installing (base python/miniconda). Thanks so much for your help!
