### ISSUE TITLE
One error about GAP on ubuntu20.04

### ISSUE THREAD

**Issue by tiandijunhao** [libAtoms/QUIP#206]
Dear Sir，
Hello. I tried to install gap on Ubuntu 20.04. The Intel 2019 compiler is used. But always prompt the following errors:

```bash
gap_fit_module.f95(281): error #6404: This name does not have a type, and must have an explicit type.   [PRINT_ANALYSIS]
         call verbosity_push(PRINT_ANALYSIS)
-----------------------------^
```

My GAP_version: 1571495255
Please tell me how to solve it.

Thank you very much!

Wang

**Comment by gabor1** [comment]
that’s an odd error to get. Please redownload the entire source tree into a new directory and try it with gfortran first, just to see what happens, then let’s go from there. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by tiandijunhao** [comment]
> that’s an odd error to get. Please redownload the entire source tree into a new directory and try it with gfortran first, just to see what happens, then let’s go from there.
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 1 Jun 2020, at 04:16, tiandijunhao ***@***.***> wrote: Dear Sir， Hello. I tried to install gap on Ubuntu 20.04. The Intel 2019 compiler is used. But always prompt the following errors: gap_fit_module.f95(281): error #6404: This name does not have a type, and must have an explicit type. [PRINT_ANALYSIS] call verbosity_push(PRINT_ANALYSIS) -----------------------------^ My GAP_version: 1571495255 Please tell me how to solve it. Thank you very much! Wang — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Dear sir，

I solve it. It maybe that the edition of QUIP is older than the edition of GAP.

Thank you for your reply.
