### ISSUE TITLE
Extended xyz format for LAMMPS

### ISSUE THREAD

**Issue by abhijeetdhakane** [libAtoms/QUIP#207]
What is the best way to incorporate extended xyz file from LAMMPS dump files.

Example from https://libatoms.github.io/GAP/ uses the below header in extended xyz.
Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy="_JSON 70.38809727285381" pbc="T T T"

However it won't be straight forward to made such flags in lammps dump file. I used ovito to generate extended xyz from lammps dump files, but it won't work as per expected and the GAP program didn't recognize the energies. I used following as opposed to given examples:
Properties=species:S:1:pos:R:3:force:R:3:c_keng:R:1:energies:R:1:mass:R:1:id:I:1

It will be great if someone resolve or gave idea on this.

Also it will be very helpful if developers add GAP tutorial with LAMMPS, especially the post-processing stuff before used into the GAP. Otherwise code work fantastic!!

**Comment by gabor1** [comment]
this was a bugged update to ASE. get the latest ASE and these _JSON strings should disappear

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by abhijeetdhakane** [comment]
Thanks Dr. Csányi, 

Also the positional argument for the energy parsing i.e. energy_parameter_name=energies is not parsing energies in the extended xyz file.

Thanks

**Comment by gabor1** [comment]
that’s odd, I am typically using that feature every day. Can you please attach an example XYZ and a command line which demonstrates your problem. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Jun 1, 2020, at 2:17 PM, Abhijeet <notifications@github.com> wrote:
> 
> 
> Thanks Dr. Csányi,
> 
> Also the positional argument for the energy parsing i.e. energy_parameter_name=energies is not parsing energies in the extended xyz file.
> 
> 
Note that this string refers to a per-atom quantity (Properties=...), not a per-config quantity, in the xyz header included in the earlier email.

							Noam


____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by gabor1** [comment]
yeah, can you explain why you have "energies" as a Property (per atom) and also "energy" (with the JSON crap) ? As Noam points out, the "energy_parameter_name" option in gap_fit is where you give the name of the per-configuration key that you want gap_fit to understand as the total energy to fit the potential to. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by abhijeetdhakane** [comment]
Dr. Csányi,

I realized my mistake, I thought the energy was per atom energies. As I
didn't have energy flag i.e. TOTAL ENERGY in my header of extended xyz,
sorry for that.

Best,
Abhijeet

**Comment by DQM520** [comment]
> What is the best way to incorporate extended xyz file from LAMMPS dump files.
> 
> Example from https://libatoms.github.io/GAP/ uses the below header in extended xyz. Properties=species:S:1:pos:R:3:forces:R:3:energies:R:1 energy="_JSON 70.38809727285381" pbc="T T T"
> 
> However it won't be straight forward to made such flags in lammps dump file. I used ovito to generate extended xyz from lammps dump files, but it won't work as per expected and the GAP program didn't recognize the energies. I used following as opposed to given examples: Properties=species:S:1:pos:R:3:force:R:3:c_keng:R:1:energies:R:1:mass:R:1:id:I:1
> 
> It will be great if someone resolve or gave idea on this.
> 
> Also it will be very helpful if developers add GAP tutorial with LAMMPS, especially the post-processing stuff before used into the GAP. Otherwise code work fantastic!!

Could you please look into my questions?https://github.com/mir-group/nequip/discussions/463. I also use lammps command:dump  1 all custom ${DUMP_FREQ} methane.lammpstrj id type x y z, and convert the lammpstrj form to xyz by ovito, but the file doesn't include energy and force, I'm wondering how to get the correct extxyz form. Looking for your reponse!

**Comment by jameskermode** [comment]
You could use [ase.io.extxyz](https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#extxyz) or our [extxyz](https://github.com/libAtoms/extxyz) package.

**Comment by jameskermode** [comment]
Answered at https://github.com/libAtoms/QUIP/issues/207
