### ISSUE TITLE
convert.py does not recognize extxyz format

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#21]
It would be nice if it did, for compatibility with ASE.

**Comment by jameskermode** [comment]
Both of these work for me , is there something else that doesn't?

```
$ convert.py tmp.xyz -o tmp.extxyz
$ convert.py tmp.extxyz -o tmp.xyz
```

**Comment by noambernstein** [comment]
Seems to work with the latest version (the one that's supposed to fix
"stdout").  Go ahead and close this one.
