### ISSUE TITLE
Segmentation fault - Lammps

### ISSUE THREAD

**Issue by g7dhaliwal** [libAtoms/QUIP#210]
Hi, 

   I have installed quip interface with lammps. My build is working properly for diamond potential but it gave me segmentation fault for Tungsten and Iron potentials. All the potentials are downloaded from the libatoms website. Below is the excerpt of lammps input script

pair_style quip
pair_coeff * * gp33b.xml "Potential xml_label=GAP_2016_10_3_60_19_29_10_891" 26

and here is the header of the xml file 

<GAP_2016_10_3_60_19_29_10_891>
<Potential label="GAP_2016_10_3_60_19_29_10_891" init_args="IP GAP label=GAP_2016_10_3_60_19_29_10_891"/>
<GAP_params label="GAP_2016_10_3_60_19_29_10_891" gap_version="1474379259">
  <GAP_data do_core="F">
    <e0 Z="1" value=".00000000000000000 "/>
    <e0 Z="2" value=".00000000000000000 "/>

I will appreciate of any help in resolving this issue. The lammps script works fine with other classical IP. So I am assuming the issue might be in initializing quip IP, but then it should have given me an error for diamond IP as well.

**Comment by gabor1** [comment]
maybe you need to set more stack space? 

ulimit -s unlimited

also, did you make sure to compile QUIP in serial ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by g7dhaliwal** [comment]
Thanks. The issue was with stack space.

Quip architecture is linux_x86_64_ifort_icc. I installed lammps with mpi. Now that I think of, will it affect that Quip is compiled serially and lammps as mpi?

**Comment by gabor1** [comment]
as written in the docs, that is the only way to run it. lammps does the mpi data parallelism, and calls many quip processes in serial.

-- Gábor

**Comment by g7dhaliwal** [comment]
Thanks...closing the issue.
