### ISSUE TITLE
Enviroment averaging

### ISSUE THREAD

**Issue by giovannidoni** [libAtoms/QUIP#212]
Hi all, I have found this issue on Dscribe reposotory https://github.com/SINGROUP/dscribe/issues/44 and I was wondering how to perform environment averaging on quippy/quip? I expect by default the power spectrum is returned, but to get the kind ov average over end mentioned in the issue above, one need either to have access to the full expansion, of such average being performed within quip (at least, this is as far as I got by looking a bit into the code).

Unfortunately, I could not find much info about syntax used by quip in the docs, so following @jameskermode suggesiton I am opening an issue here. Ty!

**Comment by gabor1** [comment]
you pass the "average=true" command in the string that specifies the soap descriptor

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
