### ISSUE TITLE
 expansion of density

### ISSUE THREAD

**Issue by bpfrd** [libAtoms/QUIP#214]
Hello
I was wondering if QUIP has this possibility to add a weight for each atom in the expansion of density in formula 6 in the below paper? that is:
\rho_a(r) = \sum_b  w_b*exp(-\frac{(r-r_{ab})^2}{2\sigma^2} )*f_{cut}(r_{ab})
I added w_b.
https://arxiv.org/pdf/1611.03277.pdf
Best regards
Behnam

**Comment by gabor1** [comment]
Have various mechanisms to adjust the weight of those Gaussians, the cutoff function is one of them. In addition, we have a radial scaling option, which is basically saying that the weight w in your equation below would be w(|r_{ab}|). What sort of weight are you interested in? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
can I close this?

**Comment by bpfrd** [comment]
yes.
