### ISSUE TITLE
Make config option for python command does not seem to be passed correctly

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#215]
I have been trying to make quippy on a big cluster where the default python /= python3. I passed python3 as default Python command to the make config, but this did not work. It may be related to how the make script handles the choice of shell. My default shell is bash and the make script seems to be trying to use sh instead. I had to put "alias python=python3" into my .profile (it looks like sh ignores .bashrc) to make this work. Maybe someone with a better understanding of shell environments than myself can take a look at this issue (the main point being that entering python3 as Python command during make config does not necessarily work out of the box)?

**Comment by gabor1** [comment]
Would this be solved if we made the default shell "bash" ? or somehow settable ?

**Comment by mcaroba** [comment]
Maybe it would make sense if the same shell as is being used to invoke the
make command was used, no? But how is the python3 command being passed to
the shell anyway? Because to me this seems to be the issue. Does this info
get lost if switching shells, somehow? My knowledge of make is very limited
so I just have no idea.

**Comment by gabor1** [comment]
we store your answer as a variable, and then assemble a command that starts with the contents of that variable. make uses shell commands to actually do all of the work. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Jul 1, 2020, at 2:29 PM, gabor1 <notifications@github.com> wrote:
> Would this be solved if we made the default shell "bash" ? or somehow settable ?
> 

I don't see how.  Every script should either be run explicitly with a shell (which needs to be bash, but we specify that), or with #!/bin/bash.

							Noam


____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by gabor1** [comment]
well in this case the /bin/sh is just a bug

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Jul 1, 2020, at 2:42 PM, gabor1 <notifications@github.com> wrote:
> 
> 
> well in this case the /bin/sh is just a bug
> 

If it's behaving differently from bash, yes.

						Noam


____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by mcaroba** [comment]
When I've tried to make quippy (after providing python3 as the Python
command) the installer has always run python instead. That's why the
solution for me involved an alias. Could there be a bug in the python
command part of make config or just some unexpected behaviour when the
user's shell is no sh?

**Comment by gabor1** [comment]
it could be just a missing use of the PTYHON variable, easy to check with a grep on "python" in the makefiles..

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by mcaroba** [comment]
I think this is the problem. The python3 command is registered successfully by the make config, but there is a previous check for python3 in the top-level Makefile:

PY_VERSION=$(shell python -c "import sys;t='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(t)")
HAVE_PYTHON3=$(shell python -c 'import sys; print(int(sys.version_info[0] >= 3))')
@if [ ${HAVE_PYTHON3} != 1 ] ; then echo "make quippy: Error: python3 needed. current version: ${PY_VERSION}."; exit 1; fi

These variables use "python", not the python specified by the user during make config. So if one could get past this step (e.g., by making an alias python=python3) then installation would presumably proceed successfully. Should the top-level Makefile include

include ${BUILDDIR}/Makefile.inc

(is that even possible), or maybe put the check for python3 in the quippy/Makefile instead of top-level Makefile?

**Comment by jameskermode** [comment]
Good spot, yes, that’s the problem. I’ll try to take a look tomorrow and see if I can fix it. Will require some careful escaping in the Makefile shell commands.

**Comment by jameskermode** [comment]
@mcaroba can you check if #218 fixes the problem for you? if so I'll go ahead and merge it.

**Comment by mcaroba** [comment]
Yep, this one is good, thanks for fixing it.
