### ISSUE TITLE
GAP predicted errors 

### ISSUE THREAD

**Issue by lipai-ustc** [libAtoms/QUIP#216]
Hi
I noticed that GAP predicted errors are provided in some papers, such as PHYS. REV. X8,041048 (2018). I am interested in this concept which seems not existed in neural network potential. Can I get the predicted error of each atom using quip or quippy?

**Comment by gabor1** [comment]
yes, you need to pass the "local_gap_variance" argument to quip

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
Hi,  I try adding "local_gap_variance" in the command as follows:
```
quip verbosity=ANALYSIS atoms_filename=test.xyz param_filename=gap_soap.xml E=T F=T L=T local_gap_variance=T output_file=a.out
```
but it failed to give results with the error message "unknown key local_gap_variance".  I also searched the output of "quip --help", but no information on "local_gap_variance". 
Can you tell me how to pass the "local_gap_variance" argument to quip?

**Comment by gabor1** [comment]
I think you need to pass it as part of the calc_args, which are arguments to be passed onto the calculator. 

so add this to the command line:

calc_args="local_gap_variance"

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
Yes, it works. Thank you very much. I have another question about the quip output where it gives
```
species:S:1:pos:R:3:forces:R:3:Z:I:1:map_shift:I:3:n_neighb:I:1:force:R:3:local_energy:R:1:local_gap_variance:R:1:gap_variance_gradient:R:3
```
There are two "force" items and these values are not identical. What's the difference between them?

**Comment by gabor1** [comment]
The difference is that "forces" is something you had in the XYZ before. "force" is GAP’s predictions. 

(or may be the other way around, I don’t remember)

the quip program adds new properties to your XYZ file, overwriting ones that have the SAME name

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
got it. Thank you.
