### ISSUE TITLE
How to improve the stability  of gaps potential

### ISSUE THREAD

**Issue by ZengZezhu** [libAtoms/QUIP#219]
Hi, Professor.

I just encountered a problem that my potential will collapse when used a large supercell (14000 atoms) at 400K.

I fitted my potential by the command like below:
# gap_fit energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=stress do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.001 0.03 0.03 0} gap={distance_2b cutoff=7 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=20 : soap l_max=6 n_max=6 cutoff=6.0 cutoff_transition_width=1.0 delta=1.0 atom_sigma=0.5 zeta=4 sparse_method=cur_points  add_species=T n_sparse=500 covariance_type=dot_product}

My training data are generated by AIMD at 100K, 300K 400K, and 500K. 

I would want to know how to improve the stability of potential? maybe increasing the complexity of potential (increasing the l_max and n_max and n_sparse) can solve this problem? or increasing the training data at high temperatures?

Best,

**Comment by gabor1** [comment]
I'm assuming by "collapse" you mean that atoms go on top of each other.

Is this a solid or a liquid system? For solid you should increase the 2b theta to 2A that might just do it. A sure fire solution (but more work) is to use a repulsive pair potential as a baseline - if you want to do that I have suggestions on how to make those. 

For a liquid you probably have to do iterative training, ie pick a few configurations from the gap md and fold it back into the training set. (This of course also works for solids but is again more work)

-- Gábor

**Comment by ZengZezhu** [comment]
solid, it is a simple crystal structure.

sorry for my poor expression, I mean when I used the lammps to run the MD at high temperatures after 50ps, the energy and temperatures of this system will increase dramatically and finally, some bonds of this system will break and then the lammps will have a error.

I dont know what is 2b theta, you mean the 'theta_uniform' parameter should set up 2A?

**Comment by gabor1** [comment]
check the minimum distances between atoms, it is overwhelmingly likely that atoms squashed because you didn’t have sufficient repulsion.

yes, theta_uniform=2.0 might help a bit

This sort of behaviour is very generic with any very flexible fitting system - so you need a good strategy to deal with it - see the ideas in my previous email. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
It’s also possible that you can simply include training data from 1000K and that that would solve it (for the same reasons : it will include smaller  atom-atom distances than your 500K training). If you plan to run a simulation at temperature T, you might want to include training data from temperature 2*T. This is another general strategy that helps with this. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by ZengZezhu** [comment]
Thank you for your suggestions, professor.

I will test the theta_uniform first.

I also want to learn how to add repulsive pair potential, could you give me some suggestions?

**Comment by ZengZezhu** [comment]
Yes, 2T maybe work for many system, but if the T is near of melting point, that is so sticky to deal with.....

**Comment by gabor1** [comment]
Agreed. So then you are left with iterative training or using a repulsive pair potential. Depends on which you find more interesting : something general but more DFT work, or more human work but more thinking needed. For example you can also sample smaller interatomic distances by putting in high pressure configurations. 

-- Gábor

**Comment by ZengZezhu** [comment]
Hi, professor.

I want to learn how to implement the repulsive pair potential into the gaps
potential. Because I think more DFT work cannot help me to learn anything
else as it is simple.

**Comment by ZengZezhu** [comment]
Hi, Professor.

I tried to increase the theta parameter to 2A, and it  has no distinct improvement for this problem.

**Comment by gabor1** [comment]
There are many ways to create and use  a repulsive potential with GAP. For example, take a look at the xml file of the silicon potential that we published in PRX in 2018. It is the sum of a "Glue" potential and a SOAP term. The Glue is like an EAM, with a pair potential and a density-dependent potential, but in this case we zeroed out the density dependent part, and just used the pair potential part, and put in a repulsive potential represented by spline points by hand (they were fitted to highly compressed Si crystal structures). When you train a SOAP-GAP, you can give as an argument another potential as a "baseline", and it will be subtracted from the data before the fit is made, and added back at the end. in the gap_fit command line this is called a "core" potential. 

Another possibility is to add another term to your gap string in the same fit as you did above, but to ensure that it is repulsive at close range, which you can do by using the "distance_2b" descriptor and specifying distance exponents, and choosing e.g. r^12. this is done by specifying e.g.  n_exponents=2 exponents={6 12}, this will fit a Lennard-Jones style potential (you still need to give a n_sparse but it doesn't matter what you use, e.g. n_sparse=4 is enough), which almost always ends up with a positive r^12 term and a negative r^6 term, so the right way around. To ensure that this indeed is the case, I would even remove the current distance_2b term that you have (or reduce its delta by a factor of 10)

**Comment by ZengZezhu** [comment]
Thank you professor, I will try.

**Comment by gabor1** [comment]
can I close this?

**Comment by ZengZezhu** [comment]
Yes, Professor, Thanks!
