### ISSUE TITLE
Error in openning GAP.xml

### ISSUE THREAD

**Issue by Arunimaghosh693** [libAtoms/QUIP#221]
I want to load a GAP potential in python code and for this, I execute this line :
gap3b = Potential(param_filename='GAP.xml').
But it is giving me the following error : "File "/home/arunima/Arunima/QUIP/src/libAtoms/System.f95", line 429 kind unspecified
IO error opening "GAP.xml" on unit 9, error number: 5004". Can you please tell me where I am going wrong?

**Comment by Arunimaghosh693** [comment]
I got this error in notebook and no other process is running apart from it.

**Comment by gabor1** [comment]
I've never seen this error, so it will take a little bit of experimenting. Please do the following tests. Write a stand-alone python script (so no notebook) to see if you still get the error. 

Also, try the "quip" command line program, so no python, to use there danger GAP.xml file to see if it works.

-- Gábor

**Comment by zhongliliu** [comment]
I got the same error for tests/test_gappot.py.

**Comment by gabor1** [comment]
and the "quip" program test ? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by zhongliliu** [comment]
Yes, the quippy import is ok.

Python 3.7.6 (default, Jan  8 2020, 19:59:22)                         
[GCC 7.3.0] :: Anaconda, Inc. on linux                                
Type "help", "copyright", "credits" or "license" for more information.
>>> import quippy                                                     
>>>

**Comment by gabor1** [comment]
I'm not asking about the quippy import. I'm asking you to try the quip command line program that got made when you compiled. It can also read the XML file and evaluate the potential. Type "quip --help" to see the usage


-- Gábor

**Comment by zhongliliu** [comment]
This test is also successful.

I am using:
quip atoms_filename=gap_sample.xyz param_filename=GAP.xml E F > quip.log


[quip.log](https://github.com/libAtoms/QUIP/files/4974544/quip.log)

**Comment by gabor1** [comment]
So your potential is ok and your Fortran compilation is ok. I can only suggest that you create a new python virtual environment, check that no previous installation of quippy exists and try to install it again. 

Alternatively, you can use it from the command line or from lammps.

Still alternatively you could use it from our docker where it works from python..

-- Gábor

**Comment by zhongliliu** [comment]
Thank you so much! I'll try these.

**Comment by gabor1** [comment]
when you do that, it’s probably worth downloading a fresh copy of everything. so that your quippy compilation is happenning with the correct python

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by zhongliliu** [comment]
Thanks!

I succeeded after removing previous installations and starting from a new environment.
