### ISSUE TITLE
Having Trouble generating quippy Atoms Objects

### ISSUE THREAD

**Issue by Zausinator** [libAtoms/QUIP#224]
Hi, 
I would like to run a MD on a system using a GAP Potential and having trouble feeding my atoms into this calculation.

I assume that the quippy Atoms class no longer exists (at least it doesnt appear to be a part of my install). However I do not quite know how to add the Atoms to my quippy.DynamicalSystem class. I have tried ase.Atoms, as well as the quippy.dynamicalsystem_module.Atoms class (although to be honest I do not quite understand how the inputs in this class work).

I am grateful for your help!

With kind regards,
Nicolas

**Comment by gabor1** [comment]
All those are obsolete. The only things we expose from QUIP to quippy are Potentials and Descriptors. Use ASE Atoms and ASE MD. quippy.potentials can be used like an ASE calculator. For large runs, use LAMMPS and the QUIP pairstyle
