### ISSUE TITLE
linmin_method not passed on by quip cli

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/QUIP#23]
Reported by Gabor:

`quip cij` fails with `Invalid linminroutine: default`. If I give `linmin_method=NR_LINMIN` then it works. changing to `minim_method=precond` doesn't work either. I can see in line 416 of quip.f95 where the "default" is supposed to be dispatched, but it doesn't work.

**Comment by gabor1** [comment]
I moved the dispatch for the linmin method and so this now gives a sensible error.
