### ISSUE TITLE
Missing deallocation when using `quip` to compute descriptor gradients

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#237]
I'm using the `quip` program to compute just SOAP descriptors (and their gradients), no kernels or GAP. It immediately crashes because the array `grad_descriptor_pos`:
https://github.com/libAtoms/QUIP/blob/cfa8d30bee80c7f253fa9ee0db847cee958859f0/src/Programs/quip.f95#L790-L791
is allocated but not later deallocated with the others here:
https://github.com/libAtoms/QUIP/blob/cfa8d30bee80c7f253fa9ee0db847cee958859f0/src/Programs/quip.f95#L813-L814
leading to a multiple-allocation error on the next loop.

The fix is one line (will commit soon), but this worries me slightly because it implies the descriptors-only functionality of the `quip` program hasn't been used or tested in a long time. Or is this just some weirdness introduced by a merge or something?

**Comment by gabor1** [comment]
Thanks. it is rarely used indeed
