### ISSUE TITLE
Regular builds take too long

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#24]
Travis builds all configurations for all pushes. During peak times, this can take nearly four hours, which is not ideal for checking in small changes. Break the builds into two sets:

Regular builds (9 total configurations ~ 30 mins on a good day):
- Python 2.7
- Default GCC 4.6
- VANILLA, ALL_NOEXTERNAL, and ALL configurations
- gfortran, gfortran_openmp, gfortran_openmpi

'Weekly' builds:
- Python 2.7, 2.6
- Default GCC 4.4, 4.6, (4.9?), 5
- VANILLA, ALL_NOEXTERNAL, and ALL configurations
- gfortran, gfortran_openmp, gfortran_openmpi

Weekly builds could be triggered and separated by restarting the last build on Sunday night and putting logic to skip certain builds if it is not overnight on Sunday.

Could also force building of all configurations if the last build failed?

**Comment by gabor1** [comment]
the regular could be just VANILLA

**Comment by albapa** [comment]
Could there be the regular build for VANILLA with gfortran_openmp,
gfortran_openmpi (which should catch almost everything), a daily build of
what is currently the "regular" and on top of that the weekly?

On 26 January 2016 at 12:23, gabor1 notifications@github.com wrote:

> the regular could be just VANILLA
> 
> > On 26 Jan 2016, at 13:00, Tom Daff notifications@github.com wrote:
> > 
> > Travis builds all configurations for all pushes. During peak times, this
> > can take nearly four hours, which is not ideal for checking in small
> > changes. Break the builds into two sets:
> > 
> > Regular builds (9 total configurations ~ 30 mins on a good day):
> > 
> > Python 2.7
> > Default GCC 4.6
> > VANILLA, ALL_NOEXTERNAL, and ALL configurations
> > gfortran, gfortran_openmp, gfortran_openmpi
> > 'Weekly' builds:
> > 
> > Python 2.7, 2.6
> > Default GCC 4.4, 4.6, (4.9?), 5
> > VANILLA, ALL_NOEXTERNAL, and ALL configurations
> > gfortran, gfortran_openmp, gfortran_openmpi
> > Weekly builds could be triggered and separated by restarting the last
> > build on Sunday night and putting logic to skip certain builds if it is not
> > overnight on Sunday.
> > 
> > Could also force building of all configurations if the last build failed?
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/libAtoms/QUIP/issues/24>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/libAtoms/QUIP/issues/24#issuecomment-174979273.

## 

Dr Albert Bartok-Partay
Leverhulme Early Career Fellow

Department of Engineering, University of Cambridge, Cambridge, CB21PZ
Magdalene College, Cambridge, CB30AG

T: +44 1223 748232
W: http://www.bartokpartay.com
E: ab686@cam.ac.uk
PGP public key: http://pgp.mit.edu (ID:FC646FB1)
