### ISSUE TITLE
Size of input string

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#247]
I seem to have trouble with a long `gap_fit` command (I'm explicitly defining *a lot* of descriptor types). I get this error:

    SYSTEM ABORT: Traceback (most recent call last)
    File "/projappl/project_2000634/quip/quip_dev/src/libAtoms/System.f95", line 1167 kind unspecified
    parse_string ran out of space for fields

I can progressively remove descriptors until I have few enough that the string will get processed. These variables look like they might be involved:

    Dictionary.f95:  integer, parameter :: STRING_LENGTH = 10240     !% Maximum string length
    System.f95:  integer, parameter, private      :: SYSTEM_STRING_LENGTH = 1024 !max line length read
    Table.f95:  integer, parameter :: TABLE_STRING_LENGTH = 10

Can I make QUIP parse more descriptors by changing these defaults or am I looking in the wrong place?

**Comment by jameskermode** [comment]
It's the size of the `fields` array passed to `parse_string()` which is being exceeded. This is set by `MAX_N_FIELDS = 300` in `libAtoms/ParamReader.f95`, so you could increase this.

**Comment by mcaroba** [comment]
Yes, that fixed the issue - thanks.
