### ISSUE TITLE
GAP calculation results very large error in boron example

### ISSUE THREAD

**Issue by bigd4** [libAtoms/QUIP#249]
Dear libAtoms and QUIP developers and users,
I just started to learn to use  GAP model for elemental boron as described in Phys. Rev. Lett. 120, 156001 (2018). I download the dataset with B.xml and sps_all.xyz, however, I get unexpected large RMSE on the dataset.
Here is my test code:
```
import numpy as np                                                          
from ase.io import read, write
from quippy.potential import Potential
calc = Potential(param_filename='B.xml')

frames = read('sps_all.xyz',':')
for atoms in frames:
    atoms.info['true'] = atoms.get_potential_energy()
    atoms.set_calculator(calc)
    atoms.info['predict'] = atoms.get_potential_energy()
write('out.traj', frames)

targete = np.array([atoms.info['true']/len(atoms) for atoms in frames])
predicte = np.array([atoms.info['predict']/len(atoms) for atoms in frames])
print(np.sqrt(np.mean((targete-predicte) ** 2)))
```
And I get the result 10.835327067886942, how can I solve this problem?

**Comment by gabor1** [comment]
which URL did you use to grab the data? I want to run your script on the same

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bigd4** [comment]
> which URL did you use to grab the data? I want to run your script on the same
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 5 Nov 2020, at 08:33, wang laosi ***@***.***> wrote: Dear libAtoms and QUIP developers and users, I just started to learn to use GAP model for elemental boron as described in Phys. Rev. Lett. 120, 156001 (2018). I download the dataset with B.xml and sps_all.xyz, however, I get unexpected large RMSE on the dataset. Here is my test code: import numpy as np from ase.io import read, write from quippy.potential import Potential calc = Potential(param_filename='B.xml') frames = read('sps_all.xyz',':') for atoms in frames: atoms.info['true'] = atoms.get_potential_energy() atoms.set_calculator(calc) atoms.info['predict'] = atoms.get_potential_energy() write('out.traj', frames) targete = np.array([atoms.info['true']/len(atoms) for atoms in frames]) predicte = np.array([atoms.info['predict']/len(atoms) for atoms in frames]) print(np.sqrt(np.mean((targete-predicte) ** 2))) And I get the result 10.835327067886942, how can I solve this problem? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for your reply, here is my url:
https://www.dropbox.com/s/z6ai5non3s9t4nv/B_GAP-RSS.tar.gz?dl=0

**Comment by gabor1** [comment]
I can confirm the output of the script. I am looking into it. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bigd4** [comment]
> I can confirm the output of the script. I am looking into it.
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 5 Nov 2020, at 11:17, wang laosi ***@***.***> wrote: which URL did you use to grab the data? I want to run your script on the same … -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/ On 5 Nov 2020, at 08:33, wang laosi @.***> wrote: Dear libAtoms and QUIP developers and users, I just started to learn to use GAP model for elemental boron as described in Phys. Rev. Lett. 120, 156001 (2018). I download the dataset with B.xml and sps_all.xyz, however, I get unexpected large RMSE on the dataset. Here is my test code: import numpy as np from ase.io import read, write from quippy.potential import Potential calc = Potential(param_filename='B.xml') frames = read('sps_all.xyz',':') for atoms in frames: atoms.info['true'] = atoms.get_potential_energy() atoms.set_calculator(calc) atoms.info['predict'] = atoms.get_potential_energy() write('out.traj', frames) targete = np.array([atoms.info['true']/len(atoms) for atoms in frames]) predicte = np.array([atoms.info['predict']/len(atoms) for atoms in frames]) print(np.sqrt(np.mean((targete-predicte) ** 2))) And I get the result 10.835327067886942, how can I solve this problem? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Thank you for your reply, here is my url: https://www.dropbox.com/s/z6ai5non3s9t4nv/B_GAP-RSS.tar.gz?dl=0 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Could you please tell me your output? If it is different, how can I find the problem?

**Comment by gabor1** [comment]
the test training I submitted a week ago still hasn’t run for some reason, I’m booting my students off the queue now so that I can figure out what’s going on. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Thanks for the patience. I have verified that this problem is because of a change in a default value, since the time that file was written, which results in the wrong interpretation of the data. I have made a copy of that B.xml file and corrected it so the current code can now interpret its data correctly. Here is a link:

https://www.dropbox.com/s/1atzz738p1ai6yt/Bfixed.xml?dl=0

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bigd4** [comment]
> Thanks for the patience. I have verified that this problem is because of a change in a default value, since the time that file was written, which results in the wrong interpretation of the data. I have made a copy of that B.xml file and corrected it so the current code can now interpret its data correctly. Here is a link: https://www.dropbox.com/s/1atzz738p1ai6yt/Bfixed.xml?dl=0
> […](#)
> -- Gábor Gábor Csányi Professor of Molecular Modelling Engineering Laboratory, University of Cambridge Pembroke College Cambridge Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
> On 5 Nov 2020, at 08:33, wang laosi ***@***.***> wrote: Dear libAtoms and QUIP developers and users, I just started to learn to use GAP model for elemental boron as described in Phys. Rev. Lett. 120, 156001 (2018). I download the dataset with B.xml and sps_all.xyz, however, I get unexpected large RMSE on the dataset. Here is my test code: import numpy as np from ase.io import read, write from quippy.potential import Potential calc = Potential(param_filename='B.xml') frames = read('sps_all.xyz',':') for atoms in frames: atoms.info['true'] = atoms.get_potential_energy() atoms.set_calculator(calc) atoms.info['predict'] = atoms.get_potential_energy() write('out.traj', frames) targete = np.array([atoms.info['true']/len(atoms) for atoms in frames]) predicte = np.array([atoms.info['predict']/len(atoms) for atoms in frames]) print(np.sqrt(np.mean((targete-predicte) ** 2))) And I get the result 10.835327067886942, how can I solve this problem? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much!
