### ISSUE TITLE
quippy build fails at the f90wrap_Potential.f90 step

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#251]
I am trying to build quippy on a VM with Ubuntu 20.04 on it. The system is very similar to others where I have successfully built QUIP/GAP/quippy, and unfortunately I can't extract too much information from the error message spit out during `make quippy`:

    compiling Fortran sources
    Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
    Fortran f90 compiler: gfortran -ffree-line-length-none -fPIC -O3 -funroll-loops
    Fortran fix compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -ffree-line-length-none -fPIC -O3 -funroll-loops
    compile options: '-I./src.linux-x86_64-3.8/./src.linux-x86_64-3.8 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.8 -c'
    gfortran:f90: f90wrap_Atoms_types.f90
    gfortran:f90: f90wrap_Atoms.f90
    gfortran:f90: f90wrap_System.f90
    gfortran:f90: f90wrap_Dictionary.f90
    gfortran:f90: f90wrap_DynamicalSystem.f90
    gfortran:f90: f90wrap_nye_tensor.f90
    gfortran:f90: f90wrap_Potential.f90
    gfortran: fatal error: Killed signal terminated program f951
    compilation terminated.
    analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '10240'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.error: Command "gfortran -ffree-line-length-none -fPIC -O3 -funroll-loops -I./src.linux-x86_64-3.8/./src.linux-x86_64-3.8 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.8 -c -c f90wrap_Potential.f90 -o ./f90wrap_Potential.o" failed with exit status 1
    make[1]: *** [Makefile:94: _quippy.so] Error 1
    make[1]: Leaving directory '/home/caro/apps/quip/quip_dev/build/linux_x86_64_gfortran'
    make: *** [Makefile:227: quippy] Error 2

Does anybody have any ideas what may be going wrong?

**Comment by gabor1** [comment]
the test training I submitted a week ago still hasn’t run for some reason, I’m booting my students off the queue now so that I can figure out what’s going on. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by mcaroba** [comment]
I think it may be related to memory, I'm checking at the moment to see if that's the case. VMs with 1 and 2 GB of RAM failed. I will update in a moment.

**Comment by mcaroba** [comment]
Actually, the successful build completed as I wrote the previous lines. A summary:

It appears that this problem was not related to QUIP directly. It seems it was an issue with the amount of available memory on the VM (1 GB, 2 GB also failed) being too small to compile Quippy. When I tried with more memory (8 GB VM) the code compiled successfully. I wonder why the compilation of f90wrap_Potential.f90 requires so much available RAM.

**Comment by jameskermode** [comment]
I guess it's just a big file which requires lots of compiler resources. Good to know that increasing the memory limit solved the problem. If the problem recurs we could reduce the list of functions/subroutines in Potential.f95 that we wrap, since we only really need the high-level entry points.
