### ISSUE TITLE
installing QUIP/GAP in LAMMPS

### ISSUE THREAD

**Issue by weilaigit** [libAtoms/QUIP#255]
I was able to install Libatoms/QUIP/GAP following the instruction.  I was alos able to use gap_fit and run ASE using the fitted model.

However, I wasn't able to compile LAMMPS (3Mar20 version) using the libquip.a and it gave me an undefined reference error.  I used the src/f90wrap (version 0.2.3).  The undefined reference usually means a missing header file but I couldn't figure out what is missing.

ld: /mnt/research/lai-lab/Software/QUIP/build/linux_x86_64_ifort_icc/libquip.a(error.o): in function `error_module_mp_error_abort_with_message_':
/mnt/research/lai-lab/Software/QUIP/src/libAtoms/error.f95:308: undefined reference to `f90wrap_abort_'
make[1]: *** [../lmp_mpi] Error 1
make[1]: Leaving directory `/mnt/ufs18/rs-006/lai-lab/Codes-C7/lammps-3Mar20/src/Obj_mpi'
make: *** [mpi] Error 2

**Comment by mcaroba** [comment]
I remember trying to install LAMMPS with QUIP support using the Intel compiler and having trouble. It was too long ago to remember what the problem was, but you may want to try to build the codes using gfortran/gcc, it may be simpler to get it to work.

**Comment by gabor1** [comment]
No, this is something very recent, we’re looking at it. Thanks for reporting it. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by mcaroba** [comment]
Does it also affect gcc/gfortran?

**Comment by gabor1** [comment]
I'm sure it will, this is the result of a recent change in how quippy and libatoms interact, and somehow the unintended side effect on the lammps compilation was missed. we're on it.

**Comment by weilaigit** [comment]
I tried to compile QUIP with cp2k using both GNU and Intel compilers, it's the similar error associated with f90wrap.

Thanks for working on this.  At the same time, is there a QUIP repo that works together with LAMMPS?

**Comment by jameskermode** [comment]
Commit 759b5da3c64075515b0b597960d5b9290a33e1a9 will work if you need an immediate fix. GAP would also need to be reverted by one commit. I’ll try to check in a fix later tonight.

**Comment by weilaigit** [comment]
I don't have easy access to GAP commits. I guess I will wait for the fix then.

**Comment by jameskermode** [comment]
I pushed a fix that builds for me locally - haven't tested with LAMMPS, but I would expect it to work so please let me know. This is the corresponding change you'll need to make in `src/GAP/Makefile` (also pushed, but the download tarball won't update straight away)

```diff
diff --git a/Makefile b/Makefile
index b6b81a9..01e50ec 100644
--- a/Makefile
+++ b/Makefile
@@ -69,7 +69,7 @@ endif

 PROGRAMS = gap_fit

-LIBS = -L. -lquiputils -lquip_core -lgap -latoms f90wrap_stub.o
+LIBS = -L. -lquiputils -lquip_core -lgap -latoms
 ifeq (${HAVE_THIRDPARTY},1)
   LIBS += -lthirdparty
 endif
```

**Comment by weilaigit** [comment]
Thanks James.  QUIP compiled with intel 2019.1 could be linked to LAMMPS (also intel 2019.1 and intel mpi) but the lammps executable had the early termination error without any results.

QUIP compiled with gfortran (8.2) could be linked to LAMMPS 3Mar20 version (g++ and openmpi) and lammps-quip ran successfully.

If the issue with intel compilers is not a concern, this can be closed.
