### ISSUE TITLE
Error on compile from git using intel compiles (2015-version).

### ISSUE THREAD

**Issue by erlendd** [libAtoms/QUIP#26]
Is there a recommended revision to checkout from the git repo for stable use?

`integer, intent(out), dimension() :: mainlog_ptr, errorlog_ptr
------------------------------------^
/home/erdavids/src/git/QUIP.intel/src/libAtoms/System.f95(2093): error #6364: The upper bound shall not be omitted in the last dimension of a reference to an assumed size array.   [MAINLOG_PTR]
    mainlog_ptr = transfer(mainlog_p, mainlog_ptr)
----^
/home/erdavids/src/git/QUIP.intel/src/libAtoms/System.f95(2093): error #6364: The upper bound shall not be omitted in the last dimension of a reference to an assumed size array.   [MAINLOG_PTR]
    mainlog_ptr = transfer(mainlog_p, mainlog_ptr)
--------------------------------------^
/home/erdavids/src/git/QUIP.intel/src/libAtoms/System.f95(2095): error #6364: The upper bound shall not be omitted in the last dimension of a reference to an assumed size array.   [ERRORLOG_PTR]
    errorlog_ptr = transfer(errorlog_p, errorlog_ptr)
----^
/home/erdavids/src/git/QUIP.intel/src/libAtoms/System.f95(2095): error #6364: The upper bound shall not be omitted in the last dimension of a reference to an assumed size array.   [ERRORLOG_PTR]
    errorlog_ptr = transfer(errorlog_p, errorlog_ptr)
`----------------------------------------^``

**Comment by gabor1** [comment]
In the meantime, can you use gfortran? I'll raise an issue on github. We don't much use Intel compilers any more, but it's strict nature is useful to help catch bugs. 

Why do use QUIP for the nested sampling? QUIP is the most cumbersome, you can use your own Fortran subroutine our lammps. 

-- Gábor

**Comment by jameskermode** [comment]
I agree, I'm mostly using gfortran too. Erlend, if you let me know the exact ifort version, I'll see if I can reproduce. I just checked that our autobuilder with ifort is still working on womble. The code is still compiling correctly with ifort 11.1.069 so this must be an issue with newer intel compilers only. There are quite often compiler bugs in X.Y.0 versions....

**Comment by erlendd** [comment]
Thanks for the replies. It's not an ifort issue and it occurs with every version of ifort I've tried (from 8.0 through to 2015.3). I tracked the issue down to "SIZEOF_FORTRAN_T" being unset in build/linux_x86_64_ifort_icc/Makefile.inc. I set that to 2 and that particular error goes away. I'm guessing make config is supposed to set it automatically though?

With SIZEOF_FORTRAN_T set I was able to compile using ifort 11.1.073. I was also able to compile with gfortran (I forget the version).

**Comment by jameskermode** [comment]
Aha! Yes, that is supposed to be set by make config, which uses `bin/find_sizeof_fortran_t` to find the size of a Fortran derived type pointer on your system. Can you check if this script works for you if you invoke it directly?

**Comment by erlendd** [comment]
Here's the output of find_sizeof_fortran_t:

_-bash-4.1$ sh ./bin/find_sizeof_fortran_t
make: /bin/gitversion: Command not found
make: /bin/gapversion.sh: Command not found
SIZEOF_FORTRAN_T= 2_

**Comment by jameskermode** [comment]
OK, that is because it would normally be invoked from Makefile with QUIP_ROOT env var set to path to top-level QUIP directory. Can you try doing that?

**Comment by erlendd** [comment]
Yes, then it works without an error.

**Comment by erlendd** [comment]
I've just worked out what the problem is.
Basically if you run "make config" before loading the 'intel-suite' (or equivalent) module then sizeof_fortran_t will be unset, as it isn't possible to build the fortran code. This doesn't happen with gfortran because usually a system-wide version in /usr/bin is always available.

Maybe the first check in "make config" should test that whichever compiler is selected via QUIP_ARCH= is actually in the path?

**Comment by jameskermode** [comment]
Good work. Patches/pull requests welcome :-)
