### ISSUE TITLE
How to run EMA calculations

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#262]
Is there any online (or offline) documentation on how to run embedded-atom method (EAM) calculations with QUIP? The docs say this is possible (it's actually the first item in the list of featured methods). How is it invoked, how to find potential files, etc?

**Comment by gabor1** [comment]
it's called "Glue" model. you can see how it's used in the silicon PRX potential. the glue.xml has three parts,  a pair potential, and a radial density, and an embedding function (energy as a function of density). for the si prx only the pair potential is used, the rest set to zero, but you can see the format in the file.

**Comment by gabor1** [comment]
[glue.xml.zip](https://github.com/libAtoms/QUIP/files/5673617/glue.xml.zip)

**Comment by jameskermode** [comment]
Glue != EAM, though

We also have EAM_ErcolAd in QUIP. I wouldn't particularly recommend using it in preference to EAM from ASE, matscipy or LAMMPS, unless you need to combine it with GAP.

**Comment by gabor1** [comment]
I guess one could recreate most EAMs as a glue, no?

**Comment by jameskermode** [comment]
I've never taken the time to look at the differences, just pointing out we have both implemented so presumably they're not exactly equivalent.

**Comment by jameskermode** [comment]
(I'm going to press 'convert to discussion' on this issue, since it doesn't report a fault in the code)
