### ISSUE TITLE
linked lists don't build with gfortran 4.4

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#27]
@albapa I'm not sure if you can just remove the `allocatable`?

```
/home/travis/build/libAtoms/QUIP/src/libAtoms/LinkedList.f95:48.33:
     integer, allocatable :: data
                                 1
Error: Allocatable component at (1) must be an array
make[1]: *** [LinkedList.o] Error 1
make: *** [libAtoms] Error 2
```

**Comment by albapa** [comment]
Absolutely, it shouldn't have been there in the first place. Removed now. Thanks!

**Comment by xyk-62** [comment]
Hi! 
when I try to run gap_fit, I encountered an error as follows:

Operating system error: Cannot allocate memory
Allocation would exceed memory limit

**Comment by gabor1** [comment]
Well yes, you need a lot of memory to solve large linear systems. 

-- Gábor

**Comment by xyk-62** [comment]
Does it mean that I need to expand the memory for my computer, or run it on the server?




------------------ 原始邮件 ------------------
发件人: "gabor1"<notifications@github.com>; 
发送时间: 2019年7月26日(星期五) 上午10:36
收件人: "libAtoms/QUIP"<QUIP@noreply.github.com>; 
抄送: "熊园坤"<1372455028@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [libAtoms/QUIP] linked lists don't build with gfortran 4.4 (#27)



Well yes, you need a lot of memory to solve large linear systems. 
 
 -- Gábor

**Comment by gabor1** [comment]
Um... I'm not sure what you mean by "the server". But I suspect you should get some advice from someone in your group who knows about computers.

How many atoms are in your input file in total and how many different atomic numbers are in the file?

-- Gábor

**Comment by xyk-62** [comment]
There are approximately 150,000 local atomic environments




------------------ 原始邮件 ------------------
发件人: "gabor1"<notifications@github.com>; 
发送时间: 2019年7月26日(星期五) 上午10:54
收件人: "libAtoms/QUIP"<QUIP@noreply.github.com>; 
抄送: "熊园坤"<1372455028@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [libAtoms/QUIP] linked lists don't build with gfortran 4.4 (#27)



Um... I'm not sure what you mean by "the server". But I suspect you should get some advice from someone in your group who knows about computers.
 
 How many atoms are in your input file in total and how many different atomic numbers are in the file?
 
 -- Gábor

**Comment by gabor1** [comment]
That's a very large system, assuming you have forces for all of it. We fit those on a server that has 1500GB of memory (and 32 cores), it takes 36 hours.

AWS has servers with 1000GB memory if you can't get access to such a machine.

I strongly suggest you play with smaller fits to get the hang of it.

Also use small n_max and l_max to start with (eg 6), that reduces both the memory footprint and the computation time.

-- Gábor

**Comment by xyk-62** [comment]
I see, thank you very much!




------------------ 原始邮件 ------------------
发件人: "gabor1"<notifications@github.com>; 
发送时间: 2019年7月26日(星期五) 中午11:09
收件人: "libAtoms/QUIP"<QUIP@noreply.github.com>; 
抄送: "熊园坤"<1372455028@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [libAtoms/QUIP] linked lists don't build with gfortran 4.4 (#27)



That's a very large system, assuming you have forces for all of it. We fit those on a server that has 1500GB of memory (and 32 cores), it takes 36 hours.
 
 AWS has servers with 1000GB memory if you can't get access to such a machine.
 
 I strongly suggest you play with smaller fits to get the hang of it.
 
 Also use small n_max and l_max to start with (eg 6), that reduces both the memory footprint and the computation time.
 
 -- Gábor
