### ISSUE TITLE
Import quippy Error: Aborted

### ISSUE THREAD

**Issue by vishankkumar** [libAtoms/QUIP#274]
Hi,

I have installed quippy on hpc following all the steps till `make install-quippy` and it compiled without an error but now if I run the tests or simply `import quippy` in python, it prints `Aborted` and exit python. Any idea if I am missing something or have to set some paths?

**Comment by gabor1** [comment]
hm.. hard to say, maybe dome of the more wizardly python experts here will chip in. it’s important that the C compiler used in the process of building quippy is compatible with the python you run. hpc centers sometimes have weird python and compiler configurations. 
 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gelzinyte** [comment]
In my case the issue was with f90wrap installation from conda-forge; re-installing from source in QUIP (`pip install QUIP/src/f90wrap`) worked.

**Comment by jameskermode** [comment]
Yes - the only version of f90wrap that currently works with QUIP is the tagged version in `QUIP/src/f90wrap`. Neither the pip release nor the conda one are sufficiently up to date. Making a new release is on my TODO list...
