### ISSUE TITLE
Latest container version does not include python3 quippy support?

### ISSUE THREAD

**Issue by max1c** [libAtoms/QUIP#276]
$ singularity exec QUIP_latest.sif python
Python 2.7.14 (default, Oct 10 2017, 02:49:49) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>>> import quippy
 WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
\>>> 

$ singularity exec QUIP_latest.sif python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import quippy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'quippy'
\>>>

**Comment by jameskermode** [comment]
Is this the Docker image converted to Singularity? The version on SingularityHub is certainly not up to date.

**Comment by max1c** [comment]
> Is this the Docker image converted to Singularity? The version on SingularityHub is certainly not up to date.

No this was downloaded from SingularityHub according to the instructions. I will download one from Docker. Thanks for letting me know.

**Comment by jameskermode** [comment]
I will remove the reference to SingularityHub from the README. I think it's going to shutdown soon anyway.
