### ISSUE TITLE
gcc10 failed to compile on Mac OS

### ISSUE THREAD

**Issue by thuwangming** [libAtoms/QUIP#277]
Hello!
I encountered a problem when compiling QUIP using gcc10 on Mac OS.
It raised errors like: "non-void function 'xyz_find_index' should return a value [-Wreturn-type]"
The full output is as follows:

/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:180:5: error: non-void
      function 'xyz_find_index' should return a value [-Wreturn-type]
    RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot access xyz file %s\n", fname);
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:203:7: error: non-void
      function 'xyz_find_index' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot stat xyz file %s\n", fname);
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:206:7: error: non-void
      function 'xyz_find_index' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot stat xyz.idx file %s\n", fname);
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:224:5: error: non-void
      function 'xyz_read_index' should return a value [-Wreturn-type]
    RAISE_ERROR_WITH_KIND(ERROR_IO, "Index file %s cannot be opened\n", ...
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:227:5: error: non-void
      function 'xyz_read_index' should return a value [-Wreturn-type]
    RAISE_ERROR_WITH_KIND(ERROR_IO, "Index file %s is empty\n",indexname);
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:233:7: error: non-void
      function 'xyz_read_index' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO, "Premature end of indexfile %s\n",...
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:250:5: error: non-void
      function 'xyz_update_index' should return a value [-Wreturn-type]
    RAISE_ERROR_WITH_KIND(ERROR_IO, "xyz_update_index: cannot open %s fo...
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:281:7: error: non-void
      function 'xyz_update_index' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO, "xyz_find_frames: malformed XYZ fi...
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:346:3: error: non-void
      function 'xyz_find_frames' should return a value [-Wreturn-type]
  PASS_ERROR;
  ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:128:155: note:
      expanded from macro 'PASS_ERROR'
  ...c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
                                                                      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:351:5: error: non-void
      function 'xyz_find_frames' should return a value [-Wreturn-type]
    PASS_ERROR;
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:128:155: note:
      expanded from macro 'PASS_ERROR'
  ...c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
                                                                      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:356:5: error: non-void
      function 'xyz_find_frames' should return a value [-Wreturn-type]
    PASS_ERROR;
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:128:155: note:
      expanded from macro 'PASS_ERROR'
  ...c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
                                                                      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:359:7: error: non-void
      function 'xyz_find_frames' should return a value [-Wreturn-type]
      RAISE_ERROR("xyz_find_frames: empty file!");
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:126:300: note:
      expanded from macro 'RAISE_ERROR'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:363:5: error: non-void
      function 'xyz_find_frames' should return a value [-Wreturn-type]
    PASS_ERROR;
    ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:128:155: note:
      expanded from macro 'PASS_ERROR'
  ...c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
                                                                      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:413:43: warning: format
      string is not a string literal (potentially insecure) [-Wformat-security]
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
                                          ^~~~
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:70: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
#define RAISE_ERROR_WITH_KIND(kind, info, ...) sprintf(error_h_info, info, ## __...
                                                                     ^~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:47:56: note:
      expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:413:43: note: treat the
      string as an argument to avoid this
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
                                          ^
                                          "%s",
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:70: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
#define RAISE_ERROR_WITH_KIND(kind, info, ...) sprintf(error_h_info, info, ## __...
                                                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:47:56: note:
      expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:413:7: error: non-void
      function 'get_line' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:425:2: error: non-void
      function 'get_line' should return a value [-Wreturn-type]
        RAISE_ERROR_WITH_KIND(ERROR_IO, "cannot strip prefix from line <...
        ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:431:43: warning: format
      string is not a string literal (potentially insecure) [-Wformat-security]
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
                                          ^~~~
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:70: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
#define RAISE_ERROR_WITH_KIND(kind, info, ...) sprintf(error_h_info, info, ## __...
                                                                     ^~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:47:56: note:
      expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:431:43: note: treat the
      string as an argument to avoid this
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
                                          ^
                                          "%s",
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:70: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
#define RAISE_ERROR_WITH_KIND(kind, info, ...) sprintf(error_h_info, info, ## __...
                                                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:47:56: note:
      expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:431:7: error: non-void
      function 'get_line' should return a value [-Wreturn-type]
      RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
      ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:438:2: error: non-void
      function 'get_line' should return a value [-Wreturn-type]
        RAISE_ERROR_WITH_KIND(ERROR_IO, "cannot strip prefix from line <...
        ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:303: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...if (error != NULL) { *error = error_h_kind; return; } else c_error_abort...
                                                 ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/xyz.c:1047:138: warning: data
      argument not used by format string [-Wformat-extra-args]
  ..."incomplete row, frame %d atom %d - got %d/%d entries line %d\n", frame, n, k, entry_count, frame, l...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                   ^
/Users/wangming/Downloads/QUIP-py2/src/libAtoms/libatoms.h:127:79: note:
      expanded from macro 'RAISE_ERROR_WITH_KIND'
  ...info, ...) sprintf(error_h_info, info, ## __VA_ARGS__ ); error_h_line = ...
                                      ~~~~     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:47:56: note:
      expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
3 warnings and 17 errors generated.
make[1]: *** [xyz.o] Error 1
make: *** [libAtoms] Error 2

How can I solve this problem? 
Thanks!

**Comment by thuwangming** [comment]
I tried to add flags "-Wreturn-type" and it's OK.

**Comment by gabor1** [comment]
Note that we discourage building with native MacOS development tools, none of us do any testing like that. on the mac, either homebrew, macports, or docker is the preferred way. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
