### ISSUE TITLE
GAP training using quippy/python without QUIP

### ISSUE THREAD

**Issue by sshepherd637** [libAtoms/QUIP#279]
Hi all,

Firstly, apologies if this question is trivial or if it's labelled quite clearly within the source code, but I have been unable to find a solution to it. 

Essentially, I'm trying to recreate the output alpha values within the gap.xml file using quippy and bypassing the use of gap_fit if possible. I've used the libatoms tutorials and am able to generate descriptors no problem at all, however I seem to be unable to find/use the right matrix operations to create the same alpha values as those calculated by gap_fit.

I've included my code to generate the descriptors, kernels and alpha values as well as the datafile I was using to see if it could be done (It's just a N2 molecule MD). Any comments or advice is greatly appreciated.

[quippy_regression.zip](https://github.com/libAtoms/QUIP/files/5934179/quippy_regression.zip)

**Comment by gabor1** [comment]
hi! 

very interesting attempt. Let's try to figure it out. (I think @albapa must have done things like this in the past). Apart from the values of the alphas, does your model do the right thing, and how does it compare in predictive power with the model that gap_fit builds? One issue about getting the same alphas is that the linear system that is being solved is extremely ill-conditioned, so tiny variations in how you actually compute the alphas will result in big changes to the actual values, without affecting the quality of the model (sort of this is the definition of being ill-conditioned!).

For example, we perform QR decomposition, and use linear least squares solver, not pinv. We also use various regularisers, some of them are like the ones in your code, but others are added at the end just before the solve (this is controlled by the sparse_jitter command line variable in gap_fit). 

maybe @albapa can help modify the gap_fit code to print out the actual linear system before it is solved, and that can go a long way towards comparing the fortran and the python algorithms.

**Comment by mcaroba** [comment]
I have trained lots of these types of models in Python combining numpy and Quippy, and the accuracy is very similar to gap_fit, regardless of the specific details (e.g., L2 vs Gaussian noise regularization). There is the question of how regularization is implemented specifically (per atom vs per config, the square root of the number of atoms or not) and if CUR is used to sparsify, it's a non deterministic algorithm unless one provides the seed explicitly, so even gap_fit would give different alphas between runs. I think the gap_fit command being used would be useful to know what could be a winning Python recipe to approximate the gap_fit alphas.

**Comment by albapa** [comment]
If you're using `zeta=2` in `gap_fit` then you should use it in the python code as well. Otherwise in this case the two should gave the same (or at least similar) answer.
