### ISSUE TITLE
" 'setjmpvalue' undeclared" error during quippy installation

### ISSUE THREAD

**Issue by DingChangjie** [libAtoms/QUIP#285]
Hi, everyone. I get into a weird trouble with installing quippy. I've successfully installed quip by "make", as is documented in [GAP tutorial](https://libatoms.github.io/GAP/installation.html). Then I typed "make install-quippy", however a bunch of similar errors occured:
`
./src.linux-x86_64-3.8/_quippymodule.c: In function ‘f2py_rout__quippy_f90wrap_potential_fm__get__create_hybrid_weights_params’:
./src.linux-x86_64-3.8/_quippymodule.c:95282:1: error: ‘setjmpvalue’ undeclared (first use in this function)
95282 | setjmpvalue = setjmp(environment_buffer);
      | ^~~~~~~~~~~
./src.linux-x86_64-3.8/_quippymodule.c: In function ‘f2py_rout__quippy_f90wrap_potential_fm__set__create_hybrid_weights_params’:
./src.linux-x86_64-3.8/_quippymodule.c:95393:1: error: ‘setjmpvalue’ undeclared (first use in this function)
95393 | setjmpvalue = setjmp(environment_buffer);
`
and these errors were caused by the following compilation process : 
`Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_DISABLE_OPTIMIZATION=1 -I./src.linux-x86_64-3.8/./src.linux-x86_64-3.8 -I/home/dingchangjie/.local/lib/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -c ./src.linux-x86_64-3.8/_quippymodule.c -o ./src.linux-x86_64-3.8/_quippymodule.o -MMD -MF ./src.linux-x86_64-3.8/_quippymodule.o.d" failed with exit status 1`

Consequently the compilation was aborted. Actually I suspect (but not sure) that such errors do matter in some aspects, because I tried "import quippy" after that and got a "No module named _quippy" error.
Does anyone have ideas on that ?

**Comment by jameskermode** [comment]
This is a known issue with the latest version of numpy. See https://github.com/jameskermode/f90wrap/pull/139 for a workaround - you could apply this patch directly, but note that for now you need to do this on top of the version of `f90wrap` distributed with QUIP, not the latest development release. I'll try to fix this properly soon, but won't have time until at least next week.

**Comment by DingChangjie** [comment]
@jameskermode Hi James. Thanks to your help, I 've successfully fixed that. 👍 
However, it seems that python2 along with a  corresponding numpy is also needed —— when I continued, the following error occurred :
`make[1]: Entering directory '/home/dingchangjie/SimTools/QUIP/quippy'
LD=gfortran CC=gcc F90=gfortran F77=gfortran QUIP_ROOT=/home/dingchangjie/SimTools/QUIP python2 setup.py build
/bin/sh: 1: python2: not found
make[1]: *** [Makefile:43: build] Error 127
make[1]: Leaving directory '/home/dingchangjie/SimTools/QUIP/quippy'
make: *** [Makefile:207: quippy] Error 2`
Since I only had python 3.8 along with numpy 1.20.1 installed (numpy via pip3), does it mean I should also install python2 and a numpy particularly for python2?
Thanks a lot.

**Comment by jameskermode** [comment]
No, python2 is not required. You can set the PYTHON variable in the Makefile.inc to the path to your python 3.8 executable.

**Comment by DingChangjie** [comment]
@jameskermode For the second error, please forgive me I made a silly beginners' mistake : having cloned a wrong branch particular for python2, haha
 Anyway thanks for your kindly help, and I encountered exactly the same problem as reported by [BernardoPacini](https://github.com/jameskermode/f90wrap/pull/139) when using the correct "public" branch, along with Ubuntu 20.04 (distributed on Windows Subsystem for Linux 2) with GCC 9.3.0 and Numpy 1.20.1. I agree with there might being some issues with new Numpy though.
