### ISSUE TITLE
quippy ImportError: undefined symbol: _gfortran_transpose_r8

### ISSUE THREAD

**Issue by leoil** [libAtoms/QUIP#288]
Hi, I have this error when installing QUIP.
The first `make` and `make install-quippy` compiled without error, but when I import `quippy` in python, this error shows up. And `make test` failed when making GAP.
I have already install f90wrap using `pip install QUIP/src/f90wrap`
```
f90wrap                   0.2.3                    pypi_0    pypi
```
Am I missing something or is there any solution?

 Error Info: 
```python
>>> import quippy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/xxx/project/QUIP/build/linux_x86_64_gfortran/quippy/__init__.py", line 2, in <module>
    import _quippy
ImportError: /public/xxx/project/QUIP/build/linux_x86_64_gfortran/_quippy.cpython-38-x86_64-linux-gnu.so: undefined symbol: _gfortran_transpose_r8
```
```
python version: 3.8.8
gcc version: 4.4.7
gofortran version: 4.4.7
```

**Comment by gabor1** [comment]
I think you need at least gcc 4.6

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
But also, it looks like the c compiler your python expects/uses is different from the one you used to compile quip

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by jameskermode** [comment]
Either that or a missing `-lgfortran` in `QUIPPY_LIBS`

**Comment by noambernstein** [comment]
That is a _very_ old version of gcc. Even CentOS 7 , which uses rather old
stable versions of everything, is at 4.7
