### ISSUE TITLE
GAP Potential Error

### ISSUE THREAD

**Issue by tarbaugh** [libAtoms/QUIP#290]
Hi, after building LAMMPS with QUIP, running the GAP examples produces the following error...

```bash
SYSTEM ABORT: Traceback (most recent call last)
File "/home/<user>/QUIP/src/Potentials/Potential.f95", line 450 kind unspecified
potential_Filename_Initialise: empty filename   
```

This error is produced on CENTOS7 on a HPC, and is reproduced from a fresh build on Google Cloud Platform (also CENTOS7). The Google Cloud Platform is compiled with gfortran and linked to LAMMPS mpi. (Quippy was not used).

I am currently combing through the source code to see if I can isolate the problem, but any help is appreciated!

**Comment by gabor1** [comment]
hm... puzzling. Can you post the first few lines of your GAP xml file and the lamps pairstyle command?

**Comment by gabor1** [comment]
can you also confirm that you are using the latest QUIP, GAP (now available from GitHub directly) and lammps ?

**Comment by tarbaugh** [comment]
Thanks for the response, yes I can confirm that this occurred lammps version 29 Oct 2020 and GAP pulled from the GitHub repository in the past few days.  
The GAP xml file/lammps input scripts can be found in the source for lammps (lammps/examples/USER/quip/). Each example produced the same error.

As an example in.gap reads ...
```
# Test of GAP potential for Si system

units		metal
boundary	p p p

atom_style	atomic

read_data	data_gap

pair_style	quip
pair_coeff	* * gap_example.xml "Potential xml_label=GAP_2015_2_20_0_10_54_35_765" 14
...
```

referencing data_gap ...
```
Position data for Silicon system

	64 	atoms
	1 	atom types
  0.00 	10.968476161 	xlo xhi
  0.00	10.968476161 	ylo yhi
  0.00 	10.968476161 	zlo zhi

Masses

1 28.0000

 Atoms

1	1       4.1342    7.7779    2.6819
2	1       3.8227    4.8354    8.5466
3	1       3.3367    5.6117    3.2337
...
```

and gap_xml
```
<GAP_2015_2_20_0_10_54_35_765>
<Potential label="GAP_2015_2_20_0_10_54_35_765" init_args="Sum init_args_pot1={IP Glue} init_args_pot2={IP GAP label=GAP_2015_2_20_0_10_54_35_765}"/>
<Glue_params n_types="2">
  <per_type_data atomic_num="14" type="1">
    <!-- Si -->
    <density num_points="14" density_y1="-0.4144" density_yn="0.0">
      <point a="0.821917808219178" rho="0.258391"/>
      <point a="1.027397260273973" rho="0.173248"/>
      <point a="1.232876712328767" rho="0.097399"/>
      ...
```

**Comment by tarbaugh** [comment]
Rebuilding again on Debian produces the same error... Will try older versions of lammps next.

**Comment by tarbaugh** [comment]
The issue has been resolved by using lammps-11Aug17.
