### ISSUE TITLE
Segmentation fault when modifying Atoms during dynamics

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/QUIP#3]
Reported by Max Veit:

This bug also results in a segmentation fault, but thankfully these are
the last of the segfaults I've come across so far.

Modifying an Atoms object within a dynamics hook (a function passed to
'DyamicalSystem.run()' that executes at a set interval) causes a
segmentation fault on the next dynamics step. It doesn't matter whether
the 'Atoms.remove_atoms()' or the 'DynamicalSystem.remove_atoms()'
function is used; each causes a segfault if it's called inside the hook.
The attached examples 'dynamics-hook-segv.py' and
'dynamics-althook-segv.py', respectively, demonstrate the error using
the above atom modification functions. Another interesting error arises
if the hook throws a particular exception after modifying the atoms. In
the attached example 'dynamics-hook-smash.py', Python exits with the
ominous message 'stack smashing detected' before triggering a segfault.

I'm aware that modifying Atoms objects inside a dynamics hook is
probably nonstandard usage; it would be more common to run dynamics,
stop, mutate the atoms, and run dynamics again. But even in this case
the user needs to take care: If the 'Atoms.remove_atoms()' function is
used instead of 'DynamicalSystem.remove_atoms()' (the latter apparently
updates the degrees of freedom correctly), again a segfault results, as
the attached example 'dynamics-between-segv.py' demonstrates.

To run the examples, place the file 'dodecane-bigcell.xyz' (same
structure as last time) in the same directory as the Python examples.
I'm also using a DFTB potential to run the dynamics so you'll need to
place a DFTB parameter file in the same directory as the Python examples
and name it 'dftb_params.xml'. The DFTB parameters can be found in the
ThirdParty directory; I used
"$QUIP_ROOT/ThirdParty/DFTB-parameters/self_consistency.DFTB.pbc-0-1.xml".
I haven't tested these examples with other potentials, though that could
also be useful.

**Comment by jameskermode** [comment]
`````` python
#!/usr/bin/env python
"""Code to cause a segfault by modifying Atoms in a dynamics hook."""

from quippy import Atoms, DynamicalSystem, Potential

at = Atoms("dodecane-bigcell.xyz")
ds = DynamicalSystem(at)
pot = Potential("TB DFTB", param_filename="dftb_params.xml")
out = []

def hook_segv():
    """Hook function that modifies the Atoms object during the dynamics"""
    if round(at.params['time'], 2) == 2.0:
        # Using DynamicalSystem.remove_atoms() instead of calling the
        # Atoms version directly doesn't help
        ds.remove_atoms(1)  # Causes SEGV
    out.append(at.copy())

ds.run(pot, dt=0.1, n_steps=40, hook=hook_segv)```
``````

**Comment by max-veit** [comment]
Here's the exception-smash code as well:

`dynamics-hook-smash.py`

``` python
#!/usr/bin/env python
"""Code to cause stack smashing by modifying Atoms in a dynamics hook."""

from quippy import Atoms, DynamicalSystem, Potential

at = Atoms("dodecane-bigcell.xyz")
ds = DynamicalSystem(at)
pot = Potential("TB DFTB", param_filename="dftb_params.xml")
out = []

def hook_smash():
    """Hook function that modifies the Atoms object during the dynamics"""
    if round(at.params['time'], 2) == 2.0:
        ds.remove_atoms(1)
        assert at.n == 42  # Raises AssertionError -- at.n should be 37
    out.append(at.copy())

ds.run(pot, dt=0.1, n_steps=40, hook=hook_smash)  # This time, ends in stack smashing
```

(FYI, Github supports markdown in comments, so if you surround code blocks with triple code blocks and specify the language - as in [this help page](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) - the code will be formatted and highlighted, making it much easier to read).

**Comment by jameskermode** [comment]
Thanks for the Markdown tip Max. I thought creating issues was a good way to get things out of my inbox and not loose track of them.

**Comment by max-veit** [comment]
Sure thing. On that note, might it be a good idea to move toward the Github tracker for bug reporting, rather than emails to the developer list? There are some features we might miss from email (e.g. attaching XYZ files could be a pain) and those of us with email notifications turned off might not see the reports as quickly. However, as you said, there is the advantage of keeping track of the issues in one place without cluttering everyone's inboxes.

**Comment by max-veit** [comment]
And closing, as this is something very few (rational) people will ever want to do.
