### ISSUE TITLE
could not initialise potential from xml_label

### ISSUE THREAD

**Issue by marian-code** [libAtoms/QUIP#306]
Hi,

I have been trying to run QUIP pair_style in lammps. My main aim is to use Tangney-Scandolo potential, but I have been getting various errors and have not been able to successfully run any simulation.

I am using potential file: https://github.com/libAtoms/QUIP/blob/e8cc4daaef5477a23b5b3229e9369b2beecd81c1/share/Parameters/ip.parms.TS.xml#L1 When I take the file as is I get this error from LAMMPS:

```bash
ERROR(FoX)
Cannot open second root element (Possibly near line=0 col=949)
```

When run through xmllint it produces this error:

```bash
$ xmllint ip.parms.TS.xml
ip.parms.TS.xml:15: parser error : Extra content at the end of the document
<TS_params label="screened_LDA" betapol="0.75" cutoff="20.0 20.0 18.0 0.0" cutof
^
```

After this I have tried to modify the file and left only the first section of it:

```xml
<TS_params label="ewald_GGA" betapol="0.75" cutoff="20.0 22.0 18.0 0.0" n_types="2" yuksmoothlength="0.0" pred_order="2" 
  maxipol="60" tolpol="1e-10" yukalpha="0.0" tewald="T" a_ew="1e-06" iesr="-1 -1 -1">

  <per_type_data atomic_num="8" pol="8.89378" z="-1.38257" type="1" />
  <per_type_data atomic_num="14" pol="0.0" z="2.76514" type="2" />

  <per_pair_data C_pol="0.0" atnum_j="8" atnum_i="8" D_ms="0.00024748" gamma_ms="12.07092" B_pol="0.0" R_ms="7.17005" /> 
  <per_pair_data C_pol="-1.50435" atnum_j="8" atnum_i="14" D_ms="0.0019033" gamma_ms="11.1523" B_pol="2.02989" R_ms="4.6371" />
  <per_pair_data C_pol="0.0" atnum_j="14" atnum_i="14" D_ms="-0.0020846" gamma_ms="10.45517" B_pol="0.0" R_ms="5.75038" />

</TS_params>
```

After this modification the `xml` is read OK but I get new error:

```bash
SYSTEM ABORT: proc=0 Potential_read_params_xml: could not initialise potential from xml_label. param_str=<TS_params label-
="ewald_GGA" betapol="0.75" cutoff="20.0 22.0 18.0 0.0" n_types="2" yuksmoothlength="0.0" pred_order-
="2"   maxipol="60" tolpol="1e-10" yukalpha="0.0" tewald="T" a_ew="1e-06" iesr="-1 -1 -1">   <per_ty-
pe_data atomic_num="8" pol="8.89378" z="-1.38257" type="1" />   <per_type_data atomic_num="14" pol="-
0.0" z="2.76514" type="2" />   <per_pair_data C_pol="0.0" atnum_j="8" atnum_i="8" D_ms="0.00024748"
gamma_ms="12.07092" B_pol="0.0" R_ms="7.17005" />   <per_pair_data C_pol="-1.50435" atnum_j="8" atnu-
m_i="14" D_ms="0.0019033" gamma_ms="11.1523" B_pol="2.02989" R_ms="4.6371" />   <per_pair_data C_pol-
="0.0" atnum_j="14" atnum_i="14" D_ms="-0.0020846" gamma_ms="10.45517" B_pol="0.0" R_ms="5.75038" />
</TS_params>
--------------------------------------------------------------------------
```

The relevant part of LAMMPS input script:

```lammps
pair_style	quip
pair_coeff * * ip.parms.TS.xml "TS_params xml_label=ewald_GGA" 8 14
```

I have no idea how to fix this and would appreciate any help.

**Comment by gabor1** [comment]
you don’t need the xml_label in the pairstyle spec. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by jameskermode** [comment]
Alternatively, you could try wrapping the `<TS_params>` in a `<Potential label=ewald_GGA> ... </Potential>` tag

**Comment by gabor1** [comment]
can you please verify that the potential works correctly when called from the fortran-only binary called "quip" ? ("quip —help" gives usage)
 
-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by marian-code** [comment]
@gabor1 I have tried before removing the xml_label but I just get another error:

```bash
SYSTEM ABORT: proc=0 Potential_Simple_Initialise_str found too few or too many Potential_Simple types args_str=' TS_param-
s'
```
The input:
```lammps
pair_style	quip
pair_coeff * * ip.parms.TS.xml "TS_params" 8 14
```

@jameskermode 
I have tried adding what you are suggesting but, I get this error:

```bash
SYSTEM ABORT: proc=0 Potential_startElement_handler: no init_args attribute found
```

@gabor1
I will try to verify that if it works with QUIP alone

**Comment by jameskermode** [comment]
Ah, ok, try adding `init_args="IP TS label=ewald_GGA"` to the outer `<Potential>`.

**Comment by marian-code** [comment]
Thanks for the suggestion, I really appretiate the quick replies, but unfortunately I got yet another error:

```bash
SYSTEM ABORT: proc=0 IPModel_TS_read_params_xml cannot find cutoff_coulomb
```

Just to be sure we understand each other, the xml now looks like this:

```xml
<Potential label="ewald_GGA" init_args="IP TS label=ewald_GGA">
<TS_params label="ewald_GGA" betapol="0.75" cutoff="20.0 22.0 18.0 0.0" n_types="2" yuksmoothlength="0.0" pred_order="2" 
  maxipol="60" tolpol="1e-10" yukalpha="0.0" tewald="T" a_ew="1e-06" iesr="-1 -1 -1">

  <per_type_data atomic_num="8" pol="8.89378" z="-1.38257" type="1" />
  <per_type_data atomic_num="14" pol="0.0" z="2.76514" type="2" />

  <per_pair_data C_pol="0.0" atnum_j="8" atnum_i="8" D_ms="0.00024748" gamma_ms="12.07092" B_pol="0.0" R_ms="7.17005" /> 
  <per_pair_data C_pol="-1.50435" atnum_j="8" atnum_i="14" D_ms="0.0019033" gamma_ms="11.1523" B_pol="2.02989" R_ms="4.6371" />
  <per_pair_data C_pol="0.0" atnum_j="14" atnum_i="14" D_ms="-0.0020846" gamma_ms="10.45517" B_pol="0.0" R_ms="5.75038" />

</TS_params>

</Potential>
```

and the lammps input: 

```lammps
pair_style	quip
pair_coeff * * ip.parms.TS.xml "TS_params xml_label=ewald_GGA" 8 14
```

**Comment by jameskermode** [comment]
It's a long time since I wrote the TS potential in QUIP, but it's slowly coming back to be that fully long-range Coulomb is only possible with an external interface to Paul Tangney's ASAP code. I suggest trying the refitted short-range model (the third set of parameters in the .XML linked above), which has a cutoff interaction and can be run with QUIP only. In the 2010 J Chem Phys paper we showed the cutoff had a neglible effect on accuracy and obviously leads to greatly improved performance.

**Comment by jameskermode** [comment]
Sorry that should be the 2nd set, not the third set. Here's an untested attempt:

```
<Potential label="screened_LDA" init_args="IP TS label=screened_LDA">

<TS_params label="screened_LDA" betapol="0.75" cutoff="20.0 20.0 18.0 0.0" cutoff_coulomb="20.0" cutoff_ms="18.0" tolpol="1e-10" yuksmoothlength="10.0" iesr="-1 -1 -1" a_ew="1e-06" n_types="2" gcut="0.0" pred_order="2" maxipol="60" raggio="0.0" tewald="F" yukalpha="0.1">

  <per_type_data atomic_num="8" pol="14.131863" z="-1.4295594" type="1" />
  <per_type_data atomic_num="14" pol="0.0" z="2.8591188" type="2" />

  <per_pair_data C_pol="0.44302622" atnum_j="8" atnum_i="8" D_ms="0.00030700577" gamma_ms="12.165654" B_pol="1.1221903" R_ms="7.0252019" />
  <per_pair_data C_pol="-1.5003213" atnum_j="8" atnum_i="14" D_ms="0.0020129372" gamma_ms="11.350477" B_pol="1.973181" R_ms="4.5780828" />
  <per_pair_data C_pol="0.0" atnum_j="14" atnum_i="14" D_ms="0.33967532" gamma_ms="-0.17694797" B_pol="0.0" R_ms="-0.085202834" />

</TS_params>

</Potential>
```

**Comment by marian-code** [comment]
I see. I will have a look at the mentioned paper. I assume you meant this one: https://aip.scitation.org/doi/10.1063/1.3475565. Indeed when I change to `screened_LDA` part of the xml the simulation seems to be running OK.

**Comment by jameskermode** [comment]
Yes, that's the paper I meant. Glad it's working now. I'll close this issue for now, reopen if you have further problems.

**Comment by marian-code** [comment]
After some compilation problems, I got around to try this properly. (LAMMPS with QUIP is crashing when compiled with ifort, however using gfortran seems to fix the problem)

Now I am getting another error, for the screened potential:

```bash
SYSTEM ABORT: Traceback (most recent call last)
File "/home/rynik/Software/lammps_quip/QUIP/src/Potentials/IPModel_TS.f95", line 507 kind unspecifie-
d
IPModel_TS_Calc: local_virial calculation requested but not supported yet.
```

**Comment by jameskermode** [comment]
As the error says, there are no local virials (per atom stresses) implemented for this potential

**Comment by marian-code** [comment]
I understand what that means, but I have not requested such quantity to be computed in LAMMPS input, at least not directly. I have no idea which other command would internally need such information. Atom forces are certainly needed in MD but nothing comes to mind for stresses. Perhaps I am misunderstanding this in some way.

My input script starts just a simple NPT MD at 600K and 10GPa:

```lammps

units 			metal
boundary 		p p p
atom_style		atomic
box			tilt large

read_data	data.instruc

variable set_pressure equal 10.0  # in GPa, 10000 is conversion to bar
variable pressure_bar equal ${set_pressure}*10000

variable temperature_k equal 600.0  # temperature in K

pair_coeff * * ip.parms.TS.xml "TS_params xml_label=screened_LDA" 14 8

thermo          100
thermo_style	custom step time temp press vol pe ke enthalpy lx ly lz pxx pyy pzz pxy pxz pyz cella cellb cellc cellalpha cellbeta cellgamma

dump 			trajectory all custom 25 trajectory.lammps id type x y z
dump_modify     	trajectory sort id

timestep 		0.002

velocity                all create ${temperature_k} 4928459 dist gaussian
fix 			2 all npt temp ${temperature_k} ${temperature_k} 0.2 tri ${pressure_bar} ${pressure_bar} 10.0 mtk yes nreset 0 tchain 3 pchain 3 tloop 1 ploop 1
run			2000000000
```

**Comment by noambernstein** [comment]
It is inherent to the way lammps does domain decomposition and periodic
boundaries that to get stress it sums local stress (I.e. virial)
contributions. I think you can only do NVE (or T), not P with this
potential.

**Comment by marian-code** [comment]
That, makes sense. Thank you. I will test it with NVE.

**Comment by marian-code** [comment]
Well unfortunately even after changing to NVE it is throwing the same error.

**Comment by jameskermode** [comment]
Is it perhaps computing the stress just for output? Maybe there's a way to turn this off?
