### ISSUE TITLE
core potentials in quippy

### ISSUE THREAD

**Issue by richardjana** [libAtoms/QUIP#307]
I am comparing energies I computed with a given potential file for a given set of structures with QUIP, quippy and TurboGAP. There I noticed that the total energies are consistent between QUIP and TurboGAP, but quippy gives a different energy. The difference seems to come from the core potential, as this is always 0 with quippy. Also the following is true:
`E_total_TurboGAP - E_corepotential_TurboGAP == E_total_quippy`
The attached plot shows these energies for structures with different densities.
![components](https://user-images.githubusercontent.com/13464206/121532333-ea55b780-ca07-11eb-8c59-8cd03393db24.png)

(Of course, this issue only comes up, when the structures are sufficiently dense that the core potential cutoff is reached.)

**Comment by jameskermode** [comment]
How are you invoking from quippy? I’d guess you have specified “IP GAP” which will leave out the core. You need to use “Potential xml_label=…”.

**Comment by richardjana** [comment]
You are absolutely correct, both on how I loaded the potential and the way to fix it. Thank you very much!

**Comment by jameskermode** [comment]
I guess this can be closed, then?
