### ISSUE TITLE
quip fails if distance between atoms is larger than the cutoff set in the learning of the potential

### ISSUE THREAD

**Issue by avaucher** [libAtoms/QUIP#31]
First, I learned a 2-body potential (GAP) with "teach_sparse" for the H2 molecule with potential form "distance_Nb" with "order=2".
Then I wanted to use this potential to calculate the energy for other distances, but quip crashes when the distance is larger than the cutoff set for the learning.

**Comment by albapa** [comment]
should be fixed now. @avaucher can you test it on your GAP and see if it works?

**Comment by avaucher** [comment]
@albapa Yes it works, thanks!
