### ISSUE TITLE
_quippy not in path anymore

### ISSUE THREAD

**Issue by sandipde** [libAtoms/QUIP#311]
quippy shows import error due to following line.
https://github.com/libAtoms/QUIP/blob/9bd68bcaf36f11db521afcfec03a66044065419d/quippy/quippy/convert.py#L29

when it used to be 

```
import _quippy as quippy

```
it worked because  `_quippy.cpython-36m-x86_64-linux-gnu.so` was in build dir which is in PYTHONPATH. now I had to move it to quippy directory to make it work.

**Comment by jameskermode** [comment]
Please try `make install-quippy`. Running from the build directory no longer works. These changes were made to get `pip install quippy-ase` to work from PyPI so you might like to try that if you don’t need to make local changes to the code.
