### ISSUE TITLE
How to select individual components of a composite GAP

### ISSUE THREAD

**Issue by lvjian8596** [libAtoms/QUIP#314]
I have trained a GAP containing 2b and SOAP parts. I wonder how to select individual components in quippy calculator? Thank you very much!

**Comment by gabor1** [comment]
you can do it from the ASE calculator, using the only_descriptor=<index> option. the index refers to the order of the descriptors in the xml file 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lvjian8596** [comment]
Is it like this?
cal = quippy.potential.Potential(param_filename="GAP.xml", only_descriptor=0)
at.set_calculator(cal)

**Comment by gabor1** [comment]
no, you need the “calc_args” key. it’s actually easier directly from the “quip” command line program, where calc_args is an explicit keyword, so you can add : calc_args=“only_descriptor=0"

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lvjian8596** [comment]
Thanks very much for your help. It woks now!
