### ISSUE TITLE
f90wrap version compatible with quippy

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#315]
I'm having trouble making quippy. After the `make quippy` workflow installs `f90wrap` using `pip`, I need to add the `~/.local/bin` directory to the path and all the quippy objects appear to be built. But when I try to import a quippy module, I get a `ModuleNotFoundError: No module named 'quippy._quippy'` error. In the `README.md` file the instructions tell to get the `f90wrap` version which is retrieved as a QUIP submodule; however, there does not seem to be any `f90wrap` submodule liked under `src/` at the moment. I wonder 1) if the issue is due again to an `f90wrap` version mismatch, as I have experienced in the past and 2) if so, which version to use in order to make quippy work. If the problem lies elsewhere, pointers would be appreciated.

**Comment by gabor1** [comment]
did you do a recursive clone of QUIP ? that brings the submodules 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by mcaroba** [comment]
Yes, I did. GAP is there, but f90wrap is not.

**Comment by mcaroba** [comment]
Under `src/` the only submodules that appear to me are GAP and fox.

**Comment by mcaroba** [comment]
And I can see James removed it a month ago: https://github.com/libAtoms/QUIP/commit/a98a86babe5b47a9ee69bf1b65500e7fd58bfe2c#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

It looks like the README file should be updated, but this still does not explain why the installation fails for me. It also looks like the required version is ~2.6.0~ 0.2.6, which as far as I can tell is the one pip is installing.

**Comment by mcaroba** [comment]
OK, I think I solved the issue. I was adding the `build` directory to my `PYTHONPATH`, but the `build/quippy/` directory was missing the quippy library, which is directly under `build/`. So I made a symlink to `build/_quippy.cpython-38-x86_64-linux-gnu.so` in `build/quippy/` and that seems to fix the problem.

**Comment by jameskermode** [comment]
Maybe you didn’t `make install-quippy`. Running from the build directory is no longer expected to work. This change was necessary to get `pip install quippy-ase` to work in a portable way.

**Comment by jameskermode** [comment]
Correct, f90wrap is now installed as a build dependency by pip so doesn’t need to be a submodule anymore. I’ll fix the README. What is the exact error you are getting?

**Comment by mcaroba** [comment]
It's as you said, I didn't do `make install-quippy` because I use a module system on this machine and want to keep `~/.local/` clean. I used to just add the `build/` directory to my path and that worked but not anymore. But with the simple hack I mentioned above (symlink) it's working again by just adding `build/` to my Python path.

**Comment by mcaroba** [comment]
The error was `ModuleNotFoundError: No module named 'quippy._quippy'`.

**Comment by jameskermode** [comment]
Thanks. There’s no good reason not to allow this, so I’ll add an equivalent fix to the quippy Makefile (probably building the .so directly within the quippy/ directory to remove the need for a symlink)

An alternative to polluting your .local would be to install in a virtualenv.
