### ISSUE TITLE
What does this parameter ( config_type_n_sparse) mean

### ISSUE THREAD

**Issue by yinhuipeng** [libAtoms/QUIP#317]
Hi,I have encountered a very uncomfortable problem.  I do not know how to find the meaning of a parameter.I do not understand you explained to people how to get the parameter before.how to use  this command ( heip ) to get config_type_n_sparse?

Thank you and I look forward to your reply

**Comment by gabor1** [comment]
This parameter (actually a set of parameters) allow you to set the number fo basis functions assigned to each config_type, if you have labelled some or all of your configurations by config_type. One good use of this is to ensure that certain config_types of which there are very few, but very important to you, guaranteed to receive some basis functions. normally if you select sparse_method=cur_points, then that takes care of it all, so it’s rare that you need this option. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by yinhuipeng** [comment]
Thank you very much for your reply. I used the above parameters to repeat a literature and applied the parameter settings in the literature to my own data training. 

Now its parameters are as follows, he calculated the system which is HfO2 .
config_type_n_sparse={crystal:25:amorph:15}
but it reported the following error during the training:
On entry to DPOTRF parameter number  4 had an illegal value

I don't understand this parameter, so I don't know what to do with it, but if I simply use n_xparse = 40, it will work.But I'm not sure if this affects the accuracy of the calculation very much.

Thanks again for your reply 

Best wishes

**Comment by gabor1** [comment]
I wouldn't bother with it unless you feel some special configs don't receive enough attention. BTW these are very small nsparse numbers, good potentials have hundreds or thousands 

-- Gábor
