### ISSUE TITLE
Quip prediction on the total energy with GAP

### ISSUE THREAD

**Issue by ML-EF** [libAtoms/QUIP#324]
Hi, I installed QUIP with GAP potential, gap_version="1626770938". I select GAP in the make config. I predict the total energy with QUIP using the phosphorus potential give in https://zenodo.org/record/4003703#.YP6DNLUzbIU for some structures in the P_GAP_20_train_data.xyz.  

The command: srun quip init_args="IP GAP" atoms_filename=P_GAP_20_fitting_data.xyz param_filename=P_GAP_20.xml E
But there has a deviation of around 1eV between DFT energy and predicted energy.  Is the command for prediction correct? I attached the output file below. 

[wf22N-43294.txt](https://github.com/libAtoms/QUIP/files/6878383/wf22N-43294.txt)

**Comment by ML-EF** [comment]
The deviation is around 0.14eV/atom.  Is this normal for QUIP?  

![00](https://user-images.githubusercontent.com/25586920/126996639-c49f2262-0099-4ddc-9b92-ed83a01a7118.jpg)

**Comment by mcaroba** [comment]
This is not normal, the scatter plot should look like the one I posted in your previous issue. There is a problem here, and we need to find where it is. Can you somehow link the entire output you get from running QUIP (e.g., tar it and put it on Google Drive, then put a link here, since it will be quite a few MB)?

**Comment by ML-EF** [comment]
Hi, here is the google drive link. https://drive.google.com/file/d/1qjUYrShD51KNApJnjByPm7s4W592INea/view?usp=sharing
I just test several structures with 8 Phosphrous atoms. You can try to do the prediction with your quip program.  Just to check whether it is because of the quip compiled in my computer.   Thanks.

**Comment by mcaroba** [comment]
You need to remove the `init_args="IP GAP"` part from your command. With this keyword, the pair potential is missing from the calculation and you get wrong results. Let me know if this fixes your issues. (I'm closing but feel free to reopen I your problems persist)

**Comment by Rabbiiiiit** [comment]
> You need to remove the `init_args="IP GAP"` part from your command. With this keyword, the pair potential is missing from the calculation and you get wrong results. Let me know if this fixes your issues. (I'm closing but feel free to reopen I your problems persist)

Hi, @mcaroba , thanks for your contributions. My question is: `init_args` should be set to something or should I just totally remove  `init_args="IP GAP"`? I tried the same commands with @YuqiangGao and obtained the same result and plots as him (her), but if I remove the argument `init_args="IP GAP"`, the output was only this much:

`libAtoms::Hello World: 2023-09-12 22:57:36
libAtoms::Hello World: git version  https://www.github.com/libAtoms/QUIP,v0.9.14-4-g7e5cf9439-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Sep 12 2023 at 00:20:56
libAtoms::Hello World: Random Seed = 82656435
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

Using calc args:
Using pre-relax calc args:
Using param_filename: P_GAP_20.xml
Using init args:`

The run only takes a few seconds to stop. My gapversion is 1686220958, where did I do wrongly? Thanks for your help!

**Comment by Rabbiiiiit** [comment]
> > You need to remove the `init_args="IP GAP"` part from your command. With this keyword, the pair potential is missing from the calculation and you get wrong results. Let me know if this fixes your issues. (I'm closing but feel free to reopen I your problems persist)
> 
> Hi, @mcaroba , thanks for your contributions. My question is: `init_args` should be set to something or should I just totally remove `init_args="IP GAP"`? I tried the same commands with @YuqiangGao and obtained the same result and plots as him (her), but if I remove the argument `init_args="IP GAP"`, the output was only this much:
> 
> `libAtoms::Hello World: 2023-09-12 22:57:36 libAtoms::Hello World: git version https://www.github.com/libAtoms/QUIP,v0.9.14-4-g7e5cf9439-dirty libAtoms::Hello World: QUIP_ARCH linux_x86_64_gfortran libAtoms::Hello World: compiled on Sep 12 2023 at 00:20:56 libAtoms::Hello World: Random Seed = 82656435 libAtoms::Hello World: global verbosity = 0
> 
> Calls to system_timer will do nothing by default
> 
> Using calc args: Using pre-relax calc args: Using param_filename: P_GAP_20.xml Using init args:`
> 
> The run only takes a few seconds to stop. My gapversion is 1686220958, where did I do wrongly? Thanks for your help!


I got the reason. I didn't set `ulimit -s unlimited`, leading to core dump which was checked in /var/log/messages

The errors became much better after removing `init_args="IP GAP"`.

**Comment by Rabbiiiiit** [comment]
> > You need to remove the `init_args="IP GAP"` part from your command. With this keyword, the pair potential is missing from the calculation and you get wrong results. Let me know if this fixes your issues. (I'm closing but feel free to reopen I your problems persist)
> 
> Hi, @mcaroba , thanks for your contributions. My question is: `init_args` should be set to something or should I just totally remove `init_args="IP GAP"`? I tried the same commands with @YuqiangGao and obtained the same result and plots as him (her), but if I remove the argument `init_args="IP GAP"`, the output was only this much:
> 
> `libAtoms::Hello World: 2023-09-12 22:57:36 libAtoms::Hello World: git version https://www.github.com/libAtoms/QUIP,v0.9.14-4-g7e5cf9439-dirty libAtoms::Hello World: QUIP_ARCH linux_x86_64_gfortran libAtoms::Hello World: compiled on Sep 12 2023 at 00:20:56 libAtoms::Hello World: Random Seed = 82656435 libAtoms::Hello World: global verbosity = 0
> 
> Calls to system_timer will do nothing by default
> 
> Using calc args: Using pre-relax calc args: Using param_filename: P_GAP_20.xml Using init args:`
> 
> The run only takes a few seconds to stop. My gapversion is 1686220958, where did I do wrongly? Thanks for your help!


I got the reason. I didn't set `ulimit -s unlimited`, leading to core dump which was checked in /var/log/messages

The errors became much better after removing `init_args="IP GAP"`.
