### ISSUE TITLE
pypi, docker, and releases

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#330]
Do we want to tag releases that correspond to each pypi version?  Also, does the docker image need to be updated to include the 6-element stress, similarly to the pypi version?

**Comment by jameskermode** [comment]
Releases are tagged in https://github.com/libAtoms/quippy-wheels, just not here in QUIP. I agree it would be good to tag them here too, just not quite sure what the best workflow to do that consistently would be. 

Ideally perhaps there wouldn't be a separate repo at all, but that's how multibuild currently works. I had a brief go at switching to [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/), which is a newer and better solution that doesn't need a separate repo, but it doesn't much like Fortran compilers. The CI recipe is here if anyone wants to have another go (currently disabled)

https://github.com/libAtoms/QUIP/blob/public/.github/workflows/build-wheels.yml

Not sure about Docker status.

**Comment by bernstei** [comment]
Can we do it with this? https://github.community/t/run-action-on-event-in-another-repository/17667

**Comment by jameskermode** [comment]
Closing since we are not using cibuildwheel here and tagging releases.
