### ISSUE TITLE
Problem building LAMMPs with the QUIP package

### ISSUE THREAD

**Issue by Dankomaister** [libAtoms/QUIP#334]
Hi!

I’m trying to compile LAMMPs with the QUIP package using the Intel compilers.
However, the compilation fails when trying to link the CXX executable lmp with the error:
`ld: liblammps.so.0: undefined reference to 'lb2_'`

I’m using a libquip.a also build with the intel compilers using thelinux_x86_64_ifort_icc makefile.
Something worth noting is that compiling LAMMPs without QUIP using the Intel compilers works and compiling LAMMPs with QUIP but using the gcc compilers also works.
I have tracked down the error to the fact that LAMMPs is compiled with shared libs, this seems to cause a problem when including the QUIP package.
But since everting works fine using the gcc compilers is suspect that the error comes from the compilation of libquip.a
Are the any compiler flags that I need to modify in the Makefile.linux_x86_64_ifort_icc file in order to create a libquip.a that can be used to build LAMMPS with QUIP and shared libs using the Intel compilers?

I attaced the logfile with the error
[easybuild-LAMMPS-29Oct2020-20210823.153124.ChdBQ.log](https://github.com/libAtoms/QUIP/files/7036428/easybuild-LAMMPS-29Oct2020-20210823.153124.ChdBQ.log)

/Daniel

**Comment by Dankomaister** [comment]
any progress on this ?

**Comment by gabor1** [comment]
this kind of thing is hard to diagnose remotely. Libquip.a is a static library, so when everything else is shared, the intel linker might get confused… I don’t have much recent experience with intel compilers. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by jameskermode** [comment]
I’d suggest trying to find where `lb2_` is defined with the `nm` tool. It’s probably in one of the intel support libraries, which would need to be added to the link line.

**Comment by Dankomaister** [comment]
Hi!
Thanks for the suggestion, I will see if I can find which library this is.
/Daniel

**Comment by wcwitt** [comment]
I'm seeing this too. I can compile QUIP with Intel, and the tests pass, but I can't manage to link it to LAMMPS.

I found that `lb2_` originates in the Nocedal LBFGS routine (`lbfgs.f` and `minimization.f95`). So maybe it is some `F77` thing that isn't communicated properly?

With GNU compilers
```
[linux_x86_64_gfortran]$ nm -A libquip.a | grep lb2
libquip.a:lbfgs.o:0000000000000000 B quiplb2_
```
but with Intel compilers
```
[linux_x86_64_ifort_icc]$ nm -A libquip.a | grep lb2
libquip.a:lbfgs.o:0000000000003dc0 T quiplb2_
libquip.a:minimization.o:                 U lb2_
```
and it's that last bit that's giving problems.

I've gone back to `gfortran` for now.

**Comment by RemiLacroix-IDRIS** [comment]
Isn't it weird that there is:
https://github.com/libAtoms/QUIP/blob/a11e5728a4e91d2b9e8686c022a02c2b042ec1f3/src/libAtoms/minimization.f95#L105
while:
https://github.com/libAtoms/QUIP/blob/a11e5728a4e91d2b9e8686c022a02c2b042ec1f3/src/libAtoms/lbfgs.f#L197-L199
and
https://github.com/libAtoms/QUIP/blob/a11e5728a4e91d2b9e8686c022a02c2b042ec1f3/src/libAtoms/lbfgs.f#L532

I have proposed a PR.

**Comment by Sideboard** [comment]
Intermediate feedback: I have trouble replicating the original error. Instead I get
```
liblammps.so.0: undefined reference to `quip_lammps_api_version'
liblammps.so.0: undefined reference to `quip_lammps_wrapper'
liblammps.so.0: undefined reference to `quip_lammps_potential_initialise'
```
for the `stable_23Jun2022_update2` version with `ifort (IFORT) 2021.8.0 20221119` and the current public of QUIP/GAP (`5ce3d4147`, `926af0c`) using the following configuration
```
cmake ../cmake -D BUILD_SHARED_LIBS=yes -D PKG_ML-QUIP=yes -D QUIP_LIBRARY=$QUIP_ROOT/build/$QUIP_ARCH/libatoms.a -D CMAKE_C_COMPILER=icc -D CMAKE_CXX_COMPILER=icpc -D CMAKE_Fortran_COMPILER=ifort
```

@RemiLacroix-IDRIS Which versions and configuration have you used to test this?

**Comment by RemiLacroix-IDRIS** [comment]
@Sideboard : I used the same version of LAMMPS but I let it download and compile QUIP for me.

**Comment by Sideboard** [comment]
> @Sideboard : I used the same version of LAMMPS but I let it download and compile QUIP for me.

And which modules do you load / packages do you activate / options do you use? As of now, the auto build of QUIP fails for me:
```
cmake ../cmake -D BUILD_SHARED_LIBS=yes -D PKG_ML-QUIP=yes -D CMAKE_C_COMPILER=icc -D CMAKE_CXX_COMPILER=icpc -D CMAKE_Fortran_COMPILER=ifort
⋮
cmake --build .
⋮
ar: error.o: No such file or directory
make[4]: *** [Makefile:131: libatoms.a] Error 1
make[3]: *** [Makefile:155: libAtoms] Error 2
gmake[2]: *** [CMakeFiles/quip_build.dir/build.make:86: quip_build-prefix/src/quip_build-stamp/quip_build-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:762: CMakeFiles/quip_build.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by RemiLacroix-IDRIS** [comment]
Right I forgot about that, there is a bug on LAMMPS side, just run `export F95_PRE_FILENAME_FLAG=-Tf` before starting the compilation.

I will report it on LAMMPS repo.

**Comment by Sideboard** [comment]
Could reproduce the error and the change solves it.

**Comment by MES-physics** [comment]
I'm trying to install Lammps with QUIP and get these same errors you got above, for latest stable Lammps and latest QUIP/GAP, on my Ubuntu 18.04 laptop, with linux_x86_64_gfortran.  I installed QUIP first as told in instructions I saw.    I enabled MANYBODY and ML_QUIP before building, and linked by editing the ```QUIP_ROOT``` and ```QUIP_ARCH =``` in the Makefile.lammps.  
Can you help?
```
liblammps.so.0: undefined reference to `quip_lammps_potential_initialise'
liblammps.so.0: undefined reference to `quip_lammps_wrapper'
liblammps.so.0: undefined reference to `quip_lammps_api_version'
collect2: error: ld returned 1 exit status
CMakeFiles/lmp.dir/build.make:107: recipe for target 'lmp' failed
make[2]: *** [lmp] Error 1
CMakeFiles/Makefile2:668: recipe for target 'CMakeFiles/lmp.dir/all' failed
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by yhorbatenko** [comment]
I have similar problem ... even worse :(
I installed quip  with
                               pip install quippy-ase
Now trying to configure lammps  with 
                              cmake -C ../cmake/presets/basic.cmake     -D PKG_EXTRA-PAIR=yes  -D PKG_ML-QUIP=yes  -D QUIP_LIBRARY=${HOME}/anaconda3/lib/python3.9/site-packages/quippy/libquip.a   ../cmake

and install with cmake --build .

Even have done export F95_PRE_FILENAME_FLAG=-Tf, as suggested by @RemiLacroix-IDRIS, still there are lots of errors like 'undefined reference ...'

versions of packages used/tried during
installation:
gcc 4.9.2
gfortran 4.9.2
lammps 23Jun2022
cmake 3.12.3


Below is the attachment of all the errors that appeared.  
[bld.log](https://github.com/libAtoms/QUIP/files/10822858/bld.log)

Any help please?
In particular, wondering, why does libquip.a produce lots of undefined reference

**Comment by jameskermode** [comment]
`libquip.a` is a static library. It needs to be linked with libgfortran and libgomp when building the lammps executable. Adding `-lgfortran -lgomp` to the LAMMPS link flags should do that. Not sure how this is done with cmake, however.

I also note your gfortran and gcc versions are exceedingly old (from 2016!) which might be part of the problem.

**Comment by yhorbatenko** [comment]
@jameskermode Thank you for the explanation. Let me find out how to do that.

**Comment by yhorbatenko** [comment]
Essentially, i manage to install.
The most important thing is one has to compile libquip.a by himself, do not use libquip.a made with pip install quippy-ase. 
Then, i  compiled lammps-quip by using the following:
cmake -C ../cmake/presets/basic.cmake -D PKG_EXTRA-PAIR=yes -D PKG_ML-QUIP=yes -D QUIP_LIBRARY=${HOME}/bin/libquip.a ../cmake
 
versions of packages used for the latter compilation:
gcc 8.4.1
gfortran 8.4.1
lammps 23Jun2022
cmake 3.18.2

**Comment by jameskermode** [comment]
What is wrong/different about the libquip.a we distribute? By the way this is from PyPI (pip), not conda.

**Comment by yhorbatenko** [comment]
By "one has to compile libquip.a by himself" i mean i compiled the library by following the compilation instructions at https://github.com/libAtoms/QUIP. 

Every time i used the library from pip i got the errors i mentioned in my first post.

Frankly, i do not know why there is a difference between these two methods of obtaining libquip.a
Just letting know what worked for me.
