### ISSUE TITLE
Please update to current intel compilers/mkl

### ISSUE THREAD

**Issue by iridos** [libAtoms/QUIP#335]
Hi, 
documentation says that the compile was tested using Ubuntu 12.04 from 2012 and ifort from 2009 - is that correct?

I tried to compile it for lammps on Centos 7 with intel compiler 19 and mkl 2020 and seem to indeed see  a lot of problems that stem from a lack of adaption to recentish compilers. 

Regards,
Karsten

**Comment by gabor1** [comment]
well, the documentation is old :-) We use continuous integration now, and compile every push using very recent gcc. we no longer test with intel compilers.
