### ISSUE TITLE
quip_wrapper_simple_example_C.c does not compile with Intel compilers

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#34]
Seems like it is trying to make something in the Fortran `main()` too. 

```
quip_wrapper_simple_example_C.o: In function `main':
/scratch/quip/QUIP/src/Programs/quip_wrapper_simple_example_C.c:6: multiple definition of `main'
/opt/intel/Compiler/11.1/069/lib/intel64/for_main.o:/export/users/nbtester/efi2linux_nightly/branch-11_1/20100204_010000/libdev/frtl/src/libfor/for_main.c:(.text+0x0): first defined here
/opt/intel/Compiler/11.1/069/lib/intel64/for_main.o: In function `main':
/export/users/nbtester/efi2linux_nightly/branch-11_1/20100204_010000/libdev/frtl/src/libfor/for_main.c:(.text+0x38): undefined reference to `MAIN__'
make[1]: *** [quip_wrapper_simple_example_C] Error 1
make[1]: Leaving directory `/scratch/quip/QUIP/build/linux_x86_64_ifort_icc_mpi'
make: *** [Programs] Error 2
```

**Comment by gabor1** [comment]
I guess it's a linking issue. On the Mac, I had to link with fortran otherwise the cross language call didn't work. Is it possible that the Intel fortran linker will put in a main function even if the object already has one? Stupid machine. 

-- Gábor

**Comment by albapa** [comment]
If the main program is in C I think it should be possible to link with gcc/icc and link with the appropriate fortran library: -lgfortran for GNU and -lifcore -lifport for intel.

**Comment by jameskermode** [comment]
I think adding the -nofor_main argument to ifort link line should fix this.

**Comment by tdaff** [comment]
Yep, `-nofor-main` does the trick, thanks. I'll push it in a minute.

**Comment by gabor1** [comment]
Could ppl pls sign their comments? Github emails contain no from field...

-- Gábor

**Comment by jameskermode** [comment]
That’s interesting, identification works for me in Mail.app: I see gabor1<notifications@github.com <mailto:notifications@github.com>>

James.
