### ISSUE TITLE
system_abort should lead to a non-zero return value

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#340]
It appears that `system_abort` does not (necessarily?) lead to a non-zero return value.  For example 
```
tin 1256 : gap_fit bob
libAtoms::Hello World: 09/09/2021   15:43:28
libAtoms::Hello World: git version  /home/cluster2/bernstei/src/work/git_canonical_copies/QUIP,86b2edc-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Sep  1 2021 at 10:39:16
libAtoms::Hello World: Random Seed = 56608354
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

param_read_line: unknown key bob
gap_fit
SYSTEM ABORT: Exit: Mandatory argument(s) missing...   
tin 1257 : echo $?
0
```

This is especially annoying if python is running it, since it cannot detect a failure.

**Comment by gabor1** [comment]
I think we had a debate about this a very long time ago, and at that point we wanted to distinguish between graceful failure and other stuff (like segfaults). I’m happy to change this and return a nonzero return value to the shell

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
I don't recall this debate, but I don't think `system_abort` means anything graceful. Let me see if I can figure out how to control the return code.

**Comment by bernstei** [comment]
Also, there are many ways to exit in that routine (mpi_abort, fabort, integer division by zero, and `stop`) and all but the one that triggered here return a non-zero status, so right now it's not even internally consistent.

**Comment by gabor1** [comment]
I agree

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
