### ISSUE TITLE
ModuleNotFoundError: No module named 'quippy._quippy'

### ISSUE THREAD

**Issue by Frozen-herea** [libAtoms/QUIP#347]
Hello! After I run the code, I find that I can't find this file. Can you point out where there is a solution?
![1632989378(1)](https://user-images.githubusercontent.com/91186156/135413412-f7eba2df-15fe-45e4-ba2e-c25bf78f8a30.png)

**Comment by jameskermode** [comment]
The compiled extension module is not found. This could be because you are trying to import from the `QUIP/` source directory, or because there was a problem with compilation. I suggest trying to install the binary distribution first with `pip install quippy-ase`.

**Comment by Frozen-herea** [comment]
After listening to your suggestions, the problem has been solved. Thank you very much！！！

**Comment by sandipde** [comment]
@jameskermode Just wanted to report that, I tried to compile the latest version now and faced the same error. It's because _quiipy.so is compiled with name _quippy.cpython-36m-x86_64-linux-gnu.so for me. renaming this manually worked.

**Comment by jameskermode** [comment]
It should import correctly with that name providing its somewhere on your Python path. The suffix identifies the Python version and system architecture.

**Comment by sandipde** [comment]
As I told you, Had to rename the file to make it work. Pythonpath and everything else were alright.
