### ISSUE TITLE
potential tests

### ISSUE THREAD

**Issue by albapa** [libAtoms/QUIP#349]
Without having a solid understanding of the testing system, I'm wondering if we should change the `assertAlmostEqual` instances in `tests/test_pot.py` (lines 183 and 200) to `assertArrayAlmostEqual`.

**Comment by jameskermode** [comment]
Good spot - but E1, E2 etc are lists not arrays so I think `assertAlmostEqual()` will work as expected.

**Comment by albapa** [comment]
Yes, it would work that way if the two lists are exactly the same numerically, as then the lists are also equivalent. However this test wasn't tolerant to any numerical noise in the elements of the lists. For a single float, it would have been fine, though. See my related PR.

**Comment by jameskermode** [comment]
You are right. Thanks! Closed by #354
