### ISSUE TITLE
Differences between python GAP and LAMMPS GAP

### ISSUE THREAD

**Issue by wilsonbill** [libAtoms/QUIP#352]
I am comparing the python QUIP force calculations to the LAMMPS QUIP force calculations. 
I understand the following webpages stating that both LAMMPS and QUIP python are in units of eV and Angstoms.
https://docs.lammps.org/pair_quip.html
https://docs.lammps.org/units.html

Below I show the python code and the calculated forces. Then I show the output of LAMMPS and the corresponding input files.
Should the python code and LAMMPS be so different?

I used the following GAP potential:
git clone https://github.com/libAtoms/silicon-testing-framework.git
cp silicon-testing-framework/models/GAP/gp* .
bunzip2 gp_iter6_sparse9k.xml.sparseX.GAP_2017_6_17_60_4_3_56_1651.bz2

from ase.build import bulk
si_bulk = bulk('Si', 'diamond', a=5.44, cubic=True)
from quippy.potential import Potential

pot = Potential(init_args='Potential xml_label="GAP_2017_6_17_60_4_3_56_165"',param_filename='gp_iter6_sparse9k.xml')

pot.get_forces(si_bulk)
si_bulk.positions

>>> pot.get_forces(si_bulk)
WARNING: Potential_calc: cutoff of Atoms object (-1.0000000000000000) < Potential cutoff (5.0000000000000000) - increasing it now
array([[ 4.58224502e-11,  1.21783939e-11, -3.56149552e-11],
       [ 2.13088037e-10, -6.70237789e-11,  2.92068814e-10],
       [ 4.57986171e-11, -1.22019942e-11,  3.55879739e-11],
       [ 2.13111374e-10,  6.70485210e-11, -2.92044247e-10],
       [-4.58452785e-11,  1.21532407e-11,  3.55883903e-11],
       [-2.13064803e-10, -6.69992917e-11, -2.92044969e-10],
       [-4.58468525e-11, -1.22025918e-11, -3.56358306e-11],
       [-2.13062612e-10,  6.70495690e-11,  2.92095018e-10]])
>>> si_bulk.positions
array([[0.  , 0.  , 0.  ],
       [1.36, 1.36, 1.36],
       [0.  , 2.72, 2.72],
       [1.36, 4.08, 4.08],
       [2.72, 0.  , 2.72],
       [4.08, 1.36, 4.08],
       [2.72, 2.72, 0.  ],
       [4.08, 4.08, 1.36]])

lmp_mpi <in.lmps
root@b4660e5f008c:~# cat siForce.dump 
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
8
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 5.4400000000000004e+00
0.0000000000000000e+00 5.4400000000000004e+00
0.0000000000000000e+00 5.4400000000000004e+00
ITEM: ATOMS id type x y z fx fy fz
1 1 0 0 0 -5.63655e-12 2.79221e-11 -3.5839e-11
2 1 1.36 1.36 1.36 4.70059e-11 4.49247e-11 -1.00564e-10
3 1 0 2.72 2.72 -5.66179e-12 -2.79454e-11 3.58163e-11

4 1 1.36 4.08 4.08 4.70287e-11 -4.4901e-11 1.00586e-10
5 1 2.72 0 2.72 5.61313e-12 2.78984e-11 3.58159e-11
6 1 4.08 1.36 4.08 -4.698e-11 4.49494e-11 1.00587e-10
7 1 2.72 2.72 0 5.60991e-12 -2.79474e-11 -3.58652e-11
8 1 4.08 4.08 1.36 -4.69783e-11 -4.48982e-11 -1.00537e-10

\<begin contents of in.str\>

8  atoms

1  atom types

0.000000 5.440000  xlo xhi
0.000000 5.440000  ylo yhi
0.000000 5.440000  zlo zhi

Masses

1  28.0855

Atoms

1  1 0.000000 0.000000 0.000000
2  1 1.360000 1.360000 1.360000
3  1 0.000000 2.720000 2.720000
4  1 1.360000 4.080000 4.080000
5  1 2.720000 0.000000 2.720000
6  1 4.080000 1.360000 4.080000
7  1 2.720000 2.720000 0.000000
8  1 4.080000 4.080000 1.360000

\<end contents of in.str\>

\<start contents of in.lmps\>

units           metal
boundary        p p p
atom_style      atomic

neighbor        3.0 bin
neigh_modify    every 10 delay 0 check no

read_data       in.str
mass 		1 28

pair_style      quip
pair_coeff      * * gp_iter6_sparse9k.xml "Potential xml_label=GAP_2017_6_17_60_4_3_56_165" 14

velocity        all create 3000.0 23456789

fix             1 all nvt temp 3000.0 400.0 0.5
timestep        0.0005
thermo_style    custom step pe ke etotal temp press vol
thermo          1
thermo_modify line one format float %12.12g
dump		1 all custom 10 siForce.dump id type x y z fx fy fz

run             1
\<end contents of in.lmps\>

**Comment by jameskermode** [comment]
Theses forces are all more or less zero since the atoms are on perfect crystal sites. The variations of the order of 1e-10 is due to numerical round-off. I suggest testing with a non-symmetric configuration where there are significant forces.

**Comment by wilsonbill** [comment]
Thank you. I got many significant digits of agreement when I tried some heated structures.

**Comment by bernstei** [comment]
Are we sure that LAMMPS handles cell < cutoff correctly?  That could be a source of problems.  If these are small cells, try making moderate supercells, big enough that they are larger than the GAP cutoff, and try those.

**Comment by wilsonbill** [comment]
The following is the 250 atom structure I used to verify that python QUIP gives the same forces at LAMMPS QUIP.
I generated 3000 structures with 250 atoms in each structure with corresponding energy and force data to use for training a kernel ridge regression model. I selected 1000 "sparse points" from the training set to create the kernel matrix using SOAP features. By "sparse points" I mean feature vectors of sites in structures. How many "sparse points" or "inducing points" are used to create the GAP_2017_6_17_60_4_3_56_165 potential?

h2oCell= np.array([[19.2     ,  0.      ,  0.      ],
       [-9.6     , 16.627688,  0.      ],
       [ 9.6     , -5.542563, 15.676734]])

coord= np.array([[ 1.45389679e+01,  2.19860959e+01, -1.58581101e+01],
       [-2.95896443e+01, -5.75393266e+00, -5.73476910e+00],
       [-2.49274233e+00,  3.11038087e+00,  1.50583509e+00],
       [ 1.45713376e+01, -6.55329235e-01, -7.52456888e-01],
       [ 2.65921835e+01,  1.86882372e+01,  1.15115277e+01],
       [-3.37649314e+00,  1.26535785e+01, -5.48414055e+00],
       [-5.29130929e+01,  3.14343880e+01, -3.49518252e+01],
       [ 1.73828988e+01,  2.61457855e+01, -8.70336134e+01],
       [ 1.97070884e+00,  2.37198555e+00, -3.75527687e-01],
       [-2.57109095e+01,  2.07397074e+01, -5.79334121e+00],
       [ 1.38110711e+01,  1.37528248e+01,  4.90333294e+00],
       [ 3.94913411e+01,  4.84112300e+00,  7.32777578e+00],
       [ 3.37145617e+01,  9.50193799e+00,  2.90074427e+01],
       [-1.04285779e+01,  7.02777872e-01, -2.43040836e+00],
       [-5.58182190e+00, -1.04392954e+01, -8.97652923e+00],
       [ 2.13209925e+01, -2.15463992e+01, -5.12883441e+01],
       [ 1.62740085e+00, -7.18772710e-01,  1.64670917e+00],
       [-4.18896823e+01,  4.99144804e+01,  2.02902295e+01],
       [ 1.90084071e+00,  9.99536954e-01,  2.71543473e-01],
       [ 2.37024794e+01, -4.55342519e+01,  3.93971476e+01],
       [ 1.11978307e+01,  3.46716919e+01,  3.57909177e+01],
       [-1.53326827e+01,  1.43376974e+01,  2.43273110e+01],
       [ 5.14063119e+01,  1.20209200e+00, -3.48053103e+01],
       [ 1.54604337e+00, -1.30654770e-01,  1.48384743e+00],
       [ 1.25471672e+00, -2.22304418e-01,  2.98907833e+00],
       [ 2.97413562e+01,  1.57020141e+00, -1.96432686e-01],
       [ 2.94323962e+01,  2.37961740e+01,  6.01564378e+00],
       [ 2.34141417e+01,  3.84803030e+01,  1.26485556e+01],
       [-3.58110802e+01, -5.25675588e+01, -2.48821182e+01],
       [ 8.60932422e+00, -2.93913329e+00,  2.85466946e+01],
       [-2.61978719e+01,  2.07014590e+00, -1.98427748e+01],
       [ 1.46067948e+01, -4.83771327e+01,  2.78069352e+01],
       [-7.73944382e-01,  8.54618966e-01, -1.76142502e+00],
       [-1.48861160e+01,  7.70727971e+00,  3.49471078e+01],
       [-1.43394824e+00,  2.93897985e+00, -8.97352009e-01],
       [ 3.10400209e+01,  5.27585059e+01,  4.63439225e+01],
       [ 3.56076253e+01,  2.48368927e+01, -4.48634826e+01],
       [ 7.40738805e+01,  1.56467187e+01,  1.32074450e+01],
       [ 4.91067794e+01, -1.83863362e+01, -5.16368425e+01],
       [-2.56844992e+01,  1.87121255e+01,  8.11674171e+00],
       [-1.90037491e+01,  8.28601921e+01,  4.87379115e+01],
       [ 2.50140555e+00, -4.64293987e+00, -1.85214680e+00],
       [ 8.67632480e+00,  2.76167536e+00, -4.28511472e+00],
       [-1.27629481e+00,  1.43488263e+00,  4.59136440e+00],
       [ 1.12334921e+01,  3.50144974e+00,  2.91307841e+01],
       [ 8.07038367e+00,  2.57077083e+00, -1.77306287e+00],
       [-3.61532136e+01, -6.56022503e+01, -4.85261375e+01],
       [-1.11622097e+01, -2.30755295e+01,  1.74712296e+01],
       [-5.34424090e-01,  1.30169142e+00, -1.48395272e+00],
       [ 2.36167755e+01,  7.11285050e+00,  3.70244567e+01],
       [-2.61000491e+01,  3.43354922e+01, -5.49567704e+01],
       [-1.87249401e+00,  3.39574601e+00,  5.82521664e-01],
       [ 1.33431420e+01, -4.59416058e+00, -2.46914927e+01],
       [-5.02275311e+01, -8.47337453e+01,  5.14117062e+01],
       [-6.69693932e+00,  2.90205264e+00, -3.26430508e+00],
       [-3.56473787e+01, -4.83178708e+00, -9.59703307e+00],
       [-8.40390856e-01,  1.22956623e+00,  3.33292547e-01],
       [ 7.37768001e+00,  5.36685929e-01,  1.12545070e+01],
       [ 9.15664017e-02,  1.52678616e+00,  9.00499954e-01],
       [-4.49458502e-01, -1.30807837e-01,  1.14151340e+00],
       [-2.15445473e+00, -2.01876554e+01,  3.04862191e+01],
       [ 8.71928966e+00, -5.00184221e+00,  4.39737605e-01],
       [-8.80628815e-01,  9.52182039e+00,  9.19580535e+01],
       [-1.34868221e+00, -1.17519526e+01,  4.80950389e+00],
       [-1.95325177e+01,  7.59608243e+01,  2.14357849e+01],
       [-6.46355713e+00, -9.84680134e+00,  1.55917645e+01],
       [-6.06734773e+01,  2.61362854e+01,  7.58101042e+00],
       [-5.46400104e+00,  5.68420147e+00, -4.13361702e+00],
       [-4.99908463e+00, -3.48323207e+00, -6.14514026e+00],
       [ 6.84835055e+00, -3.44093881e+01, -1.58228866e+01],
       [-8.05231104e+01, -1.05743858e+01, -1.74509965e+00],
       [-6.56738080e+00,  2.86862512e+01, -2.16505633e+01],
       [ 1.67053922e-01,  3.29783628e+00, -2.37273788e+00],
       [ 1.13556009e+01, -1.11584638e+01, -1.25735767e+01],
       [-1.64734985e+00,  7.12420253e-01, -8.62767862e-01],
       [-2.10605860e+00, -3.87842131e+00,  3.88424915e+00],
       [ 3.76920338e+01,  1.08553114e+01,  5.55567776e+00],
       [ 1.91052086e+00, -1.83933056e+00, -1.14508175e+01],
       [-1.21231254e+01, -7.19323602e+01,  1.22021960e+01],
       [ 2.74379578e+01, -4.98688779e+01, -4.76838994e+01],
       [-7.35192061e+00, -5.21231040e+01,  9.16617153e+00],
       [-4.20759315e+00,  7.04356242e+00, -1.03790057e+01],
       [ 1.76816525e+01, -4.62016376e-01, -2.45539618e+01],
       [-1.52378918e+01, -1.75946511e+01,  1.54622751e+01],
       [-3.06092963e+00, -7.41110238e-01,  4.28598989e+00],
       [ 1.06394016e-01,  6.57502586e+01,  4.71516968e+01],
       [ 1.33189702e+01, -5.90863284e+00, -1.66191328e+01],
       [-2.25553456e+01,  8.73787515e-01,  3.32687922e+01],
       [-1.00764870e+01,  3.18267562e+01, -3.13666462e+01],
       [-4.60042340e+01,  3.81352152e+01, -2.66014553e+01],
       [ 3.19665925e+00, -2.38717998e+01, -2.47883123e+00],
       [-1.29260398e+01, -1.18183944e+01, -3.31237494e+01],
       [ 5.74146835e+01,  6.36511253e+01, -3.45551669e+01],
       [ 2.77554665e+01, -4.63017162e+00, -1.17812538e+01],
       [-2.98381019e+01, -2.80977244e+01, -2.93976801e+00],
       [-6.38263388e+00,  1.15188244e+01, -9.69802735e+00],
       [ 1.16059961e+00,  4.55192324e-01,  1.80854156e-01],
       [ 3.95255761e+01, -4.03854800e+01,  2.11383657e+01],
       [ 1.00443836e+01,  2.92258242e+01, -1.04675028e+01],
       [-6.30525973e+01, -8.74962787e+00,  4.36046004e+00],
       [ 2.95298560e-01, -4.91204962e-01, -7.82698865e-01],
       [-1.22281010e+00, -1.26852257e+00, -1.52841219e+00],
       [ 9.69883372e+00,  3.90029332e+00, -9.63354626e+00],
       [-4.98915288e+01, -9.03181963e+00, -2.09059472e+01],
       [ 1.71756701e+01, -1.04872326e+01,  2.77268278e+01],
       [-5.70423382e+01, -3.30463346e+01, -5.52394065e+01],
       [-5.28848006e+00, -6.56936619e+01, -4.30210405e+01],
       [-6.23747677e+01,  7.32122113e+01, -2.18201181e+01],
       [-2.05930534e+01,  4.03957169e+00,  6.63054981e+01],
       [ 1.43029719e+00,  1.43857572e-01,  7.56732499e-01],
       [-1.29944434e+01, -2.86341074e+01,  1.33077134e+01],
       [-1.24319927e+01,  2.59774468e+01,  3.84760524e+01],
       [-7.55651235e-01, -9.85324092e+00, -2.76113337e+01],
       [-9.58448732e-01, -3.44904926e+00,  1.13029889e+00],
       [ 2.40188171e+01, -4.52590713e+01, -6.78756848e+01],
       [ 3.83656309e+00,  9.14959569e+00,  2.12733234e+01],
       [ 4.75504666e+01, -6.05578119e+01,  4.09875278e+01],
       [-2.94292260e-01, -8.26711025e-01,  6.18521367e-01],
       [ 1.82264356e+01,  3.52204566e+01,  5.02830092e+01],
       [-2.87524425e+01, -2.44479240e+01,  2.34893668e+01],
       [-1.94873140e+00,  5.76355292e-01, -1.90269493e+00],
       [ 1.20130802e+01, -1.77229098e+01, -4.00697353e+01],
       [-3.21936514e+00, -4.67548368e+00, -2.34769335e+01],
       [-1.34280716e+00,  4.08049984e+01,  1.52427809e+00],
       [ 2.47701827e+01, -3.26048150e+01,  5.46715094e+01],
       [-1.11827241e+00,  7.28247726e+00, -3.19934952e+01],
       [ 9.93284892e+00,  8.97598916e+00,  3.52200324e+01],
       [ 3.85675219e+00, -8.00229418e+00, -1.86974794e+01],
       [-8.56617516e+00,  4.20320391e+00,  7.54866389e-01],
       [-3.63945954e+00, -1.65471923e-01, -2.47631903e-01],
       [ 2.16284966e+01,  5.52808889e+01, -2.86019888e+01],
       [ 2.07305787e+01,  3.87834039e+01, -2.17617456e+01],
       [ 2.23438263e+00, -3.01239811e-01,  1.54342747e+00],
       [-3.51535083e-01, -2.45464957e+00,  7.03853365e-01],
       [ 7.48265023e+01,  8.29231482e+00, -1.57817096e+01],
       [ 8.45256028e-01,  5.78048719e+00, -1.68622962e+00],
       [ 1.79837763e+01, -3.76130207e+01,  4.42615742e+01],
       [ 1.12867201e+02,  3.28914155e+01,  3.61809460e+01],
       [ 1.91347544e+00,  1.57540012e+00,  1.70810580e-01],
       [ 1.45082459e+01, -1.23732954e+01, -6.53062243e-01],
       [-1.82230850e+01, -2.76710929e+01,  1.08738629e+01],
       [ 4.78675438e+00,  5.76215966e+00,  9.24489410e+00],
       [ 2.31545230e+01,  3.55279295e+01, -2.21026072e+01],
       [ 4.46313371e+01, -5.22885546e+01,  1.35916095e+01],
       [-3.79279124e+01,  5.71262066e+01,  3.48506457e+01],
       [-9.04487406e-01, -8.72093247e-01,  4.78930867e-01],
       [-2.75821519e+01,  1.19765178e+01,  1.70801089e+00],
       [ 3.75423199e+01, -5.10728254e+01,  1.31688145e+01],
       [-4.55435674e-01,  2.24181269e-01,  5.13858650e-01],
       [ 2.75472846e+00, -3.63286376e+00, -2.72554980e+00],
       [-7.99596772e-01,  4.43007253e-01,  1.03659581e+00],
       [-5.38671781e+00,  5.19157739e+01, -1.47319718e+01],
       [ 1.64904186e+00, -3.30782279e+00,  5.70160078e-01],
       [ 2.86004451e+01, -6.61372308e+00, -2.22500744e+01],
       [-3.23259642e+00,  2.69905567e+01, -1.99413520e+01],
       [-1.71733063e+01,  1.34176105e+01,  3.66670612e+01],
       [ 8.72272750e-01,  7.88874873e-01,  4.50703617e-01],
       [-7.29525359e+01, -3.04196828e+00, -1.21913736e+01],
       [ 7.35633648e+00,  3.01827249e+00,  1.61808404e-01],
       [-7.90213870e+00, -6.43522394e+01,  3.67897700e+01],
       [-8.34994141e+00, -8.90886994e+00,  7.90563591e-01],
       [-3.06735473e-01, -8.80322986e-01, -7.39374854e-01],
       [ 7.84157371e-01,  2.73440363e+00, -5.37060655e+00],
       [-1.85033013e+01,  6.20862781e+01,  4.07086045e-01],
       [ 2.59883375e+01,  7.20532556e+01,  4.58949266e+01],
       [ 6.66062092e+00, -3.03429885e+01,  1.85860607e+01],
       [-3.44371980e+01,  2.25191500e+01,  1.14301121e+01],
       [ 1.47526418e+00, -8.02814985e+00,  3.03564519e+01],
       [-5.07609054e+00, -9.14858404e+00, -2.18679197e+01],
       [-7.59706843e-01, -1.73078747e+00, -8.47863553e-01],
       [-3.99376090e+01,  3.92377589e+01, -2.18375926e+01],
       [-1.37681484e+00, -9.40715964e-01,  1.31763254e+00],
       [ 1.01478168e+01, -6.71708361e+00, -1.75522726e+01],
       [-5.83466330e+00, -4.47673164e+00, -2.72499503e+00],
       [ 2.74982620e+01, -1.25137367e+01, -1.51850090e+00],
       [-3.35508194e+01,  8.57488078e+00,  7.82816136e-01],
       [ 2.22004443e+01,  7.53459461e-01,  6.03769135e+00],
       [ 1.70353516e+00, -2.68576669e+01, -5.43310373e+00],
       [ 1.07775128e+01,  1.44939527e+01,  3.18088816e+01],
       [ 5.53658000e+00, -1.24463787e+01, -5.73344464e+00],
       [ 3.06222113e+01, -2.57054832e+01,  5.15113708e+01],
       [ 6.07155592e+01, -4.79858380e+01, -2.43120858e+01],
       [ 2.00906694e+01, -1.14243179e+01, -3.69291679e+01],
       [-2.07555306e+00, -1.30533261e+00, -3.78371203e+00],
       [-2.77978077e+01,  5.40904161e+01, -5.23881476e+01],
       [ 1.78222169e+01,  4.54934357e+00,  6.83620688e+01],
       [-3.82517515e+00, -3.73823325e+01,  5.02713742e+01],
       [-2.52550694e+01,  2.48655947e+01, -2.59428514e+01],
       [ 5.60617137e+00, -4.08052816e+01,  3.03656326e+01],
       [ 1.17900274e+00, -1.67920331e+00,  6.59647172e+00],
       [-4.29920949e+01,  7.33563254e+01,  9.65531421e+00],
       [ 9.34484234e+00,  2.25231558e+00,  1.45341103e+01],
       [ 2.18958960e+00,  1.06103731e-01, -1.28999943e-01],
       [-1.81618124e-01, -3.41567001e-01,  1.42324121e-01],
       [-2.02676732e+00,  1.07925737e+01, -2.47237773e+00],
       [ 1.80049207e+00,  3.46926943e-01, -1.80106590e+00],
       [ 4.74839226e-01, -8.11659237e-02, -9.25759264e-02],
       [ 7.28940866e-02, -3.28412544e-01,  1.94916652e+00],
       [-2.12989255e+01,  4.60516549e+01, -2.92287894e+01],
       [-7.66611432e+00,  4.92071484e+00,  6.18537724e-01],
       [ 6.96666661e-01, -1.54033651e-01,  1.49974062e-01],
       [ 2.78320264e+00,  3.35292870e+00, -1.77874985e+00],
       [ 3.87069623e+00,  6.19937300e+00,  4.97398729e+00],
       [-2.67703906e+01, -4.44166345e+01, -2.18315715e-01],
       [-3.10342674e+01, -6.49870932e+00, -2.29945522e+01],
       [ 1.55137506e+01,  2.41981329e+01,  2.34116555e+01],
       [-2.64254427e-01, -3.09675249e+00, -8.86836046e-02],
       [-1.77750100e+00, -3.29637575e+00, -2.22908973e+00],
       [-6.01276684e+01,  3.13738190e+01, -2.17260685e+01],
       [ 8.55839622e-01, -1.66263957e+00,  8.50039034e-01],
       [-5.25563555e+00,  3.90415236e+00,  5.12677352e+00],
       [-4.47607374e+00, -8.88601089e+00, -8.55727944e+00],
       [ 4.61102910e+00,  1.23627514e+01,  1.35886824e+01],
       [-4.65696478e+00, -1.13681068e+01,  4.49479063e+00],
       [-2.14430176e+01, -8.09200393e+00, -3.45899339e+01],
       [-9.29604398e+00, -7.99609776e+00, -1.51386528e+01],
       [ 1.54912397e+00, -3.09005884e-01, -1.19761317e+00],
       [ 2.54082616e+01, -1.90164210e+01,  7.00181797e+00],
       [ 8.54969895e+00, -5.22832437e-01,  5.90942799e+00],
       [-2.34151947e+00,  7.04273786e+00,  1.66698805e+01],
       [-3.67147857e+01,  6.47125877e+00,  2.15223152e+01],
       [-2.40781071e+01, -1.06780909e-01, -1.25433382e+01],
       [ 1.27461446e+02,  3.81162005e+01, -1.97480167e+01],
       [-1.04196095e+00,  2.71950196e+00, -1.31685402e+00],
       [-3.99666227e-01,  3.08085613e+00,  9.01525863e-01],
       [-2.92691722e+01,  9.07196751e+00, -2.37427472e+01],
       [ 4.56607266e+01, -5.64369174e+01,  7.62395762e+00],
       [ 1.27662719e+00,  3.43805804e+00,  1.02176129e+01],
       [ 8.18107599e-01, -1.32897329e-01, -9.20002560e-01],
       [-1.99748368e-01,  1.95687545e+00,  7.71993467e+00],
       [ 3.34207528e-01,  5.86735924e+00, -2.91815409e+01],
       [ 1.34664070e+00, -5.22908143e-01,  3.03906549e-01],
       [-1.14245517e+00,  3.46766616e+00,  3.63072120e+00],
       [-4.07208485e+00, -2.00793488e+00, -5.41617031e+01],
       [-1.44661808e+01, -5.77657153e+01,  9.03170187e+00],
       [ 2.31693233e+00, -2.07826205e+00,  8.82253766e+00],
       [-9.38387198e+00,  2.41156272e+00,  1.23155894e+01],
       [ 5.70558551e+01, -2.56256151e+01, -1.28731552e+01],
       [-2.68719613e+00,  2.93542645e+01,  1.88407497e+00],
       [ 8.00799691e+00, -4.45658146e+01, -1.41457365e+01],
       [ 4.52293017e+01, -4.26474008e+01,  2.24372275e+01],
       [-1.93908605e+01, -1.19684439e+01, -4.00775555e+00],
       [-1.31157205e+01,  5.84329126e+00,  1.52539639e+01],
       [-1.23144273e+00,  2.25677903e-02,  2.30496865e-01],
       [-3.95788684e+00,  1.61794615e+01,  1.06047383e+01],
       [-1.44211089e+01, -8.14026152e+01,  2.47294850e+01],
       [-2.23159808e+01, -3.14684536e+00, -8.67431795e+00],
       [-4.43336135e+01,  9.31638725e+00, -4.93927927e+01],
       [-3.22595881e+01, -5.53594970e+01, -4.57085082e+01],
       [-2.28882426e+01, -9.92432177e+00, -7.00675363e+01]])

**Comment by gabor1** [comment]
you can find out the number of sparse points from the xml file, e.g. if you grep for the string "command", it will show you the command line arguments that were used when making the potential, and the number of sparse points is part of the command line.
