### ISSUE TITLE
add vasp_driver to quippy wheel binaries

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#353]
I have lots of users who rely on `vasp_driver` for historical reasons.  Would it be OK if I added it to the build and install via the python wheel? I guess an alternative would be to write one in pure python, e.g. using the ASE vasp calculator.

**Comment by gabor1** [comment]
sure go ahead. as long as it's allowed by the vasp license...

**Comment by bernstei** [comment]
On Oct 26, 2021, at 8:45 AM, gabor1 ***@***.******@***.***>> wrote:

sure go ahead. as long as it's allowed by the vasp license...

I don't see why not - besides, we're still distributing it as part of the source, just not the pypi wheel.
