### ISSUE TITLE
angle_3b not MPI ready

### ISSUE THREAD

**Issue by xinglong-zhang** [libAtoms/QUIP#355]
Greetings!

I complied the QUIP program from the github source code on Linux machine with ARCH=linux_x86_64_gfortran_openmpi.

I note that when I run the training of distance_2b and angle_3b, the training finishes without any issue. The command I used for training is
 
`gap_fit energy_parameter_name=energy force_parameter_name=forces do_copy_at_file=F sparse_separate_file=T gp_file=GAP_3b.xml e0={H:0.0:O:0.0} at_file=train.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10 : angle_3b cutoff=3.5 covariance_type=ard_se delta=0.5 theta_fac=0.5 add_species=T n_sparse=30 sparse_method=uniform}`

However, when I tried to applied the trained model to do prediction using the command `quip E=T F=T atoms_filename=train.xyz param_filename=GAP_3b.xml | grep AT | sed 's/AT//'  > quip_3b_train.xyz`, it gave the following error:
 

> SYSTEM ABORT: proc=0 Traceback (most recent call last)
> File "/home/xinglong/bin/QUIP/src/GAP/descriptors.f95", line 937 kind unspecified
> descriptor_MPI_setup: angle_3b not MPI ready.            
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
> with errorcode 1.
>  
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.

 
This seems to be that “angle_3b not MPI ready” however, the program is compiled with openmpi support.

I wonder if it may be possible to do the prediction with the compiled version with openmpi support or do we need to separately compile a version that is serial? 

Thank you for your attention and looking forward to your kind reply!

**Comment by bernstei** [comment]
gap_fit is not currently MPI-parallelized (although there is work in progress).  The only form of parallelism that is supported is OpenMP.

**Comment by gabor1** [comment]
As @bernstei says, gap_fit is not yet mpi parallelized. It is parallel using OpenMP threads, so if you compile with openmp, then you get parallelism within a shared memory node. The mpi version is coming in a couple of months (it's already been coded, now under testing)

**Comment by MES-physics** [comment]
Hello,  
I have a newly installed MPI version, (OneAPI and MKL) and I get this error :  
```descriptor_MPI_setup: angle_3b not MPI ready.```
when trying to run this script :
```
quip E=T F=T atoms_filename=Atoms.xyz param_filename=Cpotential.xml | grep AT | sed 's/AT//' > quip_trainGAPC.xyz
```
And the output file is empty.     What can I do?   Thanks.

**Comment by gabor1** [comment]
IF you use lammps, you can use angle_3b and compile GAP in serial, and lammps does the domain decomposition and gives you parallelisation. 

If you swap the angle_3b descriptor to "distance_Nb order=3" it is functionally equivalent to angle_3b and then you can use QUIP's own MPI parallelisation like you are trying to do above.

**Comment by MES-physics** [comment]
Thanks, I did this command swap (option 2), got a potential with the MPI version, but still the above trial using quip in the MPI version creates a segfault.  I appreciate any further advice, thanks.

**Comment by gabor1** [comment]
Ok so that's something new. Segfaults with MPI are hard to debug because output gets eaten. Can you try running this not through a queue system and attach your full output and error log?

**Comment by MES-physics** [comment]
Here are output and error from my slurm batch submission, I couldn't get interactive nodes now if that's what you mean.
[EvalCours348-1836811.err.txt](https://github.com/libAtoms/QUIP/files/15195498/EvalCours348-1836811.err.txt)
[EvalCours348-1836811.out.txt](https://github.com/libAtoms/QUIP/files/15195499/EvalCours348-1836811.out.txt)
Thanks.

**Comment by gabor1** [comment]
The logs are not very helpful. If you are willing to post your XML file and your starting structure I can try to reproduce your issues.

**Comment by MES-physics** [comment]
Oh oh, my 3rd xml sparse file is way over 25 MB, the limit here.
Can I give you access to files on google drive or something?
Or maybe that's the problem , it can't evaluate with files that big?  91MB

**Comment by gabor1** [comment]
no, file size shouldn’t be a problem. but maybe this points to something - can you send over your command line ? maybe you have too many 3b terms. you want to restrict the cutoff of the 3b to be essentially nearest neighbour only. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by MES-physics** [comment]
My 3b cutoff is 2.5.
Here it is.
[gap_fitMPI.sh.txt](https://github.com/libAtoms/QUIP/files/15199407/gap_fitMPI.sh.txt)

**Comment by gabor1** [comment]
the xml file has the training set it in it. just delete those lines. the rest should be much smaller.

but yes, give me access to your gdrive

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by MES-physics** [comment]
how do I share with you?

**Comment by gabor1** [comment]
you can just share the gdrive with my university email address

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by MES-physics** [comment]
I sent you the link, thanks!
