### ISSUE TITLE
How to output the atomic energy

### ISSUE THREAD

**Issue by yliu1240** [libAtoms/QUIP#356]
Hi, all!
Since GAP uses 'single-atom' energies in fitting and add them up to get the total energy, where these 'single-atom' energies may or may not be physically meaningful (depends on how to set the E0 for each atom type). I'm wondering if there's a way to extract these 'single-atom' energies in prediction, such as an argument for gap_predict, or a function in quippy?

Also, if we're able to get these 'single-atom' energies, are they subtracted by E0? To clarify my question, is E_tot:
        E_tot = sum(E_single-atom) + n*E0
or just:
        E_tot = sum(E_single-atom)

Thanks a lot for your time and have a nice day!

Best regards,

**Comment by gabor1** [comment]
The fit target is  E_tot-n*E0 (Assuming a single element in the training database), and at prediction time, the n*E0 is added back to the sum(E_GAP). so along the lines of your first equation.

**Comment by yliu1240** [comment]
> The fit target is E_tot-n_E0 (Assuming a single element in the training database), and at prediction time, the n_E0 is added back to the sum(E_GAP). so along the lines of your first equation.

Thank you very much for clarifying that!

For the first question: is there a function / command to get the 'single-atom' energies (atomic energies) in QUIP?
I think the atomic energy (the last column in the question section) in another issue thread seems very close to my question:
https://github.com/libAtoms/QUIP/issues/248#issue-736488011
![image](https://user-images.githubusercontent.com/24704006/139340235-66a8a89d-cdae-43de-81d5-73a81244c3fb.png)
(the column with numbers: 0.1527, 1.1053, 0.3478. I'm wondering if there's any suggestion to get these values in QUIP?)

Thanks in advance and have a nice day!

Best regards,

**Comment by jameskermode** [comment]
In Python you can use `pot.get_potential_energies(atoms)` where atoms is your ASE Atoms object and pot is a quippy Potential.

**Comment by jameskermode** [comment]
Alternatively, with the `quip` command line tool you can use the `local` and `energy` arguments. Check `quip --help` for usage.

**Comment by yliu1240** [comment]
> Alternatively, with the `quip` command line tool you can use the `local` and `energy` arguments. Check `quip --help` for usage.

Thank you very much! I tried both methods. They solve my problem.

Thank you again and have a nice day!

Best regards,
