### ISSUE TITLE
Error while make quippy

### ISSUE THREAD

**Issue by DjordjeDangic** [libAtoms/QUIP#358]
Hello everyone,

I am trying to install quip on a local cluster. 
I used git clone --recursive https://github.com/libAtoms/QUIP.git to download the code.
I use QUIP_ARCH=linux_x86_64_gfortran. 
The config section is defaults, except for linking lapack and blas where I used -lopenblas and that I included GAP(y option).
make and make libquip finished without any errors. 
make quippy gives an error:

**/software/eb/software/GCCcore/7.3.0/bin/gfortran -Wall -g ./src.linux-x86_64-3.6/_quippymodule.o ./src.linux-x86_64-3.6/src.linux-x86_64-3.6/fortranobject.o ./f90wrap_Atoms_types.o ./f90wrap_Atoms.o ./f90wrap_System.o ./f90wrap_Dictionary.o ./f90wrap_DynamicalSystem.o ./f90wrap_nye_tensor.o ./f90wrap_Potential.o ./f90wrap_Potential_simple.o ./f90wrap_descriptors.o -L. -L/home/djordjedangic/QUIP/src/fox/objs.linux_x86_64_gfortran/lib -L/software/eb/software/GCCcore/7.3.0/lib64/../lib64 -L/software/eb/software/GCCcore/7.3.0/lib64/../lib64 -L/software/eb/software/Python/3.6.6-foss-2018b/lib -lquip_nostub -lFoX_sax -lFoX_wxml -lFoX_utils -lFoX_common -lFoX_fsys -lopenblas -lpython3.6m -lgfortran -o ./_quippy.cpython-36m-x86_64-linux-gnu.so
/lib/../lib64/crt1.o(.text+0x20): error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
/lib/../lib64/crt1.o(.text+0x20): error: undefined reference to 'main'
collect2: error: ld returned 1 exit status**

I tried pip install quippy-ase and that one works and installs the package. However, if I try to run make test I get the same error as above. If I try to use quippy it works, it can load the potential and calculate potential energy. 

However, I am bit bothered by the error above. Should I worry or just continue to use the pip installed quippy?

**Comment by jameskermode** [comment]
Pip version should be fine for most use cases. You can run the tests with the pip installed version by running the run_all.py script in QUIP/tests directly.

**Comment by DjordjeDangic** [comment]
I tried also gap_fit function and that one works as well. I will close the issue now. Thank you.
