### ISSUE TITLE
  Error executing command of gap_fit in docker of jupyter？

### ISSUE THREAD

**Issue by e-724** [libAtoms/QUIP#359]
===================== Report on number of descriptors found ====================

---------------------------------------------------------------------
Descriptor: soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=5.0 cutoff_transition_width=1.0 n_sparse=9000 delta=3.0 f0=0.0 covariance_type=dot_product sparse_method=cur_points n_species=1 Z=14 species_Z={14 }
Number of descriptors:                        640000
Number of partial derivatives of descriptors: 111360000

========================================  ======================================

Operating system error: Cannot allocate memory
Allocation would exceed memory limit

Error termination. Backtrace:
#0  0x2b467a29b8da
#1  0x2b467a29c395
#2  0x2b467a29c592
#3  0x56282d6f9179
#4  0x56282d332c54
#5  0x56282d3205a5
#6  0x56282d31ff3e
#7  0x2b467a74309a
#8  0x56282d31ff79
#9  0xffffffffffffffff

**Comment by noambernstein** [comment]
As the error message says pretty clearly, you don’t have enough memory.
Your fitting database is huge, almost certainly far bigger than it needs to
be. As I recall the silicon potential published used only 1.5e5
environments, and you have 6.4e5, and even that fit used of order 1 TB.

**Comment by gabor1** [comment]
You could reduce n_max to 8 and l_max to 4, which will reduce the memory requirements, and only mildly compromise the accuracy. The cutoff could come down to 4.5 which again will be a small decrease in accuracy, but will help with training time quite a bit (fewer force cross terms)

**Comment by gabor1** [comment]
when you are running in the docker, make sure the docker is allowed to use the full memory of your system
