### ISSUE TITLE
Problem with quippy

### ISSUE THREAD

**Issue by Petitpachiderle** [libAtoms/QUIP#360]
Hello,
I think it's a stupid problem but I don't understand a problem I have when i try to import quippy.potential  : 
"from quippy.potential import Potential"
I have this error message : 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-6b61908e03bf> in <module>
      3 from ase.optimize.bfgs import BFGS
      4 from ase.constraints import ExpCellFilter
----> 5 from quippy.potential import Potential

/opt/anaconda3/lib/python3.8/site-packages/quippy/potential.py in <module>
     37 
     38 
---> 39 @set_doc(quippy.potential_module.__doc__,
     40 """
     41 Pythonic interface to auto-generated quippy.potential_module.Potential class

AttributeError: module 'quippy' has no attribute 'potential_module'

I tried to search on other issues but i didn't find how to fix my problem.

Thank you

**Comment by jameskermode** [comment]
How did you install quippy? If via pip then note that’s it’s `pip install quippy-ase` not `pip install quippy`

**Comment by xuxrishandsome** [comment]
what computer system do you use, windows or linux?

**Comment by jameskermode** [comment]
`pip install quippy-ase` currently works only on Linux or Mac OS, and not on Windows. Contributions to make wheels for Windows would be welcome via a PR to https://github.com/libAtoms/quippy-wheels
