### ISSUE TITLE
gap_fit problem

### ISSUE THREAD

**Issue by pobo95** [libAtoms/QUIP#380]
Dear sir
Hi I'm really new in QUIP but I try to learn it.

But when I install quippy with conda (conda install -c conda-forge quippy)

I got a error massage when use gap_fit command

Traceback (most recent call last):
  File "/home/grad/pjpark/.conda/envs/PJ/bin/gap_fit", line 10, in <module>
    sys.exit(gap_fit())
  File "/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/site-packages/quippy/cli.py", line 10, in gap_fit
    sp.call([command] + sys.argv[1:])
  File "/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/site-packages/quippy/gap_fit'

I think I can solve this problem when  I copied 
gap_fit file form "/home/grad/pjpark/.conda/envs/PJ/bin/" 
to '/home/grad/pjpark/.conda/envs/PJ/lib/python3.10/site-packages/quippy/

Is It right?

Thank you for your help.

**Comment by jameskermode** [comment]
That solution sounds fine. We don’t maintain the conda forge recipe, so please open a issue there, or just use plain `pip install quippy-ase` which also installs a gap_fit executable

**Comment by pobo95** [comment]
Thank you sir!
I fix the problem with copping the 'gap_fit' file into the quippy folder.

But I got a new massage which 'libgomp: Thread creation failed: Resource temporarily unavailable'

I think something wrong with my system can you know me how to fix it?
I found 'export OMP_NUM_THREADS=1' command can help but it didn't work.

**Comment by pobo95** [comment]
I fix the problem with pip install quippy-ase

Thank you sir!
