### ISSUE TITLE
latest quip doe not work with kim_1.7.3

### ISSUE THREAD

**Issue by milfeld** [libAtoms/QUIP#41]
I'm installing the latest lammps at TACC on our KNL machine, and of course want to include a recent version of kim (1.7.3) because some of our users are developing MSMEAM code with this version of kim.  When I build the latest quip version (from github) in lammps and include kim in the build it doesn't compile because quip is expecting a "KIM_API" module (as found in earlier versions of kim) not the "KIM_API_F03" module of the latest release.
Are you developing, or could you please develop, a branch which will accommodate kim_1.7.3's latest changes?
Thanks,
Kent Milfeld

ifort  -fpp -free -warn unused -fPIC -I/work/00770/milfeld/knl_lammps/lammps-17Nov16/lib/quip/src/libAtoms -I/work/00770/milfeld/knl_lammps/lammps-17Nov16/lib/quip/src/fox/objs.linux_x86_64_ifort_icc_serial/finclude -I/opt/apps/intel17/netcdf/4.3.3.1/x86_64/include `kim-api-v1-build-config --includes` -O3 -xMIC-AVX512 -fp-model fast=2 -qno-offload -qoverride-limits -diag-disable=7712 -g -traceback -DDUMP_CORE_ON_ABORT  -DGETARG_F2003 -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,4a32314-dirty"' -D'GAP_VERSION=1480975044' -D'QUIP_ARCH="linux_x86_64_ifort_icc_serial"' -D'SIZEOF_FORTRAN_T=2' -DHAVE_NETCDF -DNETCDF4 -DHAVE_KIM -DHAVE_PRECON -DHAVE_QR  -c -Tf /work/00770/milfeld/knl_lammps/lammps-17Nov16/lib/quip/src/Potentials/IPModel_KIM.f95 -o IPModel_KIM.o
/work/00770/milfeld/knl_lammps/lammps-17Nov16/lib/quip/src/Potentials/IPModel_KIM.f95(59): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [KIM_API]
use KIM_API

**Comment by noambernstein** [comment]
What's with the recent interest in QUIP+OpenKIM?  You're the second person
to ask about this in the last month or two.

Anyway, while the fact is poorly documented (and I'll make sure that gets
fixed), the support for KIM in QUIP is so out of date it's not functional,
as you discovered.  I was working on a revised version, but without a
decent testing framework I was uncomfortable releasing it.  There's a
pretty major change to the OpenKIM API in the works, so I was hoping to
delay the new implementation until it was complete.  In any case, I believe
there's a direct connection between LAMMPS and OpenKIM that is being more
actively maintained (and is likely to be more computationally efficient
anyway), so in the context of LAMMPS I don't even really understand the
need for the QUIP-OpenKIM connection.  If I'm wrong about the last
statement let me know, and I'll reconsider my development priorities.
​

**Comment by milfeld** [comment]
Hi Noam,
   This is not a high priority "issue".  I found that quip is now in the LAMMPS user library area; and I thought, therefore, that users in the community might be employing quip (with/through) lammps.  I was just trying to install as many of the user-libs as the LAMMPS folks provided, since we have about 2K projects on our systems, and we never know what our users will try/need.  Certainly, some of libs (components) are never used in LAMMPS; but, it is best for me to have as much available when I release a new LAMMPS, so that I reduce the probability of having to rebuild and reinstall the package for corner use cases.   So, there is no need for the kim component to quip at this time in LAMMPS.  I will not include the kim component in quip for now.  If we have a specific request, I'll contact you.  Also, at the next install, I'll just get a new repo version, and check the kim status. 
Thanks for the quick response.
Thank you for libAtoms, the QUIP method and all the work/science you put into it!   Best, Kent

**Comment by gabor1** [comment]
Hi,

Sorry for chiming in, just for the avoidance of doubt: there are many people using quip through lammps without the KIM API compiled into quip. We need to know about any problem with that configuration of the interface.

— Gábor
