### ISSUE TITLE
Found 1 GAPs instead of 2

### ISSUE THREAD

**Issue by tavanfran** [libAtoms/QUIP#416]
Dear all,

I am trying to use gap_fit on a HPC system, but I get an error when using two gaps: ditance_2b and angle_3b (or soap). 

This is the command  that gives me the error:

gap_fit force_parameter_name=forces do_copy_at_file=T sparse_separate_file=T gp_file=GAP_3b.xml at_file=conf.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b  cutoff=5.0 covariance_type=ard_se delta=0.1 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10 : angle_3b cutoff=5.0 covariance_type=ard_se delta=0.1 theta_fac=1.0 add_species=T n_sparse=20 sparse_method=uniform} e0={Ge:-155.78:Se:-279.73:P:-185.71}

end the error if:
execvp error on file angle_3b (Permission denied)

If I use the same command on my ubuntu machine, I do not have the errors and I get that it works fine.

In the HPC machine,  I tried to use the following command:

gap_fit force_parameter_name=forces do_copy_at_file=T sparse_separate_file=T gp_file=GAP_3b.xml at_file=conf.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b  cutoff=5.0 covariance_type=ard_se delta=0.1 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}  gap={angle_3b cutoff=5.0 covariance_type=ard_se delta=0.1 theta_fac=1.0 add_species=T n_sparse=20 sparse_method=uniform} e0={Ge:-155.78:Se:-279.73:P:-185.71}

but it reads only 1 GAP (the angle_3b) and it says:
Found 1 GAPs
and it works, but it does not read the distance_2b.

I tried to use the single gaps as 

gap_fit force_parameter_name=forces do_copy_at_file=T sparse_separate_file=T gp_file=GAP_3b.xml at_file=conf.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b  cutoff=5.0 covariance_type=ard_se delta=0.1 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}

and it works.
The same happens in the HPC if I use any combination of soap, distance_2b and angle_3b. In my local ubuntu they work all together without problems. The installation procedures in the machines (local and HPC) are the same and they are very simple, I just tell to use GAP during the "make config".

Do you have any suggestions?

Otherwise, can I do the single gap (ditance_2b and angle_3b separately) and then merge them all together?

Thank you for your help

**Comment by gabor1** [comment]
This sounds to me like a shell problem. can you check which shell you use on your two systems? I think the shell  isn't passing the arguments correctly to the gap_fit executable

**Comment by gabor1** [comment]
and no, you can't fit gaps separately and then merge them.

**Comment by tavanfran** [comment]
Dear @gabor1 ,
thank you very much for your reply. I contacted my sys admin and she solved the problem. Now it works with 2 or 3 keywords.

Now I have another problem connected with Lammps: when I launch lammps, it reads everything up to the command where it read the potential. This is the input file for lammps:

units           metal
boundary        p p p
atom_style      atomic
read_data       data_gap
pair_style      quip
pair_coeff      * * GAP_3b.xml "Potential xml_label=GAP_2022_3_11_60_11_26_4_412" 32 34 15
neighbor        0.3 bin
neigh_modify    delay 10
fix             1 all npt temp 1000.0 1000.0 0.01 iso 100000 100000 2
thermo          10
timestep        0.001
dump            10 all custom 10 dump.lammpstrj id type element x y z
run             1000
unfix 1
fix 2 all npt temp 1000.0 300.0 0.01 iso 100000 100000 2
run 2000
unfix 2

and I get this error:

SYSTEM ABORT: proc=1 Trying to read into extendable_str from unopened unit 7.

I see that this error comes from the file ExtendableStr.f95 at line 488
if (.not. is_open(unit))

Do you have any idea on how to solve it?
Thank you!

**Comment by gabor1** [comment]
it sounds like it didn't manage to open some files. did you make sure that not only the xml file but the *sparseX* files that the gap_fit generated are all in your working directory?

**Comment by tavanfran** [comment]
Yes, I generated all files in the same directory. 
I tried to run the same command on my ubuntu and it did not work due to an error because in lammps I did not insert the masses. After adding the masses, it runs on my ubuntu, but on the HPC I still get this error:

ERROR: Too many tokens in Masses section of data file: 2    78.9600 Se (src/read_data.cpp:1788)
Last command: read_data data_gap

the input of lammps is:

pair_coeff      * * GAP_3b.xml "IP GAP" 32 34 15

so 3 atomic types. In the input of lammps (the structure file) I have:

100 atoms
3 atom types
0.0 13.514 xlo xhi
0.0 13.514 ylo yhi
0.0 13.514 zlo zhi
0.000 0.000 0.000 xy xz yz
Masses
1    72.5900 Ge
2    78.9600 Se 
3    30.9737 P
Atoms...
...

I put the atoms in the same order of the quip potential. It seems to me like if it reads only one atom. Is the problem on how I give the quip input in lammps?

**Comment by bernstei** [comment]
This looks like a LAMMPS issue, nothing to do with GAP.  Are you sure all the LAMMPS versions, input file, and data_gap file are the same on both machines?   I’m pretty sure the number of species in LAMMPS is not set by the pair_coeff line.  I forget where it’s set (it’s someplace I find illogical, I think), but it’s elsewhere in the lammps input. I think it’s the create_box command, normally.

**Comment by tavanfran** [comment]
Dear @gabor1 @bernstei 

I managed to fix a problem with lammps:
1) the error "Too many tokens in Masses section of data file" is fixed removing the names of the atoms in the Masses keyword of Lammsp:

Masses
1 72.5900 Ge
2 78.9600 Se
3 30.9737 P

2) When I try to use lammps and quip on my local cluster I still have the error:
SYSTEM ABORT: proc=1 Trying to read into extendable_str from unopened unit 7.
but in my ubuntu it works. Lammps and quip versions are the same. 
Any idea? Do I have to contact Lammps staff?

Thank you for your effort

**Comment by tavanfran** [comment]
Dear all,

I found an explanation of the error

SYSTEM ABORT: proc=1 Trying to read into extendable_str from unopened unit 7.    

Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

If I run lammps and quip with mpirun -np N, I get this error for N-1 processors. If I run mpirun -np 1, it works. It is like lammps with N process calls N times quip, that opens N times the GAP potentials. The problem is that after the first opening, quip finds the GAP files already opened and it stops. 
Do you know how it can be solved?
Both lammps and quip are complied in parallel with mpi.

Thank you

**Comment by jameskermode** [comment]
QUIP should not be compiled with MPI, since we rely on LAMMPS for the parallelisation.

**Comment by noambernstein** [comment]
On Thu, Mar 17, 2022 at 5:05 AM James Kermode ***@***.***>
wrote:

> QUIP should not be compiled with MPI, since we rely on LAMMPS for the
> parallelisation.
>

Should we make the QUIP lammps interface fail with some understandable
message if it detects that it was compiled with MPI? Or maybe not even
compile it at all into the libquip.a if MPI support is on?

**Comment by albapa** [comment]
Good idea. I think we can keep libquip.a but should be possible to detect in the interface if MPI was on.

**Comment by jameskermode** [comment]
`nm libquip.a | grep -q libmpi` would probably do it

**Comment by jameskermode** [comment]
Note that we do now distribute an appropriate `libquip.a` as part of the `pip install quippy-ase` distribution. Link arguments can be obtained by running `quip-config --libs`.

**Comment by bernstei** [comment]
Is there even an mpi compiled pip version?  Anyway, I still think it's worth detecting and giving a sensible error _at runtime_

**Comment by albapa** [comment]
I hope the pull request #419 solves this issue.
