### ISSUE TITLE
Error when running LAMMPS with latest GAP

### ISSUE THREAD

**Issue by VladCarare** [libAtoms/QUIP#425]
Good afernoon,

Yesterday I managed to compile the latest QUIP on Archer2, and trained a GAP. The header for the training stdout is, for reference: 
```
libAtoms::Hello World: 2022-04-08 09:55:47
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,53fa928b8-dirty
libAtoms::Hello World: QUIP_ARCH    archer2-mpi+openmp
libAtoms::Hello World: compiled on  Apr  7 2022 at 15:59:13
libAtoms::Hello World: MPI parallelisation with 128 processes
libAtoms::Hello World: OpenMP parallelisation with 40 threads
libAtoms::Hello World: OMP_STACKSIZE=2G
libAtoms::Hello World: MPI run with the same seed on each process
libAtoms::Hello World: Random Seed = 280690049
libAtoms::Hello World: global verbosity = 0
```

Today I compiled LAMMPS, provided the path to libquip.a (present in the QUIP compiled yesterday), and tried to run some dynamics, with the same script that I used to successfully run LAMMPS in the past (another installation but same version (the QUIP in that case was installed automatically by lammps when making the program)).

It fails after a few seconds with the error:
```
At line 311 of file /work/e89/e89/vc381/Calculations/dev/gap-mpi-3/QUIP/src/libAtoms/error.f95
Fortran runtime error: Unit number is negative and unit was not already opened with OPEN(NEWUNIT=...)
```
followed by a segmentation fault.

I mention that the potential works seamlessly for manually (in ASE) evaluating energies, forces, etc.

**Comment by VladCarare** [comment]
Also, it seems that the error is printed as many times as I have mpi tasks for LAMMPS.
I.e. if I do `srun --nodes 1 --ntasks=24 lmp -in laamps.sh` those 2 error lines get repeated 24 times. 

So I guess the issue may arise because both LAMMPS and QUIP start their own MPI tasks? Also, I noticed that as opposed to LAMMPS, where I have to manually specify how many nodes & tasks I want, in the new QUIP, the gap_fit uses as many tasks as the submission script has reserved. I think the default should be 1 node 1 task unless manually specified otherwise by some flags?

**Comment by albapa** [comment]
Are you linking an mpi-compiled QUIP to LAMMPS? I think QUIP is trying to tell you not to do that.

**Comment by VladCarare** [comment]
Yes, I'm linking the same QUIP that I used to generate the potential I want to run the dynamics with, and whose stdout header is pasted above.

> Are you linking an mpi-compiled QUIP to LAMMPS? I think QUIP is trying to tell you not to do that.

Ah, I see. Ok, I will try to compile a new QUIP, without MPI and check if it works.

**Comment by albapa** [comment]
LAMMPS deals with everything MPI, so QUIP must run (and be compiled) in serial when called as a library.

**Comment by VladCarare** [comment]
It works with serial QUIP. Thanks!

I guess the issue can be closed?

**Comment by bernstei** [comment]
Any chance the potential file is in the wrong place, or named wrong?
