### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#43]
Python 2.6 has been end of life for three and a half years. I propose removing it from the testing and no longer making an effort to support it. Code can then use new features as and when needed.

All of the packages that quippy uses have moved on:
- pip now complains when using 2.6
- f90wrap minimum version is 2.7
- ase are drop support for 2.6
- numpy has dropped support for 2.6

Many features of 2.7 will make porting to Python 3 less painful.

The only place that one is likely to still see Python 2.6 as the default these days is in CentOS/RedHat 6 (which will apparently be supported until 2020!), but I suggest directing those users to Anaconda.

**Comment by jameskermode** [comment]
Agreed. miniConda is now easy enough to install in user's home directories on clusters that's there's little excuse for Python <= 2.7.
