### ISSUE TITLE
quippy.potential.Potential errors with ase-3.23.0b1

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/QUIP#432]
```
In [3]: gap = Potential(param_filename="files/tiny_gap.xml")
WARNING: Potential_initialise using default init_args "Potential xml_label=GAP_2021_4_27_60_15_30_41_87"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-31383b89174a> in <module>
----> 1 gap = Potential(param_filename="files/tiny_gap.xml")

/opt/womble/miniconda3/user_envs/eg475/wo/lib/python3.9/site-packages/quippy/potential.py in __init__(self, args_str, pot1, pot2, param_str, param_filename, atoms, calculation_always_required, calc_args, add_arrays, add_info, **kwargs)
    101         if atoms is not None:
    102             atoms.calc = self
--> 103         self.name = args_str
    104         if isinstance(calc_args, dict):
    105             calc_args = key_val_dict_to_str(calc_args)

AttributeError: can't set attribute
```
Removing `self.name = args_str` at line 103 fixes the problem, although that's without looking for the cause of this incompatibility or thinking about any consequences.

**Comment by jameskermode** [comment]
can you share the .xml file?

**Comment by gelzinyte** [comment]
[tiny_gap.xml.txt](https://github.com/libAtoms/QUIP/files/8706782/tiny_gap.xml.txt)

Just fyi it works fine with the ase version on which quippy-ase is dependent (I think ase-3.22.1), but I'm using some of ase-3.23.0b1.

**Comment by jameskermode** [comment]
That potential loads fine for me with ase-3.23.0b1 and quippy-are 0.9.8, but does indeed break with latest development version of ASE. Let's change quippy to store the args_str in a new `self.args_str` attribute rather than in `self.name`. Would you be willing to open a PR?
