### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#44]
Python 3 has been around for over 8 years now. Although 2.7 will be supported until at least 2020, there is a movement within the scientific stack to drop support well before then: http://www.python3statement.org. I think that `quippy` **needs** to be updated for Python 3 support as soon as possible.

I think the main steps will probably be:

- [ ]  Move to an external version of `f90wrap`. This already has Python 3 support, but I don't know how much it the version in QUIP has been customised, so it is probably not straightforward, or even the best solution.
- [ ]  Check the remaining code for compatibility. This will be tedious, but not difficult.

Last time I attempted to do something like this it ended up with a infinitely recursive dictionary, so I feel like it will need a bit more intimate knowledge of the inner workings than I currently have.

This could also be an opportunity to gut obsolete code or get some of the more general stuff moved to ase.

Any comments, or volunteers?

**Comment by jameskermode** [comment]
I absolutely agree in principal and this has been an ambition of mine for the last couple of years but I just haven't got around to it. `f90wrap` is indeed Python 3 compliant. The version used with QUIP predates the rewrite that led to `f90wrap` so there will no doubt be some pain along the way.

Volunteers certainly encouraged, or maybe we can schedule a hackathon in Cambridge for a day or two and get it done? First week in April could work for me, or early May.

**Comment by max-veit** [comment]
I'd definitely like to do a hackathon; dates are fairly flexible, although
not the third week of April (from the 16th).

And one place to start, and catch lots of errors, is to add the following
future imports to all modules:

```python
from __future__ import division, print_function, unicode, absolute_import
```
(roughly in order of importance). The unicode switch will cause the most
errors, so we could consider leaving it out for now. The rest, though, are
simple fixes that have no business being around even in 2.7 code.

Max

**Comment by max-veit** [comment]
Oh, and the unicode future import is actually `from __future__ import
unicode_literals`

**Comment by max-veit** [comment]
Also, #28 has been particularly irksome, especially with the unicode future import.

And since Markdown apparently isn't supported in email replies, here is the correct (and prettily formatted) list of future imports to consider:
```python
from __future__ import division, print_function, unicode_literals, absolute_import
```

**Comment by tdaff** [comment]
Agree that hackathon would be a good way to get over the hump. Early April or May work, but I am pretty much always free.

Python 2.6 has been removed from the testing now so the feel free to modernise any code that you happen to be editing with the `__future__` imports.

**Comment by jameskermode** [comment]
Here's a doodle poll based on dates I can make: http://doodle.com/poll/cst3t84a27fqws8b

Once core participants have signed up I'll send an email to quip-users too.

**Comment by max-veit** [comment]
The hackathon would also be a good time to look at static checking tools and test coverage, cf #29

**Comment by tdaff** [comment]
Newest Ubuntu release: https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes

> **Python 2** is no longer installed by default. Python 3 has been updated to 3.6.

**Comment by jameskermode** [comment]
Fair point. Contributions welcome to the hackathon-f90wrap branch... :-)

**Comment by alvarovm** [comment]
Hi, I wonder what is the status of Python 3 support. 
It is seems that quippy still is building with python2.7, despite that I am building with python 3 loaded in my environment.
After 'import quippy' I get an error like the follow:
/home/vama/soft/python-tests/quippylib/lib/python2.7/site-packages/quippy/_quippy.so: undefined symbol: PyCObject_Type 

Is there any known solution for this?

**Comment by jameskermode** [comment]
Quippy doesn’t work with Python 3 yet. This is a big job but I hope to get it sorted this summer.

**Comment by jameskermode** [comment]
Closing :-)
