### ISSUE TITLE
Dataset availability - libatoms unavailable

### ISSUE THREAD

**Issue by rubber-duck-debug** [libAtoms/QUIP#443]
I'm looking for the graphene and tungsten datasets previously available at,

http://www.libatoms.org/

however this link seems to be dead. Have these datasets been moved somewhere?

Sorry for posting the issue here, not sure where else to make it!

**Comment by jameskermode** [comment]
Yes, unfortunately that webpage is defunct. The data for some other GAP models are available here: https://libatoms.github.io/GAP/data.html

@gabor1 or @albapa might be willing to add the tungsten data there. The database for the GAP-20 is available here: https://www.repository.cam.ac.uk/handle/1810/307452 - this could also be uploaded or linked to the page above.

**Comment by jameskermode** [comment]
(Alternatively, a PR to update this file would be welcome: https://github.com/libAtoms/GAP/blob/main/doc_src/data.rst)
