### ISSUE TITLE
quip crashes while ase.calc does not when evaluating with gap pot - good_to_know/feature_req

### ISSUE THREAD

**Issue by efako** [libAtoms/QUIP#444]
(installed via pip, https://github.com/libAtoms/QUIP,704e49f-dirty)

Eg.
If one asks for an O-O pair potential in training but there are no O-O configurations within cutoff in the training set, training appears to terminate successfully. When trying to evaluate the potential (`gap.xml`):

- `quip E=T F=T V=T atoms_filename=test.xyz param_filename=./gap.xml` **crashes**.
- running `atoms.calc =  Potential(param_filename=./gap.xml, calc_args='local_gap_variance')` **crashes**.
- running `atoms.calc =  Potential(param_filename=./gap.xml)` returns E/F/V. **Does not crash**.

In the instances where there is a crash the following warning appears:
`** On entry to DPOTRF parameter number  4 had an illegal value`

To generate a working, configurations that contain all species pairs within cutoff must be present (eg. for an InOx potential: O-O, In-In, In-O)

Does it make sense to implement a warning in the cases when the gap_fit is missing the pair interactions in the training data?

**Comment by albapa** [comment]
The output of `gap_fit` already prints out the number of descriptors found, but 0 does not trigger an extra warning. In principle, such a potential should work, but in this case setting up the variance estimation workflow trips it - unnecessarily, as it won't be executed.

Could you please post a MRE  of a `gap.xml` and a `test.xyz` combination that shows this behaviour? I'll then be able to fix the behaviour.

**Comment by efako** [comment]
Sure!
Here is an example: 
- `./pot/train.xyz` (~120 In conf, 1 isolated O conf)
- `./pot/gap.xml` trained on ./pot/train.xyz
- `./run.py` calc ase calc
- `./quip_command.txt` calls quip
- `./test.xyz` only In conf.

[pip_version_test.zip](https://github.com/libAtoms/QUIP/files/8806816/pip_version_test.zip)

Many thanks!

**Comment by albapa** [comment]
~This [pull request](https://github.com/libAtoms/GAP/pull/46) aims to fix the problem. If you're comfortable with installing from source, you may try replacing `src/GAP` with this preview and confirm if it fixes the crashes.~

If you're comfortable with installing from source, a fresh clone from the [repo](https://github.com/libAtoms/QUIP) should fix the problem.
