### ISSUE TITLE
Evaluation of GAP variance on Fe-H system

### ISSUE THREAD

**Issue by vshah3011** [libAtoms/QUIP#447]
Dear all,

I am trying to evaluate the GAP variance for a Fe-H system with a single frame. I get an error related to invalid entry to DPOTRF.
The complete error is as follow:

------------------------------------
** On entry to DPOTRF parameter number  4 had an illegal value
SYSTEM ABORT: Traceback (most recent call last)
File "/home/zhanglei1/software/QUIP/src/libAtoms/linearalgebra.f95", line 2348 kind unspecified
LA_Matrix_Factorise: cannot factorise, error: -4
STOP 1
---------------------------------------

Can anyone assist with this?

**Comment by albapa** [comment]
That seems somewhat similar to https://github.com/libAtoms/QUIP/issues/444 where the issue has been fixed.

Do you have an up to date QUIP installation? If yes and you're still getting this problem, please post a minimal reproducible example and I'll happy to look at it.

**Comment by vshah3011** [comment]
@albapa Thank you prompt response. Let me check and get back to you.
Regards,
Varun

**Comment by vshah3011** [comment]
@albapa Updating the QUIP installation solved the issue. Thank you for the tip.

**Comment by DGKang234** [comment]
I have downloaded QUIP again using `git clone --recursive https://github.com/libAtoms/QUIP.git` and recompiled it.
However, I still get the error '** On entry to DPOTRF parameter number 4 had an illegal value'.
