### ISSUE TITLE
xyz reader fails when .idx file exists but is unreadable

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#45]
I'm reading an xyz from another user's directory, where I have read but not write permissions.  Mostly the xyz reader handles that OK, creating .idx files in my current directory, but in one case there's already an idx file in the same directory as the xyz file, but I have read permission only for the xyz.  This fails with an error 
`        Index file /home_cluster1/ksalerno/repo/protein/single-ubq/nve-ni8-nmce40960-nwalkers2304-at8-4/rundir/poly-ubq-ni8-nmce40960-nwalkers2304-at8-nve-lammps-n1.traj.0.extxyz.idx cannot be opened
`
There's probably a check for an existing idx file which should be replaced with a check for an existing and readable idx file.

**Comment by jameskermode** [comment]
You are right, I'll take a look at this ASAP.  If it's urgent, this is the [line of code](https://github.com/libAtoms/QUIP/blob/16bcba7632841760146988c1fcf946eb430d02ed/src/libAtoms/xyz.c#L183) that needs changing. (I don't remember enough about `stat()` to guess the flags for a readable file without looking it up!)

**Comment by jameskermode** [comment]
Should now be fixed - turns out I should have been using `access()` not `stat()`.

**Comment by jameskermode** [comment]
@noambernstein Can this issue be closed?

**Comment by gabor1** [comment]
@noambernstein , @jameskermode 
Come on guys, James wants to close this issue!

**Comment by noambernstein** [comment]
Oh, sorry, missed the original email. I'll check later today.

   Noam

**Comment by noambernstein** [comment]
Fixed, you can go ahead and close it.​
