### ISSUE TITLE
python3.10 support for quippy-ase

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/QUIP#455]
Python3.10 has been around for the bigger part of the year and it's the default version for new Conda environments. It would be very convenient to extend quippy-ase support to cover 3.10.

**Comment by jameskermode** [comment]
Yes, I agree we should do this. As a short term fix it should just be a matter of adding Python 3.10 to the build matrix, but currently the build is broken Mac OS X. See https://github.com/libAtoms/quippy-wheels/actions/ for the CI failure, if anyone who time to dig into this would be much appreciated. 

I'd like to move the wheel building into main QUIP repo, see this action for the WIP attempt at that: https://github.com/libAtoms/QUIP/blob/public/.github/workflows/build-wheels.yml.

**Comment by jameskermode** [comment]
Test Py 3.10 wheels now available at https://github.com/libAtoms/QUIP/suites/8284629208/artifacts/363084154

May also need f90wrap from https://github.com/jameskermode/f90wrap/suites/8284634058/artifacts/363044630

Please test and report back, then I'll go ahead and do a PyPI release.
