### ISSUE TITLE
ASE conversion OUTCAR to xyz errors

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#459]
Hello Developers,
I'm a new student starting out and, for practice, tried to convert various **single** element OUTCAR files with your recommended ASE script I saw here in another question:
from ase.io import read,write
atoms = read("OUTCAR")
atoms.info["virial"] = -atoms.get_volume() * atoms.get_stress(voigt=False)
write("atoms.xyz", atoms)
      I get the same type of error for every one:
" raise ParseError(
ase.io.ParseError: Expected length of ion_types to be same as species, but got ion_types=1 and species=6"
      Different OUTCAR files I had lying around give different species values, 2, 3, 6, etc. but I had only a single element in them.
  I am new to DFT also .
  Could this be a vasp version incompatibility?  OUTCAR format incompatibility? 
Thanks in advance.

**Comment by gabor1** [comment]
Try using the command line tool "ase convert" to see if that works. Can you post an example outcar file here?

**Comment by bernstei** [comment]
`ase convert` _should_ be identical.  An example OUTCAR is definitely needed to figure out what's going on.

**Comment by jameskermode** [comment]
agreed. If you are using an old version of VASP you might need to do `atoms = read("OUTCAR", vasp5=False)`

**Comment by MES-physics** [comment]
Example OUTCAR file:

[OUTCAR.pdf](https://github.com/libAtoms/QUIP/files/9471223/OUTCAR.pdf)

This was from some exercise in a course I took last year.

**Comment by bernstei** [comment]
We'd need a text version to be really useful, but I'm guessing that perhaps the ASE OUTCAR reader can't handle VASP6? We're switching to VASP6 here, so I'll be motivated to fix that if it's a problem.

**Comment by MES-physics** [comment]
Saved as text:  Does this work?
[OUTCAR.txt](https://github.com/libAtoms/QUIP/files/9471288/OUTCAR.txt)

**Comment by bernstei** [comment]
Works for me.  What ASE version are you using?
```
> python -c "import ase; print(ase.__version__); import ase.io; ase.io.read('OUTCAR')"
3.22.0
>
```
(also OK on some preliminary version of 3.23, which I'm using on another machine, so they didn't break it with an update, unless it's very recent)

**Comment by MES-physics** [comment]
ase-3.22.1

**Comment by bernstei** [comment]
Can you confirm that you get the error from the `ase.io.read` call, and see what happens with the `ase convert` CLI tool.

**Comment by MES-physics** [comment]
later this afternoon, thanks!

**Comment by bernstei** [comment]
Can you post the full stack trace, too, not just the final error message?

**Comment by MES-physics** [comment]
Now I think it's a python version problem, between 3.6 and 3.8.
See below when I put the commands in separately and call a different python each time.
3.6 works and makes a nice xyz file!  3.8 gives that error.  And it looks like the reading part is what goes awry.   On top of that, my python3 call in my script is really calling 3.8  instead of 3.6 as you can see.  (My python3 is 3.6,  python is 3.8, as it works with the separate commands.)
Then there is the (None or integer) exception.   I will try the ASE convert tool soon.

   Here is my script calling python3 :

#!/home/marie/miniconda3/bin/python3
from ase.io import read,write
atoms = read("OUTCAR")
atoms.info["virial"] = -atoms.get_volume() * atoms.get_stress(voigt=False)
write("atoms.xyz", atoms)

TRIALS:
Precision-7530:~/Desktop$ python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ase.io import read,write
>>> atoms = read("OUTCAR")
>>> atoms.info["virial"] = -atoms.get_volume() * atoms.get_stress(voigt=False)
>>> write("atoms.xyz", atoms)
>>> 
^^  (THIS gave a nice xyz file)

marie@marie-Precision-7530:~/Desktop$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ase.io import read,write
>>> atoms = read("OUTCAR")

Traceback (most recent call last):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 250, in _getslice
    iterator = islice(self.ichunks(fd),
ValueError: Indices for islice() must be None or an integer: 0 <= x <= sys.maxsize.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 682, in read
    return next(_iread(filename, slice(index, None), format, io,
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/parallel.py", line 273, in new_generator
    for result in generator(*args, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 749, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 505, in wrap_read_function
    for atoms in read(filename, index, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/utils/__init__.py", line 455, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp.py", line 266, in read_vasp_out
    return list(g)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 245, in __call__
    for chunk in self._getslice(fd, index):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 262, in _getslice
    for chunk in self.ichunks(fd):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 679, in outcarchunks
    header = header_parser.build(lines)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 609, in build
    symbols = self._build_symbols(results)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 582, in _build_symbols
    raise ParseError(
ase.io.ParseError: Expected length of ion_types to be same as species, but got ion_types=1 and species=3
>>> 
   ^^  (This python 3.8 gave the error)

And using a script, calling my python3 which is 3.6, is also an error, because somehow it is really calling python 3.8  :

Precision-7530:~/Desktop$ ./ASEconvert.sh
Traceback (most recent call last):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 250, in _getslice
    iterator = islice(self.ichunks(fd),
ValueError: Indices for islice() must be None or an integer: 0 <= x <= sys.maxsize.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ASEconvert.sh", line 3, in <module>
    atoms = read("OUTCAR")
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 682, in read
    return next(_iread(filename, slice(index, None), format, io,
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/parallel.py", line 273, in new_generator
    for result in generator(*args, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 749, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/formats.py", line 505, in wrap_read_function
    for atoms in read(filename, index, **kwargs):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/utils/__init__.py", line 455, in iofunc
    obj = func(fd, *args, **kwargs)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp.py", line 266, in read_vasp_out
    return list(g)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 245, in __call__
    for chunk in self._getslice(fd, index):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/utils.py", line 262, in _getslice
    for chunk in self.ichunks(fd):
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 679, in outcarchunks
    header = header_parser.build(lines)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 609, in build
    symbols = self._build_symbols(results)
  File "/home/marie/miniconda3/lib/python3.8/site-packages/ase/io/vasp_parsers/vasp_outcar_parsers.py", line 582, in _build_symbols
    raise ParseError(
ase.io.ParseError: Expected length of ion_types to be same as species, but got ion_types=1 and species=3

**Comment by bernstei** [comment]
Are they both using the same ASE version?  My tests were with python 3.8, and various people use various other versions, so it's unlikely to be inherent to the python version.  But default installations of ASE (via pip or setup.py) would end up being separate for each python version, so that could be the real difference.

**Comment by bernstei** [comment]
Note that your script is explicitly asking for `/home/marie/miniconda3/bin/python3`, which may or may not be the version that's in your `PATH` when you just run `python3`. You can do `which python3` to tell where your python 3.6 comes from. Could be the system python.

**Comment by bernstei** [comment]
Ignore the previous question about a POTCAR file.  Can you post the output of `fgrep POTCAR OUTCAR` here?  That's where "species" is coming from, from what I can tell, and I have no idea how it's getting 3, which your error message indicates, from the OUTCAR.txt you uploaded.

**Comment by MES-physics** [comment]
Oh my yes, I should have thought of checking the path for python....
No POTCAR in the directory I'm working in for this practice.
I checked and believe I have only one ASE package, that came with intalling QUIP/GAP I think.  Unless another one was in there long ago.

**Comment by bernstei** [comment]
Can you post the output of `python -c "import ase; print(ase.__version__, ase.__file__)"` substituting the full path to the two different python versions?

**Comment by MES-physics** [comment]
How to subsitute?  Instead of everything about ase in those parentheses?

When I say which python, I get usr/bin/python.   When I say which python3, I get usr/bin/python3.
When I did this without substituting:
~$ python -c "import ase; print(ase.__version__, ase.__file__)"
3.21.1 /home/marie/miniconda3/lib/python3.8/site-packages/ase/__init__.py

**Comment by MES-physics** [comment]
Precision-7530:~/Desktop$ fgrep POTCAR OUTCAR
 POTCAR:   PAW_GGA Al 05Jan2001                   
 POTCAR:   PAW_GGA Al 05Jan2001

**Comment by bernstei** [comment]
I suspect that the fundamental problem is that miniconda appears to have ASE 3.21.1. All of the successful tests have been on 3.22 or newer, so it could easily be that this ASE version is broken.  Before trying to update it, you should also figure out what's going on with your path.  What the output of 
```
which python
python --version
which python3
python3 --version
/home/marie/miniconda3/bin/python3 --version
```

I _hate_ conda, so I'm not sure exactly what to suggest, but my normal step would be to do `<python> -m pip install --upgrade`, but replace `<python>` with the executable that I plan to put on the `#!` line of my scripts. If you want the script to use the version that runs when you just run `python3`, you can use the following line
```
#!/usr/bin/env python3
```
instead of specifying a particular path for your script.

**Comment by MES-physics** [comment]
Thank you so much Sir! I can go forward now.

**Comment by bernstei** [comment]
By the way, we also use the conda python (because a few packages are really hard to install without conda), but as much as possible I add python packages with `pip`, not conda. As a normal user I just do "python3 -m pip install --user name_of_package", which puts it in `~/.local/lib/....`. You have to add `~/.local/bin` to your path, but otherwise it's pretty smooth.
