### ISSUE TITLE
Difference in XYZ files by ase convert vs. using script

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#461]
Dear Developers,
   OK, I made changes and went with pointing to my python 3.6 path.
Using that same outcar file I posted before,
I'm getting a difference in the xyz file outputs using the script versus the ase convert command.  The ase convert command prints all of the configurations found.  But I now notice that the script prints only one configuration.  
(  I also reinstalled ase. Then it shows :  
~/Desktop$ which ase
/home/marie/.local/bin/ase   (This is in my PATH too)  )

Is there something I'm supposed to add to the script to capture more configurations?
If I use the ase convert command, the stresses will be the wrong sign, yes?

Thanks very much.
Script:  
 #!/usr/bin/env python3.6
from ase.io import read,write
atoms = read("OUTCAR")
atoms.info["virial"] = -atoms.get_volume() * atoms.get_stress(voigt=False)
write("atoms.xyz", atoms)

**Comment by noambernstein** [comment]
You need `read(filename, “:”)` to read all the configs.
