### ISSUE TITLE
TurboGAP installation question

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#463]
Dear Sirs,
 I originally installed QUIP/GAP capability with LAMMPS.
I later installed TurboGAP but mistakenly not connected to them.
Is there a way "to provide QUIP with the TurboGAP root directory" 
now, without starting all over again?
Thanks.

**Comment by mcaroba** [comment]
With the current version of QUIP/GAP you do not need a separate TurboGAP installation to be able to use `soap_turbo` descriptors. They are now part of the GAP repository (they have been for a while). You just need to use the `--recursive` flag when you `git clone` QUIP, and you'll get everything you need. If you installed QUIP recently it's entirely possible you already have support for `soap_turbo` descriptors in your installation.

Are you trying to run something specific and is that failing?

**Comment by MES-physics** [comment]
Great, thanks!
Yes I did install with --recursive. 
Nothing specific yet, just getting things together.
Now I need to follow a tutorial on how to do an MD simulation with turboGAP.   Your page on /Simple_molecular_dynamics is still good to follow?

**Comment by mcaroba** [comment]
TurboGAP is an alternative MD engine to LAMMPS. You need QUIP/GAP to fit a potential and then that potential can be run with QUIP or LAMMPS (if you installed LAMMPS with the QUIP plugin). Some of these potentials can be run with TurboGAP, if you chose compatible descriptors during the fit, but they are not generally compatible. I am going to close this. If you have TurboGAP-specific questions please ask them in the TurboGAP github issue tracker. (and yes, the tutorials are ok but the quick start page needs an update)
