### ISSUE TITLE
Different cutoff_skin defaults in quip and quippy

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#47]
I've come across a bug that only came up when I was running with quip md (the Fortran `md` program) but not when running with `quippy.DynamicalSystem` - turns out, the two methods have a different default cutoff_skin (0.0 Å in quippy, 0.5 Å in quip). I'm still working on reproducing the (fairly spectacular) bug caused by the quip cutoff skin, but in the meantime:

I think it would be a good idea to unify defaults (and maybe trickier things, like available thermostats and minimization methods) across quippy and quip, if only for the sake of reproducibility when moving from one system to the other. My expectation was that I could translate the parameters from a quip md script, put them into the python system, and have the exact same simulation. But because of the discrepancy in the defaults, that expectation was (in this case, jarringly) violated.

**Comment by gabor1** [comment]
The fortran and python classes initialise the skin to zero. if you initialise your own dynamical systems object in python, set the cutoff skin to what you want, just like the md program does
