### ISSUE TITLE
QUIP/ GAP install question

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#471]
Hello again Sirs,
I am tryng to reinstall QUIP with GAP,( it seems my other version was labelled "dirty" . I don't know what that means, but a gap_fit command was not working.)
   When QUIP is installed, the GAP directory is empty and GAP fails.
Before posting all errors, can someone please tell me the correct sequence of actions,
Install GAP first?   Then what ? Move GAP files into /QUIP/src/GAP ?  I tried that, didn't work (output below).   Is there a different install command that gets GAP into QUIP?
Thanks for any advice.

 I am folllowing these instructions:
$ git clone https://github.com/libAtoms/QUIP.git QUIP
$ cd QUIP
$ export QUIP_DIR=/path/to/QUIP
$ export QUIP_ARCH=linux_x86_64_gfortran
$ make config
$ make libquip

Here's the end of the $make libquip feedback:
make[1]: Leaving directory '/home/marie/QUIP/build/linux_x86_64_gfortran'
rm /home/marie/QUIP/build/linux_x86_64_gfortran/Makefile
********************************************

 Making GAP 

********************************************
rm -f /home/marie/QUIP/build/linux_x86_64_gfortran/Makefile
cp /home/marie/QUIP/src/GAP/Makefile /home/marie/QUIP/build/linux_x86_64_gfortran/Makefile
make -C /home/marie/QUIP/build/linux_x86_64_gfortran QUIP_ROOT=/home/marie/QUIP VPATH=/home/marie/QUIP/src/GAP -I/home/marie/QUIP -I/home/marie/QUIP/arch
make[1]: Entering directory '/home/marie/QUIP/build/linux_x86_64_gfortran'
make[1]: *** No rule to make target 'soap_turbo_functions.o', needed by 'libgap.a'.  Stop.
make[1]: Leaving directory '/home/marie/QUIP/build/linux_x86_64_gfortran'
Makefile:148: recipe for target 'GAP' failed
make: *** [GAP] Error 2

**Comment by bernstei** [comment]
`git clone --recurse https://github.com/libAtoms/QUIP.git QUIP` should get everything, assuming a sufficiently new version of git, I guess.

**Comment by MES-physics** [comment]
oh the recurse!   Thanks
