### ISSUE TITLE
System abort error

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#472]
Sorry to bother you again,
I reinstalled and recompiled everything, and tried a test input.  Thanks for feedback!
I made sure there were no spaces after the backslashes for bash syntax.  The backslashes
don't show up in this preview here.

$ ./gap_fitBASH.sh
libAtoms::Hello World: 2022-09-15 20:01:37
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,v0.9.10-rc7-4-g4111ab3ea-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Sep 15 2022 at 17:44:52
libAtoms::Hello World: Random Seed = 72097051
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

SYSTEM ABORT: Traceback (most recent call last)
File "/home/marie/QUIP/src/libAtoms/System.f95", line 1468 kind unspecified
string_to_real: could not convert, iostat=5010            
STOP 1

My Bash file:
#!/bin/bash
#gap_fit command bash file .  Change as needed for new runs and atoms,
#in a new folder.

gap_fit atoms_filename=Test.xyz at_file=Test.xyz \
gap = {distance_Nb order=2 cutoff=5.0 n_sparse=15 covariance_type=ard_se \
delta=2.0 theta_uniform=2.5 sparse_method=uniform compact_clusters=T : \
distance_Nb order=3 cutoff=2.0 n_sparse=15 covariance_type=ard_se \
delta=2.0 theta_uniform=2.5 sparse_method=uniform compact clusters=T : \
soap l_max=6 n_max=12 atom_sigma=0.5 cutoff=5.0 radial_scaling=0.5 \
cutoff_transition_width=1.0 central_weight=1.0 n_sparse=8000 delta=0.2 \
f0=0.0 covariance_type=dot_product zeta=4 sparse_method=cur_points} \
default_sigma={0.002 0.2 0.2 0.0} \
default_kernel_regularisation={0.002 0.2 0.2 0.0}\
sparse_jitter=1.0e-8 \
energy_parameter_name=energy force_parameter_name=forces \
virial_parameter_name=virial stress_parameter_name=stress \
do_copy_at_file=F sparse_separate_file=T \
gp_file=gap.xml \

**Comment by gabor1** [comment]
Post your xyz file. One of your numbers couldn't be interpreted!

**Comment by MES-physics** [comment]
Here it is:
[Test.xyz.txt](https://github.com/libAtoms/QUIP/files/9585087/Test.xyz.txt)

**Comment by MES-physics** [comment]
Further info:  This same error happens when I input an xyz file from the published Fe database, such as the DB1.xyz, Db2.xyz.

**Comment by albapa** [comment]
Descriptor definitions are generated automatically based on system composition, but if there are no actual descriptors in the database, the code returns an error. You can see the number of descriptors found for each definition in the output file. For example: if the definition includes H-H pairs, but if configurations only contains single H atoms, there will be no H-H pair descriptors found. In such cases you either need to add appropriate configurations, or define your descriptors manually.

**Comment by MES-physics** [comment]
I don't understand this.   In a previous version of the software I was able to test some of the various published xyz files for the Fe database, and it made a gap.xml.
Now the same xyz input files do not work.    Please tell me in my file(s) above what is wrong with it?  Are you saying that I cannot put distance-Nb descriptors in the gap command ? 
 I'm a beginner student.

**Comment by MES-physics** [comment]
OK I found my problem.  I didn't know the bash script file had to have all the gap_fit
attributes with their arguments on separate lines to be read by the software.
Now it works.
