### ISSUE TITLE
Error message: ** On entry to DPOTRF parameter number  4 had an illegal value

### ISSUE THREAD

**Issue by DGKang234** [libAtoms/QUIP#475]
To Whom It May Concern,

I am trying to train the GAP (2b) potential with 23 non-periodic (nanocluster) training structures (including individual atom data).
During the training process, I get an error message which is the same as the title of the ticket. I downloaded the QUIP from GitHub and compiled it which was advised in other tickets. However, I still get the error.

When I try with a larger data set it works fine. Would the error occur because of the size of the data set?
If so, is there a minimum number of data to train the GAP?

Could you please help me with the error?
Thanking you for your time.

------------------------------------------------------------------------------------------------------

libAtoms::Hello World: 2022-09-16 16:47:39
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,d5a6af313-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran
libAtoms::Hello World: compiled on  Aug 30 2022 at 12:07:49
libAtoms::Hello World: Random Seed = 60459380
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

================================ Input parameters ==============================

config_file =
atoms_filename = //MANDATORY//
at_file = GAP_1-1_10_1-1_n_3.0_100/FIT/Training_set.xyz
gap = "distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100"
e0 = 0.0
local_property0 = 0.0
e0_offset = 0.0
e0_method = isolated
default_kernel_regularisation = //MANDATORY//
default_sigma = "0.008 0.04 0 0"
default_kernel_regularisation_local_property = 0.001
default_local_property_sigma = 0.001
sparse_jitter = 1.0e-10
hessian_displacement = 1.0e-2
hessian_delta = 1.0e-2
baseline_param_filename = quip_params.xml
core_param_file = quip_params.xml
baseline_ip_args =
core_ip_args =
energy_parameter_name = energy
local_property_parameter_name = local_property
force_parameter_name = forces
virial_parameter_name = virial
stress_parameter_name = stress
hessian_parameter_name = hessian
config_type_parameter_name = config_type
kernel_regularisation_parameter_name = sigma
sigma_parameter_name = sigma
force_mask_parameter_name = force_mask
parameter_name_prefix =
config_type_kernel_regularisation =
config_type_sigma =
kernel_regularisation_is_per_atom = T
sigma_per_atom = T
do_copy_atoms_file = T
do_copy_at_file = F
sparse_separate_file = T
sparse_use_actual_gpcov = F
gap_file = gap_new.xml
gp_file = GAP_1-1_10_1-1_n_3.0_100/FIT/GAP.xml
verbosity = NORMAL
rnd_seed = -1
openmp_chunk_size = 1000
do_ip_timing = F
template_file = template.xyz
sparsify_only_no_fit = F
dryrun = F
condition_number_norm =
linear_system_dump_file =
mpi_blocksize_rows = 0
mpi_blocksize_cols = 100
mpi_print_all = F

========================================  ======================================

============== Gaussian Approximation Potentials - Database fitting ============

Initial parsing of command line arguments finished.
Found 1 GAPs.
Descriptors have been parsed
XYZ file read
Old GAP: {distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100}
New GAP: {distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=13}
New GAP: {distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=9}
New GAP: {distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=9 Z2=9}
Multispecies support added where requested

===================== Report on number of descriptors found ====================

---------------------------------------------------------------------
Descriptor 1: distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=13
Number of descriptors:                        0
Number of partial derivatives of descriptors: 0
---------------------------------------------------------------------
Descriptor 2: distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=9
Number of descriptors:                        0
Number of partial derivatives of descriptors: 0
---------------------------------------------------------------------
Descriptor 3: distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=9 Z2=9
Number of descriptors:                        0
Number of partial derivatives of descriptors: 0

========================================  ======================================

========================= Memory Estimate (per process) ========================

Descriptors
Descriptor 1 :: x 1 0 memory 0  B
Descriptor 1 :: xPrime 1 0 memory 0  B
Descriptor 2 :: x 1 0 memory 0  B
Descriptor 2 :: xPrime 1 0 memory 0  B
Descriptor 3 :: x 1 0 memory 0  B
Descriptor 3 :: xPrime 1 0 memory 0  B
Subtotal 0  B

Covariances
yY 300 281 memory 674 KB * 2
yy 300 300 memory 720 KB
A 300 581 memory 1394 KB * 2
Subtotal 4857 KB

Peak1 674 KB
Peak2 4857 KB
PEAK  4857 KB

Free system memory  68 GB
Total system memory 134 GB

========================================  ======================================

E0/atom =   0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000  0.00000000000000000E+000

========== Report on number of target properties found in training XYZ: ========

Number of target energies (property name: energy) found: 23
Number of target local_properties (property name: local_property) found: 0
Number of target forces (property name: forces) found: 258
Number of target virials (property name: virial) found: 0
Number of target Hessian eigenvalues (property name: hessian) found: 0

================================= End of report ================================

===== Report on per-configuration/per-atom sigma (error parameter) settings ====

Number of per-configuration setting of energy_sigma found:     0
Number of per-configuration setting of force_sigma found:      0
Number of per-configuration setting of virial_sigma found:     0
Number of per-configuration setting of hessian_sigma found:    0
Number of per-configuration setting of local_propery_sigma found:0
Number of per-atom setting of force_atom_sigma found:          0
Number of per-component setting of force_component_sigma found:          0
Number of per-component setting of virial_component_sigma found:          0

================================= End of report ================================

WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (100), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=13
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (100), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=13 Z2=9
WARNING: gpCoordinates_sparsify: number of data points (0) less than the number of sparse points (100), number of sparse points changed to 0
WARNING: gpCoordinates_sparsify: affected descriptor : distance_2b cutoff=3.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform n_sparse=100 Z1=9 Z2=9
Cartesian coordinates transformed to descriptors
Started sparse covariance matrix calculation of coordinate 1

Finished sparse covariance matrix calculation of coordinate 1
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1_sparse  done in .11999999999998123E-004 cpu secs, .11955853551626205E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate1         done in .32999999999998308E-004 cpu secs, .32464973628520966E-004 wall clock secs.
Started sparse covariance matrix calculation of coordinate 2

Finished sparse covariance matrix calculation of coordinate 2
TIMER: gpFull_covarianceMatrix_sparse_Coordinate2_sparse  done in .10000000000003062E-004 cpu secs, .10170973837375641E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate2         done in .23999999999996247E-004 cpu secs, .24099834263324738E-004 wall clock secs.
Started sparse covariance matrix calculation of coordinate 3

Finished sparse covariance matrix calculation of coordinate 3
TIMER: gpFull_covarianceMatrix_sparse_Coordinate3_sparse  done in .11000000000004062E-004 cpu secs, .10245013982057571E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate3         done in .24000000000003185E-004 cpu secs, .24851877242326736E-004 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse_FunctionValues      done in .19999999999950613E-005 cpu secs, .11702068150043488E-005 wall clock secs.
TIMER: gpFull_covarianceMatrix_sparse                     done in .13400000000000217E-003 cpu secs, .13318331912159920E-003 wall clock secs.
 **** On entry to DPOTRF parameter number  4 had an illegal value
SYSTEM ABORT: Traceback (most recent call last)
File "/home/uccatka/software/QUIP/src/libAtoms/linearalgebra.f95", line 2348 kind unspecified
LA_Matrix_Factorise: cannot factorise, error: -4
Note: The following floating-point exceptions are signalling: IEEE_OVERFLOW_FLAG
STOP 1**

  The GAP fitting has finished

**Comment by Sideboard** [comment]
The problems seems to be that the descriptors are not created from the data: `Number of descriptors: 0`

Can you share your structures?

**Comment by DGKang234** [comment]
@Sideboard 
Here is the training set file (ext is in txt for uploading)
[Training_set.xyz.txt](https://github.com/libAtoms/QUIP/files/9585613/Training_set.xyz.txt)

**Comment by Sideboard** [comment]
The problem is that gap_fit does not find any neighbours for the atoms.

**Comment by Sideboard** [comment]
I tried to trace the error back through the atoms and connections modules but it hangs when I try to print in that routine (`n_neighbour_*`). Will have to get back to it another time.

Maybe the atoms are too far from each other wrt. to explicit or implicit threshold?

**Comment by DGKang234** [comment]
@Sideboard 
Ah, that was a silly mistake. I have fed the wrong type of data because of the wrong training data with the cut-off parameter the program cannot detect the nearest neighbors.
Thank you for pointing out the mistake.
I will be more careful before asking a question.
