### ISSUE TITLE
Different forces in lammps and ase using the same potential

### ISSUE THREAD

**Issue by DjordjeDangic** [libAtoms/QUIP#476]
Dear all,

The potential I fitted gives different forces when called from lammps and ASE. Has anyone else encountered this problem before and do you know how to resolve it? There was one similar previous issue but there I think the difference was at the order of 10^{-10}, while in this case, it is around 10^{-3}.

 I prepared the input files and you can download them from the following link if you want to replicate the issue: https://1drv.ms/f/s!ALMGUtQV1n5bg1Q . in.si is the input file that will generate data.atom which contains the forces on the trajectory. Finally, you can use compare_datasets.py to check the differences between lammps and ASE forces. I attached data.atom for a very short trajectory.

**Comment by albapa** [comment]
The digits in your input file are truncated. Compare `data.si` and `data.atom`. The `z` coordinate of the first atom is `7.606479` vs. `7.60648` etc.

Please try again with full double precision input to ASE and let us know if you still find significant discrepancies.

**Comment by DjordjeDangic** [comment]
True. Increasing precision in the output decreased the difference between lammps and ase evaluation of force. Thank you!
