### ISSUE TITLE
Program stops on "number of target properties"

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#477]
Dear Sirs,
What would be the most likely reason the program would stop at the line below?
I'm trying to run this on a cluster, one node of 48 cpu cores. There is no error output.
Thanks

E0/atom = .................
0.00000000000000000E+000  0.000000000000000
00E+000  0.00000000000000000E+000

========== Report on number of target properties found in training XYZ: ========

**Comment by MES-physics** [comment]
Additional info:  My command line works on my laptop for a smaller subset of data.
The system does not abort off the node, the node keeps running.

**Comment by Sideboard** [comment]
This is for gap_fit, right? Which version are you using (commit id), is it the most recent one? Which compiler do you use on the cluster? Can you provide the input data and command line?

**Comment by MES-physics** [comment]
Yes gap_fit, but I narrowed the problem further, my command script works fine when using a node interactively, but not when submitting thru a slurm script.  I think slurm is not loading the openblas module on the node, as I can do interactively.
Has anyone had this problem with loading openblas on a cluster?

**Comment by MES-physics** [comment]
I found out the program was still working on the node, but was not printing out the steps on the screen.  I needed to set $export PYTHONUNBUFFERED=TRUE
to clear out the buffer, my admin told me.  Nothing to do with GAP.
