### ISSUE TITLE
Atoms neighbour functions behave unexpectedly with max_dist parameter

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#48]
I'm using the neighbour functions to only return neighbours within a certain distance using the `max_dist` parameter of `Connection::(n_)neighbour(s)`. If the effective cutoff (including cutoff_skin) is greater than that distance, instead of getting only the neighbours within that distance, I occasionally also get zero indices and (much worse) missing neighbours. I'm using the following, completely logical paradigm, which is what the documentation would seem to suggest:

```python
n = at.n_neighbours(idx, max_dist=d)
for i in range(n):
    print(at.neighbour(idx, i+1, max_dist=d)
```

Since the internal neighbour list is apparently not sorted by distance -  at least, that's what I'm inferring, since the above loop seems to return them in no particular order - this means that the above iteration over a subset of the neighbours can actually miss some neighbours that were, in fact, within the range `max_dist`.

**To reproduce**, use the following code:
```python
#vim set encoding=utf-8
"""Reproduce the quippy neighbour inconsistency with max_dist"""

from quippy import Atoms, Potential

at = Atoms('methane-box.xyz')
at.set_cutoff(1.5, 0.5)

pot = Potential('IP LJ', param_filename='lj_bogus.xml')

pot.calc(at, energy=True, force=True)

idx_test = 296
print("Number of neighbours of atom {:d} is {:d}".format(
      idx_test, at.n_neighbours(idx_test)))
print("Neighbours of atom {:d} are: ".format(idx_test) +
      ', '.join(str(at.neighbour(idx_test, i+1))
                for i in range(at.n_neighbours(idx_test))))

print("---- Now with max_dist ----")

print("Number of neighbours of atom {:d} _within 1.5 Å_ is {:d}".format(
      idx_test, at.n_neighbours(idx_test, max_dist=1.5)))
print("Neighbours of atom {:d} _within 1.5 Å_ are: ".format(idx_test) +
      ', '.join(str(at.neighbour(idx_test, i+1, max_dist=1.5))
                for i in range(at.n_neighbours(idx_test, max_dist=1.5))))
```
with the geometry
[methane-box.xyz](https://github.com/libAtoms/QUIP/files/774073/methane-box.xyz.txt) (be sure to remove the `.txt` extension).

The potential itself isn't important as long as it has a cutoff of 1.5 Å - try the following bogus LJ parameters, saved into `lj_bogus.xml`:
```xml
<!-- Some made-up params to vaguely keep a methane molecule together -->
<!-- DO NOT USE for any sort of production simulation! -->
<LJCONF>
    <Potential label="ljconf" init_args="IP LJ"/>
    <LJ_params n_types="2" only_inter_resid="T" label="ljconf-lj">
    <per_type_data type="1" atomic_num="1" />
    <per_type_data type="2" atomic_num="6" />
    <per_pair_data type1="1" type2="2" sigma="0.971" eps6="5.0" eps12="5.0" cutoff="1.5" energy_shift="T" linear_force_shift="T" />
    </LJ_params>
</LJCONF>
```

**Comment by max-veit** [comment]
I think the solution could be as simple as a documentation update, and maybe eliminating or changing the name of the `max_dist` parameter to `Connection::n_neighbours`. It's easy enough to just iterate through all neighbours, then only use the `max_dist` parameter in `Connection::neighbour` (to avoid calculating unnecessary quantities), of course checking for zero indices.

**Comment by gabor1** [comment]
The neighbours are not stored in any order, and it would be inefficient to do so, as any atom can acquire a neighbour at any time, and we don't want to resort. 

I think the "solution" is to make this clear in the doc. you should not get the number of neighborus within some max_dist, but loop through ALL neighbours, and when you get them, check for the distance. 

I'm not sure the max_dist parameter of atoms.neighbour() thus makes sense. 

-- Gábor

**Comment by jameskermode** [comment]
I don't think there's a big problem - the [documentation](https://libatoms.github.io/QUIP/atoms.html#quippy.atoms.Atoms.neighbour) for `atoms_neighbour` already says:
"If distance > max_dist, return 0, and do not waste time calculating other quantities", so it doesn't make sense to write the loop over the reduced set of neighbours as you've done above. It should be something like:

```python
n = at.n_neighbours(idx)
for i in range(n):
    nj = at.neighbour(idx, i+1, max_dist=d)
    if nj == 0:
        continue
    # do something with neighbour (i, nj)
```

However, I agree that changing how `max_dist` is described in `atoms_n_neighbours()` might be a good idea: the main use of this function is to count the neighbours within `max_dist`, not to do anything further with them.

Moreover, given how slow loops like the above are in Python, plus the annoyance of zero-based to one-based indexing conversions, accessing QUIP neighbours from Python directly is often not that useful. matscipy has a fast [neighbourlist](http://libatoms.github.io/matscipy/matscipy.html#matscipy.neighbours.neighbour_list) that allows for more Pythonic access by returning vectors of atom indices, distances, etc.

**Comment by max-veit** [comment]
> I don't think there's a big problem - the documentation for atoms_neighbour already says:
> "If distance > max_dist, return 0, and do not waste time calculating other quantities", so it doesn't make sense to write the loop over the reduced set of neighbours as you've done above.

From the perspective of a (relatively) inexperienced QUIP user, it's still not clear that I was supposed to iterate over the whole neighbour list and just discard the ones that turn up zero (i.e. outside the cutoff). I'm probably going to add a little reminder in the documentation to explicitly warn against iterating over a "partial list" - it may be obvious to someone who knows how QUIP and other codes handle neighbour lists (and it was to me once I thought about it again), but not necessarily otherwise. Plus, in documentation as in code, explicit is better than implicit :smiley: 


> Moreover, given how slow loops like the above are in Python, plus the annoyance of zero-based to one-based indexing conversions, accessing QUIP neighbours from Python directly is often not that useful. matscipy has a fast neighbourlist that allows for more Pythonic access by returning vectors of atom indices, distances, etc.

I was doing this in Fortran and using quippy to illustrate, but I'll check that out.

**Comment by jameskermode** [comment]
Yup - more documentation is never a bad thing. I'll leave you to close this issue when you're happy.

**Comment by gabor1** [comment]
In this, you are absolutely right. there is no other way to discover these than for people to run into the problem, and the correct response is to improve the docs. I agree with you that the docs for the neighbour() function should have a very prominent statement that the neighbours are in no particular order, and setting the max_dist argument isn't going to change the list itself. 

another way to do what you want is to create an entirely new connection object with your max_dist as the cutoff, and then you can iterate over its list. 

what about the other problem that the skin is not consistent? have we dealt with that? 

-- Gábor

**Comment by max-veit** [comment]
> another way to do what you want is to create an entirely new connection object with your max_dist as the cutoff, and then you can iterate over its list. 

Hm, I've been seeing the `alt_connect` as more of an option to use e.g. hysteretic connection objects in tandem with the ordinary long-range connection list, but there's no reason that shouldn't work as well.

> what about the other problem that the skin is not consistent? have we dealt with that?

Not yet; #47 is still open.
