### ISSUE TITLE
Reasonable range of MBs for a .xyz file to train?

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#480]
Dear QUIP/GAP people,
What is the usual range of MBs in a .xyz file that is reasonable for training?  
That is, if one has 1 or 2 TBs on a cluster node available.
Thanks

**Comment by gabor1** [comment]
In MB I don't know but we regularly train databases with several hundred thousand atoms. Note that with MPI training you can use lots of memory on multiple nodes (or are you already doing that and that's what 1-2 TB refers to?)

**Comment by MES-physics** [comment]
Just one node , not MPI.

**Comment by gabor1** [comment]
So if you switch to multiple nodes you can significantly increase database sizes and reduce training times.

**Comment by MES-physics** [comment]
Thanks.  How do I find how many atoms are in my xyz files?

**Comment by jameskermode** [comment]
You could load it into ASE and sum the lengths of all the Atoms objects, with something like (not tested)

```python
from ase.io import read
dataset = read("file.xyz", index=":")
total_atoms = sum([len(atoms) for atoms in dataset])
```

or if you have only a single species eg Si then `grep -Ec ‘^Si' file.xyz` would suffice (this counts the number of lines starting with Si).

**Comment by gabor1** [comment]
If you have many elements, you can also `grep -c  'Lattice' file.xyz` which will count the number of structures, and subtract twice this number from the result of `wc file.xyz` to get the overall number of atoms.

**Comment by Sideboard** [comment]
You can also sum up the atom numbers at the start of each frame/configuration:
```grep '^[0-9]\+$' data.xyz | awk '{s+=$1} END {print s}'```

Number of frames accordingly:
```grep '^[0-9]\+$' data.xyz | wc -l```
