### ISSUE TITLE
Submodules missing from release tar-ball

### ISSUE THREAD

**Issue by oschuett** [libAtoms/QUIP#481]
First off, thanks a lot for making an official release!

Unfortunately, one can not build QUIP from the release [tar-ball](https://github.com/libAtoms/QUIP/archive/refs/tags/v0.9.10.tar.gz) because the submodules are missing. Perhaps you could create a complete archive, e.g. via [git-archive-all](https://pypi.org/project/git-archive-all/)?

**Comment by jameskermode** [comment]
Thanks for reporting. Releases are intended primarily for the binaries deployed to PyPI, the tar balls are actually just put there automatically by GitHub. I’ll look into whether it’s possible to customise how the tarball is built to include submodules.

**Comment by oschuett** [comment]
Thanks! We're building QUIP as part of the [CP2K toolchain](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage6/install_quip.sh). In the past we've always created our own tar-balls, but I'd much rather use an official one.

**Comment by jameskermode** [comment]
I've added a [tarball](https://github.com/libAtoms/QUIP/releases/download/v0.9.10/QUIP-v0.9.10.tar.gz) manually to the [v0.9.10 ](https://github.com/libAtoms/QUIP/releases/tag/v0.9.10) release and added to the build-wheels workflow to do this automatically in future. Reopen this issue if there are any further problems.

**Comment by albapa** [comment]
It's great that you're including QUIP in the CP2K toolchain, thanks! I just wanted to point out that the reason for submodules are the different licensing arrangements of QUIP, GAP and soap_turbo (as well as other bits, such as f90wrap and FoX). Bundling them all together is fine and the license agreements are all included in the appropriate places, but some top-level document pointing out that could be useful.

**Comment by oschuett** [comment]
Oh that's an important point. We actually made the [decision](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/README.md#licenses) to only install GPL-compatible software via the toolchain because it also builds our public [Docker images](https://hub.docker.com/r/cp2k/cp2k).

Since libatom is GPL I presume you are excluding GAP from those PyPI binaries? Maybe you could publish a corresponding GPL-compatible tar-ball?

**Comment by jameskermode** [comment]
GAP is in the PyPI binaries, and the dual licence is pointed out in the PyPI metadata. 

QUIP is no longer much used without the GAP plugin so I can’t really see the point in us distributing a separate tarball.

**Comment by oschuett** [comment]
Ok, fair point. Then I'll adopt our toolchain script to remove the GAP folder on our side. In any case, thanks again for the tarball!

**Comment by oschuett** [comment]
I have decided not to use the complete tarball to stay clear of the licensing conflict.
Nevertheless, thanks a lot for your quick response and help!
