### ISSUE TITLE
MPI version won't take gap_fit

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#487]
Dear GAP people,
  After I installed QUIP/GAP as the MPI version, and now tried to run it,
I got this slurm error saying gap_fit is illegal.  What could possibly be the problem?  This gap_fit command (didn't show the rest) ran fine with the other installation.  I must have forgotten something? Maybe it really didn't build correctly?  Thanks

$ more *89.err
Loading 2022.0.2 version modulefiles
Loading tbb version 2021.5.1
Loading compiler-rt version 2022.0.2
Loading oclfpga version 2022.0.2
  Load "debugger" to debug DPC++ applications with the gdb-oneapi debugger.
  Load "dpl" for additional DPC++ APIs: https://github.com/oneapi-src/oneDPL

Lmod is automatically replacing "gnu9/9.3.0" with "intel/2022.0.2".

Removing 2022.0.2 version modulefiles
Use `module list` to view any remaining dependent modules.
  Load "debugger" to debug DPC++ applications with the gdb-oneapi debugger.
  Load "dpl" for additional DPC++ APIs: https://github.com/oneapi-src/oneDPL
Loading 2022.0.2 version modulefiles
  Load "debugger" to debug DPC++ applications with the gdb-oneapi debugger.
  Load "dpl" for additional DPC++ APIs: https://github.com/oneapi-src/oneDPL
Loading mpi version 2021.5.1

Lmod is automatically replacing "openmpi4/4.0.4" with "mpi/2021.5.1".

Removing mpi version 2021.5.1
Use `module list` to view any remaining dependent modules.
Loading mpi version 2021.5.1
/var/spool/slurmd/job960789/slurm_script: line 70: 1589989 Illegal instruction     (core dumped) gap_fit

**Comment by Sideboard** [comment]
Assuming you compiled it on the login node, that might have another CPU than your compute nodes. Probably should ask the admins about that. It might work if you compile it on a compute node (via a job) instead but maybe the cluster is mixed. Restricting through compiler option is also possible, again something to discuss with the admins.

**Comment by jameskermode** [comment]
Also worth checking gap_fit you compiled runs on the login node, eg with gap_fit --help

**Comment by MES-physics** [comment]
OK, it had to do with not pointing to the right path for the new gap_fit executable on the cluster.    Works now, thanks!
