### ISSUE TITLE
Question about 

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#488]
Dear QUIP people,
  On trying to follow these instructions: 
**make simple plots of the energies and forces on the EMT and GAP datas[](https://libatoms.github.io/GAP/gap_fitting_tutorial.html#make-simple-plots-of-the-energies-and-forces-on-the-EMT-and-GAP-datas)**

I get this error:

File "./MATPLOTcode.sh", line 39, in energy_plot
    _rms = rms_dict(ener_in, ener_out)
NameError: name 'rms_dict' is not defined

Can you please tell how to define it?   Thanks!

**Comment by jameskermode** [comment]
It’s defined earlier in the notebook you linked to.

**Comment by MES-physics** [comment]
Yes thanks, it works now !
