### ISSUE TITLE
Question about the ```distance_2b``` descriptor 

### ISSUE THREAD

**Issue by DGKang234** [libAtoms/QUIP#489]
Dear professors,

Probably this is not the appropriate place to ask questions about the GAP algorithm as it is not the software matter.
But I couldn't find or figure out whether the GAP ```distance_2b``` descriptor treats differently for the chiral (reflectional) structures or not (invariant).
Is the ```distance_2b``` recognise the chiral structures as identical structures to each other?

I have followed your documentation to investigate the question using a simple ```distance_2b``` case
(https://libatoms.github.io/GAP/quippy-descriptor-tutorial.html).

```
>>> from quippy import descriptors
>>> import ase
>>> import ase.build
>>> water_1 = ase.build.molecule('H2O')
>>> water_2 = ase.build.molecule('H2O')
>>> water_2.rotate(90, 'z')
>>> water_2
Atoms(symbols='OH2', pbc=False)

>>> desc = descriptors.Descriptor("distance_2b Z1=8 Z2=1 cutoff=4")

>>> water_1.get_positions()
array([[ 0.      ,  0.      ,  0.119262],
       [ 0.      ,  0.763239, -0.477047],
       [ 0.      , -0.763239, -0.477047]])
>>> water_2.get_positions()
array([[ 0.00000000e+00,  0.00000000e+00,  1.19262000e-01],
       [-7.63239000e-01,  4.67349099e-17, -4.77047000e-01],
       [ 7.63239000e-01, -4.67349099e-17, -4.77047000e-01]])

>>> w1 = desc.calc(water_1)
>>> w2 = desc.calc(water_2)
>>> test2 = desc.calc(water_2, grad=True)
>>> test1 = desc.calc(water_1, grad=True)
```

The output format is in a dictionary format. (```['has_grad_data', 'ii', 'pos', 'grad_covariance_cutoff', 'covariance_cutoff', 'data' 'has_data', 'grad_data']```)

The document briefly explained the key of the dictionary

> data = the descriptor values (equivalent to desc.calc(at)) # earlier descriptor - grad_data = the gradients # earlier grad - ii = the indices (i_desc, i_atom, i_coord) # this was index, right?

but I couldn't understand the ```descriptor - grad_data``` and ```grad-ii``` part.

May I ask what is the meaning of ```has_grad_data```, ```ii``` and ```grad_data``` ?

```has_grad_data```, ```ii``` and ```grad_data``` gives non-identical values.
```
>>> test1['ii']
[array([27793744,        0], dtype=int32), array([27664224,        0], dtype=int32), array([27796688,        0], dtype=int32), array([27793776,        0], dtype=int32)]
>>> test2['ii']
[array([909521152, 959854392], dtype=int32), array([1925671248, 32524], dtype=int32), array([91,  0], dtype=int32), array([-340813160, 1072248672], dtype=int32)]

>>> test1['has_grad_data']
[array([27,  0], dtype=int32), array([1431064387, 1028869709], dtype=int32), array([0, 0], dtype=int32), array([91,  0], dtype=int32)]
>>> test2['has_grad_data']
[array([250,   0], dtype=int32), array([-427853120, 32523], dtype=int32), array([27787424,  0], dtype=int32), array([-340813160, 1072248672], dtype=int32)]

>>> test1['grad_data']
array([[[-0.        ],
        [ 0.78801008],
        [ 0.61566233]],

       [[ 0.        ],
        [-0.78801008],
        [-0.61566233]],

       [[-0.        ],
        [-0.78801008],
        [ 0.61566233]],

       [[ 0.        ],
        [ 0.78801008],
        [-0.61566233]],

       [[-0.        ],
        [ 0.78801008],
        [-0.61566233]],

       [[ 0.        ],
        [-0.78801008],
        [ 0.61566233]],

       [[-0.        ],
        [-0.78801008],
        [-0.61566233]],

       [[ 0.        ],
        [ 0.78801008],
        [ 0.61566233]]])
>>> test2['grad_data']
array([[[-7.88010083e-01],
        [ 4.82517013e-17],
        [ 6.15662334e-01]],

       [[ 7.88010083e-01],
        [-4.82517013e-17],
        [-6.15662334e-01]],

       [[ 7.88010083e-01],
        [-4.82517013e-17],
        [ 6.15662334e-01]],

       [[-7.88010083e-01],
        [ 4.82517013e-17],
        [-6.15662334e-01]],

       [[-7.88010083e-01],
        [ 4.82517013e-17],
        [-6.15662334e-01]],

       [[ 7.88010083e-01],
        [-4.82517013e-17],
        [ 6.15662334e-01]],

       [[ 7.88010083e-01],
        [-4.82517013e-17],
        [-6.15662334e-01]],

       [[-7.88010083e-01],
        [ 4.82517013e-17],
        [ 6.15662334e-01]]])
```

Thank you.

**Comment by gabor1** [comment]
Sorry for the delay in answering. The distance_2b descriptor is simple the interatomic distances between pairs of atoms, so it allows you to fit a pair potential. As such it cannot tell you anything about chirality, since all distances remain the same under a mirror reflection. 

the grad_data is the gradient of the descriptor with respect to atomic positions.
