### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by albapa** [libAtoms/QUIP#49]
Simone Sturniolo in STFC tried to use pip (as in pip install from local folder, see [here](http://stackoverflow.com/questions/2087148/can-i-use-pip-instead-of-easy-install-for-python-setup-py-install-dependen)) to install quippy but failed. The reason is in line 44 in setup.py:

quip_root = os.path.abspath(os.path.join(os.getcwd(), '../'))
When it is run via pip it uses a temporary directory so everything is messed up. Just wondering: would it be acceptable if we get QUIP_ROOT from the environment (and throw an error if it's not there) and use it.

**Comment by jameskermode** [comment]
Maybe check for `QUIP_ROOT` in `os.env` but fall back on `os.getcwd()` if it's not there, rather than throwing an error? I don't think many users set `QUIP_ROOT` by hand, but the top-level `Makefile` does.

**Comment by albapa** [comment]
OK, that's a great idea! I'll make this change.
