### ISSUE TITLE
print fewer warnings

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#490]
Is this warning really necessary every time `WARNING: Potential_initialise using default init_args "Potential xml_label=GAP_CsPbBr3_pert_and_froz_phon_gap_rss_universal_SOAP.freq_weighted_10_max_wt_1e7"
`

**Comment by gabor1** [comment]
It's not really a warning, it's telling you what it's doing

**Comment by bernstei** [comment]
I know what it's doing - I gave it the (lack of) arguments. This message just litters my stdout (or stderr).  I'd at least like a quiet mode.

**Comment by Sideboard** [comment]
How about this:
- Change "WARNING" to "INFO" (or no prefix).
- Change verbosity from `normal` to `verbose` (or even `nerd`).

**Comment by jameskermode** [comment]
I'd be happy with those changes

**Comment by bernstei** [comment]
OK. Shall I do a PR?

**Comment by jameskermode** [comment]
Please go ahead if you have time

**Comment by bernstei** [comment]
I'm going to code it up with a separate `message_type` string argument which will be `"INFO"` here (and default to `"WARNING"` for backward compatibility), and independent `verbosity`, although one could imagine having the verbosity derived from the message type.  I don't think it's worth it  to recreate the complexity of python's logging/warning interface here. If someone else feels strongly about it, feel free to modify my PR or even just let me know.

I would perhaps consider replacing `print_warning` with `print_message`, because that can be updated with a search and replace: `print_warning(message)` -> `print_message('WARNING', message)`

**Comment by Sideboard** [comment]
I would prefer for it to not be named `print_warning` when it may not be a warning at all. Also, `print_warning` is anyway only a wrapper to not add the prefix explicitly. Is it worth it to have `print_message`, which then calls `print`, or could it be `print` everywhere?

**Comment by jameskermode** [comment]
Noam’s solution in the PR plus the offer of search and replace for `print_message()` sounds a good compromise to me.

**Comment by bernstei** [comment]
I definitely don't want just `print`, because if nothing else it'll be harder to do with a search and replace (adding a new initial argument is much easier with a regexp), but I'll do `print_message()`.

**Comment by bernstei** [comment]
Or does that violate the "libatoms is dead, minimal changes only" principle, and I should just revert `print_warning` and add `print_info()` function? It's certainly less likely to lead to missed changes.

**Comment by Sideboard** [comment]
I wasn't aware of that principle. :sweat_smile:

Both `print_message` and `print_info` are possible solutions. I don't think it's likely that you miss a `print_warning`.

Then again, `print_warning` is such a simple procedure (a single string argument) that replacing it with print should not be that difficult. Although, I had single lines in mind, with multiple lines it would get ugly. Just checked: 11 out of 67 calls are multilined.

Edit: Oh wait, replacing with `print("WARNING: " // ` should be simpler than replacing with `print_message(` plus additional arguments for multilined ones. :thinking:

**Comment by jameskermode** [comment]
I think `print_warning()` -> `print_message()` is a perfectly good solution. If you do the search/replace I'll approve and merge.

**Comment by bernstei** [comment]
Take a look at the latest commit.

**Comment by jameskermode** [comment]
New release v0.9.11 including this PR is now on PyPI, so let the warnings be silenced!
