### ISSUE TITLE
getting local atomic energy contributions 

### ISSUE THREAD

**Issue by sandipde** [libAtoms/QUIP#491]
Hello GAP developers,
   In the quippy lammps wrapper code, I see that you pass on the neighbourlists from lammps. Is it possible to get local energy contributions of the env center with our ML potential without providing the big full structure? 
Thanks in advance.
Best regards
Sandip

**Comment by gabor1** [comment]
you can cut out a sphere equal or bigger than your cutoff and if you evaluate a GAP on that,  the local energy of the central atom will be the same as in the full big structure.
