### ISSUE TITLE
How to deal with incomplete data read with command of gap_fit？

### ISSUE THREAD

**Issue by e-724** [libAtoms/QUIP#493]
Here are my command statements.Incomplete reading of stress data.
! gap_fit at_file=dyn_emt1.xyz energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=stress \
gap={soap l_max=4 n_max=8\
     atom_sigma=0.5 \
     zeta=4 cutoff=5.5 \
     cutoff_transition_width=1.0 n_sparse=1000 \
     delta=3.0 f0=0.0 \
     covariance_type=dot_product \
     sparse_method=cur_points} \
default_sigma={0.001 0.1 0.05 0.0} \
e0={Zr:0.0:O:0.0}\
do_copy_at_file=F sparse_separate_file=F \
gp_file=gap_2b.xml

Here is the data set.

stress="-0.038930221044453775 -3.020890416927497e-06 7.95168262637527e-06 -3.020890416927497e-06 -0.03890660317392144 1.7482467061599005e-05 7.95168262637527e-06 1.7482467061599005e-05 -0.03891405553581774" free_energy=-114.21164407

**Comment by bernstei** [comment]
It's quite likely that stresses _have_ to be 6 element (Voigt), while virials are 9 element (3x3).

**Comment by gabor1** [comment]
is this the default and intended behaviour of the new xyz reader?

**Comment by noambernstein** [comment]
I don’t remember what the new reader does. Nothing uses it yet, though, at
least not outside of development branches.

**Comment by mcaroba** [comment]
I can confirm that if you have a 9-element stress tensor in your XYZ line that leads to bad potentials. This is a bit messy at the moment so we're currently just removing the stress info altogether from our XYZ database files and using the virial as before. I should be able to check the issue in more detail next week.

**Comment by bernstei** [comment]
I suspect this is related to the fact that the fortran xyz parser needs to know _at compile time_ the number of elements in an array read from the comment line.  I'll take a look at how exactly I implemented stress reading, and see if at least error messages could be improved.

**Comment by bernstei** [comment]
No - my last idea was wrong.  It should be able to handle both 6 Voigt and 3x3 full matrix stress entries.  Note that both are assumed by the code to have the same sign convention, namely virial = -stress * volume (bad potentials were definitely caused in the past by incorrect sign conventions).

 [Parsing code](https://github.com/libAtoms/GAP/blob/6adcca909752f0e90bb3f2903398ee4064075951/gap_fit_module.f95#L870 ) seems fine to me, unless we think that 3x3 stress *should* have a different sign convention than Voigt 6.

**Comment by mcaroba** [comment]
I think the stress should follow the standard convention, which is consistent with how ASE's read() imports the stress, at least from VASP. From what you write this is the case. I will do some more testing ASAP to try and diagnose the problem better than my unhelpful "bad potential".
