### ISSUE TITLE
MPI question

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#498]
Dear GAP people,
In setting up to run as MPI, do we still have to follow these instructions below (from February here)?  Or which part(s)?
I am using an intel compiler with OneAPI module, and QUIP_ARCH with ifort and "avon",  instead of gfortran openmpi+openmp.
Thanks

"This functionality is very new (just merged into public this week) and there are some limitations - principally that you need to do a standard run first to generate the sparse points - so for most users we suggest waiting until we can provide some examples and documentation.

However, if you are very keen to try it here are some very rough instructions (adapted from those provided by @Sideboard for local users to test here at Warwick). If you give it a shot please give us feedback on your experiences.

Compiling
Load appropriate modules to provide Fortran, BLAS/LAPACK and ScaLAPACK. On our HPC cluster this requires module load GCC/10.3.0 OpenMPI/4.1.1 ScaLAPACK/2.1.0-fb OpenBLAS/0.3.15
QUIP_ARCH=linux_x86_64_gfortran_openmpi+openmp
make config creates build/$QUIP_ARCH/Makefile.inc
MATH_LINKOPTS=-lscalapack -lopenblas
HAVE_GAP=1
HAVE_QR=1
HAVE_SCALAPACK=1
Using
Calculate without MPI to get the sparseX output files
Use sparsify_only_no_fit=T to just create the sparseX files
Convert output files to input files (QUIP script gap_prepare_sparsex_input.py gp.xml)
Optionally rename them to something shorter (e.g. 1.input, 2.input etc.)
Change input method (sparse_method=FILE sparse_file=1.input)
For more than one species use add_species=F and explicit input
Check the number of braces (gap={{$gap1}:{$gap2}:{$gap3}})
Run with mpirun -np … (or srun for Slurm)
MPI can trip up on the ….xyz.idx file. Usually works if it's there from the start, so retry can help."

**Comment by Sideboard** [comment]
The base workflow is still the same: sparsify without MPI, convert output to input files, change descriptors to use files, run with MPI.

I have added some information to the documentation of QUIP and GAP.

We have not added a full ?MPI+OpenMP arch Makefile yet but it is possible run gap_fit with both via Intel.

Edit: Some of the problems from before, e.g. the .idx file, have been solved.

**Comment by MES-physics** [comment]
When I did the sparsification only, the original way (that worked before), it finishes normally with Bye-bye!,  but I don't get any sparseX output files.  Do you know what could be the problem?
I do get this at the end of the .err file :
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
Thanks

**Comment by MES-physics** [comment]
Funny thing, when I did the sparsify_only_no_fit=T  on my own laptop, it DID create the sparseX files, which I then transferred to the cluster to input as sparse_method=FILE , sparse_file=1.input, etc. for the MPI run.
I hope that works for the meanwhile, maybe the problem is on our cluster.

**Comment by MES-physics** [comment]
But now when I run the MPI version, I get this problem.  Please help?

SYSTEM ABORT: proc=0 Traceback (most recent call last)
File "gp_fit.f95", line 199 kind unspecified
gpCoordinates_sparsify: file 1.input contains 15 lines, not conforming with descriptor size 1            
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

Here is my gap_fit script for MPI:  (I do have 15 sparse points requested.)
gap_fit \
atoms_filename=C3909evenhalf.xyz \
at_file=C3909evenhalf.xyz \
gap = \
{distance_Nb \
order=2 \
cutoff=4.2 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=FILE \
sparse_file=1.input \
compact_clusters=T : \
distance_Nb \
order=3 \
cutoff=2.0 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=FILE \
sparse_file=2.input \
compact_clusters=T : \
soap \
l_max=4 \
n_max=12 \
atom_sigma=0.5 \
cutoff=4.2 \
radial_scaling=0.5 \
cutoff_transition_width=1.0 \
central_weight=1.0 \
n_sparse=8000 \
delta=0.2 \
f0=0.0 \
covariance_type=dot_product \
zeta=4 \
sparse_method=FILE \
sparse_file=3.input} \
default_sigma={0.002 0.2 0.2 0.0} \
default_kernel_regularisation={0.002 0.2 0.2 0.0} \
sparse_jitter=1.0e-8 \
energy_parameter_name=energy \
force_parameter_name=force \
virial_parameter_name=virial \
stress_parameter_name=stress \
do_copy_at_file=F \
sparse_separate_file=T \
openmp_chunk_size=10000 \
sparsify_only_no_fit=F \
gp_file=gapC3909EhalfSHORT_2b3bSoap.xml \

**Comment by Sideboard** [comment]
Is this only for carbon or are more species involved?

**Comment by MES-physics** [comment]
Just carbon.

**Comment by Sideboard** [comment]
Ok, then it should be fine.

Did you use the script `$QUIP/bin/gap_prepare_sparsex_input.py`? You cannot use the sparseX files from the sparsify run directly.

**Comment by MES-physics** [comment]
Oh!  How to do that exactly, please?  I didn’t understand.

**Comment by Sideboard** [comment]
1. Go into the directory of your sparsify output.
2. Call `$QUIP_ROOT/bin/gap_prepare_sparsex_input.py gap.xml` (assuming the main output file is called `gap.xml`).
3. Copy the created `*.input` files to your fit directory. 

The script just takes the cutoffs from the xml and adds them to the sparseX files.

**Comment by MES-physics** [comment]
In trying to do a sparsify_only_no_fit=T (normal, not MPI, using one node) run on the cluster, I get this message in my .err file: "Note: The following floating-point exceptions are signalling: IEEE_DENORMAL".  
 And the run finishes saying Bye Bye as if completed,  but no gap.xml files are output!
This message does not appear when the fitting action is included (and files are there).
The message does not appear when I do the normal run with sparsify_only on my laptop, but of course I can't do a large data file on the laptop.  
What could be the difference on a cluster with this message and not putting out the files?
Here is my gap_fit command, which works with fitting.
  module load gnu10
module load openblas
source /home/m/quippy-env/bin/activate
cd /home/m/GAP_SOAP/GAP_C
export PYTHONUNBUFFERED=TRUE
ulimit -s unlimited
export OMP_STACKSIZE=1G
export OMP_DYNAMIC=false
export OMP_PROC_BIND=true
export OMP_NUM_THREADS=64

gap_fit \
atoms_filename=C3909evenhalf.xyz \
at_file=C3909evenhalf.xyz \
gap = \
{distance_Nb \
order=2 \
cutoff=4.5 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=uniform \
compact_clusters=T : \
distance_Nb \
order=3 \
cutoff=2.0 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=uniform \
compact_clusters=T : \
soap \
l_max=4 \
n_max=12 \
atom_sigma=0.5 \
cutoff=4.5 \
radial_scaling=0.5 \
cutoff_transition_width=1.0 \
central_weight=1.0 \
n_sparse=8000 \
delta=0.2 \
f0=0.0 \
covariance_type=dot_product \
zeta=4 \
sparse_method=cur_points} \
default_sigma={0.001 0.1 0.1 0.0} \
default_kernel_regularisation={0.001 0.1 0.1 0.0} \
sparse_jitter=1.0e-8 \
energy_parameter_name=energy \
force_parameter_name=force \
virial_parameter_name=virial \
stress_parameter_name=stress \
do_copy_at_file=F \
sparse_separate_file=T \
openmp_chunk_size=10000 \
sparsify_only_no_fit=T \
gp_file=gapC3909R1sparse4pt5ehalf_2b3bSoap.xml \

**Comment by Sideboard** [comment]
Could you please run the sparsify again with `verbosity=VERBOSE`? Maybe that gives more insight.

Please also give more details on your cluster: e.g. operating system, which compilers/libraries incl. version.

Bonus: Please use triple backticks to provide code blocks (or single ones if you want to use it inline, e.g. `config_file=my_config`), that makes it easier to read.

**Comment by MES-physics** [comment]
OK, the cluster's OS is RHEL8[Rocky Linux release 8.5(Green obsidian)].
Compiler and library:gnu10 , openblas.

Now I get this error:  (It also said completed instead of failed, and didn't print any .xml files.)

Operating system error: Cannot allocate memory
In file '/io/QUIP/src/GAP/gp_predict.f95', around line 511: Error allocating 547103884752 bytes

Error termination. Backtrace:
#0  0x148a3b314dfd in ???
#1  0x148a3b315995 in ???
#2  0x148a3b315ba5 in ???
#3  0xad3591 in ???
#4  0x7b8e48 in ???
#5  0x416ea4 in ???
#6  0x405e7c in ???
#7  0x40586e in ???
#8  0x148a3a335492 in ???
#9  0x40589e in ???
#10  0xffffffffffffffff in ???

These settings :  export PYTHONUNBUFFERED=TRUE
ulimit -s unlimited
export OMP_STACKSIZE=1G
export OMP_DYNAMIC=false
export OMP_PROC_BIND=true
export OMP_NUM_THREADS=48

My gap_fit command:
```
gap_fit \
atoms_filename=C3909evenhalf.xyz \
at_file=C3909evenhalf.xyz \
gap = \
{distance_Nb \
order=2 \
cutoff=4.5 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=uniform \
compact_clusters=T : \
distance_Nb \
order=3 \
cutoff=2.0 \
n_sparse=15 \
covariance_type=ard_se \
delta=2.0 \
theta_uniform=2.5 \
sparse_method=uniform \
compact_clusters=T : \
soap \
l_max=4 \
n_max=12 \
atom_sigma=0.5 \
cutoff=4.5 \
radial_scaling=0.5 \
cutoff_transition_width=1.0 \
central_weight=1.0 \
n_sparse=8000 \
delta=0.2 \
f0=0.0 \
covariance_type=dot_product \
zeta=4 \
sparse_method=cur_points} \
default_sigma={0.001 0.1 0.1 0.0} \
default_kernel_regularisation={0.001 0.1 0.1 0.0} \
sparse_jitter=1.0e-8 \
energy_parameter_name=energy \
force_parameter_name=force \
virial_parameter_name=virial \
stress_parameter_name=stress \
do_copy_at_file=F \
sparse_separate_file=T \
openmp_chunk_size=10000 \
verbosity=VERBOSE \
sparsify_only_no_fit=T \
gp_file=gapSparseTest.xml \
```
Here is the verbose output file:
[Sparse-80992.txt](https://github.com/libAtoms/QUIP/files/10070537/Sparse-80992.txt)

Thanks for any advice.

**Comment by bernstei** [comment]
It's saying it can't allocate ~550 GB.  Do you have 500 GB on this machine?  Is there a system limit that would stop you from using it?

**Comment by MES-physics** [comment]
Oh, I'll have to increase that to a higher node then.  
But I didn't think I'd need that just for sparsification only.  I requested 450GB on this run, which I thought was far and away more than required.
In addition, I did this sparsification-only run on my laptop, it finished fine, and gave output files.  So now I'm wondering if it did anything correct on my laptop, if it really needs that much?  Laptop has only about 65GB, and only 4 cores.

**Comment by Sideboard** [comment]
I think your cluster QUIP/GAP version is quite old. Please try to compile a new version, then it should also skip the derivatives for the sparsification. I guess your local version is already newer.

**Comment by Sideboard** [comment]
I suppose this can be closed.

**Comment by MES-physics** [comment]
Yes thanks, closing.
