### ISSUE TITLE
error when setting initialtemperature in creation of Dynamics object

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#5]
Traceback (most recent call last):
  File "run-model-test.py", line 42, in <module>
    import test  # import and run the current test
  File "../tests/liquid/test.py", line 32, in <module>
    dyn_heat = quippy.Dynamics(bulk, 0.5*ase.units.fs, initialtemperature=5000.0, trajectory=None)
  File "/usr/local/quip/2015-06-03/mkl/lib64/python/quippy/dynamicalsystem.py", line 186, in **init**
    if not all(abs(self._ds.atoms.velo) < 1e-3):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Removing the initialtemperature specification allows this statement to work fine.

**Comment by jameskermode** [comment]
Should be fixed in commit 06d46a9c68daa905cea825fc85406cce968533db to public branch

**Comment by jameskermode** [comment]
Closing as now resolved.
