### ISSUE TITLE
gap_fit is not working

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#501]
#gap_fit command not working in my windows laptop. 
I have downloaded GAP under QUIP. But gap_fit not working.

! gap_fit energy_parameter_name=energy force_parameter_name=forces do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.008 0.04 0 0} gap={distance_2b cutoff=4.0 covariance_type=ard_se delta=0.5 theta_uniform=1.0 sparse_method=uniform add_species=T n_sparse=10}

I get this  Input In 
    ^
SyntaxError: invalid syntax

**Comment by gabor1** [comment]
try running it from a terminal

**Comment by bernstei** [comment]
That's a very generic python error.  Is it true that you're getting gap_fit by installing quippy? It's the only way I can think of for `gap_fit` to generate a python syntax error (there's a python wrapper that runs the compiled fortran executable).

I don't know if that's properly supported on windows.  Have you tried running it in a Linux virtual machine, e.g. WSL? That's more likely to work.

**Comment by Amitcuhp** [comment]
I tried again on linux. Now it's working.

Thanks:)))))
