### ISSUE TITLE
Anyone explain these steps please

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#504]
Decide your architecture by looking in the arch/ directory, and define an environmental variable QUIP_ARCH, e.g.::

export QUIP_ARCH=linux_x86_64_gfortran
for standard gfortran on Linux. Here is where you can adjust which compiler is being used, if you do not like the defaults. You may need to create your own arch/Makefile.${QUIP_ARCH} file based on an existing file for more exotic systems.

MPI: Some arch files already include adjustments for MPI use. Those usually have mpi in their name, e.g. linux_x86_64_gfortran_openmpi+openmp.

Customise QUIP, set the maths libraries and provide linking options::

make config
Makefile.config will create a build directory, build/${QUIP_ARCH}, and all the building happen there. First it will ask you some questions about where you keep libraries and other stuff, if you don't use something it is asking for, just leave it blank. The answers will be stored in Makefile.inc in the build/${QUIP_ARCH} directory, and you can edit them later (e.g. to change compiler, optimisation or debug options).

If you later make significant changes to the configuration such as enabling or disabling tight-binding support you should force a full rebuild by doing a make deepclean; make.

**Comment by Amitcuhp** [comment]
make: *** No targets specified and no makefile found.  Stop.

**Comment by Sideboard** [comment]
Did you run the command in the root directory, i.e. `/my/path/QUIP` or in some subdirectory? The latter won't work.

**Comment by Amitcuhp** [comment]
Yes I write the command..but this coming....please guide me what to do..step by step if possible.

**Comment by Sideboard** [comment]
What is the path to your copy? What does `ls` return?

**Comment by Amitcuhp** [comment]
(base) amit@amit-Mi-NoteBook-14:~/QUIP/src/GAP$ ls
clustering.f95                              descriptors_wrapper.f95  gp_fit.f95                              orig_descriptors.f95     soap_turbo_functions.f90
descriptors.f95                             doc_src                  gp_predict.f95                          README.md                soap_turbo_radial.f90
descriptors_noncommercial.inc               error.inc                hybrid_md_package                       soap_turbo
descriptors_noncommercial_permutations.inc  gap_fit.f95              LICENSE.md                              soap_turbo_angular.f90
descriptors_noncommercial_types.inc         gap_fit_module.f95       Makefile                                soap_turbo_compress.f90
descriptors_v1.f95                          gapversion               make_permutations_noncommercial_v2.f95  soap_turbo.f90

**Comment by Amitcuhp** [comment]
what should we do now?

**Comment by Amitcuhp** [comment]
now everthing is working
.But plz tell these steps
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_24979/1540441006.py in <module>
     18 # call general purpose elastic constants calculator
     19 #   using ASE Atoms and QUIP Potential
---> 20 from matscipy.elasticity import fit_elastic_constants
     21 Cij = fit_elastic_constants(si, optimizer=LBFGS,
     22                             symmetry='cubic', logfile='-')

ModuleNotFoundError: No module named 'matscipy'

**Comment by bernstei** [comment]
run
<your_python_executable> -m pip install matscipy
like the way you'd install most other python packages.

**Comment by Amitcuhp** [comment]
package installed but not working here

**Comment by jameskermode** [comment]
More details needed if we are to help you: do you get an error during the installation of matscipy?

**Comment by Amitcuhp** [comment]
It is installed succesfully , but it is not working

**Comment by bernstei** [comment]
If you do `import matscipy` in python after you install it, does it work?

**Comment by Amitcuhp** [comment]
also 
not working after importing

**Comment by Amitcuhp** [comment]
imported succesfully but not working

**Comment by bernstei** [comment]
> On Nov 19, 2022, at 10:37 AM, Amitcuhp ***@***.***> wrote:
> imported succesfully but not working
> 
"not working" is way too vague to give anyone else any meaningful chance of figuring out what's wrong.  At the very minimum you need to provide the exact command you're running and what the result is.
