### ISSUE TITLE
gap si surface problem

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#506]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_26588/90115364.py in <module>
     20 from ase.optimize.precon import PreconLBFGS, Exp
     21 
---> 22 from gap_si_surface import ViewStructure

ModuleNotFoundError: No module named 'gap_si_surface'

**Comment by jameskermode** [comment]
That module can be found here: https://github.com/libAtoms/GAP/tree/main/doc_src/gap_si_surface

**Comment by Amitcuhp** [comment]
I have already insalled by git cloning. 
But its not working.

Can you tell me how to make it work

**Comment by jameskermode** [comment]
You need to copy the gap_si_surface directory linked above into the same directory where you are running the notebook.

**Comment by Amitcuhp** [comment]
not working after this

**Comment by Amitcuhp** [comment]
Can yoy please explain these steps ? How to resolve



---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_11858/2531361136.py in <module>
      1 # attach tight binding calculator
----> 2 qm_pot = Potential('TB DFTB', param_filename='dftb-params.xml')
      3 atoms.set_calculator(qm_pot)
      4 
      5 # Thermalize atoms

~/anaconda3/lib/python3.9/site-packages/quippy/potential.py in __init__(self, args_str, pot1, pot2, param_str, param_filename, atoms, calculation_always_required, calc_args, add_arrays, add_info, **kwargs)
     79         if param_filename is not None and isinstance(param_filename, str):
     80             # from a param filename
---> 81             self._quip_potential = quippy.potential_module.Potential.filename_initialise(args_str=args_str,
     82                                                                                          param_filename=param_filename)
     83         elif pot1 is not None and pot2 is not None:


~/anaconda3/lib/python3.9/site-packages/quippy/potential_module.py in filename_initialise(cls, args_str, param_filename, bulk_scale, error)
    132         bare_class = cls.__new__(cls)
    133         f90wrap.runtime.FortranDerivedType.__init__(bare_class)
--> 134         result = quippy._quippy.f90wrap_potential_filename_initialise(args_str=args_str, param_filename=param_filename, \
    135             bulk_scale=None if bulk_scale is None else bulk_scale._handle, error=error)
    136         bare_class._handle = result[0] if isinstance(result, tuple) else result

RuntimeError: Traceback (most recent call last)
  File "/project/src/libAtoms/System.f95", line 537 kind unspecified
    IO error opening "dftb-params.xml" on unit 7, error number: 2
