### ISSUE TITLE
Issues when using LAMMPS GAP potential for the Li-C system

### ISSUE THREAD

**Issue by jinlhr542** [libAtoms/QUIP#510]
Dear developer

I encountered a problem when using this Li-C GAP potential:
https://www.repository.cam.ac.uk/handle/1810/307758

This is my input:
#Initialize Simulation --------------------- 
units metal 
dimension 3 
boundary p p p
atom_style atomic
atom_modify map array
# ---------- Create Atoms --------------------- 
lattice 	diamond 	3.5 orient x 1 0 0 orient y 0 1 0 orient z 0 0 1  
region	box block 0 1 0 1 0 1 units lattice
create_box	1 box
create_atoms 1 box
replicate 5 5 5

mass 1 12.011 #Si
# ---------- Define Interatomic Potential --------------------- 
pair_style quip
pair_coeff * * lithium_carbon.xml "IP GAP label=GAP_2017_10_26_540_23_55_28_308" 6

# ---------- Run Minimization ---------------------
compute eng all pe/atom 
compute eatoms all reduce sum c_eng 

# ---------- Run Minimization --------------------- 
reset_timestep 0 
fix 1 all box/relax iso 0.0 vmax 0.001
thermo 10 
thermo_style custom step pe lx ly lz press pxx pyy pzz c_eatoms 
min_style cg 
minimize 1e-25 1e-25 5000 10000 

variable natoms equal "count(all)" 
variable teng equal "c_eatoms"
variable length equal "lx/5"
variable ecoh equal "v_teng/v_natoms"

print "Total energy (eV) = ${teng};"
print "Number of atoms = ${natoms};"
print "Lattice constant (Angstoms) = ${length};"
print "Cohesive energy (eV) = ${ecoh};"

print "All done!" 
---------------------------------------------------

Then I ran 'mpirun -np 14 lmp_mpi -in p.in'

Output:

----------------------------------------------------
LAMMPS (3 Nov 2022)
Lattice spacing in x,y,z = 3.5 3.5 3.5
Created orthogonal box = (0 0 0) to (3.5 3.5 3.5)
  1 by 2 by 7 MPI processor grid
Created 8 atoms
  using lattice units in orthogonal box = (0 0 0) to (3.5 3.5 3.5)
  create_atoms CPU = 0.001 seconds
Replication is creating a 5x5x5 = 125 times larger system...
  orthogonal box = (0 0 0) to (17.5 17.5 17.5)
  1 by 2 by 7 MPI processor grid
  1000 atoms
  replicate CPU = 0.007 seconds
Neighbor list info ...
  update: every = 1 steps, delay = 0 steps, check = yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 7.5
  ghost atom cutoff = 7.5
  binsize = 3.75, bins = 5 5 5
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair quip, perpetual
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
Setting up cg style minimization ...
  Unit style    : metal
  Current step  : 0
WARNING: Energy due to 1 extra global DOFs will be included in minimizer energies
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1
SYSTEM ABORT: Traceback (most recent call last)
File "/QUIP/src/GAP/descriptors.f95", line 8954 kind unspecified
distance_Nb_calc: MPI/LAMMPS ready only for compact_clusters=T type of distance_Nb.            
STOP 1

Any suggestion will be greatly appreciated

Jason

**Comment by gabor1** [comment]
As the comment says, that old potential was made with settings that preclude its use with lammps (due to how the neighbourlist is handled). You can either refit it to the same training data with the latest version of gap_fit (and turn on the "compact_clusters=T" option), or use the "md" code packages with QUIP to run it (you still get openMP thread parallelism within a node), or use it from ASE via python. 

note that this potential is just for carbon-lithium INTERACTION so you need to add it to a potential which describes carbon.
