### ISSUE TITLE
Discontinuities in the potential

### ISSUE THREAD

**Issue by DjordjeDangic** [libAtoms/QUIP#514]
Hello everyone,

I am trying to fit a potential to describe phase transitions in one of the inorganic perovskites. However, I am getting weird discontinuities in the potential. What can be the cause of this and do you have any idea how to fix it? I attach the figure of energy vs volume where we can see the mentioned discontinuity. I obtained these results by applying small pressure to the material and relaxing the atomic positions. Weirdly enough the variance for the structure that shows discontinuity is not larger than for the other points (shown as an error bar in the attached figure). I also attach the figures for energy, force, and stress errors between DFT and GAP. Finally, I give the command used to fit this potential:

energy_parameter_name=energy force_parameter_name=forces stress_parameter_name=stress virial_parameter_name=dummy3 do_copy_at_file=F sparse_separate_file=T gp_file=GAP.xml at_file=train.xyz default_sigma={0.00099 0.033 0.033 0} sparse_jitter=1.0e-8 gap={soap cutoff=6.0 n_sparse=2000 covariance_type=dot_product sparse_method=cur_points delta=0.205 zeta=4 l_max=4 n_max=8 atom_sigma=0.5 cutoff_transition_width=0.8 add_species }

[Energy_vs_volume.pdf](https://github.com/libAtoms/QUIP/files/10140295/Energy_vs_volume.pdf)
[Energy_errors.pdf](https://github.com/libAtoms/QUIP/files/10140249/Energy_errors.pdf)
[Force_errors.pdf](https://github.com/libAtoms/QUIP/files/10140254/Force_errors.pdf)
[Stress_errors.pdf](https://github.com/libAtoms/QUIP/files/10140257/Stress_errors.pdf)

**Comment by jameskermode** [comment]
Does the structure perhaps change symmetry during the relaxation at the point where the discontinuity occurs? It looks like there is a transition to a lower energy structure, which could either really be lower in energy (i.e. DFT would agree) or fictiously so with your potential. One way to prevent symmetry changes during relaxation is to constrain the space group. @bernstei and I added a `FixSymmetry` constraint to do this to ASE, which you can find here: https://wiki.fysik.dtu.dk/ase/ase/constraints.html#the-fixsymmetry-class

**Comment by DjordjeDangic** [comment]
Sorry, I forgot to mention that I relax the structure at a given pressure with FixSymmetry constraint.

**Comment by jameskermode** [comment]
If you visualise the structures along the energy-volume curve can you see any discontinuous changes in positions, or do they vary smoothly and it is only the energy which is discontinuous?

**Comment by DjordjeDangic** [comment]
Yes, the reduced coordinates change significantly. Also as it is obvious from the figure the lattice parameters change significantly as well. The structure has one free parameter and it is 0.276534493505681 and 0.276108506622693 for the two closest structures and for the one with discontinuity it is 0.309692539780252. So the structure changes significantly and that leads to a large difference in energy, but why does it change significantly in the first place? Is it the error in stress or something else?

**Comment by jameskermode** [comment]
Is the 'bad' structure still consistent with the original spacegroup symmetry? You can use [check_symmetry()](https://wiki.fysik.dtu.dk/ase/ase/constraints.html#ase.spacegroup.symmetrize.check_symmetry) to test for this, to rule out a bug in the FixSymmetry constraint.

**Comment by DjordjeDangic** [comment]
Nope, the structure is the same as in the other cases.

**Comment by bernstei** [comment]
There's no inherent reason there can't be multiple minima. You should at least evaluate (or even relax with the same constraints) the entire set of GAP-relaxed configurations with DFT, and see if DFT predicts similar energies, forces, and stresses.

**Comment by DjordjeDangic** [comment]
The error between GAP and DFT is the largest for the structure where "discontinuity" occurs (about 2 times larger than for the other structures). I have not tried relaxing DFT for this structure but its energy is much higher than the energies for other structures in the set.

 As I said I am trying to model phase transition in this material. I have gathered DFT data from the high-symmetry structure and low-symmetry structure. The high symmetry structure (tetragonal) is not commensurate with the low symmetry structure (orthorhombic) in my dataset because I used the conventional orientation of the lattice vectors. Could this be the source of this weird behavior? I know that descriptors employed here (atomic densities) are chosen so that this should not be the issue, but I still wonder.

**Comment by bernstei** [comment]
Can you post the E(V) plot, with the relaxed GAP energies and the single-point evaluated DFT energies together?  What I'm wondering about is that you say that the energy error is about *twice* as large, but I usually expect to see nearly zero error between GAP and DFT on such simple E(V) curves, and the energy difference in your plot is much larger, so if the error on the weird structure is _only_ twice as large it would still be consistent with a DFT energy that's much lower than the supposed minimum. 

Also, can you post the relaxation trajectories and/or the final relaxed structures for a few normal and weird structures?

Also, what are the chances that your DFT calculation aren't consistent between the two types of structures because it's not possible (or at least non-trivial) to get a consistent k-point mesh, except in the high k-point density limit?

**Comment by DjordjeDangic** [comment]
I attached the figure of the energy error for different volumes.

I generate all of my DFT input files with ASE (except for isolated atoms) for quantum espresso software. I choose k-point density by specifying kspacing variable to be 0.01x2xpi. I do however have configurations with different shapes and sizes so I am not sure how consistent k spacing is. Could this be the reason for this behavior? 

[Energy_error_vs_volume.pdf](https://github.com/libAtoms/QUIP/files/10155549/Energy_error_vs_volume.pdf)

**Comment by bernstei** [comment]
The k-point density seems reasonable, but you could try to spot check by increasing it and re-evaluating a few configs, to see if any energy differences between systems with very differrent unit cells change.

Two things appear to be happening. There's an initial discontinuity two configs before the crazy one, which you can see in the x values and the increased error. Then there's the crazy one, which is qualitatively different.  I think it'll be easier to interpret if you plot what I suggested before, which is the GAP relaxed and DFT-evaluated energies in the same plot.

Also, it would be interesting to take one of the larger volume relaxations and re-run it with DFT (using an ASE calculator for the same DFT code, so the minimizer is the same), starting from the GAP relaxed config (and with the same negative pressure applied).

My guess is that the GAP just has a false minimum, and you'll need to add some of those large volume configurations to the fit. That's pretty normal for ML potentials.

**Comment by DjordjeDangic** [comment]
I agree that the issue was that GAP has a false minimum and that was messing up with the results. I added some configurations to the training set and this corrected the issue. Thank you.
