### ISSUE TITLE
  Error executing command of gap_fit?

### ISSUE THREAD

**Issue by e-724** [libAtoms/QUIP#519]
===================== Report on number of descriptors found ====================

---------------------------------------------------------------------
Descriptor: soap l_max=12 n_max=10 atom_sigma=0.5 zeta=4 cutoff=5.0 cutoff_transition_width=1.0 n_sparse=9000 delta=3.0 f0=0.0 covariance_type=dot_product sparse_method=cur_points n_species=1 Z=14 species_Z={14 }
Number of descriptors:                        640000
Number of partial derivatives of descriptors: 111360000

========================================  ======================================

Operating system error: Cannot allocate memory
Allocation would exceed memory limit

Error termination. Backtrace:
#0  0x2b467a29b8da
libAtoms/GAP#1  0x2b467a29c395
libAtoms/QUIP#497  0x2b467a29c592
libAtoms/QUIP#516  0x56282d6f9179
libAtoms/QUIP#496  0x56282d332c54
libAtoms/GAP#5  0x56282d3205a5
libAtoms/QUIP#517  0x56282d31ff3e
libAtoms/GAP#7  0x2b467a74309a
libAtoms/GAP#8  0x56282d31ff79
libAtoms/QUIP#495  0xffffffffffffffff

**Comment by gabor1** [comment]
see comments in the QUIP issue page
