### ISSUE TITLE
Successor to `quip-reference-manual.pdf`?

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#52]
I remember that there used to be a make target that would pull together all the f90doc output of the source into a pdf. Some of this info is made available in the quippy docs, but there is a lot of documentation in `QUIP` that is now only accessible by looking at the source code.

I think it would be worth trying to integrate the `libatoms`/`QUIP` documentation into the Sphinx docs for quippy and getting it all online. Including things like docs for all the different xml formats (i.e. issue #50) would make life easier for newcomers too.

**Comment by gabor1** [comment]
I'm going to work on docs at the hackathon.  

-- Gábor

**Comment by jameskermode** [comment]
No need for PDF, but we should expose more and deeper, e.g. Potentials

**Comment by max-veit** [comment]
Can't sphinx make offline documentation? Might be worth advertising a make
target that builds that.

**Comment by jameskermode** [comment]
@max-veit Sure - we are actually discussing work plans in person in the meeting room.

**Comment by gabor1** [comment]
We decided to eliminate PDF docs.
