### ISSUE TITLE
md5sum bug in gap_fit

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/QUIP#521]
Occasionally I see md5 sum warnings when fitting GAP: 

```
WARNING: quip_md5sum: could not obtain md5 sum of gap.xml.sparseX.GAP_2022_3_16_0_0_50_29_6611
WARNING: quip_md5sum: fmd5sum returned with code 12
```
which result in no `sparseX_md5sum` entries in the resulting gap.xml: 

```
<gpCoordinates label="GAP_2022_3_16_0_0_50_29_6611" dimensions="4663" signal_variance="1.0000000000000000" signal_mean=".00000000000000000E+000" sparsified="T" n_permutations="1" covariance_type="2" zeta="4.0000000000000000" n_sparseX="2000" sparseX_filename="gap.xml.sparseX.GAP_2022_3_16_0_0_50_29_6611" sparseX_md5sum="">
```

As far as I can tell that only happens with very large fits. Full gap_fit output: [gap.out.txt](https://github.com/libAtoms/GAP/files/8263142/gap.out.txt)

This fit has been done with quippy-ase v0.9.9 on Ubuntu 18.04.6.

**Comment by albapa** [comment]
Hi, where did you upload the sparse file?

**Comment by gelzinyte** [comment]
[Here's a Dropbox link](https://www.dropbox.com/s/rh1dpgb4uiwvenw/gap_md5sum_bug.tar.gz?dl=0) to fitting script, gap & sparse files and the output - 600 MB tarball

**Comment by albapa** [comment]
Please report back in case of any problems - I hope with the md5sum done internally as opposed to a system call will fix the issue.
