### ISSUE TITLE
Config via file

### ISSUE THREAD

**Issue by Sideboard** [libAtoms/QUIP#523]
Instead of cramming all options into a single command line and masking special characters so they are not interpreted by the shell, there should be the option to put everything into a file.

#### Thoughts

1. The path to this file would be the (only?) argument for gap_fit: `gap_fit my-config-file`
2. A newline is equivalent to a space.

**Comment by bernstei** [comment]
I thought we already had that someplace.

**Comment by bernstei** [comment]
`gap_fit config_file=my-config-file`, I believe.

**Comment by albapa** [comment]
These are all closed issues, transferred from the GAP repo.
