### ISSUE TITLE
Trouble compiling QUIP with GAP support

### ISSUE THREAD

**Issue by lydiash** [libAtoms/QUIP#524]
I am trying to compile QUIP to interface with Python (quippy) to calculate SOAP using GAP. I follow all of the directions and it seems to compile and imports successfully in Python, but returns empty SOAP vectors. I am getting some errors with compilation but it finishes and looks like it will work and then doesn't. I am running Python 3.8. 

This is a log of my compilation process: 
`source bin/activate` in my Python venv, then 
```
pip install numpy --no-chache-dir 
pip install f90wrap --no-chache-dir 
pip install ase --no-chache-dir 
```
then I check out QUIP with `git clone --recursive https://github.com/libAtoms/QUIP.git`, navigate to the QUIP directory, and set the environment variable `export QUIP_ARCH=linux_x86_64_gfortran`.

In `make config` the only thing I don't keep as default is :
```
Would you like to compile with GAP support ? [y/n]
   Default: n
y
``` 
since I want to calculate SOAP. Then I `make` which doesn't throw any warnings, then `make quippy` which runs with no errors, followed by `make install-quippy` which fails with this error:
```
Building wheels for collected packages: quippy-ase
  Building wheel for quippy-ase (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lydiash/environments/quippy/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-delckjdz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-delckjdz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sbd56ogu
       cwd: /tmp/pip-req-build-delckjdz/
  Complete output (7 lines):
  version: 0.9+gitaadb4a0a1.dirty
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for quippy-ase
  Running setup.py clean for quippy-ase
Failed to build quippy-ase
Installing collected packages: quippy-ase
    Running setup.py install for quippy-ase ... done
Successfully installed quippy-ase-0.9+gitaadb4a0a1.dirty
make[1]: Leaving directory '/home/lydiash/codes/QUIP/build/linux_x86_64_gfortran'
rm /home/lydiash/codes/QUIP/build/linux_x86_64_gfortran/Makefile
```
But when I run `python3`, it imports just fine:
```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quippy
>>> 
```
and when I try to calculate SOAP using the following function, it returns empty arrays:
```
def quippy_soap(atoms, cutoff, n_max, l_max, atom_sigma=0.5, normalise='F', n_Z=1,n_species=1, species_Z=13, Z=13):
    from quippy.descriptors import Descriptor
    #args have to be a string.
    compstr = ("soap cutoff={0:.1f} n_max={1:d} l_max={2:d} atom_sigma={3:.2f} normalise={4:s} n_Z={5:d}"
        " n_species={6:d} species_Z={{{7:d}}} Z={{{8:d}}}")
    argstr = compstr.format(cutoff, n_max, l_max, atom_sigma, normalise, n_Z, n_species, species_Z, Z)
    desc = Descriptor(argstr)
    return desc.calc_descriptor(atoms)
```

So it installs with errors, lets me import it, and then it doesn't work for me. What am I doing wrong?

**Comment by jameskermode** [comment]
That import is only succeeding as you are in the QUIP working directory, which includes the quippy/ source subdirectory. You need to fix the compile errors. I suspect these are due to quippy using the wrong pip and/or python: try setting PIP and PYTHON in your Makefile.inc. 

Alternatively you could try `pip install quippy-ase` to use our pre-built binary wheels.

**Comment by lydiash** [comment]
I'm not seeing a Makefile.inc, when I `ls` in QUIP, I see this:
```
CITATION.cff  Makefile.config  Makefile.rules  arch  build  docker  share  tests
Makefile      Makefile.fox     README.md       bin   doc    quippy  src    travis
```
Should I `make clean` before I remake?

**Comment by jameskermode** [comment]
Makefile.inc is within `build/${QUIP_ARCH}`. It’s produced automatically by the `make config` you ran earlier. 

You shouldn’t need to make clean.

**Comment by lydiash** [comment]
It looks like Pip and Python are already set in `Makefile.inc` :
```
PYTHON=/home/lydiash/environments/quippy/bin/python
PIP=/home/lydiash/environments/quippy/bin/pip
```
and those should be correct.

**Comment by jameskermode** [comment]
Did you try `pip install quippy-ase`? If you don’t need to modify the code that’s the easiest option.

**Comment by lydiash** [comment]
Yes I did, but I retried just in case it was a problem on my end. I did everything the same except when I was `pip install`ing things I added `quippy-ase` to the list. I got this error this time:
```
Building wheels for collected packages: quippy-ase
  Building wheel for quippy-ase (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lydiash/environments/quippy/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ewmhm_cb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ewmhm_cb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y2wtroz6
       cwd: /tmp/pip-req-build-ewmhm_cb/
  Complete output (7 lines):
  version: 0.9+git6f2ad16d1.dirty
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for quippy-ase
  Running setup.py clean for quippy-ase
Failed to build quippy-ase
Installing collected packages: quippy-ase
  Attempting uninstall: quippy-ase
    Found existing installation: quippy-ase 0.9.9
    Uninstalling quippy-ase-0.9.9:
      Successfully uninstalled quippy-ase-0.9.9
    Running setup.py install for quippy-ase ... done
Successfully installed quippy-ase-0.9+git6f2ad16d1.dirty
```
It imports again, but I get the same problem as before when I try to calculate SOAP

**Comment by noambernstein** [comment]
There’s some python package that’s missing, which is why it’s complaining
about the bdist_wheel.  I think you need to do “pip  install wheel”.  I
doubt you’re getting the new quippy. Assuming you know where it’s
installing, you may want to delete it manually and try the pip install
again, to make sure your installed copy is the latest one.

**Comment by lydiash** [comment]
Ok, I tried `pip install wheel` and it says : `Requirement already satisfied: wheel in ./environments/quippy/lib/python3.8/site-packages (0.37.1)` Are you saying I should delete quippy manually or delete wheel?

**Comment by lydiash** [comment]
I just deleted anything quippy related in `./environments/quippy/lib/python3.8/site-packages`, which contained
```
quippy/                     quippy_ase-0.9.9.dist-info/ quippy_ase.libs/
```
 and then tried `pip install quippy-ase` and now it seems to be working! Thank you very much for your help.

**Comment by bernstei** [comment]
By the way, is there a reason you're not just using the pypi version with `pip install quippy-ase`, but instead compiling your own copy?

**Comment by lydiash** [comment]
I'm not sure I knew that was an option. Is that documented somewhere that I missed? I was following the directions found [here](https://libatoms.github.io/GAP/installation.html#compilation-instructions)

**Comment by bernstei** [comment]
It's documented in the QUIP top level README pointed to from https://libatoms.github.io/QUIP/install.html, but apparently not the GAP docs.

**Comment by bernstei** [comment]
Before we dive into this complex system, is there a reason you're not using `pip install quippy-ase`, which is pre-compiled for you ?
