### ISSUE TITLE
GAP docs don't mention quippy-ase

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#525]
The GAP installation docs in https://libatoms.github.io/GAP/installation.html do not mention the easy option of `pip install quippy-ase`, unlike the QUIP README, which is also linked to from https://libatoms.github.io/QUIP/install.html

**Comment by jameskermode** [comment]
I suggest the duplicate instructions should be removed and replaced with a link, that way they won’t go out of date.

**Comment by gabor1** [comment]
I see that now the libatoms.github.io/QUIP page says "look at GAP or QUIP/Readme.md", and libatoms.github.io/GAP has an explicit and detailed instructions. I suggest removing the latter and just leave a single copy, the Readme.md of QUIP
