### ISSUE TITLE
Lammps compilation with quip

### ISSUE THREAD

**Issue by sandipde** [libAtoms/QUIP#526]
Hi  I am trying to compile latest lammps with quip activated. Followed the documentation chain and  tried using 

-D QUIP_LIBRARY=<path_to_libquip.a>
For lammps cmake. It says the flag is ignored. 
 ![IMG_20220726_180334.jpg](https://user-images.githubusercontent.com/11316489/181073060-06eb4ca5-a355-42a3-b2b1-84cecff82d81.jpg)

Is the document outdated? 
Thanks a lot in advance.

**Comment by albapa** [comment]
I haven't yet compiled LAMMPS with cmake. Others (@jameskermode) may have more experience...

**Comment by noambernstein** [comment]
I definitely have used cmake, pretty sure it’s with QUIP. I’ll check what I
did.

**Comment by sandipde** [comment]
I figured out later that day only. One needs to add -DPKG_ML-QUIP-ON flag for lammps to take rest of the flags. Someone have to update the readme at lammps website.

**Comment by bernstei** [comment]
I believe that LAMMPS cmake (at least a recent github version, not sure about tagged releases) downloads its own QUIP.
