### ISSUE TITLE
gap_fit segfault in MPI fitting

### ISSUE THREAD

**Issue by stenczelt** [libAtoms/QUIP#528]
I have noticed on Archer2, that `gap_fit` fails with a segmentation fault after sparsification has  been done, in QR. I have further found that this only happens with `-O2` and above, not below that.

This is more of a retrospective log of the issue I have been trying to solve this weekend, but I think it is worth saving the details of the investigation.

Compiler & machine:
Archer2, using the `archer2_mpich+openmp` arch file & the associated module suggestions from QUIP.
- cray-libsci/21.08.1.2
- cray-mpich/8.1.15
- GNU Fortran (GCC) 11.2.0 20210728 (Cray Inc.)

The error occurs when compiled normally and fitting a model, where sparsification & associated descriptor-wise input files have been generated. After that, you run the MPI fitting program and get the following:
```
Finished sparse covariance matrix calculation of coordinate 5
TIMER: gpFull_covarianceMatrix_sparse_Coordinate5_sparse  done in 575.94637200000000 cpu secs, 9.9617995978333056 wall clock secs, 9.9618018930000289 mpi wall secs.
TIMER: gpFull_covarianceMatrix_sparse_Coordinate5         done in 576.12422500000002 cpu secs, 9.9647188088856637 wall clock secs, 9.9647200529999509 mpi wall secs.
TIMER: gpFull_covarianceMatrix_sparse_FunctionValues      done in .34000000027845090E-004 cpu secs, .34696888178586960E-004 wall clock secs, .34687000038502447E-004 mpi wall secs.
TIMER: gpFull_covarianceMatrix_sparse                     done in 619.57809199999997 cpu secs, 10.650316021870822 wall clock secs, 10.650316051999994 mpi wall secs.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2b3eddca549f in ???
libAtoms/GAP#1  0x7902d0 in ???
libAtoms/QUIP#497  0x72ae06 in ???
libAtoms/QUIP#516  0x407c8a in ???
libAtoms/QUIP#496  0x40741e in ???
libAtoms/GAP#5  0x2b3eddc90349 in ???
libAtoms/QUIP#517  0x407459 in ???
	at ../sysdeps/x86_64/start.S:120
libAtoms/GAP#7  0xffffffffffffffff in ???
srun: error: nid004030: task 1: Segmentation fault (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=2273322.0
slurmstepd: error: *** STEP 2273322.0 ON nid004030 CANCELLED AT 2022-09-03T17:12:18 ***
srun: error: nid004030: task 0: Terminated
srun: Force Terminated StepId=2273322.0
```

Then, recompiling with debug flags, the error disappeared. Moving up in optimisation flags, `-O1` is OK, but `-O2` is not. 

I have bisected the code and found that the error was happening in:
https://github.com/libAtoms/QUIP/blob/d5a6af313f3e55a11d29cb79a4781dfab101006e/src/libAtoms/MPI_context.f95#L1647

Where it turns out, that `v_in` (array to be scattered) which is the array to be scattered is different between the compiler optimisation levels. If I understand correctly, this is the square matrix of the sparse points which is constructed temporarily on the root process and gets distributed between the workers. This is not allocated on the worker processes, but is then passed through a number of subroutine calls. Apparently this leads to the array being of shape (0, 0) on `-O1` but from `-O2` this has shape (1, 1) with memory error raised if you want to index into it.

So what happens is:
1. `gp_predict.f95`: `gpSparse_fit` allocates `factor_c_subYsubY` on the root process only, trying to scatter it, so everyone stores parts of it in the varaible called `a` (what a non-descriptive variable name :( )
    - https://github.com/libAtoms/GAP/blob/c0571e94920ee673976416287b48bbb788d38896/gp_predict.f95#L819
2. `gp_predict.f95`: `scatter_shared_task` gets an unallocated variable and passes it forward to 'scatterv' 
   - input variable is simply `real(qp), intent(inout) :: factor_c_subYsubY(:,:)`
   - https://github.com/libAtoms/GAP/blob/c0571e94920ee673976416287b48bbb788d38896/gp_predict.f95#L950
3. `MPI_comtext.f95`: `MPI_context_scatterv_real2` passes this into `MPI_scatterv`
   - at this point, the array is shape (0, 0) on `-O1` but from `-O2` this has shape (1, 1) with memory error raised if you want to index into it.

It appears though, that if you simply allocate an empty array at the top level for `factor_c_subYsubY` then it just works, see PR soon.

**Comment by jameskermode** [comment]
Thank you for digging into this so thoroughly. I’m sure @Sideboard  will be in touch when he’s back from annual leave next week

**Comment by stenczelt** [comment]
Here is a patch file to highlight the issue.
For some reason the browser does not let me attach it as a file.

```
Index: src/libAtoms/MPI_context.f95
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/libAtoms/MPI_context.f95 b/src/libAtoms/MPI_context.f95
--- a/src/libAtoms/MPI_context.f95	(revision d5a6af313f3e55a11d29cb79a4781dfab101006e)
+++ b/src/libAtoms/MPI_context.f95	(date 1662320576362)
@@ -1614,6 +1614,8 @@
   integer :: my_root, err, i, count
   integer, allocatable :: displs(:)
 
+  integer :: rank, comm_size, ierr
+
   INIT_ERROR(error)
 
   if (.not. this%active) then
@@ -1643,6 +1645,17 @@
   else
     allocate(displs(1), source=0)
   end if
+
+  call print('allocations done')
+
+  ! print on ALL PROCESSES to find the mismatched stuff
+  call MPI_COMM_RANK(this%communicator, rank, ierr)
+  print *, 'MPI-DEBUG: shapes on: ', rank, ':  v_in', shape(v_in),   'v_out:', shape(v_out)
+  if (size(v_in) > 0) then
+    print *, 'MPI-DEBUG: v_in(1, 1) on: ', rank, ':  ', v_in(1, 1)
+  else
+    print *, 'MPI-DEBUG: v_in(1, 1) on: ', rank, ':  size = 0'
+  end if
 
   call MPI_scatterv(v_in, counts, displs, MPI_DOUBLE_PRECISION, v_out, count, MPI_DOUBLE_PRECISION, my_root, this%communicator, err)
   PASS_MPI_ERROR(err, error)
Index: src/GAP/gp_predict.f95
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/GAP/gp_predict.f95 b/src/GAP/gp_predict.f95
--- a/src/GAP/gp_predict.f95	(revision c0571e94920ee673976416287b48bbb788d38896)
+++ b/src/GAP/gp_predict.f95	(date 1662319551379)
@@ -754,6 +754,7 @@
 
       character(len=STRING_LENGTH) :: my_condition_number_norm
 
+      integer :: rank, ierr
       integer :: i, j, mb_A, nb_A
       integer :: i_coordinate, i_sparseX, i_global_sparseX, n_globalSparseX, n_globalY, i_y, i_yPrime, &
       i_globalY, i_global_yPrime, nrows
@@ -814,14 +815,20 @@
 
       a(1:n_globalY,:) = transpose(c_subYY_sqrtInverseLambda)
       if (allocated(c_subYY_sqrtInverseLambda)) deallocate(c_subYY_sqrtInverseLambda)
-
       if (task_manager%active) then
+         ! print on ALL PROCESSES to find the mismatched stuff
+         call MPI_COMM_RANK(task_manager%MPI_obj%communicator, rank, ierr)
+         if (allocated(factor_c_subYsubY)) then
+            print *, 'MPI-DEBUG: factor_c_subYsubY on: ', rank, ': allocated', allocated(factor_c_subYsubY), "shape:", shape(factor_c_subYsubY)
+         else
+            print *, 'MPI-DEBUG: factor_c_subYsubY on: ', rank, ': allocated', allocated(factor_c_subYsubY)
+         end if
+
          call scatter_shared_task(task_manager, factor_c_subYsubY, a, n_globalY, n_globalSparseX, from%do_subY_subY)
       else
          a(n_globalY+1:,:) = factor_c_subYsubY
       end if
       if (allocated(factor_c_subYsubY)) deallocate(factor_c_subYsubY)
-
       if (my_condition_number_norm(1:1) /= ' ') then
          if (task_manager%active) then
             call print_warning("Condition number of distributed matrix is not implemented.")
@@ -870,6 +877,8 @@
       if(allocated(a)) deallocate(a)
       if(allocated(globalY)) deallocate(globalY)
       if(allocated(alpha)) deallocate(alpha)
+
+      call print('END HAVE_QR block')
 #else
       allocate( c_subYY_inverseLambda(n_globalSparseX,n_globalY), c_subYY_inverseLambda_c_YsubY(n_globalSparseX,n_globalSparseX), &
 !      inverse_q_subYsubY(n_globalSparseX,n_globalSparseX), inverse_c_subYsubY(n_globalSparseX,n_globalSparseX), &
```

**Comment by stenczelt** [comment]
@jameskermode it is significantly easier to fix than finding it :)
