### ISSUE TITLE
File required to perform gap2b gap3b and soap !! If anyone can provide sample jupiter file that will be helpful !

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#529]
Please help as soon as possible

**Comment by gabor1** [comment]
I am not sure which file you are looking for. Can you give the python or command line you are trying to execute together with any output that shows your problem?

**Comment by Amitcuhp** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_3802/1247473112.py in <module>
----> 1 qm_energies = [at.info['energy'] for at in db]
      2 gap2b_energies = []
      3 for dba in db:
      4     a = dba.copy()
      5     a.set_calculator(gap2b)

/tmp/ipykernel_3802/1247473112.py in <listcomp>(.0)
----> 1 qm_energies = [at.info['energy'] for at in db]
      2 gap2b_energies = []
      3 for dba in db:
      4     a = dba.copy()
      5     a.set_calculator(gap2b)

KeyError: 'energy'



Following this tutorial : Not able to run the tutuorial 
https://libatoms.github.io/GAP/gap_si_surface.html

Can you run this tutorial and send this to me . This found be very thankful to you

**Comment by gabor1** [comment]
The tutorial is a bit out of date (not the GAP parts but the ASE parts). We are discussing what to do about it.

**Comment by Amitcuhp** [comment]
Can you tell me how to make .xyz file in ascending order according to energy.
it would be helpful

**Comment by gabor1** [comment]
I do not understand what you mean by "ascending order" in this context. full info on xyz files is here https://github.com/libAtoms/extxyz which also shows you examples of how to generate them using ASE.
