### ISSUE TITLE
quippy documentation and cleanup

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#53]
This is mostly a wishlist and collection for miscellaneous documentation and code cleanup tasks I'd like to work on, either at the hackathon or whenever one of us gets the chance:

- [ ] Document (in readable, searchable, web and pdf format) initialization of `Potential` and the most important Potentials, e.g. `GAP`, see #52 
- [ ] Make a tutorial or some basic guidance on implementing a new Potential, both in Fortran and in quippy (might help create more uniformity, e.g. in how potentials handle common parameters)
- [ ] Think about deprecating `FortranArray` (I know this has been discussed before; maybe it deserves its own issue)

**Comment by gabor1** [comment]
replaced with the TODO list
