### ISSUE TITLE
How to make train.xyz file in ascending order of energies?

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#532]
Can you tell me how to make .xyz file in ascending order according to energy.
it would be helpful

**Comment by bernstei** [comment]
This is a generic ASE/python question, nothing to do with QUIP. You're better off asking someplace related to ASE.

**Comment by bernstei** [comment]
[Sorry - accidentally sent during editing]

This is a generic ASE/python question, nothing to do with QUIP. You're better off asking someplace related to ASE.  However, out of the generosity of my heart
python -c 'import ase.io<http://ase.io>; ase.io<http://ase.io>.write("sorted.xyz<http://sorted.xyz>", sorted(ase.io<http://ase.io>.read("configs.xyz<http://configs.xyz>"), key=lambda atoms: atoms.info<http://atoms.info>["REF_energy"]))'
or something like that should work, if you make all the filenames and energy info key consistent with what you have

**Comment by Amitcuhp** [comment]
Can you please tell me if I have positions file how can i get forces using that ase file

**Comment by bernstei** [comment]
Still an ASE question.  Run a DFT calculation and append the force data to each atom's row and add the "forces" item to the Properties field according to the extxyz format syntax https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#extxyz
