### ISSUE TITLE
How can I treat pseudo-hydrogens?

### ISSUE THREAD

**Issue by yonghyuklee** [libAtoms/QUIP#535]
Dear *,

I want to train the GAP for the system including various pseudo-hydrogens. Is it possible to define the same element several times with different atom energies--marking with different atom labels?

Many thanks!

**Comment by bernstei** [comment]
I don't think there's support for anything except atomic numbers, but you can make fictitious ones for your pseudo-hydrogens.   There's no physical meaning attached to the number except perhaps default atomic masses that you can override. Note that if you're going to use ASE (python) at any point, it does not support atomic numbers outside the periodic table range, so you should pick fictitious numbers within that, e.g. 101, 102, etc, which shouldn't conflict with anything assuming you aren't planning to simulate unstable radioactive elements at any point.

**Comment by yonghyuklee** [comment]
Thanks a lot for the prompt reply. This makes sense. How then can I override the default atomic masses? Can I do it with some simple commands or should I modify the source code?

**Comment by bernstei** [comment]
On Dec 30, 2022, at 10:35 AM, yonghyuklee ***@***.******@***.***>> wrote:

Thanks a lot for the prompt reply. This makes sense. How then can I override the default atomic masses? Can I do it with some simple commands or should I modify the source code?

It only matters for MD, not for fitting or energy minimization, and it depends on what exactly you're doing:  QUIP vs. ASE vs. LAMMPS all have different ways to set masses.

**Comment by yonghyuklee** [comment]
Oh, I see. It is then very clear for me to do so. I appreciate your help. I would close the thread. Happy new year!
