### ISSUE TITLE
md and vasp_driver binaries missing from pypi installation

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#539]
I just did a fresh `python3 -m pip install quippy-ase`, and while it creates an  entry point in `$PREFIX/bin/md`, the actual executable in `$PREFIX/lib64/python3.9/site-packages/quippy/md` does not exist. The only executables there are `gap_fit` and `quip`.  This appears to be the case for a wheel I installed last Nov 22, as well, although I didn't notice until now.  An earlier version from Sep 2022 is fine. It looks like `vasp_driver` has the same issue.

Anyone (@jameskermode ?)  know what might have changed?

**Comment by jameskermode** [comment]
I think I know why this is. Wheel building moved from quippy-wheels repo to this one at about that point, and I must have forgotten to add those binaries. Can be re-added to `build-wheels.yaml` workflow.

**Comment by bernstei** [comment]
Thanks.  Can you do it, or give me a pointer?

**Comment by jameskermode** [comment]
Add two more `cp` statements after this line 
https://github.com/libAtoms/QUIP/blob/public/.github/workflows/prepare-wheel-build.sh#L46

**Comment by bernstei** [comment]
Thanks.  I'll do a PR, and maybe add a test
