### ISSUE TITLE
Update element masses to IUPAC 2016

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#54]
IUPAC regularly update the masses of the elements based on the precision with which isotope masses and their abundance can be measured. Recently, ase adopted the most recent published values, and for cases where the mass can only be given as a range, they defer to the recommended 'conventional' values with 5 significant figures: https://gitlab.com/ase/ase/merge_requests/360 changed values: https://gitlab.com/ase/ase/commit/0db997027eabb7da6c5cab9f1341955cdf045b9f 

I suggest that QUIP(py) adopt the same values. Unfortunately, changing the values will affect dynamics, phonons, etc where the masses have not been explicitly set, but I think it is a change that needs to be done. (maybe worth updating CODATA units at the same time?) If anyone has any strong opinions on this, I'd be happy to hear them!

At the moment dynamicalsystem tests fail with ase's git master.

**Comment by gabor1** [comment]
In general I think it’s a good idea to stay current. 

-- Gábor
