### ISSUE TITLE
Published data question

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#546]
Hello Developers,
  Can you please show me where to find the supplemental material file for 
"An accurate and transferable machine
learning potential for carbon"?   (I have the erratum file.)
Also, what is the difference between this training file "General_Carbon_V10_2_4000_All_GAP_17_Unique_LD_Iteration_1.xyz"
and the one available in the download list  "Carbon_GAP_20_Training_Set.xyz" ?
If they are different, how to obtain the first one?
Thanks so much.

**Comment by gabor1** [comment]
We only release the file for the updated potential, not the original one. The training file just got renamed to the shorter name.
