### ISSUE TITLE
Descriptor initializing error

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#547]
Dear People,
 I am only trying to replicate making the Carbon_GAP_20 potential from your files.
I tried to run the gap_fit with your published gap_fit command, with sparsify_only_no_fit=T on my laptop to test initially.  I just reinstalled the QUIP/GAP software today. Ubuntu 18.04.    I get this error:       Please help?  Thanks.
```
SYSTEM ABORT: Traceback (most recent call last)
File "/project/src/GAP/gp_predict.f95", line 1258 kind unspecified
gpFull_addCoordinates: object full, no more descriptors can be added            
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 1
```
Here is the gap_fit command copied from the data website:
```
gap_fit \
atoms_filename=Carbon_GAP_20_Training_Set.xyz \
at_file=Carbon_GAP_20_Training_Set.xyz \
gap=\
{distance_2b \
n_sparse=15 \
theta_uniform=1.0 \
sparse_method=uniform \
covariance_type=ard_se \
cutoff=4.5 \
delta=2.0 \
: \
angle_3b \
n_sparse=200 \
theta_uniform=1.0 \
sparse_method=uniform \
covariance_type=ard_se \
cutoff=2.5 \
delta=0.05 \
: \
soap \
n_max=12 \
l_max=4 \
atom_sigma=0.5 \
zeta=4.0 \
cutoff=4.5 \
cutoff_transition_width=1.0 \
central_weight=1.0 \
n_sparse=9000 \
delta=0.2 \
covariance_type=dot_product \
sparse_method=cur_points \
radial_decay=-0.5} \
default_sigma={0.001 0.01 0.05 0.0} \
energy_parameter_name=energy \
force_parameter_name=force \
virial_parameter_name=virial \
do_copy_at_file=F \
sparse_jitter=1.0e-8 \
sparsify_only_no_fit=T \
gp_file=Carbon_GAP_20ours.xml \
core_ip_args={IP Glue} \
core_param_file=r6_innercut.xml \
config_type_sigma={Liquid:0.050:0.5:0.5:0.0: \
Liquid_Interface:0.050:0.5:0.5:0.0: \
Amorphous_Bulk:0.005:0.2:0.2:0.0: \
Amorphous_Surfaces:0.005:0.2:0.2:0.0: \
Surfaces:0.002:0.1:0.2:0.0: \
Dimer:0.002:0.1:0.2:0.0: \
Fullerenes:0.002:0.1:0.2:0.0: \
Defects:0.001:0.01:0.05:0.0: \
Crystalline_Bulk:0.001:0.01:0.05:0.0: \
Nanotubes:0.001:0.01:0.05:0.0: \
Graphite:0.001:0.01:0.05:0.0: \
Diamond:0.001:0.01:0.05:0.0: \
Graphene:0.001:0.01:0.05:0.0: \
Graphite_Layer_Sep:0.001:0.01:0.05:0.0: \
Single_Atom:0.0001:0.001:0.05:0.0} \
```

**Comment by MES-physics** [comment]
Hmm... I got it to work now, I think I had a mistaken space after the last line of the command, after the \.  Is this what may have caused the error? 
Thanks.

**Comment by MES-physics** [comment]
No, that's not the reason , still getting error:    Please help.  See gap_fit command above.
```
SYSTEM ABORT: proc=0 Traceback (most recent call last)
File "gp_predict.f95", line 1331 kind unspecified
gpFull_addCoordinateDerivatives: object full, no more descriptors can be added            
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by albapa** [comment]
I think you should run this first pass in serial.

**Comment by MES-physics** [comment]
Thanks, yes, sorry for confusion, I did run the sparsification only in serial, got the input conversion files, etc. as in the docs, and that finally worked on my laptop.  Then I put it in MPI for the fitting run. And that error popped up about descriptors.  Here is the error again:
```
SYSTEM ABORT: Traceback (most recent call last)
File "/project/src/GAP/gp_predict.f95", line 1258 kind unspecified
gpFull_addCoordinates: object full, no more descriptors can be added            
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 1
```
  Here is the MPI gap_fit command:
```
gap_fit \
atoms_filename=Carbon_GAP_20_Training_Set.xyz \
at_file=Carbon_GAP_20_Training_Set.xyz \
gap = \
{distance_Nb \
order=2 \
n_sparse=15 \
theta_uniform=1.0 \
sparse_method=FILE \
sparse_file=1.input \
covariance_type=ard_se \
cutoff=4.5 \
delta=2.0 \
: \
angle_3b \
n_sparse=200 \
theta_uniform=1.0 \
sparse_method=FILE \
sparse_file=2.input \
covariance_type=ard_se \
cutoff=2.5 \
delta=0.05 \
: \
soap \
n_max=12 \
l_max=4 \
atom_sigma=0.5 \
zeta=4.0 \
cutoff=4.5 \
cutoff_transition_width=1.0 \
central_weight=1.0 \
n_sparse=9000 \
delta=0.2 \
covariance_type=dot_product \
sparse_method=FILE \
sparse_file=3.input \
radial_decay=-0.5} \
default_sigma={0.001 0.01 0.05 0.0} \
default_kernel_regularisation={0.001 0.01 0.05 0.0} \
energy_parameter_name=energy \
force_parameter_name=force \
virial_parameter_name=virial \
do_copy_at_file=F \
sparse_jitter=1.0e-8 \
sparsify_only_no_fit=F \
sparse_separate_file=T \
openmp_chunk_size=10000 \
gp_file=Carbon_GAP_20ours.xml \
core_ip_args={IP Glue} \
core_param_file=r6_innercut.xml \
config_type_sigma={Liquid:0.050:0.5:0.5:0.0: \
Liquid_Interface:0.050:0.5:0.5:0.0: \
Amorphous_Bulk:0.005:0.2:0.2:0.0: \
Amorphous_Surfaces:0.005:0.2:0.2:0.0: \
Surfaces:0.002:0.1:0.2:0.0: \
Dimer:0.002:0.1:0.2:0.0: \
Fullerenes:0.002:0.1:0.2:0.0: \
Defects:0.001:0.01:0.05:0.0: \
Crystalline_Bulk:0.001:0.01:0.05:0.0: \
Nanotubes:0.001:0.01:0.05:0.0: \
Graphite:0.001:0.01:0.05:0.0: \
Diamond:0.001:0.01:0.05:0.0: \
Graphene:0.001:0.01:0.05:0.0: \
Graphite_Layer_Sep:0.001:0.01:0.05:0.0: \
Single_Atom:0.0001:0.001:0.05:0.0} \
```

**Comment by albapa** [comment]
Thanks. It'd be useful to see the entire output of the second `gap_fit` command.

**Comment by MES-physics** [comment]
Output file:
[GAP_20ours-408717.txt](https://github.com/libAtoms/QUIP/files/10530016/GAP_20ours-408717.txt)

**Comment by albapa** [comment]
This is an odd error. Since you're only using 1 MPI process, can you try to run a direct fit, i.e. with `sparsify_only_no_fit=F` once with a serial code?

**Comment by MES-physics** [comment]
You mean with the same gap_fit command as my MPI 
one above? Previously when I ran the serial code on so much data, it took over 6 days, and I’m not sure I can get enough memory on a node, but I’ll try.

**Comment by MES-physics** [comment]
I have it working over 20 minutes now on serial with no errors, so may as well let it run and see what happens.   
Thanks.

**Comment by albapa** [comment]
> You mean with the same gap_fit command as my MPI
one above? Previously when I ran the serial code on so much data, it took over 6 days, and I’m not sure I can get enough memory on a node, but I’ll try.

In the output that you sent above, you were running it with 1 MPI process. It is (almost) equivalent to running it in serial. Simply because you compiled it with MPI, it won't magically use less memory or run faster!

But if this runs for you in serial without an error, it should give us an indication and perhaps some pointers for reproducing the error that you observed.

**Comment by MES-physics** [comment]
Unfortunately it stopped now with the same error:
```
SYSTEM ABORT: Traceback (most recent call last)
File "/io/QUIP/src/GAP/gp_predict.f95", line 1211 kind unspecified
gpFull_addCoordinateDerivatives: object full, no more descriptors can be added            
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 1
```
Here's the output file
[GAP20Norm-410693.txt](https://github.com/libAtoms/QUIP/files/10530760/GAP20Norm-410693.txt)
.

**Comment by albapa** [comment]
I think you may be dealing with an integer overflow here. For some reason, `distance_Nb` is used instead of the the original `distance_2b` - this *may* be a reason why the original worked. `distance_Nb order=2` is equivalent, but generates more descriptors. Alternatively, I'd think that if you used more than 1 MPI process, if might also work as this would distribute the data so the index wouldn't overflow.

**Comment by MES-physics** [comment]
I will try these and get back soon.
Thanks for working on a Sunday!

**Comment by MES-physics** [comment]
Also I don't know why it always says MPI is only 1 process, when I'm requesting these:            (Is there something else missing?)
```
#SBATCH   --nodes=2                         
#SBATCH   --ntasks-per-node=2
#SBATCH   --cpus-per-task=64
```

**Comment by Sideboard** [comment]
What command do you use to run the program, `srun ...` or `mpirun ...`?

**Comment by bernstei** [comment]
Those queuing system header lines only guarantee that you're allocated that many cores/nodes. As Sascha said, depending on your queuing system and MPI version, you may or may not need to specify something to the command that runs the executable to actually use them.

**Comment by MES-physics** [comment]
Oh oh,  when submitting a slurm batch file with those headers, do you need to put “srun “  before the gap_fit command? Or only do that when submitting by only a command line?
All I have is the gap_fit command after those headers and some other specifications, like ulimit, etc. 
Is this a question for my admin?

**Comment by bernstei** [comment]
There are no systems that I know of where you have to do nothing.  You might use srun, or mpirun, or mpiexec, or something else, that depends on your system, but you have to do something.

**Comment by MES-physics** [comment]
OK great, thanks.  I also saw your post from awhile back saying to wrap the gap_fit command in a bash script to put in the srun command. I will try these things.  I appreciate it!

**Comment by Sideboard** [comment]
FYI: You could have a look at `gap_fit`'s argument `config_file`. With that you can put all the other arguments into a file and don't have to care about backslashing all newlines and the shell does not eat up special characters, although that does not seem to be a problem in your case.
