### ISSUE TITLE
Simplify MPI workflow

### ISSUE THREAD

**Issue by Sideboard** [libAtoms/QUIP#548]
Seeing another case of 'gap = distance + soap' with five species for a total of 15+5 descriptors, reinforced that there needs to be a simplification for the MPI workflow (run non-MPI, convert sparseX, extend to explicit gap strings, run MPI). Initially this was a simple solution using already available options, and we could avoid parallelising the sparsification itself, which would make the code much more complicated.

Possible solutions (unordered, numbers for reference):
1. Make `sparse_method=file` work with `add_species=T`.
  a. Use default naming scheme. (simple)
  b. Use placeholder in `sparse_file` for iteration number.
2. Output a ready-to-copy converted full gap string to output and/or xml.
3. Provide a Slurm script template, which does all the steps. It would run serial on the MPI job for "a few minutes" while the other nodes/processes are idle.
4. Single-run
  a. Implement MPI sparsification after all. (Possible but I'd advise against it.)
  b. One process does sparsification first (with all data) then joins in with distributed data.
  c. One process reads both distributed (with derivatives) and all (without derivatives) data, determines sparse points, drops the "all" part. (Higher memory usage, probably least invasive single-run solution.)

**Comment by Sideboard** [comment]
Changed 4 into 4a.

Added 4b, where one process reads all data as in a sparsify run (i.e. without derivatives), then reads in its own data only. The other processes have to wait. Involves reallocating the data for that process.

Added 4c, where the root process does not have to read in the data a second time but has two copies, the distributed one and the complete (but without derivatives), which gets deallocated after sparsification.

**Comment by jameskermode** [comment]
Either 4b or 4c seem the best options to me. @gabor1 and @albapa what do you think?

**Comment by gabor1** [comment]
Why is 4c particularly high memory?

**Comment by gabor1** [comment]
Either 4b or 4c looks ok for me, whichever is easiest to implement

**Comment by albapa** [comment]
I think 4b is higher in memory because initially a process stores both the derivatives belonging to it as well as all the descriptors. The reason this is not worrying me too much is that the (all) descriptor storage is practically *distributed*, at least within the node where the root process lives. Since the two-step process remains an option, a tricky fitting could still be done in the old way if 4b exceeds the memory. So I'd go with 4c if that's the easiest.
