### ISSUE TITLE
Gaussian Approximation Potential of EC/EMC Solvent

### ISSUE THREAD

**Issue by lastconnor123** [libAtoms/QUIP#551]
Hello QUIP package managers,

I found a jupyter notebook written by Ioan-Bogdan Magdău and Gábor Csányi titled "Gaussian Approximation Potential of EC/EMC Solvent". I am interested in it as it provides a detailed step-by-step guide for building custom interatomic potentials using GAP and Quippy. 

I found this notebook nearly a year ago but can't find its source. In the interest of being able to cite it, I'd like to know its source. I thought I remembered finding it in this git repository but since I no longer can I suspect it has since been removed. If it is available elsewhere please let me know.

The notebook should be attached in a .zip file with this message

[GAP_ECEMC_potential.zip](https://github.com/libAtoms/QUIP/files/10671662/GAP_ECEMC_potential.zip)

**Comment by imagdau** [comment]
Hi,

Here's the notebook deepnote
<https://deepnote.com/workspace/ioan-bogdan-magdau-00195eee-2451-4f21-a901-fac6c0d22b2c/project/GAP-liquid-solvent-tutorial-ca2046f3-c62f-4f79-92cb-f1198bcebf68/notebook/notebook-0fad9c7b042442a685d779c770a01c64>
We also have a related manuscript in review
10.26434/chemrxiv-2022-l4tb9
<https://doi.org/10.26434/chemrxiv-2022-l4tb9>

Best wishes,
Ioan
