### ISSUE TITLE
GAP_fit MPI: unexpected out-of-memory

### ISSUE THREAD

**Issue by tcnicholas** [libAtoms/QUIP#554]
Dear GAP developers and users,

I am using the MPI version of GAP to fit a potential. This has been a fantastic tool because my system contains 4 elements; thank you!

I am running experiments where I test the quality of the potential as a function of SOAP cut-off (I end up with the same result with both soap and soap_turbo descriptors). I am able to produce the sparse files "sparsify_only_no_fit=T" okay, and up to a given cutoff can fit the full potential in the subsequent step by making use of the MPI gap_fit.

However, above certain cutoffs my fits are terminated "by the cgroup out-of-memory handler". The job competes the memory estimation task. One such example (rcut=6.0 Å) gave a PEAK1=4427 MB, PEAK2=230 MB, PEAK=  4427 MB for the fitting. (I have access to 512 GB nodes, here there was 217 GB free memory reported during this memory evaluation), here running the fitting with 8 nodes (though I also get the same error in tests with 16 and 24 nodes).

My current understanding is that the SOAP cut-off doesn't affect the descriptor size, but might have a too large spike in memory requirements during the calculation of the descriptor? I am also not certain exactly how the memory estimates are determined for the MPI fit?

Any advice or suggestions on how to interpret the memory estimations and why it does not work for my use-case would be appreciated. Thank you.

---
git version  https://github.com/libAtoms/QUIP.git,v0.9.12-11-gbebe7183b-dirty
QUIP_ARCH    archer2_mpich+openmp
compiled on  Feb 13 2023 at 16:10:57

**Comment by gabor1** [comment]
The cutoff affects the descriptor derivatives. that's the largest memory hog by far

**Comment by albapa** [comment]
What is the mpi/openmp ratio? How many cores per node?

**Comment by tcnicholas** [comment]
These are running on AMD EPYC 7742 64-core processor × 2 nodes.

**Comment by albapa** [comment]
You didn't say, but does that mean you used 128 MPI processes? I suggest you try a different combo, such as 16 MPI with 8 OpenMP or 32 MPI with 4 OpenMP, that should get rid of a lot of overhead which may be causing the memory problems.

**Comment by tcnicholas** [comment]
Yes, that was the problem. I was attempting to use too many MPI processes. Thank you!
