### ISSUE TITLE
Problem Installing Lammps with QUIP  -gnu compiler on Ubuntu

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#556]
Sorry if this is a repeat, I didn't know if anyone reads comments after an issue closes.
I'm trying to install Lammps with QUIP and get these same errors you got before, for latest stable Lammps and latest QUIP/GAP, on my Ubuntu 18.04 laptop, with linux_x86_64_gfortran.  I installed QUIP first as told in instructions I saw.    I enabled MANYBODY and ML_QUIP before building, and linked by editing the ```QUIP_ROOT``` and ```QUIP_ARCH =``` in the Makefile.lammps.  
Can you help?
```
liblammps.so.0: undefined reference to `quip_lammps_potential_initialise'
liblammps.so.0: undefined reference to `quip_lammps_wrapper'
liblammps.so.0: undefined reference to `quip_lammps_api_version'
collect2: error: ld returned 1 exit status
CMakeFiles/lmp.dir/build.make:107: recipe for target 'lmp' failed
make[2]: *** [lmp] Error 1
CMakeFiles/Makefile2:668: recipe for target 'CMakeFiles/lmp.dir/all' failed
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by albapa** [comment]
I think the new lammps CMAKE system takes care all of that - it clones and compiles QUIP and there is no need to supply it. Unless you want a custom QUIP, I'd suggest you follow this route.

**Comment by MES-physics** [comment]
Thanks! It worked to compile Lammps properly now.
