### ISSUE TITLE
Get unreasonable amorphous models by GAP potentials

### ISSUE THREAD

**Issue by Baristali** [libAtoms/QUIP#557]
Dear QUIP developers and users,

I'm fitting a GAP potentials for a binary system (Sb and Te). In my case, I successfully get a GAP potentials wiht 2b_distance and soap descriptors by mpi version. I tried to get an amorphous models by the molten-quench simulations, but the amorphous model I got is very stange, which has a large void in the box. I attched the amorphous models, obtained from aimd and gap-md, respectively. Does anyone can give me some suggestions?
 
![2](https://user-images.githubusercontent.com/50040885/220576641-e542d5b5-47b5-497b-bc14-3bdff45713bd.png)

![1](https://user-images.githubusercontent.com/50040885/220576362-342ba289-e00f-4875-b04b-18bb43c7188b.png)

My command line for training GAP potentials is
In serial version, 
`at_file=atoms_db.xyz
gap={distance_2b cutoff=6.0
                 compact_clusters=T
                 cutoff_transition_width=0.5
                 delta=1.0
                 covariance_type=ARD_SE
                 theta_uniform=1.0
                 n_sparse=20
                 add_species=T
                 sparse_method=uniform:
     soap        cutoff=5.5
                 covariance_type=dot_product
                 zeta=4
                 central_weight=1.0
                 f0=0.0
                 delta=0.2
                 cutoff_transistion_width=0.5
                 config_type_n_sparse={dimer:30:primite:1000:crystal:1000:md:1600}
                 atom_sigma=0.5
                 l_max=4
                 n_max=12
                 add_species=T
                 sparse_method=cur_points}
default_sigma={0.002 0.2 0.2 0.0}
energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=virial
sparse_jitter=1.0e-8
do_copy_at_file=F sparse_separate_file=T sparsify_only_no_fit=T
openmp_chunk_size=10000
gp_file=gap.xml`

and in mpi version,
`at_file=atoms_db.xyz
gap={distance_2b cutoff=6.0
                 compact_clusters=T
                 cutoff_transition_width=0.5
                 covariance_type=ARD_SE
                 theta_uniform=1.0
                 n_sparse=20
                 delta=1.0
                 add_species=F
                 Z1=51
                 Z2=51
                 sparse_method=file
                 sparse_file=1.input:
     distance_2b cutoff=6.0
                 compact_clusters=T
                 cutoff_transition_width=0.5
                 covariance_type=ARD_SE
                 theta_uniform=1.0
                 n_sparse=20
                 delta=1.0
                 add_species=F
                 Z1=51
                 Z2=52
                 sparse_method=file
                 sparse_file=2.input:
     distance_2b cutoff=6.0
                 compact_clusters=T
                 cutoff_transition_width=0.5
                 covariance_type=ARD_SE
                 theta_uniform=1.0
                 n_sparse=20
                 delta=1.0
                 add_species=F
                 Z1=52
                 Z2=52
                 sparse_method=file
                 sparse_file=3.input:
     soap        cutoff=5.5
                 covariance_type=dot_product
                 zeta=4
                 central_weight=1.0
                 f0=0.0
                 delta=0.2
                 cutoff_transistion_width=0.5
                 config_type_n_sparse={dimer:30:primite:1000:crystal:1000:md:1600}
                 atom_sigma=0.5
                 l_max=4
                 n_max=12
                 add_species=F
                 n_species=2
                 Z=52
                 species_Z={{51 52 }}
                 sparse_method=file
                 sparse_file=5.input}
default_sigma={0.002 0.1 0.2 0.0}
energy_parameter_name=energy force_parameter_name=forces virial_parameter_name=virial
sparse_jitter=1.0e-8
do_copy_at_file=F sparse_separate_file=T
openmp_chunk_size=10000
gp_file=st23.xml`

![2bsoaphalf-能量力拟合](https://user-images.githubusercontent.com/50040885/220579044-b577d6e1-0299-4341-a33b-761471cb2c1f.png)

The fitting precision of GAP potentials is good. Moreover, the database for the training was obtained from DFT calculation of VASP in PBEsol functionals.

Any help will be appreciated!

Thanks in advance and best wishes!

**Comment by albapa** [comment]
If you can evaluate the strange config with DFT and add it to the training set (a.k.a. active learning) should help with this. If it's too large, you may need to reconstruct the failure in a smaller cell.

**Comment by Baristali** [comment]
> If you can evaluate the strange config with DFT and add it to the training set (a.k.a. active learning) should help with this. If it's too large, you may need to reconstruct the failure in a smaller cell.

Thanks for your suggestion.  I will try it.
