### ISSUE TITLE
Atom species 11 present in teaching XYZ, but not found corresponding isolated representative SYSTEM ABORT: Determination of e0 was requested to be based on isolated atom energies, but not all  atom types present in the XYZ had an isolated representative.      STOP 1

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#560]
Atom species 11 present in teaching XYZ, but not found corresponding isolated representative
SYSTEM ABORT: Determination of e0 was requested to be based on isolated atom energies, but not all  atom types
present in the XYZ had an isolated representative.     
STOP 1

**Comment by albapa** [comment]
This is not an issue. The message should be clear: `gap_fit` cannot determine the isolated atom energy for Na. Add a single Na atom in a large cell with the energy to the XYZ file.

**Comment by Amitcuhp** [comment]
can you tell me how to attach. it would be very helpful
thanks in advance

**Comment by albapa** [comment]
There are many ways. Add
```
 1
energy=whatever  pbc="T T T" Lattice="  20.00000     0.00000     0.00000     0.00000    20.00000     0.00000     0.00000     0.00000    20.00000" Properties=species:S:1:pos:R:3:forces:R:3
 Na 0.00 0.00 0.00 0.00 0.00 0.00
```
to your XYZ file where you substitute the DFT energy of a single Na atom to `whatever`.
