### ISSUE TITLE
Pre-trained potential

### ISSUE THREAD

**Issue by tavanfran** [libAtoms/QUIP#563]
Dear developers,

I am using QUIP to obtain the interatomic potential of an amorphous system. I have some questions about the "core_param_file" keyword:

1) instead of using in the same input file 2 GAPs (eg. distance_2b and soap), is it possible to do a first train using only distance_2b and then to train again adding core_param_file to start from the previous potential using soap? Is there any "good practice" to follow?

2) Is it possible to train a preliminary potential on some configurations and then add new configurations while starting from the previous trained potential (using core_param_file) and re-training it on these new configurations? Does it take as baseline the previous potential and adjust it onto new configurations?

3) is it possible to convert a published potential (Lennard-Jones, 12-6 etc.) into a format readable from core_param_file? In which format?

Thank you!

**Comment by albapa** [comment]
Hi,

1. Yes, this is possible. However, I think overall the result should be better if you train in one go.
2. The core potential is fixed. Once you trained a potential which is then reused as a core potential, it won't change.
3. QUIP implements many analytic interatomic potentials. `IP LJ` implements a flexible Lennard-Jones potential, while with `IP Glue` you can add an EAM + pair type potential specified by splines. Examples are provided in `share/Parameters`.

**Comment by gabor1** [comment]
Yes this is indeed possible. You could train a 2b (or indeed use an EAM or a spline pair potential) and then use that as "core". Com3 back here if you need help with the keywords

**Comment by gabor1** [comment]
2. I'm not sure that would be useful.

3. Absolutely. Have a look at the published Si or P or C potentials (C in 2020 Rowe etc Al), those have all been done with an analytic pair pot.

**Comment by tavanfran** [comment]
Thank you all for your suggestions! 
I have a system containing 3 atoms, similar to GeSbTe where GAP worked well. In my system, I have problems with energies at short range (less than 2 angstrom) where the potential goes down rapidly and if I use this potential to do a short MD simulation, some atoms goes in that region overcoming the potential barrier, resulting in a too small distance between atoms. I attach an image of the potential I obtained. 

<img width="589" alt="Schermata 2023-03-15 alle 15 27 41" src="https://user-images.githubusercontent.com/49390129/225340125-77135f8f-9244-4575-acc6-ecd538f48e64.png">

I was wondering how to solve this problem. 
Can I use an initial potential (as a Morse) as core-param for the GAP training? In this case the Morse has parameters able to have a single well at 3 angstrom.
Or do I have to include in my training set a series of configurations obtained by DFT where I have only 2 atoms at a small distance (say 1 ang) in order to include a sort of repulsion at small distances?

I really appreciate you help!

**Comment by bernstei** [comment]
On Mar 15, 2023, at 10:32 AM, tavanfran ***@***.******@***.***>> wrote:

Or do I have to include in my training set a series of configurations obtained by DFT where I have only 2 atoms at a small distance (say 1 ang) in order to include a sort of repulsion at small distances?

With GAP I've had very good luck adding to the fitting database DFT E(r) for every possible species-pair dimer with r ranging from quite a short range, maybe half the bond length, out to very far, where the atoms are barely or not at all bonded.

**Comment by gabor1** [comment]
As Noam says, dimer data is very useful to add and may solve your problem. We often add condensed phase data at an elevated pressure, that will help also. You can use an analytic (tabulated spline) baseline (or "core" in the GAP language ) potential but since it won't match the dft data you will still need the above in your database in order for GAP to be able to correct your baseline.

**Comment by gabor1** [comment]
can we close this now?

**Comment by tavanfran** [comment]
I think you can close it. 
I included more configurations and refined parameters and atoms do not stack together. I included more configurations at high temperature and the final system looks better (also if not as good as DFT in terms of radial distribution function.
I also tried to include configurations where I placed 2 atoms of the same type at short distances, but the potential get worse.
However, the choice of the configurations for the input and the input parameters (based on the system) are a very hard task (for every machine learning approach)!
Thank you for all you suggestions!

**Comment by gabor1** [comment]
If you place two atoms VERY close, that's hard to describe with smooth Gaussians. Typically we exclude configurations with forces above 50 eV/A or something similar, unless one does something special like a hand-crafted pair potential that describes those close approaches well. I don't know how much data you have altogether, but to describe a complex system like GeSbTe, we needed a database with > 0.5M atoms in it, and we weren't even trying to cover the full compositional space. With the MPI version of gap_fit, having several million atoms is not a problem.
