### ISSUE TITLE
http://www.libatoms.org is not accessible

### ISSUE THREAD

**Issue by cengc13** [libAtoms/QUIP#564]
Issue is as indicted by the title.

**Comment by albapa** [comment]
Because it has been replaced by [http://libatoms.github.io/](http://libatoms.github.io/)

**Comment by cengc13** [comment]
Thanks for the info. Please update the info on the right-top corner of https://github.com/libAtoms/QUIP accordingly.

**Comment by jameskermode** [comment]
Good point, now done, thanks!
