### ISSUE TITLE
Pre-trained Si GAP models giving incorrect energies?

### ISSUE THREAD

**Issue by axyong2** [libAtoms/QUIP#567]
Hi, I'm testing out the silicon pre-trained GAP models (from the PRX and Nature papers) using quippy, but they do not seem to be giving me correct energies. I'm not sure if it's because I'm not loading the xml files correctly, but here is the code I used:

```
from quippy.potential import Potential
from ase.build import bulk

Si_potential = Potential(init_args='Potential xml_label="GAP_2017_6_17_60_4_3_56_165"',
                         param_filename='../Si_PRX_GAP/gp_iter6_sparse9k.xml')
struc = bulk('Si', a=5.44, cubic=True)
struc.set_calculator(Si_potential)
print(struc.get_potential_energy())
```

Using DFT, the total energy should be around -43 eV.
Here are the energies I got using GAP:
1. GAP_2017_6_17_60_4_3_56_165, gp_iter6_sparse9k.xml (PRX paper; https://www.repository.cam.ac.uk/handle/1810/317974): -1305.41504368442
2. GAP_2020_8_8_60_14_23_0_141, Si_SCAN_01.xml (Nature paper; https://zenodo.org/record/4174139#.ZCXD83bMJPY): -80.1218867295759
3. GAP_2020_6_11_0_19_39_52_705, gap_RPA.xml (Nature paper; https://zenodo.org/record/4174139#.ZCXD83bMJPY): -80.0030732895915

Assuming the GAP energies are in eV, they seem to be way off compared to the DFT energy. Is there something wrong with the way I'm running the code? I would truly appreciate your time in helping me with this issue, thank you.

**Comment by bernstei** [comment]
On Mar 30, 2023, at 1:24 PM, Adrian Yong ***@***.******@***.***>> wrote:

Using DFT, the total energy should be around -43 eV.

This is not a well defined statement, or at least not in practice. Different DFT codes differ in what electrons the include in the energy, and whether they subtract some sort of reference energies.  Check energy _differences_.  The PRX GAP is probably fit to raw CASTEP energies, and I think it also includes core electrons.  VASP, on the other hand, subtracts some nominal isolated single atom energies.

**Comment by axyong2** [comment]
Ah okay, the DFT energy I mentioned was calculated by VASP. Thank you for the explanation!

**Comment by gabor1** [comment]
Try with an empty init_args string. I think you are calling the soap model without the pair repulsive core potential

**Comment by albapa** [comment]
The DFT energy not only depends on which code you use, but what your pseudopotential is and which functional you choose.

**Comment by gabor1** [comment]
can we close this now?
