### ISSUE TITLE
Fortran filenames do not follow conventions

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#57]
Although there are no strict rules for how files should be named, at least the Intel and GCC compilers seem to agree on some file naming conventions. At the moment QUIP just uses a customised build with Makefiles, but if it ever wanted to move to a more automated build system (autotools, cmake, ...), most of them implement behaviour based on the file extensions, so aligning with convention could help simplify the build.

The main issues I have with the current naming are that:
- Files requiring a preprocessor should be indicated with an uppercase suffix (i.e. `.F` or `.F90`), currently `.fpp` is being used for code that has been preprocessed, when the convention is that `.fpp` indicates that a file requires preprocessing (maybe this is an f90wrap thing?). 
- While `.f95` is fine for GCC, I think the consensus is that `.f90` should just be used for everything free-format and the compiler will use the most recent standard unless told otherwise.

The rules that I'd recommend changing to are:

- `file.f` for fixed-format code
- `file.F` for fixed-format code that is to be run through a preprocessor
- `file.f90` for free-format code 
- `file.F90` for free-format code that is to be run through a preprocessor

https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gfortran/GNU-Fortran-and-GCC.html
https://software.intel.com/en-us/node/691413

One problem that I can foresee is that Macs might not deal with case sensitivity very well, but I don't have enough experience with that to know if it would be a major issue.

**Comment by noambernstein** [comment]
On Tue, Mar 21, 2017 at 7:40 AM, Tom Daff <notifications@github.com> wrote:

> One problem that I can foresee is that Macs might not deal with case
> sensitivity very well, but I don't have enough experience with that to know
> if it would be a major issue.
>

Even on "non case sensitive" filesystems macs remember and distinguish the
case of letters in the filename (in the sense that gfortran, at least, can
tell the difference between t.f90 and t.F90, and only run fpp for the
latter).  They just can't have two files that differ only by case changes
(and things like "touch t.f90; touch t.F90" leaves a single file called
t.f90, not capitalized.  But "touch t.F90; touch t.f90" leaves it as t.F90,
capitalized).

       Noam

**Comment by gabor1** [comment]
I don't object. if this can help cmake, we can do it.
