### ISSUE TITLE
Add dump of Y and Y_Prime to Linear System Dump

### ISSUE THREAD

**Issue by thomas-rocke** [libAtoms/QUIP#571]
Currently energies, forces, and virials are not exported by gap_fit when linear system dump is requested. Adding this to the dump would allow refitting/experimentation with the linear system outside of gap_fit, which is useful for future development & prototyping work.

**Comment by Sideboard** [comment]
Would you like y and yPrime separate and raw or concatened and processed as used for the solver, i.e. `globalY(i) = from%y...(j) * sqrt(1.0_qp / from%lambda(i))`?

**Comment by thomas-rocke** [comment]
I think it's probably better to have it in the same format as the solver, as this then will match the form of the K_NM dumps (to make it very easy to load the full system and solve)

Might also be convenient (but not essential) to have some way of keeping track of what is an energy/force/virial in addition, but I think trying to match the form of K_NM should be the goal.

**Comment by Sideboard** [comment]
Please check if https://github.com/libAtoms/GAP/pull/78 works as you expect. This is without `* sqrt(...)`.

**Comment by thomas-rocke** [comment]
The output of globalY has good agreement with the predictions made by the Kmn output and the .xml weights. I think this solves the initial issue.
