### ISSUE TITLE
"Version of current code is 0" when using GAP for carbon simulation

### ISSUE THREAD

**Issue by user-ting** [libAtoms/QUIP#587]
SYSTEM ABORT: Database was created with a later version of the code.Version of code used to generate the database
is 1611600208.Version of current code is 0. Please update your code.

**Comment by gabor1** [comment]
The "version of the current code" is derived from the git version number. E.g. if you removed the ".git" directory from under the GAP directory, it will be set to zero. You can run `GAP/gepversion` which is a shell script, and it outputs the version number GAP thinks it has.

**Comment by gabor1** [comment]
can I close this?

**Comment by user-ting** [comment]
> can I close this?

oh sorry, I forgot to reply.  Thank you for your help. close it please if you want.
