### ISSUE TITLE
IO error when opening xml file (but doesn't happen on a different computer)

### ISSUE THREAD

**Issue by stelladay** [libAtoms/QUIP#590]
We have trained a simple GAP potential and I am now I am trying to import it into a Jupyter notebook before doing an NVT run, with:

from quippy.potential import Potential
gap_pot = Potential("", param_filename="test.xml")

I receive the error:

File "/project/src/libatoms/System.f95", line 540 kind unspecified
IO error opening "test.xml" on unit 7, error number: 2

The error seems to be triggered by a  a quippy function "f90wrap_potential_filename_initialize"

What's really confusing me is that this exact same notebook with the exact same xml file worked fine on my home computer. I am only getting this error when I try to run it on the computer at work. My python environments are identical on each computer. What could the difference be?

**Comment by bernstei** [comment]
>  What could the difference be?

The current working directory of the python interpreter run by the notebook?

**Comment by stelladay** [comment]
> > What could the difference be?
> 
> The current working directory of the python interpreter run by the notebook?

It's a Dropbox folder, so the working directory should be the same.
