### ISSUE TITLE
Stress prediction and GAP.xml read error

### ISSUE THREAD

**Issue by yw-fang** [libAtoms/QUIP#598]
Hi, all, I got the GAP.xml and associated xml files after training with GAP (forces, energies, stresses were trained by gap_fit with nergy_parameter_name=energy force_parameter_name=forces stress_parameter_name=stress virial_parameter_name=dummy3). 
The command "quip E=T F=T atoms_filename=validation.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_validation.xyz" works well. The obtained quip_validation.xyz seems okay and gives rise to very small RMSE errors in energy and forces compared to validation.xyz.
Because I also wanted to predict the stress, I ran the command "quip E=T F=T V=T atoms_filename=test.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_test.xyz". As we can see below, there are some information included in virial in the quip_validation.xyz file, however, the stress tensors are all still 0.0.
My first question is how to calculate the stress properly?

```
 104
 energy=-7511.9356573047098 stress="0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000       0.00000000" virial="280.76183608       2.36247115      -0.69579692       2.36247115     281.48857283      -0.34586001      -0.69579692      -0.34586001     295.70932761" cutoff=5.00000000 nneightol=1.20000000 pbc="T T T" Lattice="5.46469585      -5.47738445       0.00000000       5.46469585       5.47738445       0.00000000       0.00000000       0.00000000       5.41848812" Properties=species:S:1:pos:R:3:forces:R:3:Z:I:1:map_shift:I:3:n_neighb:I:1:force:R:3
```

Then I was trying to call the potential in the python IDE in order to use get_stress, however, I got these errors:

```
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ase.io import read
>>> from quippy.potential import Potential
>>> 
>>> # Load structures from the extended XYZ file
>>> structures = read('16_scf.xyz', index=':')
>>> 
>>> # Load the GAP potential
>>> gap_pot = Potential("GAP", param_filename="GAP.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/.local/lib/python3.9/site-packages/quippy/potential.py", line 81, in __init__
    self._quip_potential = quippy.potential_module.Potential.filename_initialise(args_str=args_str,
  File "/users/.local/lib/python3.9/site-packages/quippy/potential_module.py", line 135, in filename_initialise
    result = quippy._quippy.f90wrap_potential_filename_initialise(args_str=args_str, param_filename=param_filename, \
RuntimeError: Potential_Simple_Initialise_str found too few or too many Potential_Simple types args_str=' GAP'y
```
Would any one comment on the issues? Thank you!

I confirmed that GAP.xml, 16_scf.xyz, and other xml files are all in the current directory.

Appended information:  git version  https://github.com/libAtoms/QUIP,v0.9.13-dirty

**Comment by albapa** [comment]
Shouldn't you use
`quip E F V atoms_filename=test.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_test.xyz`

**Comment by albapa** [comment]
In Python, to load a GAP model:
`gap_pot = Potential("", param_filename="GAP.xml")`
this works for 99% of the use cases, if you have an unchanged XML and just want the potential you generated.

Or include the definition by the `xml_label`, see the tutorial/documentation for more info.

**Comment by yw-fang** [comment]
> Shouldn't you use `quip E F V atoms_filename=test.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_test.xyz`

Thank you for the quick comment! I realized I omitted V=T in my raised question.

**Comment by yw-fang** [comment]
> In Python, to load a GAP model: `gap_pot = Potential("", param_filename="GAP.xml")` this works for 99% of the use cases, if you have an unchanged XML and just want the potential you generated.
> 
> Or include the definition by the `xml_label`, see the tutorial/documentation for more info.

It's magic...
I realy works after removing GAP. Does that mean it's better not include anything in ""?

**Comment by yw-fang** [comment]
> In Python, to load a GAP model: `gap_pot = Potential("", param_filename="GAP.xml")` this works for 99% of the use cases, if you have an unchanged XML and just want the potential you generated.
> 
> Or include the definition by the `xml_label`, see the tutorial/documentation for more info.

Thanks for your comment! Now I can get the stresses. Here I have one more question, what's the unit of stress tensors with GAP potentials from "get_stress" method? Thanks!

**Comment by albapa** [comment]
It's not magic at all. The fully specified initialisation is
`pot = Potential('xml_label=your_label', param_filename='your.xml')`

where `your_label` is what's inside your XML file in the line starting with `<Potential`. If you use an empty string, the initialisation tries to guess what the label might be and uses that guess. If you made some modifications that invalidates the guess, or you have something else in mind, the default won't necessarily work.

**Comment by albapa** [comment]
> what's the unit of stress tensors with GAP potentials from "get_stress" method?

Whatever ASE returns the stresses in, which I think is eV/Angstrom^3.

**Comment by albapa** [comment]
Note that QUIP returns the virial tensor in eV units. This is an extensive quantity and you need to divide by the volume (and multiply by -1) to get the pressure.

**Comment by yw-fang** [comment]
> It's not magic at all. The fully specified initialisation is `pot = Potential('xml_label=your_label', param_filename='your.xml')`
> 
> where `your_label` is what's inside your XML file in the line starting with `<Potential`. If you use an empty string, the initialisation tries to guess what the label might be and uses that guess. If you made some modifications that invalidates the guess, or you have something else in mind, the default won't necessarily work.

Get it. Thanks for pointing out it to me that is behind the magic. Lol

**Comment by yw-fang** [comment]
> > what's the unit of stress tensors with GAP potentials from "get_stress" method?
> 
> Whatever ASE returns the stresses in, which I think is eV/Angstrom^3.

Just to confirm I really get it.
The stress should have the unit eV/Angstrom^3 in the code below because I call ASE to get the stress.

```
from ase.io import read
from quippy.potential import Potential
import numpy as np

# Load structures from the extended XYZ file
structures = read('test.xyz', index=':')
# Load the GAP potential
gap_pot = Potential("", param_filename="GAP.xml")
with open('results.dat', 'w') as f:
    # Loop over the structures
    for structure in structures:
        structure.set_calculator(gap_pot)
        stress = structure.get_stress(voigt=False)
```

However, if I run quip directly, for example, ``quip E=T F=T V=T atoms_filename=test.xyz param_filename=GAP.xml | grep AT | sed 's/AT//' > quip_test.xyz '' will give me the stress in eV which I need post-process.

Do I understand all your comments properly? Thanks!

Appended: I cross-checked the stress data with test.xyz and the original output from Quantum Espresso, as well as from get_stress and direct running of quip, and confirmed the stress unit mentioned above. @albapa Thanks again for help me eliminate these obstacles. It's lucky to me that you've made multiple constructive comments!

**Comment by gabor1** [comment]
what you get from running QUIP directly is not really the stress, but the "virial stress", which needs to be divided by the volume of the cell to get the stress. That's how you go form eV to eV/Å^3

**Comment by yw-fang** [comment]
> what you get from running QUIP directly is not really the stress, but the "virial stress", which needs to be divided by the volume of the cell to get the stress. That's how you go form eV to eV/Å^3

Well noted with thanks!
