### ISSUE TITLE
Problem installing quip in new environment

### ISSUE THREAD

**Issue by stelladay** [libAtoms/QUIP#599]
I was able to successfully install quip in a python environment a week ago using "pip install quippy-ase". Everything worked perfectly. Today I am trying to install it in a new environment to show someone how, and am getting an error "Could not find a version that satisfies the requirement quippy-ase" and "No matching distribution found for quippy-ase." Was there some kind of recent update that means pip can't find the package?

**Comment by jameskermode** [comment]
What version of Python are you using and on which platform? We did just do a new release, maybe we are missing a version you need. You can install previous releases e.g via `pip install quippy-ase==0.9.12`

**Comment by Luthaf** [comment]
I have the same issue when using Python 3.11, it seems that there are no wheels for this version on PyPI. I've rolled back to Python 3.10 in the mean time!

**Comment by jameskermode** [comment]
That's correct, one of our dependencies didn't yet support 3.11 yet last time I checked but I think this should now be resolved so I'll try to add support for 3.11 wheels for the next release.

**Comment by jameskermode** [comment]
Some Python 3.11 wheels here to try. If you report back that they work I'll merge the PR and do a new release

https://github.com/libAtoms/QUIP/actions/runs/5269317691

https://github.com/libAtoms/QUIP/suites/13604388656/artifacts/750070972

**Comment by Luthaf** [comment]
The wheel for Python 3.11 on arm64-macos works for me!

**Comment by jameskermode** [comment]
Please don’t close this just yet, I didn’t merge the PR

**Comment by jameskermode** [comment]
Now merged. I'll add the wheels to the 0.9.13 release rather than making a new one.

**Comment by jameskermode** [comment]
In fact it's far easier to tag a new patch release, so I've done that. v0.9.14 should appear on PyPI in an hour or so including Python 3.11 support. Thanks @Luthaf and @stelladay for reporting this, do re-open if there's still a problem.

**Comment by ali-hmd** [comment]
The same problem is observed with python3.12. Upon trying "pip install quippy-ase" this error is received: "ERROR: No matching distribution found for quippy-ase".
