### ISSUE TITLE
Couldn't find *params.xml

### ISSUE THREAD

**Issue by XiaoqZhang** [libAtoms/QUIP#608]
Hi I am a new user to QUIP. When I was following the tutorial of [GAP](https://libatoms.github.io/GAP/gap_si_surface.html), I met problems when loading the potential file. There is a step to load the potential file 
```
# attach tight binding calculator
qm_pot = Potential('TB DFTB', param_filename='dftb-params.xml')
atoms.set_calculator(qm_pot)
```
I cannot find the potential file in the compiled library. I didn't meet any error when I was installing the quip. I just want to check with you if params.xml files like this should also be compiled in the package library during the installation. If not, do you have any recommendations for looking for these files? Thank you in advance.

**Comment by gabor1** [comment]
We cannot distribute DFTB parameters publicly, due to the licensing of DFTB. What is your ultimate goal with QUIP ? Do you want to use it to run tight binding simulations?

**Comment by XiaoqZhang** [comment]
Thank you for your efficient reply. For now, I am just following the tutorial. In the end, I would like to fit a GAP potential for other systems. Considering the efficiency and accuracy, tight binding simulations can be a potential but not necessary choice for me.

**Comment by gabor1** [comment]
maybe use one of the other TB models, for which you have param files in the public distribution? e.g. "TB GSP" or "TB NRL_TB", look in the share/parameters/ directory

**Comment by gabor1** [comment]
there is also "TB Bowler" for Si.

**Comment by XiaoqZhang** [comment]
I see. Thank you!
