### ISSUE TITLE
Has anything changed with the IP Glue method?

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#610]
We are getting segmentation faults when running a GAP (with the quip binary) that was fitted with a core potential via the IP Glue method. This GAP was fitted in the same way as we've done it a thousand times (literally), and when I run it with an old version of quip (removing the gap_version tag to trick the code) it works fine. I have a strong suspicion that this is due to the core potential ("pairpot") part, since manually deleting that from the xml file but keeping all the GAP parts leads to successful runs. The segfault happens without any printouts, even when quip is compiled with debug flags. I'm already playing around with valgrind but I'd appreciate any heads-up on any changes in the IP Glue/pairpot part of the code that took place within the last few months (perhaps up to a year from now), since that may help me substantially debug the issue.

Edit:

Possibly relevant information: Since we seem to be able to fit the potential with gap_fit, it is entirely possible the issue is with the quip XML reader only.

**Comment by mcaroba** [comment]
It turns out this error is triggered by what @Sideboard reported in #579. It goes away by setting `ulimit -s unlimited`.

**Comment by gabor1** [comment]
we've had previous problems with too large a stack requirement (it was the strings), so it would be good to keep our stack use under control
