### ISSUE TITLE
How to use lammps plugin and how to make potential from xml file?

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#613]
I have trained a model in GAP. I have GAP.xml file. How can I start use lammps?
 I am unable to start how to do lammps MD. And how to plot potential form xml file?

**Comment by gabor1** [comment]
Have a look at the relevant LAMMPS documentation : 

https://docs.lammps.org/pair_quip.html

**Comment by gabor1** [comment]
You can evaluate the potential without LAMMPS by using the ATomic Simulation Environment (ASE), see the tutorials here: https://libatoms.github.io/GAP/gap_si_surface.html

search for "xml" in the tutorial and you will see how it is used.

**Comment by Amitcuhp** [comment]
I have trained the cluster using VASP data. Now I have GAP.xml file. Now I am not able to understand how to do lammps. I have seen both the links you share. 
If you can give more info about lammps it wil be very helpful

**Comment by gabor1** [comment]
If you cannot follow our tutorials or the lammps documentation at all, you might want to attend a summer school or learn hands-on from someone who has done this before. If you have _specific_ questions on individual features or how to fix errors, we can help you with that here, but it's really not the place to learn molecular simulation by post!

**Comment by Amitcuhp** [comment]
Okay sir thank you
