### ISSUE TITLE
I have installed as per directions given here, but giving me this error. Can you help what mistake I am making.

### ISSUE THREAD

**Issue by Amitcuhp** [libAtoms/QUIP#614]
ERROR: Unrecognized pair style 'quip' is part of the ML-QUIP package which is not enabled in this LAMMPS binary. (src/force.cpp:278)

Thank you in advance

**Comment by Amitcuhp** [comment]
Is this installation problem

**Comment by bernstei** [comment]
As it says, you need to enable the ML-QUIP package when you compile LAMMPS.

**Comment by Amitcuhp** [comment]
Thank you very much. It worked well after enabling in lammps.
