### ISSUE TITLE
Behavior of add_species=True in quippy

### ISSUE THREAD

**Issue by mcaroba** [libAtoms/QUIP#615]
I am in the process of improving the ease of use of `soap_turbo` by 1) allowing implicit setting of hyperparameters by providing more and better predefined defaults and 2) providing an explicit recipe for `add_species=T`. I have tested that my `add_species=T` recipe works as I expect it to when I invoke the descriptor via the gap_fit binary. However, when I create a descriptor object with Quippy, the `add_species=T` label is ignored and the descriptors are built only for one of the species. Is this behavior to be expected? Does `add_species` require a Quippy-specific interface for each descriptor?

**Comment by albapa** [comment]
`add_species` is interpreted by `gap_fit` only. The descriptors (all of them) ignore it. We can wrap the subroutine that implements the recipes if there is appetite for this.

**Comment by mcaroba** [comment]
It could be interesting. I'm thinking about making it possible to define a descriptor string with just "soap_turbo" that internally sets everything to sensible defaults, for the lazy user. Or at least with simplified hypers.
