### ISSUE TITLE
RMSE for Liquids in GAP

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#622]
Dear Developers,
    Should the RMSEs for energy and forces improve (get smaller, fit improvement) if more liquid configurations are added with iterative training to the database?  Or are GAPs for liquids generally hard to improve?  I get no improvement or worse.  
   Also I may have a database that is too large (>160 MB) in the first place, and it has many more non-liquids than liquids.
Thanks for any advice.

**Comment by gabor1** [comment]
IT depends on other sources of error, e.g. locality (i.e. cutoff!). what is your system and what kind of errors are you getting?

**Comment by MES-physics** [comment]
Carbon, cutoff = 4.5 A,  2b, 3b angle, and soap.
RMSE energy= 34 meV, force~ 1460 meV.  The whole carbon-GAP 20 database is in there, plus a lot of our additions.

**Comment by gabor1** [comment]
well, 4.5A for carbon including liquids and 2D forms of carbon is going to be smallish (it's ok for sp3 carbon). all of carbon is a challenging data set. So while your errors are quite big overall, it would be intresting to try to break it up and see the errors for individual config types. 

ultimately, ACE and MACE are much better on carbon than GAP, especially the challenging parts (liquid and amorphous), see recent publications like https://pubs.aip.org/aip/jcp/article/159/4/044118/2904837/Evaluation-of-the-MACE-force-field-architecture

**Comment by MES-physics** [comment]
Thank you very much, I will move forward on those suggestions!

**Comment by gabor1** [comment]
how many sparse points did you use with soap? I expect ten thousand or more would be needed for GAP.

**Comment by MES-physics** [comment]
9000.   I followed the parameters in the Carbon_GAP_20 publication.
