### ISSUE TITLE
pip install quippy-ase error 

### ISSUE THREAD

**Issue by hy39531** [libAtoms/QUIP#623]
when I ran the command "pip install quippy-ase" on my MacBook, the error happened:

Collecting quippy-ase
  Obtaining dependency information for quippy-ase from https://files.pythonhosted.org/packages/69/aa/9a8e08f6adb4fc9285ad9f23e87cc8785fe907e5bece52d86775920364af/quippy_ase-0.9.14-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached quippy_ase-0.9.14-cp311-cp311-macosx_10_9_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.13 in ./Library/Python/3.11/lib/python/site-packages (from quippy-ase) (1.25.0)
Collecting f90wrap>=0.2.6 (from quippy-ase)
  Using cached f90wrap-0.2.13.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8 /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8/.mesonpy-1xjwrm0j -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8/.mesonpy-1xjwrm0j/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.3
      Source dir: /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8
      Build dir: /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8/.mesonpy-1xjwrm0j
      Build type: native build
      Project name: f90wrap
      Project version: 0.2.13
      C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.0.40.1)")
      C linker for the host machine: cc ld64 1015.7
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      
      ../meson.build:13:0: ERROR: Unable to detect linker for compiler `gfortran -Wl,--version -L/usr/local/opt/llvm/lib`
      stdout:
      stderr: collect2 version 13.2.0
      /opt/local/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/ -dynamic -arch x86_64 -platform_version macos 13.0.0 0.0 -o a.out -L/usr/local/opt/llvm/lib -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin20/13 -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin20/13/../../.. --version -lemutls_w -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin20/13 -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current
      ld: unknown options: --version
      collect2: error: ld returned 1 exit status
      
      
      A full log can be found at /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-gm7tlxuo/f90wrap_7ff612ac89b8413193e86fccb3307cc8/.mesonpy-1xjwrm0j/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python3.11 -m pip install --upgrade pip

**Comment by bernstei** [comment]
What macos version are you running?  There are known issues with recent linkers.  I'll dig up a link.

**Comment by bernstei** [comment]
This, for example https://lists.macports.org/pipermail/macports-users/2023-October/052254.html

**Comment by hy39531** [comment]
> What macos version are you running? There are known issues with recent linkers. I'll dig up a link.

It's MacBook Pro

**Comment by bernstei** [comment]
> > What macos version are you running? There are known issues with recent linkers. I'll dig up a link.
> 
> It's MacBook Pro

macos - the operating system (and XCode version). Hardware doesn't matter.

**Comment by hy39531** [comment]
> This, for example https://lists.macports.org/pipermail/macports-users/2023-October/052254.html

I downloaded Xcode 14.3.1 and ran "pip install quippy-ase", here is the new error message:

Collecting quippy-ase
  Obtaining dependency information for quippy-ase from https://files.pythonhosted.org/packages/69/aa/9a8e08f6adb4fc9285ad9f23e87cc8785fe907e5bece52d86775920364af/quippy_ase-0.9.14-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached quippy_ase-0.9.14-cp311-cp311-macosx_10_9_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.13 in ./Library/Python/3.11/lib/python/site-packages (from quippy-ase) (1.25.0)
Collecting f90wrap>=0.2.6 (from quippy-ase)
  Using cached f90wrap-0.2.13.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      + meson setup /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f/.mesonpy-kxpnloqw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f/.mesonpy-kxpnloqw/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.3
      Source dir: /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f
      Build dir: /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f/.mesonpy-kxpnloqw
      Build type: native build
      Project name: f90wrap
      Project version: 0.2.13
      C compiler for the host machine: cc (clang 14.0.3 "Apple clang version 14.0.3 (clang-1403.0.22.14.1)")
      C linker for the host machine: cc ld64 857.1
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      
      ../meson.build:13:0: ERROR: Compiler gfortran cannot compile programs.
      
      A full log can be found at /private/var/folders/r6/bx0w3mfj5_l_njpd5f0l082h0000gn/T/pip-install-92xm4qwn/f90wrap_5f3ac7d0105e49baab2b6a38bd573a5f/.mesonpy-kxpnloqw/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python3.11 -m pip install --upgrade pip

**Comment by hy39531** [comment]
> > > What macos version are you running? There are known issues with recent linkers. I'll dig up a link.
> > 
> > 
> > It's MacBook Pro
> 
> macos - the operating system (and XCode version). Hardware doesn't matter.

It's macOS Ventura 13.5.2

**Comment by bernstei** [comment]
@jameskermode do you know why this message is even hapenning during a pip install "  ../meson.build:13:0: ERROR: Compiler gfortran cannot compile programs." ?

**Comment by jameskermode** [comment]
It's failing to build f90wrap from  source. Please open an issue there instead, I suspect I'm missing a binary wheel for this OS/Python version combination.

**Comment by hy39531** [comment]
I have opened a new issue. Here is the link: https://github.com/libAtoms/QUIP/issues/624

Thank you all for the help!

**Comment by jameskermode** [comment]
Closing in preference to duplicate #624
