### ISSUE TITLE
cpu overhead during potential file reading

### ISSUE THREAD

**Issue by yonghyuklee** [libAtoms/QUIP#625]
Dear developers,

I am attempting to employ GAP for iterative and multiple minimization calculations. I've used LAMMPS for this purpose, but I've noticed a considerable CPU time overhead during the potential file reading phase. According to my understanding, LAMMPS reads the potential in serial, taking 5-6 minutes for my GAP. The actual minimization process only takes a few seconds. I am curious if there are ways to significantly reduce this time.

I've explored using quippy.potential, where I can read the potential once and apply this calculator to all ASE atom objects of interest. However, it seems that quippy doesn't pass MPI communicators (please correct me if I am wrong) and becomes very slow for structure optimization.

Are there any potential solutions that I can explore? Many thanks in advance.

**Comment by gabor1** [comment]
Are you always using the same gap?

**Comment by yonghyuklee** [comment]
> Are you always using the same gap?

yes, I am using the same gap

**Comment by gabor1** [comment]
You'll need to do it in a way that loads the potential once and then does all the subsequent minimising without reload. One way to do this is to use lammpslib from e.g. ASE, the lammps instance is kept alive between calls. If your systems are very small you may find that ASE minimisations are more convenient , entirely bypassing lammps.

**Comment by jameskermode** [comment]
Following up on this, ASE can call MPI parallel LAMMPS via lammpslib. You need to compile the LAMMPS Python module with MPI enabled and the QUIP plugin in serial, add `import mpi4py` to the top of your script and invoke as `mpirun python my script.py` or similar.

**Comment by yonghyuklee** [comment]
Thank you so much for the comments! Your suggestions work for sure.
