### ISSUE TITLE
Upgrade old optparse code to argparse

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#63]
The Python `optparse` module has been deprecated since version 2.7/3.2 in favour of `argparse`; no telling if or when they'll actually remove the old module. Since many of the quippy scripts (`convert.py` and about 10 others) use `optparse` this is something we should at least be aware of for the medium-long term (maybe after we've finally got working Py3k support?).

Conversion should be as easy as find/replace in most cases: https://docs.python.org/3/library/argparse.html#upgrading-optparse-code

**Comment by max-veit** [comment]
Only bringing this up now that we've dropped support for 2.6 (#43)

**Comment by gabor1** [comment]
I guess we don't distribute those scripts anymore.
