### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Prerna817** [libAtoms/QUIP#631]
Hello Sir,
I am trying to compile QUIP, I am getting this error. I would be grateful for any suggestion
![compile](https://github.com/libAtoms/QUIP/assets/161825712/e7906314-2a8f-478a-ab9b-f4fc9a5a056e)

**Comment by albapa** [comment]
This is not a complete log, so it's impossible to tell what exactly went wrong. I think the clue is 

> Nonexistent include directory '0'

Something could have gone wrong when you did `make config` or you haven't set your `QUIP_ARCH` etc.
