### ISSUE TITLE
gap_si_surface.ipynb: runtime error about dftb-params.xml

### ISSUE THREAD

**Issue by Mu-Jinming** [libAtoms/QUIP#639]
```
RuntimeError: Traceback (most recent call last)
  File "/project/src/libAtoms/System.f95", line 540 kind unspecified
    IO error opening "dftb-params.xml" on unit 7, error number: 2
```
Dear developer, I have reviewed the related issues, and it appears that the file "dftb-params.xml" is missing. Could you please send it to my email: 390400239@qq.com
or mujinming123@gmail.com

Thanks a lot!

**Comment by gabor1** [comment]
done
