### ISSUE TITLE
LAMMPS + QUIP

### ISSUE THREAD

**Issue by Pourasad** [libAtoms/QUIP#643]
Hello.

I installed the lammps-17Apr2024 with QUIP (by cmake) with no problem but when I try to run the examples in examples/PACKAGES/quip folder, I face this strange error:

Fortran runtime error: Incorrect extent in VALUE argument to DATE_AND_TIME intrinsic: is -2, should be >=8

-------
Here is the info from lmp -h:

Large-scale Atomic/Molecular Massively Parallel Simulator - 17 Apr 2024

OS: Linux "Red Hat Enterprise Linux Atomic Host 7.4.0.4" 3.10.0-1160.114.2.el7.x86_64 x86_64

Compiler: GNU C++ 8.3.0 with OpenMP 4.5
C++ standard: C++11
MPI v3.1: Open MPI v3.1.0, package: Open MPI applic@login01 Distribution, ident: 3.1.0, repo rev: v3.1.0, May 07, 2018

Accelerator configuration:

FFT information:

FFT precision  = double
FFT engine  = mpiFFT
FFT library = FFTW3 with threads

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit

Available compression formats:

Extension: .gz     Command: gzip
Extension: .bz2    Command: bzip2
Extension: .xz     Command: xz
Extension: .lzma   Command: xz
Extension: .lz4    Command: lz4

Installed packages:

EXTRA-PAIR KSPACE MANYBODY ML-QUIP MOLECULE REPLICA RIGID

**Comment by albapa** [comment]
This is almost certainly due to the very old gfortran/gcc. I seem to remember this error, I think it was an internal compiler bug which went away.
