### ISSUE TITLE
Error in Installing QUIP/GAP

### ISSUE THREAD

**Issue by Eadedeji** [libAtoms/QUIP#648]
Hi, 

I am having this error below while trying to install QUIP/GAP. after "make config". 

Unable to determine SIZEOF_FORTRAN_T
Check that your compiler is working and try again!
Build error:
make[1]: Entering directory ' /,...../QUIP/build/linux_x86_64_gfortran'
gfortran -x f95-cpp-input -ffree-line-length-none -ffree-form -fno-second-underscore -fPIC -fno-realloc-lhs -I/xxxxxxxx/xxxxxx/x/xxxxxxx/QUIP/src/libAtoms -I/xxxx/xxxxx/x/usr/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude y -I -O3  -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,v0.9.14-10-g694dc9c0d"' -D'GAP_VERSION=1686220958' -D'QUIP_ARCH="linux_x86_64_gfortran"' -D'SIZEOF_FORTRAN_T=' -DHAVE_NETCDF4 -DHAVE_MDCORE -DHAVE_GAP -DHAVE_TB -DHAVE_PRECON -DHAVE_QR -DSCALAPACK -DHAVE_LOTF -DHAVE_CP2K -DHAVE_ONIOM -DHAVE_LOCAL_E_MIX   sizeof_fortran_t.f90 -o sizeof_fortran_t
f951: Warning: Nonexistent include directory ‘/xxxxxxx/xxxxx/x/usr/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘-O3’ [-Wmissing-include-dirs]
f951: Fatal Error: y: No such file or directory
compilation terminated.
f951: Warning: Nonexistent include directory ‘/xxxxxx/xxxxx/x/xxxxxx/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘-O3’ [-Wmissing-include-dirs]
make[1]: *** [Makefile:10: sizeof_fortran_t] Error 1
make[1]: Leaving directory '/xxxxxxxxx/xx/x/xxxxxxxx/QUIP/build/linux_x86_64_gfortran'

make: *** [Makefile.config:178: config] Error 

Any idea what I could be doing wrong. Thank you.

**Comment by jameskermode** [comment]
What platform are you on? If you don't need the parallel MPI functionality I would strongly suggest starting with the pre-bulid binary installation available via `pip install quippy-ase`. This also installs a serial version of the `gap_fit` program.

**Comment by Eadedeji** [comment]
Good morning, Prof. Thank you for your quick response. I am a beginner at using QUIP/GAP, I am working in a cluster environment, so I thought MPI parallelization would be the best option, However, I have been able to compile QUIP without the initial error but with some new ones. Kindly see below for details. 

1.	 I started a fresh installation using after “make distclean and removing the QUIP directory 
2.	 **Quip download**
xxxxxx/xxxxxx/x/eadedeji/QUIP
(base) eadedeji@serrver::~/QUIP> make config
Using QUIP_ARCH=linux_x86_64_gfortran, MODULES=libAtoms Potentials Utils, QUIP_ROOT=/xxxxxx/xxxxxx/x/eadedeji/QUIP

In the following, hit enter to accept the defaults.


BUILD OPTIONS
=============


Please enter the linking options for LAPACK and BLAS libraries:
   Default: -llapack -lblas


Please enter the preferred python command:
   Default: /xxxxxx/xxxxxx/x/eadedeji/anaconda3/bin/python


Please enter the preferred pip command:
   Default: /xxxxxx/xxxxxx/x/eadedeji/anaconda3/bin/pip


Please enter any other extra linking options:
   Default: none


OPTIONAL INTERNAL FEATURES
==========================


Would you like to compile with CP2K support? [y/n]
   Default: n
y

Would you like to compile with VASP support? [y/n]
   Default: n
y

Would you like to compile with Tight Binding (TB) support? [y/n]
   Default: n
y

Would you like to compile with preconditioned minimisation support? (not working with Intel compiler) [y/n]
   Default: y


Would you like to compile with Learn-on-the-fly (LOTF) support? [y/n]
   Default: n
y

Would you like to compile with ONIOM support? [y/n]
   Default: n
y

Would you like to compile with LOCAL_E_MIX support? [y/n]
   Default: n
y

Would you like to compile with QuasiContinuum wrapper support? [y/n]
   Default: n
y

OPTIONAL FEATURES (EXTRA CODE REQUIRED)
=======================================


Would you like to compile with GAP support ? [y/n]
   Default: n
y


Would you like to turn on QR decomposition for some GAP operations? [y/n]
   Default: y


Would you like to compile with ScaLAPACK? [y/n]
   Default: n

Checking for ThirdParty directory...
   Not found. 

Would you like to compile with TTM3-F support? [y/n]
   Default: n

Would you like to compile with SCME support ? [y/n]
   Default: n

Would you like to compile with MTP support ? [y/n]
   Default: n

Would you like to compile with many-body dispersion support ? [y/n]
   Default: n

Would you like to compile with TTM_NF support ? [y/n]
   Default: n

Would you like to compile with CH4 support ? [y/n]
   Default: n


OPTIONAL EXTERNAL LIBRARIES
===========================

Would you like to compile with NetCDF4 support? [y/n]
   Default: n


Please enter directories where MDCORE libraries are kept:
   Default: no MDCORE present


Please enter directory where the ASAP library is kept:
   Default: no ASAP library present


Please enter directories where CGAL libraries are kept:
   Default: no CGAL present


Please enter directories where METIS libraries are kept:
   Default: no METIS present


Please enter directories where LMTO_TBE libraries are kept:
   Default: no LMTO_TBE present


3.	See below the error message I got during “make”

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms /cutil.c: In function ‘pointer_to_’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/cutil.c:273:11: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  273 |   return ((int) p);
      |           ^
gcc -fPIC  -I/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms -I/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/fox/objs.linux_x86_64_gfortran/finclude -O3  -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,v0.9.14-10-g694dc9c0d-dirty"' -D'GAP_VERSION=1686220958' -D'QUIP_ARCH="linux_x86_64_gfortran"' -D'SIZEOF_FORTRAN_T=2' -DHAVE_GAP -DHAVE_TB -DHAVE_PRECON -DHAVE_QR -DHAVE_LOTF -DHAVE_CP2K -DHAVE_ONIOM -DHAVE_LOCAL_E_MIX  -c /xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/netcdf.c
gcc -fPIC  -I/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms -I/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/fox/objs.linux_x86_64_gfortran/finclude -O3  -DGETARG_F2003 -DGETENV_F2003 -DGFORTRAN -DFORTRAN_UNDERSCORE -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,v0.9.14-10-g694dc9c0d-dirty"' -D'GAP_VERSION=1686220958' -D'QUIP_ARCH="linux_x86_64_gfortran"' -D'SIZEOF_FORTRAN_T=2' -DHAVE_GAP -DHAVE_TB -DHAVE_PRECON -DHAVE_QR -DHAVE_LOTF -DHAVE_CP2K -DHAVE_ONIOM -DHAVE_LOCAL_E_MIX  -c /xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c
In file included from /xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:50:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c: In function ‘xyz_find_index’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:180:5: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  180 |     RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot access xyz file %s\n", fname);
      |     ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:169:5: note: declared here
  169 | int xyz_find_index(char *fname, char *indexname, int *do_update, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:203:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  203 |       RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot stat xyz file %s\n", fname);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:169:5: note: declared here
  169 | int xyz_find_index(char *fname, char *indexname, int *do_update, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:206:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  206 |       RAISE_ERROR_WITH_KIND(ERROR_IO, "Cannot stat xyz.idx file %s\n", fname);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:169:5: note: declared here
  169 | int xyz_find_index(char *fname, char *indexname, int *do_update, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c: In function ‘xyz_read_index’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:224:5: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  224 |     RAISE_ERROR_WITH_KIND(ERROR_IO, "Index file %s cannot be opened\n", indexname);
      |     ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:214:5: note: declared here
  214 | int xyz_read_index(char *indexname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:227:5: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  227 |     RAISE_ERROR_WITH_KIND(ERROR_IO, "Index file %s is empty\n",indexname);
      |     ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:214:5: note: declared here
  214 | int xyz_read_index(char *indexname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:233:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  233 |       RAISE_ERROR_WITH_KIND(ERROR_IO, "Premature end of indexfile %s\n",indexname);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:214:5: note: declared here
  214 | int xyz_read_index(char *indexname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c: In function ‘xyz_update_index’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:250:5: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  250 |     RAISE_ERROR_WITH_KIND(ERROR_IO, "xyz_update_index: cannot open %s for reading", fname);
      |     ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:243:5: note: declared here
  243 | int xyz_update_index(char *fname, char *indexname, long **frames, int **atoms, int *frames_array_size, int nframes, int *error) {
      |     ^~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:281:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  281 |       RAISE_ERROR_WITH_KIND(ERROR_IO, "xyz_find_frames: malformed XYZ file %s at frame %d\n",fname,nframes);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:243:5: note: declared here
  243 | int xyz_update_index(char *fname, char *indexname, long **frames, int **atoms, int *frames_array_size, int nframes, int *error) {
      |     ^~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c: In function ‘xyz_find_frames’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:128:155: warning: ‘return’ with no value, in function returning non-void
  128 | *error != ERROR_NONE) { error_h_line = __LINE__; c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
      |                                                                                                                   ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:346:3: note: in expansion of macro ‘PASS_ERROR’
  346 |   PASS_ERROR;
      |   ^~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:337:5: note: declared here
  337 | int xyz_find_frames(char *fname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:128:155: warning: ‘return’ with no value, in function returning non-void
  128 | *error != ERROR_NONE) { error_h_line = __LINE__; c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
      |                                                                                                                   ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:351:5: note: in expansion of macro ‘PASS_ERROR’
  351 |     PASS_ERROR;
      |     ^~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:337:5: note: declared here
  337 | int xyz_find_frames(char *fname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:128:155: warning: ‘return’ with no value, in function returning non-void
  128 | *error != ERROR_NONE) { error_h_line = __LINE__; c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
      |                                                                                                                   ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:356:5: note: in expansion of macro ‘PASS_ERROR’
  356 |     PASS_ERROR;
      |     ^~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:337:5: note: declared here
  337 | int xyz_find_frames(char *fname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:126:300: warning: ‘return’ with no value, in function returning non-void
  126 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:359:7: note: in expansion of macro ‘RAISE_ERROR’
  359 |       RAISE_ERROR("xyz_find_frames: empty file!");
      |       ^~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:337:5: note: declared here
  337 | int xyz_find_frames(char *fname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:128:155: warning: ‘return’ with no value, in function returning non-void
  128 | *error != ERROR_NONE) { error_h_line = __LINE__; c_push_error_(__FILE__, &error_h_line, error, strlen(__FILE__)); return; }
      |                                                                                                                   ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:363:5: note: in expansion of macro ‘PASS_ERROR’
  363 |     PASS_ERROR;
      |     ^~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:337:5: note: declared here
  337 | int xyz_find_frames(char *fname, long **frames, int **atoms, int *frames_array_size, int *error) {
      |     ^~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c: In function ‘get_line’:
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:413:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  413 |       RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:405:7: note: declared here
  405 | char* get_line(char *linebuffer, int string, int string_length, char *orig_stringp, char *stringp, char **prev_stringp,
      |       ^~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:425:9: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  425 |         RAISE_ERROR_WITH_KIND(ERROR_IO, "cannot strip prefix from line <%s>", linebuffer);
      |         ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:405:7: note: declared here
  405 | char* get_line(char *linebuffer, int string, int string_length, char *orig_stringp, char *stringp, char **prev_stringp,
      |       ^~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:431:7: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  431 |       RAISE_ERROR_WITH_KIND(ERROR_IO_EOF, info);
      |       ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:405:7: note: declared here
  405 | char* get_line(char *linebuffer, int string, int string_length, char *orig_stringp, char *stringp, char **prev_stringp,
      |       ^~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/libatoms.h:127:303: warning: ‘return’ with no value, in function returning non-void
  127 | ror_h_line, &error_h_kind, strlen(error_h_info), strlen(__FILE__)); if (error != NULL) { *error = error_h_kind; return; } else c_error_abort_(error)
      |                                                                                                                 ^~~~~~

/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:438:9: note: in expansion of macro ‘RAISE_ERROR_WITH_KIND’
  438 |         RAISE_ERROR_WITH_KIND(ERROR_IO, "cannot strip prefix from line <%s>", linebuffer);
      |         ^~~~~~~~~~~~~~~~~~~~~
/xxxxxxx/xxxxxx/xxxxxxx/QUIP/src/libAtoms/libAtoms/xyz.c:405:7: note: declared here
  405 | char* get_line(char *linebuffer, int string, int string_length, char *orig_stringp, char *stringp, char **prev_stringp,
      |       ^~~~~~~~

4.	 **Trying to see if quip is compiled successfully** 


(base) exxxxxx@server::~/QUIP> quip atoms_filename=test.xyz
libAtoms::Hello World: 2024-07-01 06:45:36
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP,v0.9.14-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran_openmp
libAtoms::Hello World: compiled on  Jun 15 2023 at 19:28:03
libAtoms::Hello World: OpenMP parallelisation with 256 threads
WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
libAtoms::Hello World: Random Seed = 24336820
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

SYSTEM ABORT: quip_params.xml does not exist   
STOP 1

**What do think I could be doing wrong again? Thank you.**

**Comment by Eadedeji** [comment]
Also, my platform is Suse linux

**Comment by jameskermode** [comment]
Those look to be warnings not errors, so it probably completed OK. The `quip` command you are invoking was compiled on 15 June 2023, however, so it's the one from the `pip install` not the one you have just compiled. The compiled code will be in the `build.${QUIP_ARCH}` subdirectory.

**Comment by Eadedeji** [comment]
Okay, thanks. One more thing, sir: I have this error when compiling Quippy. 

1. “make quippy” 
error: Command "gcc -pthread -B /xxxxxx/xxxxxxx/x/eadedeji/anaconda3/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /xxxxxx/xxxxxxx/x/eadedeji/anaconda3/include -fPIC -O2 -isystem /xxxxxx/xxxxxxx/x/eadedeji/anaconda3/include -fPIC -DNPY_DISABLE_OPTIMIZATION=1 -I./src.linux-x86_64-3.11/./src.linux-x86_64-3.11 -I/xxxxxx/xxxxxxx/x/eadedeji/anaconda3/lib/python3.11/site-packages/numpy/core/include -I/xxxxxx/xxxxxxx/x/eadedeji/anaconda3/include/python3.11 -c ./src.linux-x86_64-3.11/_quippymodule.c -o ./src.linux-x86_64-3.11/_quippymodule.o -MMD -MF ./src.linux-x86_64-3.11/_quippymodule.o.d" failed with exit status 1
make[1]: *** [Makefile:118: quippy/_quippy.cpython-311-x86_64-linux-gnu.so] Error 1
make: *** [Makefile:230: quippy] Error 2

2. I think it is a problem with gcc. 
gcc --version. .... is ........gcc (SUSE Linux) 12.3.0 
which gcc ... is ......./usr/bin/gccltrh|grep gcc
-rwxr-xr-x 1 root root       2.2K May 25  2018 gccmakedep
lrwxrwxrwx 1 root root         12 Aug 23  2021 gcc-ranlib -> gcc-ranlib-7
lrwxrwxrwx 1 root root          8 Aug 23  2021 gcc-nm -> gcc-nm-7
lrwxrwxrwx 1 root root          8 Aug 23  2021 gcc-ar -> gcc-ar-7
lrwxrwxrwx 1 root root          5 Aug 23  2021 cc -> gcc-7
-rwxr-xr-x 1 root root        31K Sep  4  2023 gcc-ranlib-7
-rwxr-xr-x 1 root root        31K Sep  4  2023 gcc-nm-7
-rwxr-xr-x 1 root root        31K Sep  4  2023 gcc-ar-7
-rwxr-xr-x 1 root root      1003K Sep  4  2023 gcc-7
-rwxr-xr-x 2 root root       1.3M Sep  4  2023 x86_64-suse-linux-gcc-12
-rwxr-xr-x 1 root root        35K Sep  4  2023 gcc-ar-12
-rwxr-xr-x 2 root root       1.3M Sep  4  2023 gcc-12
-rwxr-xr-x 1 root root        35K Sep  4  2023 gcc-ranlib-12
-rwxr-xr-x 1 root root        35K Sep  4  2023 gcc-nm-12
-rwxr-xr-x 1 root root        11K Feb  2 13:44 dgccounter


How can I link to the appropriate gcc or solve the error? PLEASE NOTE...QUIP and GAP seem to be compiled and installed successfully. Thank you once again
