### ISSUE TITLE
Adding config_type in .xyz files

### ISSUE THREAD

**Issue by MES-physics** [libAtoms/QUIP#671]
Hi,
Can anyone tell me how ```config_type=``` are added into .xyz files ?  If I have an xyz file that has 4000 or so configurations,
and they are not grouped sequentially, must I edit each configuration manually, or is there an easier way?
Thanks for any advice.

**Comment by albapa** [comment]
That'd be a lot of files to edit! I'd use ASE to do it, just edit the `info` field of the `Atoms` object, i.e.
```
at.info["config_type"]="type1"
```
You'll still need a (programmatic) way decide which config is which type.

**Comment by MES-physics** [comment]
Hi,  I was able to add config_type to an xyz file with multiple configurations, thanks.
But a warning comes up 
```UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator warnings.warn('write_xyz() overwriting array "{0}" present ' ```
Is this something that has to be fixed? What does it mean?
Thank you.

**Comment by albapa** [comment]
This is an ASE warning and has something to do with their revamped interface. If you want to make it go away, use a different key (e.g. `dft_forces` or whatever you like) and specify it in the `gap_fit` command line, e.g. `force_parameter_name=dft_forces` or whatever your key name was.

**Comment by jameskermode** [comment]
That's correct, was about to write something similar to @albapa

**Comment by MES-physics** [comment]
Thank you!
