### ISSUE TITLE
GAP/gp_fit.f95 gpFull_sparsify_array_config_type() segmentation fault

### ISSUE THREAD

**Issue by jyrikimari** [libAtoms/QUIP#672]
At least when using Intel compiler (tested with ifort (IFORT) 2021.6.0 20220226) on a cluster, when calling gp_sparsify() **without** the optional argument print_sparse_index, the program ends in a segmentation fault on line src/GAP/gp_fit.95:506. I suspect this is because the subroutine is trying to access and pass on the ith element of the non-present (character) array to gpCoordinates_sparsify_config_type().

I worked around the error by the somewhat ugly:
```
do i = 1, this%n_coordinate
   if (present(print_sparse_index)) then
      call gpCoordinates_sparsify_config_type(this%coordinate(i), n_sparseX(:,i), default_all(i), task_manager, &
         sparse_method=my_sparse_method(i), sparse_file=my_sparse_file(i), use_actual_gpcov=use_actual_gpcov, &
         print_sparse_index=print_sparse_index(i), unique_hash_tolerance=unique_hash_tolerance(i), &
         unique_descriptor_tolerance=unique_descriptor_tolerance(i), error=error)
   else
      call gpCoordinates_sparsify_config_type(this%coordinate(i), n_sparseX(:,i), default_all(i), task_manager, &
         sparse_method=my_sparse_method(i), sparse_file=my_sparse_file(i), use_actual_gpcov=use_actual_gpcov, &
         unique_hash_tolerance=unique_hash_tolerance(i), &
         unique_descriptor_tolerance=unique_descriptor_tolerance(i), error=error)
   endif
enddo
```

I didn't test if omitting unique_hash_tolerance and/or unique_descriptor_tolerance arrays causes the same error. The other arguments are either mandatory, scalars, or internally set with optional_default(), so they are most likely fine (?).

(I didn't observe this segmentation fault on a desktop+gfortran, not sure why.)

**Comment by albapa** [comment]
This is an interesting one - this compiler does not transfer the optional attribute for the elements of the array... As you say, the same should hold for the other optional arguments.

>  An absent argument further supplied as an actual argument must be specified as a whole, and not as a subobject.

We don't call this subroutine without the optional arguments, so this could be why it went unnoticed - and I assume you made some modifications.

This would be a good use of conditional expressions. These allow passing a `null`, but these are not yet readily available in most compilers.

Possible ways forward would be to scrap the `optional` attributes or use the `merge` function with a sensible default. What is your use case?

**Comment by jyrikimari** [comment]
My use case is hijacking the GAP library for something slightly different :) I use it to train a GPR model for descriptor -> **energy barrier** mappings to parameterize a kinetic Monte Carlo simulation. So I construct a gpFull object by addFunctionValue() and addCoordinates() from the collected descriptor input / nudged elastic band output values, then gp_sparsify(), gp_covariance_sparse(), gpSparse_fit() to produce a gpSparse object, finalise the gpFull object, and call gpCoordinates_initialise_variance_estimate(). I do the entire thing potentially many times during one KMC simulation, and don't need the sparse_index output for anything.

This snippet hopefully elucidates. The "predictor" object is a derived type that holds the input/output training data, GPR hyperparameters, and the gpSparse gp_sp object, etc.
```
call initialise_gp(gp_full,predictor) ! Internal subroutine that calls gp_setParameters(), gp_addDescriptor(), gp_setPermutations() etc.
do i=1,predictor%n_y
  current_y=gp_addFunctionValue(gp_full,predictor%y(i),predictor%y_error(i))
  current_x=gp_addCoordinates(gp_full,predictor%x(:,i),1,&
                              cutoff_in=predictor%covariance_cutoff(i),current_y=current_y)
end do
if (predictor%n_y<=predictor%n_sparse_max) then
  n_sparse=predictor%n_y ! n_sparse is a rank (1,1) integer. I only have one coordinate in the gp
  sparseMethod=GP_SPARSE_NONE
else
  n_sparse=predictor%n_sparse_max
  sparseMethod=GP_SPARSE_RANDOM
endif
call gp_sparsify(gp_full,n_sparseX=n_sparse,default_all=[.true.],&
                 sparseMethod=[sparseMethod],&
                 use_actual_gpcov=.false.,unique_hash_tolerance=[1.0d-10],&
                 unique_descriptor_tolerance=[1.0d-10])
call gp_covariance_sparse(gp_full)
call gpSparse_fit(predictor%gp_sp,gp_full,task_manager)
call finalise(gp_full)
call gpCoordinates_initialise_variance_estimate(predictor%gp_sp%coordinate(1),&
                                                regularisation=predictor%regularisation)
```

**Comment by albapa** [comment]
An easy workaround would be to use `print_sparse_index=[""]` - the code tests for the length of the string and if zero, it doesn't use it.

**Comment by jyrikimari** [comment]
Do you mean calling gp_sparsify like this?
```
call gp_sparsify(gp_full,n_sparseX=n_sparse,default_all=[.true.],&
                 sparseMethod=[sparseMethod],print_sparse_index=[""],&
                 use_actual_gpcov=.false.,unique_hash_tolerance=[1.0d-10],&
                 unique_descriptor_tolerance=[1.0d-10])
```
This, at least when compiled with the same Intel compiler & environment, results in the program trying to open a random/mangled filename with, I'm guessing, len=STRING_LENGTH, and System.f95 giving the error
```
SYSTEM ABORT: Traceback (most recent call last)
File "System.f95", line 532 kind unspecified
IO error opening "Èò§^@^@^@^@^@^A^@^@^@^@^@^@^@ [... omitting the rest of the filename in this github thread]
```

**Comment by albapa** [comment]
It's surprising - it should pass an empty string, and line 373 in gp_fit.f95 should deal with the case. Any chance that a `make clean` before `make` fixes it?

**Comment by jyrikimari** [comment]
`make clean`/`make` did not help, but I figured out a similar workaround. It turns out a literal `""` as the argument is not reliable for passing an empty string, as it will be interpreted as a garbage string of whatever length specified in the called subroutine (this seems to be true also in GNU compiler). However, passing a variable set to `""` works as expected.
```
program empty_literal
  implicit none

  character(len=80) :: teststr

  call test_passing("") ! prints "80"
  teststr=""
  call test_passing(teststr) ! prints "0"

contains

  subroutine test_passing(str)
    character(len=80),intent(in) :: str

    print *,len_trim(str)

  end subroutine test_passing
  
end program empty_literal
```
Edit: looks like Intel might not compile the exact above program because the argument lengths mismatch, but you can get the same behavior by making the argument an array of characters or some other modifications.

The following call from outside GAP works without modifications to gp_fit.f95:
```
character(len=STRING_LENGTH) :: print_sparse_index
.
.
.
print_sparse_index=""
call gp_sparsify(gp_full,n_sparseX=n_sparse,default_all=[.true.],&
                 sparseMethod=[sparseMethod],print_sparse_index=[print_sparse_index],&
                 use_actual_gpcov=.false.,unique_hash_tolerance=[1.0d-10],&
                 unique_descriptor_tolerance=[1.0d-10],error=internal_error)
```

**Comment by albapa** [comment]
So what is your conclusion? Shall we make some further changes in the code or are you happy with the current workaround?

**Comment by jyrikimari** [comment]
I'm happy with the current workaround, but I think it might be good to make the optionality of print_sparse_index work better in some future update.

Setting it up as `my_print_sparse_index=optional_default(...` might be the most similar option to the other optional arguments - although I didn't test this, and I'm not sure how it works for arrays. Whatever you decide, maybe also the same treatment for unique_[hash|descriptor]_tolerance as well.

**Comment by albapa** [comment]
Thanks for the feedback! I will close this now but will link the issue to any related future feature.
