### ISSUE TITLE
Next QUIP Hackathon - Tue May 16th, Cambridge

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/QUIP#68]
There will be a one-day QUIP hackathon in Cambridge on Tue 16th May (room TBC? @gabor1)
All welcome either physically or virtually. We'll continue with list of tasks in #55, but feel free to add more by editing this issue or commenting below.

**Comment by max-veit** [comment]
There's a mandatory CDT event (on commercialising software, interestingly
enough) from 4:15pm, so some of us will have to leave early. Otherwise,
sounds good!

Max

**Comment by jameskermode** [comment]
Suggestion from @noambernstein - rewrite thermostat code to deprecate all except `ALL_PURPOSE_THERMOSTAT`

> OK - for that thermostat the tau is ignored, only Q matters.  We provide a function (in fortran at least) called nose_hoover_mass(NDOF, T, tau) which computes the mass Q from a time scale (also called tau) using a heuristic which may or may not be the same as VASP's.  The argument tau to add_thermostat() is only (I think) used to set the time scale (via a friction gamma=1/tau) for various Langevin-type thermostats, e.g. NOSE_HOOVER_LANGEVIN, but not for pure NOSE_HOOVER.  As I said, it’d probably be a good idea to redo much of that code.  There are lots of places where defaults can be made more sensible and arguments given more explanatory names, and it may be possible to just decprecate everything except ALL_PURPOSE_THERMOSTAT.

**Comment by gabor1** [comment]
venue is the same as last time

-- Gábor

**Comment by jameskermode** [comment]
Adding #69 to list of thing to work on
