### ISSUE TITLE
Descriptors wrapper breaks documentation

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#71]
I think @st-- and @jameskermode were looking at this wrapper the other day, so if either of you have input it would be appreciated!

A couple of descriptors had been exposed to the documentation recently, you can still see them in the online docs: http://libatoms.github.io/QUIP/descriptors.html and what is requested in ``doc/descriptors.rst``. The new Python wrapper now masks the fortran module and only exposes ``Descriptor``. Would the wrapper work as a mixin to the other classes so the can be kept in the documentation?

I think there is another issue that is actually causing the build to fail fail: For some reason the autosummary of that module is trying to import the quippy script ``count.py`` (which breaks as it is a script). Will investigate.

**Comment by st--** [comment]
Sorry for breaking it! I think the python wrapper ought to import everything *but* `Descriptor` from the `_descriptors` module (and then needs adding to `__all__`). Is there some way of doing that programmatically without hardcoding?

**Comment by tdaff** [comment]
@st-- I think there are so few descriptors that there is not much of an issue hard coding for now since descriptors need to be properly documented and made public before they can be added to the documentation anyway, and it avoids doing wildcard imports or hacky bad things. I've made some tweaks to fix the documentation so that it should keep all the information that was there before.
