### ISSUE TITLE
Make config broken

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#72]
From a clean checkout, `make config` is now unable to build `get_sizeof_fortran_t` It is probably something to do with commit 948232fe9edb45e311299c3714dfaa5b4b16269e now adding all the linking options for fox etc. @jameskermode is it maybe enough to just add `EXTRA_LINKOPTS` or is there a specific case you changed it for?

For reference the error is 

```
f951: Warning: Nonexistent include directory ‘/home/tdd20/Work/tmp/quip/src/fox/objs.linux_x86_64_gfortran_openmp/finclude’ [-Wmissing-include-dirs]
<command-line>:6:0:

Warning: "_OPENMP" redefined
<built-in>:

note: this is the location of the previous definition
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lFoX_sax
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lFoX_wxml
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lFoX_utils
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lFoX_common
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lFoX_fsys
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -llapack
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: sizeof_fortran_t] Error 1

Unable to determine SIZEOF_FORTRAN_T
Check that your compiler is working and try again!

rm: cannot remove 'sizeof_fortran_t': No such file or directory
```

**Comment by jameskermode** [comment]
I added it for broken conda-supplied gfortran on my Mac, which requires a `-Wl,-rpath` argument to produce working binaries. Please go ahead and change to `EXTRA_LINKOPTS` and I'll fix my local environment.

**Comment by vishikh** [comment]
While installing QUIP anew, after choosing the options I want for `make confing` it still throws up the warning `f951: Warning: Nonexistent include directory ‘/home/QUIP/src/fox/objs.linux_x86_64_gfortran/finclude’ [-Wmissing-include-dirs]
`
Should I just ignore the warning?
