### ISSUE TITLE
Error during installation: There is no specific subroutine for the generic ‘calc’

### ISSUE THREAD

**Issue by vishikh** [libAtoms/QUIP#73]
After cloning the QUIP repository, and customizing installation of QUIP using `make config`, when I compile QUIP using `make`, I get the following error during compilation:
```
Error: There is no specific subroutine for the generic ‘calc’ at (1)
Makefile.rules:188: recipe for target 'quip.o' failed
make[1]: *** [quip.o] Error 1
make[1]: Leaving directory '/home/vishikh/QUIP/build/linux_x86_64_gfortran'
Makefile:137: recipe for target 'Programs' failed
make: *** [Programs] Error 2
```

**Comment by gabor1** [comment]
Can you send the entire log of "make" please. What operating system and compiler are you using? and what is your "QUIP_ARCH" variable?

-- Gábor

**Comment by vishikh** [comment]
I'm using Ubuntu 16.04 LTS (64 bit) and the gfortran compiler and QUIP_ARCH=linux_x86_64_gfortran

Here's the log file:
[log.txt](https://github.com/libAtoms/QUIP/files/1041903/log.txt)

**Comment by gabor1** [comment]
I just checked out a fresh copy of QUIP and GAP, and it compiled fine. So could you please send me your Makefile.inc from the build directory. Are you working with a clean copy? ("make clean" will get there to some extent)


-- Gábor

**Comment by vishikh** [comment]
I tried "make clean" and then "make" again, but I get the same error. Here's my Makefile.inc (I renamed it .txt because github wouldn't let me upload it otherwise)
[Makefile.inc.txt](https://github.com/libAtoms/QUIP/files/1043935/Makefile.inc.txt)

**Comment by gabor1** [comment]
Ok. We need "make" to give us more info. Please make clean again and type "make -t" which will give a much longer output

-- Gábor

**Comment by vishikh** [comment]
There's a problem. `make -t` gives the following output:
```
Using QUIP_ARCH=linux_x86_64_gfortran, MODULES=libAtoms GAP GAP-filler Potentials Utils Programs FilePot_drivers Structure_processors, QUIP_ROOT=/home/athavale/Downloads/QUIP
touch src/fox/objs.linux_x86_64_gfortran/lib/libFoX_common.a
make: touch: open: src/fox/objs.linux_x86_64_gfortran/lib/libFoX_common.a: No such file or directory
```

**Comment by gabor1** [comment]
Could you please reclone a fresh copy? That will ensure that there are no stray files

-- Gábor

**Comment by vishikh** [comment]
Yep, I just recloned a fresh copy, but 'make -t' still gives the same problem. I'd tried recloning and compiling a few times before posting this issue.

**Comment by gabor1** [comment]
Sorry, I was on the road, and it would appear that the “-t” option (short for “trace”) that I got off the web is not a gnu make option, but valid for some other make, and it means something different with gnu make. The correct debugging option with gnu make is “-d”. 

-- Gábor

**Comment by tdaff** [comment]
You might need a new copy of the GAP code too; It looks like yours if from April and there may have been some changes that put it out of sync with QUIP.

**Comment by gabor1** [comment]
That could indeed explain the original problem, which was to do with the descriptors call. 

-- Gábor

**Comment by vishikh** [comment]
Installing with a new copy of GAP worked successfully. QUIP is compiled and running now.

**Comment by vishikh** [comment]
Installing with a new copy of GAP worked successfully. QUIP is compiled and running now.

**Comment by yufeib** [comment]
These is the error after 'make', and then I failed. What resulted in this? Thank you
"  make[1]: execvp: /public/home/md/software/mlearn/source/QUIP/bin/gitversion: Permission denied
make[1]: Entering directory `/public/home/md/software/mlearn/source/QUIP/build/linux_x86_64_gfortran'
make[1]: execvp: /public/home/baiyf/software/mlearn/source/QUIP/src/GAP/gapversion: Permission denied    "

"Error: Expected an initialization expression at (1)
make[1]: *** [descriptors.o] Error 1
make[1]: Leaving directory `/public/home/md/software/mlearn/source/QUIP/build/linux_x86_64_gfortran'
make: *** [GAP] Error 2 "

**Comment by gabor1** [comment]
please post the complete output of `make'

> On 15 Oct 2019, at 11:56, yufeib <notifications@github.com> wrote:
> 
> These is the error after 'make', and then I failed. What resulted in this? Thank you
> " make[1]: execvp: /public/home/md/software/mlearn/source/QUIP/bin/gitversion: Permission denied
> make[1]: Entering directory `/public/home/md/software/mlearn/source/QUIP/build/linux_x86_64_gfortran'
> make[1]: execvp: /public/home/baiyf/software/mlearn/source/QUIP/src/GAP/gapversion: Permission denied "
> 
> "Error: Expected an initialization expression at (1)
> make[1]: *** [descriptors.o] Error 1
> make[1]: Leaving directory `/public/home/md/software/mlearn/source/QUIP/build/linux_x86_64_gfortran'
> make: *** [GAP] Error 2 "
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
