### ISSUE TITLE
FortranArray broken with numpy-1.13.0

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#75]
It seems like something changed in a recent Numpy update and now slice indexing is broken, e.g.

```
======================================================================
ERROR: test_set_lattice_2 (test_atoms.TestAtoms_LowLevel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdd20/Work/tmp/quip/tests/test_atoms.py", line 39, in setUp
    self.dia.pos[:] += np.random.uniform(-0.1,0.1,self.dia.n*3).reshape(3,self.dia.n)
  File "/home/tdd20/Work/tmp/quip/quippy/build/linux_x86_64_gfortran_openmp/lib.linux-x86_64-2.7/quippy/farray.py", line 331, in __getslice__
    obj = np.ndarray.__getslice__(self, i, j)
  File "/home/tdd20/Work/tmp/quip/quippy/build/linux_x86_64_gfortran_openmp/lib.linux-x86_64-2.7/quippy/farray.py", line 286, in __getitem__
    indx = self.mapindices(indx)
  File "/home/tdd20/Work/tmp/quip/quippy/build/linux_x86_64_gfortran_openmp/lib.linux-x86_64-2.7/quippy/farray.py", line 227, in mapindices
    rslice_start = FortranArray.map_int(idx.start)
  File "/home/tdd20/Work/tmp/quip/quippy/build/linux_x86_64_gfortran_openmp/lib.linux-x86_64-2.7/quippy/farray.py", line 191, in map_int
    raise IndexError('index 0 not permitted - FortranArrays are one-based')
IndexError: index 0 not permitted - FortranArrays are one-based

```

**Comment by jameskermode** [comment]
Haven't come across this yet. Can you confirm version of numpy you are using?

**Comment by tdaff** [comment]
Unfortunately Travis doesn't show the versions, but locally I get:

numpy==1.12.1 ✔ passes
numpy==1.13.0 ✘ fails

Since it's only released 2 weeks ago, I guess nobody updated yet.

**Comment by jameskermode** [comment]
Further reasons to deprecate the FortranArray, but I guess we need a faster fix. I won't be able to have a look for a couple of days, so if it's more urgent then please feel free to have a dig into what might be going on.

**Comment by tdaff** [comment]
From the Numpy changelog:

> ``__getslice__`` and ``__setslice__`` have been removed from ``ndarray``
> When subclassing np.ndarray in Python 2.7, it is no longer _necessary_ to implement ``__*slice__`` on the derived class, as ``__*item__`` will intercept these calls correctly.
> 
> Any code that did implement these will work exactly as before, with the obvious exception of any code that tries to directly call ``ndarray.__getslice__`` (e.g. through ``super(...).__getslice__)``. In this case, ``.__getitem__(slice(start, end))`` will act as a replacement.
> 

Might have something to do with it?

**Comment by jameskermode** [comment]
@tdaff Changes in 8c8f30290 look good to me, thanks, please go ahead and merge when you're happy.
