### ISSUE TITLE
'make config' for netCDF is not transferable

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#79]
``make config`` has some tricks to try and determine the version of netcdf libraries and has hard coded libs in ``Makefile.rules``, but these break in cases where there is no netcdf.a and where hdf5 libs are named differently.

Two things I'd like to do:

- Drop support for netCDF3, that way we can avoid trying to figure out the version number (3.x might still be the default in RHEL5, but that is past the end of it's 10 year life cycle.)
- Ask directly for netcdf linking flags and use ``nc-config`` or ``pkg-config`` if available for a first guess.

If people are using netcdf (especially on Mac), it would be useful if they could post the output of their ``nc-config --all`` and ``pkg-config --libs netcdf``

**Comment by tdaff** [comment]
```
% nc-config --all

This netCDF 4.4.1.1 has been built with the following features: 

  --cc        -> mpicc
  --cflags    -> -I/usr/include 
  --libs      -> -L/usr/lib64 -lnetcdf

  --has-c++   -> no
  --cxx       -> 

  --has-c++4  -> no
  --cxx4      -> 

  --has-fortran-> no
  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> no
  --has-szlib -> 

  --prefix    -> /usr
  --includedir-> /usr/include
  --libdir    -> /usr/lib64
  --version   -> netCDF 4.4.1.1

```

```
% pkg-config --libs netcdf
-lnetcdf

```

**Comment by gabor1** [comment]
This is on my laptop:

bart:gap-fe/ $ nc-config --all

This netCDF 4.4.1 has been built with the following features: 

  --cc        -> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
  --cflags    -> -I/opt/local/include
  --libs      -> -L/opt/local/lib -lnetcdf -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> /opt/local/bin/gfortran-mp-5
  --fflags    -> -I/opt/local/include
  --flibs     -> -L/opt/local/lib -lnetcdff -L/opt/local/lib -Wl,-headerpad_max_install_names -lnetcdf -lnetcdf
  --has-f90   -> no
  --has-f03   -> yes

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> yes
  --has-pnetcdf-> no
  --has-szlib -> no

  --prefix    -> /opt/local
  --includedir-> /opt/local/include
  --version   -> netCDF 4.4.1

bart:gap-fe/ $ pkg-config --libs netcdf
-L/opt/local/lib -lnetcdf -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl


-- Gábor
