### ISSUE TITLE
GAP descriptors fail to install python wrapper

### ISSUE THREAD

**Issue by kbsezginel** [libAtoms/QUIP#80]
Hi,

I am trying to install quippy Python wrappers with GAP. I was able to build the software using GAP (version: 1498734806) however when I run ```make quippy``` I get the following error:

```
ValueError: Can't find Fortran module corresponding to file /home/kutay/Documents/git/QUIP/src/GAP/descriptors.f95
Makefile:43: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/kutay/Documents/git/QUIP/quippy'
Makefile:180: recipe for target 'quippy' failed
make: *** [quippy] Error 2
```

I am running on Ubuntu 16.04 (x86_64) with a Python 2.7 virtual environment (installed all dependencies).

Thanks,
Kutay

**Comment by tdaff** [comment]
Hi Kutay,

What is your ``QUIP_ARCH`` and ``bin/gitversion``?

**Comment by kbsezginel** [comment]
` QUIP_ARCH ` is `linux_x86_64_gfortran` and git version is `git version 2.7.4`.
Also if it helps the `gfortran` version is `GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`,

Thanks,
Kutay

**Comment by tdaff** [comment]
Sorry, I meant the git commit hash for QUIP. I assume you did a fresh clone or a pull, but check that you have a version at least newer than June.

Your ``QUIP_ARCH`` unfortunately rules out the easiest solution, so I'll need to check some other things:

- which version of numpy do you have?
- did you try to ``make clean`` and then ``make quippy``? Sometimes previous compiles can confuse newer ones...
- please post your ``build/linux_x86_64_gfortran/Makefile.inc``
- please post the complete build log

**Comment by kbsezginel** [comment]
I started from scratch and I was able to compile the python library this time.

I previously I compiled without GAP first, then I did `make clean` and tried to compile with GAP but I guess as you said the previous compile was causing problems.

Sorry for the trouble and thanks for the help!
