### ISSUE TITLE
Misleading definition of GPa conversion factor

### ISSUE THREAD

**Issue by max-veit** [libAtoms/QUIP#82]
In `Units.f95` (and `quippy.units.GPA`), the gigapascal conversion unit is defined as the inverse of what it should be - e.g. to convert _from_ quip units (eV Å^-3) _to_ GPa, you would expect to do
```python
press / quippy.units.GPA # WRONG!
```
but it's the other way around (this converts _from_ GPa _to_ quip units)

Since so much code uses the existing constant*, we can't just change it.  In order to avoid tripping up new users, it's been proposed to introduce a new constant, `EV_A3_IN_GPA` with the same value. This makes the correct use in conversions much clearer.  The existing `GPA` constant could then be slowly deprecated and a new constant introduced for the more intuitive (well, more consistent) conversion factor, i.e. the inverse of the one currently defined.

*(several uses in each of the following files):
```src/FilePot_drivers/cp2k_driver_module.f95
src/libAtoms/Barostat.f95
src/libAtoms/DynamicalSystem.f95
src/libAtoms/Units.f95
src/Potentials/Potential.f95
src/Potentials/Potential_Hybrid_utils.f95
src/Potentials/Potential_Precon_Minim.f95
src/Programs/md.f95
src/Programs/md_gid.f95
src/Programs/quip.f95
src/Programs/slice_sample.f95
src/Utils/cracktools.f95
src/Utils/elasticity.f95
examples/bulk-mod.py
examples/elastic.py
examples/quartz-strain.py
quippy/asap.py
quippy/castep.py
quippy/crack.py
quippy/molpro.py
scripts/bulk_properties.py
```

**Comment by max-veit** [comment]
Related is [this issue](https://github.com/jameskermode/f90wrap/issues/68) -- basically, the comment in the Fortran file that defines this constant explains its correct usage, but that comment doesn't make it to the online documentation.

**Comment by gabor1** [comment]
sounds like a sensible course of action. 

alternatively, what about changing the value of the constant, and search-replacing the units.GPA string and replacing it with (1/units.GPA) ? 

-- Gábor

**Comment by max-veit** [comment]
That would cause every other user who used GPA somewhere in their code to
suddenly start getting wrong results.

**Comment by gabor1** [comment]
you mean in code that wasn’t in the quip repo. true. let’s create a new constant then. 

-- Gábor
