### ISSUE TITLE
Build error: Unable to determine SIZEOF_FORTRAN_T

### ISSUE THREAD

**Issue by yingxingcheng** [libAtoms/QUIP#88]
I want to build QUIP using intel complier and mpi so the linux_x86_64_ifort_icc_mpi was specificed, when I finished `make config` there are some errors shown as follow:
```
Unable to determine SIZEOF_FORTRAN_T
Check that your compiler is working and try again!
Build error:
make[1]: Entering directory `/ICME/yxchen-ICME/usr/local/QUIP/build/linux_x86_64_ifort_icc_mpi'
mpif90  -fpp -free -warn unused -fPIC -I/ICME/yxchen-ICME/usr/local/QUIP/src/libAtoms -I/ICME/yxchen-ICME/usr/local/QUIP/src/fox/objs.linux_x86_64_ifort_icc_mpi/finclude -O3 -g -traceback -DDUMP_CORE_ON_ABORT  -DGETARG_F2003 -DFORTRAN_UNDERSCORE -D_MPI -D'GIT_VERSION="https://github.com/libAtoms/QUIP.git,66c553f"' -D'GAP_VERSION=1504885335' -D'QUIP_ARCH="linux_x86_64_ifort_icc_mpi"' -D'SIZEOF_FORTRAN_T=' -DHAVE_GAP_FILLER -DHAVE_GAP -DHAVE_PRECON -DHAVE_QR   sizeof_fortran_t.f90 -o sizeof_fortran_t
gfortran: error: unused: No such file or directory
gfortran: error: unrecognized command line option ‘-fpp’
gfortran: error: unrecognized command line option ‘-warn’
gfortran: error: unrecognized command line option ‘-traceback’
make[1]: *** [sizeof_fortran_t] Error 1
make[1]: Leaving directory `/ICME/yxchen-ICME/usr/local/QUIP/build/linux_x86_64_ifort_icc_mpi'

make: *** [config] Error 1
```

Another error occurs when I choose `linux_x86_64_gfortran` arch as follow:
```
Unable to determine SIZEOF_FORTRAN_T
Output::

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fe59911b1b2
#1  0x7fe59911b8ee
#2  0x3b388326af
#3  0x3b3893356f
#4  0x7fe59911d527
#5  0x400889
#6  0x3b3881ed5c
#7  0x4006d8
#8  0xffffffffffffffff

make: *** [config] Error 1

```

**Comment by tdaff** [comment]
Hi @yingxingcheng,

For the first error, your mpif90 wrapper is set up to use gfortran so you will need to either use linux_x86_64_gfortran_openmpi or figure ourt how to get your mpi wrapper to use the intel compilers instead.

Second error is a bit puzzling. What `gfortran --version` and OS are you using? Did you set any extra linking options in the `make config`. What is the output of `ulimit -a`? If there is still the binary `build/linux_x86_64_gfortran/sizeof_fortran_t` does it work if you run it directly?

**Comment by yingxingcheng** [comment]
Dear @tdaff ,

Thanks for your responds.
# For the first error
I have changed the wrapper with `export I_MPI_F90 = ifort`, `export I_MPI_F77=ifort` and `export I_MPI_CC=icc` so that the `make config` command works. However, when I type `make` and there is another error shown:
```
/tmp/ifortM7s5Rx.i: catastrophic error: **Internal compiler error: segmentation violation signal raised** 
Please report this error along with the circumstances in which it occurred in a Software Problem Report.  
Note: File and line given may not be explicit cause of this error.
compilation aborted for /ICME/yxchen-ICME/usr/local/QUIP/src/Potentials/Potential_Precon_Minim.f95 (code 1)
make[1]: *** [Potential_Precon_Minim.o] Error 1
make[1]: Leaving directory `/ICME/yxchen-ICME/usr/local/QUIP/build/linux_x86_64_ifort_icc_mpi'
make: *** [Potentials] Error 2
``` 
I found a similar error in the [documents of QUIP](http://libatoms.github.io/QUIP/install.html):
> ## Internal compiler error with ifort
> If you see an error like the following when using the Intel fortran compiler:
 ```
fortcom: Severe: **Internal compiler error: internal abort** Please
report this error along with the circumstances in which it occurred
in a Software Problem Report.
 Note: File and line given may not be explicit cause of this error.

ifort: error #10014: problem during multi-file optimization compilation (code 3)
backend signals
```
> Then the problem is due to bugs in the compiler. As a workaround, setting QUIPPY_NO_CRACK =1 in Makefile.inc should solve the problem, at the cost of excluding the fracture utilities from quippy.

Badly, it does not work!

# For the second error
## System:
-  `gfortran --version` = `GNU Fortran (GCC) 4.9.3` 
- `OS` = `Red Hat Enterprise Linux Server release 6.4 (Santiago)`
## Summary
-  `make config`: set default
-  `ulimit -a`:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 256008
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
- when I run the program `build/linux_x86_64_gfortran/sizeof_fortran_t` the output is shown as follow:
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fc6a6ffd1b2
#1  0x7fc6a6ffd8ee
#2  0x3b388326af
#3  0x3b3893356f
#4  0x7fc6a6fff527
#5  0x400889
#6  0x3b3881ed5c
#7  0x4006d8
#8  0xffffffffffffffff
Segmentation fault (core dumped)
```

# Another error in my PC
## System
- `OS` = `Ubuntu 16.04.2 LTS`
- `Python` = `2.7.12`
- `numpy` = `1.13.1`
- `ase` = `3.14.1`

## Summary
- I have tried to install QUIP and complie the Python wrapper with arch is set to `linux_x86_64_gfortran` in my PC and it works, but when I try to `import quippy` in my python interpreter there are some error message shown as follow:
```
Segmentation fault (core dumped)
```

**Comment by gabor1** [comment]
Can I close this?

**Comment by yingxingcheng** [comment]
ok
