### ISSUE TITLE
castep_driver.py not recognising OTF pseudo potential definition 

### ISSUE THREAD

**Issue by gabor1** [libAtoms/QUIP#9]
This is in my template cell file:

---------- cut here   ---------
kpoints_mp_spacing 0.020

symmetry_generate

%BLOCK SPECIES_POT
Al 2|1.2|23|26|29|20U:21U:30:31(qc=8)
%ENDBLOCK SPECIES_POT
----------- cut here ------------

**Comment by jameskermode** [comment]
closing since `castep_driver.py` has been removed, use `ase.calculators.castep.Castep`
