### ISSUE TITLE
GAP mandatory variables

### ISSUE THREAD

**Issue by yghadar** [libAtoms/QUIP#98]
Hi, 
Using the Si data from examples;

./teach_sparse at_file=data_Si.xyz 'gap={distance_2b' cutoff=4.1 n_sparseX=250 covariance_type=ard_se theta_fac=0.5: angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 'delta=0.1}' 'default_sigma={0.001' 0.05 0.01 '0.02}' sparse_jitter=1.0e-8 e0=0.0_

I get the following errors, which was not present couple of months ago. I would appreciate any suggestions. 

libAtoms::Hello World: 20/03/2018   11:16:31
libAtoms::Hello World: git version  https://github.com/libAtoms/QUIP.git,249661c-dirty
libAtoms::Hello World: QUIP_ARCH    linux_x86_64_gfortran_openmp
libAtoms::Hello World: compiled on  Dec 19 2017 at 22:35:06
libAtoms::Hello World: OpenMP parallelisation with 12 threads
 WARNING: libAtoms::Hello World: environment variable OMP_STACKSIZE not set explicitly. The default value - system and compiler dependent - may be too small for some applications.
libAtoms::Hello World: Random Seed = 40591845
libAtoms::Hello World: global verbosity = 0

Calls to system_timer will do nothing by default

================================ Input parameters ==============================

at_file = data_Si.xyz
gap = "distance_2b cutoff=4.1 n_sparseX=250 covariance_type=ard_se theta_fac=0.5: angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 delta=0.1"
e0 = 0.0
e0_offset = 0.0
do_e0_avg = T
default_sigma = "0.001 0.05 0.01 0.02"
sparse_jitter = 1.0e-8
hessian_delta = 1.0e-2
core_param_file = quip_params.xml
core_ip_args =
energy_parameter_name = energy
force_parameter_name = force
virial_parameter_name = virial
hessian_parameter_name = hessian
config_type_parameter_name = config_type
sigma_parameter_name = sigma
config_type_sigma =
sigma_per_atom = T
do_copy_at_file = T
sparse_separate_file = T
sparse_use_actual_gpcov = F
gp_file = gp_new.xml
verbosity = NORMAL
rnd_seed = -1
do_ip_timing = F
template_file = template.xyz

========================================  ======================================

============== Gaussian Approximation Potentials - Database fitting ============

Initial parsing of command line arguments finished.
Found 2 GAPs.
missing mandatory parameter delta
SYSTEM ABORT: main program failed to parse gap string (1)='distance_2b cutoff=4.1 n_sparseX=250 covariance_type=ar-
d_se theta_fac=0.5'

**Comment by gabor1** [comment]
you are indeed missing the delta parameter from the distance_2b descriptor. Can you point me to the exact place you obtained this command line from? I can then update it. 

it should be:


./teach_sparse at_file=data_Si.xyz 'gap={distance_2b' cutoff=4.1 n_sparseX=250 covariance_type=ard_se theta_fac=0.5 delta=1.0: angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 'delta=0.1}' 'default_sigma={0.001' 0.05 0.01 '0.02}' sparse_jitter=1.0e-8  e0=0.0

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/

**Comment by yghadar** [comment]
Hi  Gábor,

Thank you for your quick respond. Following your suggestions I get
the following error:

./teach_sparse at_file=data_Si.xyz 'gap={distance_2b' cutoff=4.1
n_sparseX=250 covariance_type=ard_se theta_fac=0.5 delta=1.0: angle_3b
cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 'delta=0.1}'
'default_sigma={0.001' 0.05 0.01 '0.02}' sparse_jitter=1.0e-8  e0=0.0

Initial parsing of command line arguments finished.

Found 2 GAPs.

Descriptors have been parsed

XYZ file read

Unchanged GAP: {distance_2b cutoff=4.1 n_sparseX=250 covariance_type=ard_se
theta_fac=0.5 delta=1.0}

Unchanged GAP: { angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se
theta_fac=0.5 delta=0.1}

SYSTEM ABORT: Confused: either n_sparse or config_type_n_sparse has to be
specified

Any suggestions?

Thank you,

-Yasi


*Yasaman Ghadar, PhD*
*Postdoctoral Scholar*
*Argonne National Laboratory*


*Leadership Computing FacilityEmail: ghadar@anl.gov <ghadar@anl.gov> *
*Phone: 630-252-1398 <630-252-1398>*

**Comment by yghadar** [comment]
With respect to those command lines I believe I get them from the parameters.xml file however I am not able to load libatoms.org website to provide you more details.

**Comment by gabor1** [comment]
our server room is  down until Thursday

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/

**Comment by gabor1** [comment]
There have been some cleanup of the parameter names, and the xml files you are looking at are old. But it’s not too bad. remove the “X” from n_sparseX. 

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/

**Comment by yghadar** [comment]
Thank you. It seems that it is working.

Regards,

-Yasi


*Yasaman Ghadar, PhD*
*Postdoctoral Scholar*
*Argonne National Laboratory*


*Leadership Computing FacilityEmail: ghadar@anl.gov <ghadar@anl.gov> *
*Phone: 630-252-1398 <630-252-1398>*

**Comment by gabor1** [comment]
OK. let me know if I can help with anything else.

if you put the string “--help” in any place which takes key=value arguments, the program will dump a list of allowed keys, defaults, and one line descriptions. some lists are recursively parsed, so you might have to satisfy any MANDATORY argument checks, after which the --help will cascade further"

— Gábor

Pembroke College supports CARA. A Lifeline to Academics at Risk. http://www.cara.ngo/
